### ISSUE TITLE
Add card holder's name on quick integration

### ISSUE THREAD

**Issue by vash15** [Adyen/adyen-ios#10]
Hi guys, 
is there a plan to add card holder's name to the quick integration CardFormViewController?
It would be great if it's configurable through AppearanceConfiguration class.
Also "StoreDetailsButton" is a custom control that someone would like to switch off.

Thank you,
Michele

**Comment by joostvandijk** [comment]
Hi @vash15,

Currently, there are no plans to add a card holder name field to the card form in the Quick Integration UI. If you're looking for additional fields, I'd currently suggest you implement your own UI using Custom Integration.
The store details button will be automatically hidden if you don't send a `shopperReference` with your request to `/setup`.

Let me know if you have any further questions!

Kind regards,

Joost
