### ISSUE TITLE
[NEED ASSIST] Call backs never called after PIX payment succeed

### ISSUE THREAD

**Issue by AhmedOsman00** [Adyen/adyen-ios#1011]
Hi Team, I have an issue with PIX payment, I have implemented PIX payment using QRCodeComponent, and the PIX payment QR code screen appears as in the screenshot, and when I click to copy code button the payment succeeds in the backend but the callback methods never called.
![Screenshot 2022-10-07 at 2 32 49 PM](https://user-images.githubusercontent.com/26196552/194554365-21100787-a182-4311-a602-d3c75db6174c.png)
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-10-07 at 14 30 51](https://user-images.githubusercontent.com/26196552/194554375-a3bfc361-d0ca-48eb-a511-454a05a6d867.png)

**Comment by descorp** [comment]
Hey @AhmedOsman00 

do you persist instance of `QRCodeComponent`?
How do you initiate it?

**Comment by AhmedOsman00** [comment]
@descorp Yes I keep instance of `QRCodeComponent ` and also when I copy the code, I can see the `copyToPasteboard` executed.

**Comment by mohammedDehairy** [comment]
@AhmedOsman00 

I think this is a bug in version 4, Thanks for reporting this, I have fixed it in [this PR](https://github.com/Adyen/adyen-ios/pull/1012), we'll release this fix very soon.

Kind regards

Mohamed

**Comment by mohammedDehairy** [comment]
@AhmedOsman00 , this bug has been fixed in [latest release 4.10.0](https://github.com/Adyen/adyen-ios/releases/tag/4.10.0).

Thanks for reporting this :-)

feel free to reopen the ticket if you're still experiencing the issue
