### ISSUE TITLE
Detect card brand incorrect

### ISSUE THREAD

**Issue by dovhoang** [Adyen/adyen-ios#1015]
**Describe the bug**
Sometimes, the card number input cannot detect the brand.

**To Reproduce**
Steps to reproduce the behaviour:
Use test card: `4111 1111 1111 1111` (Visa), Exp: 03/30, CVV: 737
1. Enter 10 numbers `4111 1111 11`, the component still detects Visa
2. Continue enter remain number and the component **cannot detect** the card brand 
3. See transaction in the portal, card detail show Visa type

> Note:  Get the same issue in the android SDK

**Expected behavior**
The component detects Visa card type

**Screenshots**
| Step 1 | Step 2 | Step 3 |
| ------------- | ------------- | ------------- |
| ![IMG_0010](https://user-images.githubusercontent.com/55356231/195026008-6c555c49-ec6b-455a-a99c-560c24c444f8.PNG) | ![IMG_0012](https://user-images.githubusercontent.com/55356231/195028782-120f1ecc-8c1a-4350-9997-b88b12fbd37c.PNG) | <img width="668" alt="Screenshot 2022-10-11 at 14 46 13" src="https://user-images.githubusercontent.com/55356231/195028956-f7d1b17f-011d-4d8e-85d7-8b1b9205b8db.png"> |

**Smartphone:**
 - Device:  iPhone6S Plus
 - OS: iOS15.0
 - SDK Version: 4.9.0

**Comment by mohammedDehairy** [comment]
@viethoang093 ,

is this on Test environment? if it is, then its a limitation on our Test backend environment, but this should never happen on LIVE environment, we're trying to update our TEST environment database, but this will take some time, and can't promise anything soon :-).

in the mean while, like I said this should never happen on LIVE, so you can just ignore this issue for now, and try using some other test card.

**Comment by dovhoang** [comment]
Thanks for the quick reply @mohammedDehairy
