### ISSUE TITLE
Encrypted Security code

### ISSUE THREAD

**Issue by sameers27** [Adyen/adyen-ios#102]
I'm currently encrypting a card using the `CardEncryptor.encryptedCard( for: CardEncryptor.Card(), publicKey: String)`. Part of our checkout process includes verifying the cvv as the last step. The cvv also need to be encrypted. 

How do i go about just encrypting the cvv? Do i use the same method as before and provide nil values for the other `CardEncryptor.Card` parameters?

**Comment by joostvandijk** [comment]
Hi @sameers27,

Yes, that's right. Just provide `nil` values for those you don't want to encrypt, and only read the values you're interested in from the `EncryptedCard`.

Best,

Joost
