### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Tamaraa01x** [Adyen/adyen-ios#1020]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - SDK Version [e.g. 3.3.0]

**Additional context**

**Comment by mohammedDehairy** [comment]
Hi @Tamaraa01x ,

the description that you provided is not very helpful :-).

I will close this ticket, and feel free to reopen when you have an issue.
