### ISSUE TITLE
[BUG] Stored cards CVC max limit is always four digits

### ISSUE THREAD

**Issue by Swaxer** [Adyen/adyen-ios#1038]
**Describe the bug**
When adding the information to pay with a card you get validation on all fields, as expected, and the CVC field knows whether this card should have 0, 3 or 4 digits. But once a card is stored and a new payment is to be made, the customer is asked to enter the CVC again, but this time the max limit for CVC is four digits.

**To Reproduce**
1. Add a new card in the payment sheet eg. 5555 4444 4444 4444, only three digits for CVC is allowed
2. Store the card
3. Make a new payment with stored card
4. Four digits can be entered

**Expected behavior**
I expected that I would have the same validation in the payment sheet as in the alert.

**Screenshots**
![Screenshot 2022-10-27 at 17 12 31](https://user-images.githubusercontent.com/6900003/198328711-b39a70fe-cf96-4a2a-9753-5c46d8ee9168.png)
![Screenshot 2022-10-27 at 17 13 24](https://user-images.githubusercontent.com/6900003/198328922-29d0beba-d76e-457b-ac2a-07ac6ff061b6.png)

**Smartphone (please complete the following information):**
 - Device: iPhone11
 - OS: 15.5
 - SDK Version 14.0.10

**Comment by nauaros** [comment]
Hi @Swaxer! Thanks for reporting this! We're taking a look at it and will provide a fix a soon as possible.
Have a good one

**Comment by Swaxer** [comment]
@nauaros Thanks for the quick action 🚀

**Comment by nauaros** [comment]
Hey! Bug fixed in `develop` with #1042
There's another PR #1043 to fix it in `v4` (bug-fix will be included in `v4.10.1`)

Let us know if the solution works properly!

Sorry for the inconvenience, and thanks for the feedback! 💚
Nau

**Comment by mohammedDehairy** [comment]
will close this issue for now, please feel free to reopen if you're still having issues!.
