### ISSUE TITLE
PaymentMethods decoding fails

### ISSUE THREAD

**Issue by henkvanderspek** [Adyen/adyen-ios#105]
JSONDecoder().decode(PaymentMethods.self, from: data) throws an exception when the JSON contains `"storedPaymentMethods": null`. It would be friendlier for clients if it would catch the exception inside `init(from decoder: Decoder)` and continue with `stored` set to an empty array.

**Comment by joostvandijk** [comment]
Hi @henkvanderspek,

My apologies for the delay in response. Our API never returns this field as `null`. Are you adding it yourself? I'm not sure if it's the SDK's responsibility to catch this, as the value should be either not-present or an array.

Joost

**Comment by mohammedDehairy** [comment]
@henkvanderspek I will close this issue and you can reopen it if it is still an issue.

Best regards

Mohamed
