### ISSUE TITLE
Adyen Carthage has no Apple Pay framework

### ISSUE THREAD

**Issue by bukira** [Adyen/adyen-ios#106]
I am using Carthage and latest version of Adyen

github "adyen/adyen-3ds2-ios" "2.1.0-rc.3"
github "adyen/adyen-ios" "3.1.2"

I am also using 
https://docs.adyen.com/payment-methods/apple-pay/#description

But there is on ApplePay framework in my build/os folder after a Carthage update

How do I use ApplePay with there new DropinUI ?

**Comment by joostvandijk** [comment]
Hi @bukira,

This documentation is unfortunately outdated and refers to an older version of the SDK. In the latest version, Apple Pay is part of the main `Adyen` module. You can use the `ApplePayComponent` like you would use any other component.

Best,

Joost

**Comment by bukira** [comment]
@joostvandijk 
Thanks, found it, I get the following error:

[General] Payment request is invalid: Error Domain=PKPassKitErrorDomain Code=1 "Invalid in-app payment request" UserInfo={NSLocalizedDescription=Invalid in-app payment request, NSUnderlyingError=0x126820bd0 {Error Domain=PKPassKitErrorDomain Code=1 "PKPaymentRequest must contain a property 'countryCode' of type 'NSString' within '(
    AC,
    AD,

I am using the PaymentMethods.json from your demo app in the SDK, 

I notice that the json also has PayPay in it:

 "shopperEmail" : "johnsmith@example.org",
      "id" : "8415574934329787",
      "supportedShopperInteractions" : [
        "ContAuth",
        "Ecommerce"
      ],
      "name" : "PayPal",
      "type" : "paypal"
    },

Does Adyen support PayPal?

Regards
Criss

**Comment by bukira** [comment]
Doh my bad

I created a Payment as such
 component.payment = Payment(amount: Payment.Amount(value: Int((basket?.orderTotal?.amount ?? 0.0) * 100), currencyCode: basket?.orderTotal?.currency ?? "GBP"))

But now seen I need to add 
component.payment?.countryCode = "GB"

But my question on PayPal still exists :-)

**Comment by joostvandijk** [comment]
Hi @bukira,

Yes, we do support PayPal. It's usually just a redirect to the PayPal website. When you tokenize a PayPal payment method, we are able to complete the payment without redirecting to the PayPal website.

**Comment by bukira** [comment]
Would you have a test sample of a tokenised payment method? When I use your PaymentMethods.json which has paypal in it, and I select it, it just exits the flow, do I have to do something special to cause a redirect ?

**Comment by joostvandijk** [comment]
When you submit a request to /payments with the payment method specified as `paypal`, and specify `storePaymentMethod` to be `true`, it would tokenize the payment method. You can then retrieve it with `/paymentMethods`. Since this is more related to our backend API, I'd suggest you contact support@adyen.com to receive better and more detailed help on your integration.

**Comment by bukira** [comment]
Cheers,
Im a front end iOS dev so I will let our backend devs worry about that then :-)

**Comment by bukira** [comment]
Do you have any more info on how PayPal works without tokenisation, if there's no saved PayPal details, how does it redirect, can't find anything in your api documentation

**Comment by joostvandijk** [comment]
PayPal is normally a redirect payment method, and thus doesn't require UI for it to initiate a payment. When you get a redirect URL from our backend, you can use our `RedirectComponent` to display the PayPal web page.

**Comment by bukira** [comment]
Ok makes sense :-) does the redirectURL come in the payment Methods response along with the saved cards etc or is there another call to get the url? Is there a same sandbox redirect url I can try with ?

Cheers
Criss

**Comment by joostvandijk** [comment]
@bukira You need to make a request to /payments in order to receive the PayPal redirect URL. You can play around with the request here: https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v49/payments (change `paymentMethod.type` to `paypal`).

**Comment by bukira** [comment]
Do you have any docs on your salesforce cartridge integration?

**Comment by joostvandijk** [comment]
I'm not sure. Since I'm only familiar with the iOS side of things, it might be best to forward these types of questions to support@adyen.com.

**Comment by bukira** [comment]
Thxs will do, on the PayPal, I got the redirect working I think, for saved PayPalCards there's a StoredPayPalPaymentMethod, but how do I loads this? does it load a UI like the saved cards do to prompt for payment, in the DropInComponent it does load a new UI when you select, is that via a redirect url?

**Comment by joostvandijk** [comment]
There's currently no component for stored PayPal accounts, since there is no input to be gathered. In the drop in, we prompt for confirmation. If you don't use the dropin, but will have stored PayPal accounts, I suggest you do the same.
