### ISSUE TITLE
[NEED ASSIST]  - Get Adyen SDK Version iOS

### ISSUE THREAD

**Issue by LuisTavares13** [Adyen/adyen-ios#1060]
How to get Adyen SDK Version in iOS? 

In documentation has Global Variable, but don't work when import Adyen.

Thanks

**Comment by nauaros** [comment]
Hi @LuisTavares13!

Can please give us more context of what's your problem?
You wanna get the SDK version at runtime?

Cheers

**Comment by LuisTavares13** [comment]
Hello @nauaros 

I need to get Adyen SDK Version and to send in header to backend, in Adyen Documentation exist the global variable threeDS2SdkVersion that to return SDK version, but I can't to access this variable, I'm importing Adyen, I don't know to access this variable. 

<img width="1433" alt="Screen Shot 2022-11-03 at 18 57 27" src="https://user-images.githubusercontent.com/117089684/199971508-519c3bef-21ea-41c9-8d9d-b3ee15e749bd.png">

Thanks!

**Comment by nauaros** [comment]
Hi! You need to know the version of the Adyen library or the 3DS SDK version?
Cheers

**Comment by LuisTavares13** [comment]
Hi!, I need to know the Adyen library version.
Hugs

**Comment by nauaros** [comment]
As of now, we do not offer any public variable that returns you the Adyen library version.
We're gonna discuss the possibility to add this to our public API.

In the meantime, you can do the following to retrieve the Adyen library version.

```swift
var version: String? {
    Bundle(for: AdyenContext.self).infoDictionary?["CFBundleShortVersionString"] as? String
}
```

Thanks for the feedback! 💚

**Comment by LuisTavares13** [comment]
Thanks @nauaros
