### ISSUE TITLE
[NEED ASSIST] Detect Card Brand Type

### ISSUE THREAD

**Issue by rajanbalana** [Adyen/adyen-ios#1062]
**Describe the challenge**
I'm implementing a custom UI for asking credit card details in our app. I want to leverage the functionality of detecting card brands using the iOS SDK. However, I'm not able to find a publicly exposed function that could be used for this purpose. Could someone please help with the approach that should be taken? 

What steps did you take?
I looked into the documentation and relevant classes in the module to figure a way out. But I couldn't. Because those APIs are internal.

**Comment by mohammedDehairy** [comment]
Hey @rajanbalana ,

Thanks for reaching out!.

 There is a [public Adyen endpoint](https://docs.adyen.com/api-explorer/Checkout/69/post/cardDetails) that's available for this purpose when you don't want to use the `CardComponent`.

**Comment by mohammedDehairy** [comment]
I am going to close this ticket for lack of activity, please feel free to reopen if you're still having issues!.
