### ISSUE TITLE
Adyen redirect component 

### ISSUE THREAD

**Issue by Abdo-codes** [Adyen/adyen-ios#1063]
**Describe the bug**
The redirect component picks up links that are not Adyen-related and then triggers them as if they're missing the payment data method that the user has submitted. 

**Smartphone (please complete the following information):**
 - Device: [iPhone]
 - OS: [e.g. iOS15, 16]
 - SDK Version [e.g. 4.8.0]

**Comment by neelSharma12** [comment]
@Abdo-codes Thank you so much for submitting the issue. Unfortunately , I am not able to reproduce this at my end. Could you please share the specific flow or some more details if you can?

**Comment by Abdo-codes** [comment]
For example we've "https://www.marktplaats.nl/link/zoekopdrachten/34903127199593?startDateFrom=1666269971000&utm_content=button&utm_source=systemmail&utm_medium=email&utm_campaign=SavedSearches" link that user can get from our email campaign, when it's opened during payment flow redirect component picks it up and triggers flow completion!

**Comment by neelSharma12** [comment]
To avoid this issue, In the AppDelegate's ```application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) ``` you can check if the url is a campaign url then, do not call ```RedirectComponent.applicationDidOpen(from: url)```

**Comment by Abdo-codes** [comment]
But we've a lot of urls, is there a specific pattern that I can check so I can only allow it?

**Comment by neelSharma12** [comment]
We have made some changes in [this PR](https://github.com/Adyen/adyen-ios/pull/1065/files). Please let me know if this change works for you. Also, this fix is available in v5.

**Comment by Abdo-codes** [comment]
Looks like an improvement indeed, but I'm not sure it'll fix the issue that it's picking up weird params and considering it valid payment info, for example the SDK returns a success with those params as valid handled payment data ``` {"details":{"returnUrlQueryString":"utm_source=ios_social&utm_medium=social&utm_campaign=socialbuttons&utm_content=app_ios"}} ```

**Comment by Abdo-codes** [comment]
others: 

```
{"details":{"returnUrlQueryString":"action=did-you-sell&utm_source=systemmail&utm_medium=email&utm_campaign=CO__B_Expiring_Ad"}}

--- 
{"details":{"returnUrlQueryString":"startDateFrom=1667859416000&utm_content=button&utm_source=systemmail&utm_medium=email&utm_campaign=SavedSearches"}}

```

**Comment by Abdo-codes** [comment]
others: 

```
{"details":{"returnUrlQueryString":"action=did-you-sell&utm_source=systemmail&utm_medium=email&utm_campaign=CO__B_Expiring_Ad"}}

--- 
{"details":{"returnUrlQueryString":"startDateFrom=1667859416000&utm_content=button&utm_source=systemmail&utm_medium=email&utm_campaign=SavedSearches"}}

```

**Comment by neelSharma12** [comment]
Indeed there is no 100% guarantee that we can know that the url is not a valid payment url. So, maybe you can add a parameter like ```isCampaign = true``` in your campaign url and then check for this in the appdelegate.

**Comment by Abdo-codes** [comment]
ok I'll try to do that, thank you!

**Comment by descorp** [comment]
Hey @Abdo-codes 

As a side note: your app can have multiple custom URL schemes.
For example, you can have "my-app-campaign" and "my-app-payment" respectively

Then check the prefix of url like 

```swift
if url.absoluteString.hasPrefix("my-app-payment") {
    return RedirectComponent.applicationDidOpen(from: url)
} else {
    ...
}
```

**Comment by Abdo-codes** [comment]
That's exactly how I did it, thanks @descorp !
