### ISSUE TITLE
[BUG] Billing address is sometimes nil when submitting payment details

### ISSUE THREAD

**Issue by nscille** [Adyen/adyen-ios#1066]
**Describe the bug**
When submitting payment details, if the country selected does not have a state/province field (for example, United Kingdom), then `data.billingAddress` will be `nil`.

**To Reproduce**
1. Select a country without a state/province field
2. Enter all card and billing address details
3. Submit the payment details

**Expected behavior**
`data.billingAddress` should not be `nil`.

**Smartphone:**
 - Device: iPhone 13 simulator
 - OS: iOS 15.5
 - SDK Version: 5.0.0

**Additional context**
The bug does not occur if, before submitting the details, you change to a different country that has a state/province field (for example, Ukraine), fill in this field, then change back to a country without a state/province field.

**Comment by nscille** [comment]
I've also noticed this issue can occur with countries that do have a state/province field. If you try and submit your payment details, but leave the state/province field blank, then the billingAddress object will be nil.

**Comment by lpuentes19** [comment]
I've noticed that `PaymentComponentData.billingAddress` (from the `didSubmit` delegate method) is nil when you don't add a value in the _optional_ Apartment / Suite field. I'm on the test environment, using a Discover card, US is selected as country, the apartment field is the only field that is empty. As far as `CardComponent.Configuration()`, we have `billingAddress.mode` set to `.full`, `countryCodes` to ["US", "CA"], `showsHolderNameField` set to `true`, and `requirementPolicy` is set to `.required` by default.

Please let me know if you need any other info. @mohammedDehairy @descorp @neelSharma12

**Comment by erenbesel** [comment]
Hi @nscille and @lpuentes19 

Thanks a lot for catching this, we are working on a fix!

**Comment by lpuentes19** [comment]
@erenbesel Glad this is being worked on! Any idea on when this fix will be released?

**Comment by erenbesel** [comment]
Hey @lpuentes19, this is fixed for v4 with 4.10.2.
For v5, it will be included in the next 5.1.0 (estimated mid-end of Jan)

**Comment by lpuentes19** [comment]
@erenbesel Ok, thanks. Just to confirm, will this also address the issue with the billing address coming back as nil if there is no value entered in the _Apartment / Suite_ field? I read in the release notes that it will cover the issue when the selected country doesn't include a state or province field, but doesn't mention anything about the Apartment / Suite field so want to double check that this will also be fixed in the 5.1.0 release.

**Comment by erenbesel** [comment]
@lpuentes19 yes, it will also be fixed!

**Comment by lpuentes19** [comment]
@erenbesel Any update on a more accurate release date for this?

**Comment by erenbesel** [comment]
Hey @lpuentes19 sorry for the delay!
We are preparing the release actions, so Next Monday should be good!

**Comment by erenbesel** [comment]
@lpuentes19  5.1.0 was released yesterday
