### ISSUE TITLE
[Feature] Is it possible to add a border all around the textField's and not have it be just a line below the text? Modify all of the input field's properties?

### ISSUE THREAD

**Issue by lpuentes19** [Adyen/adyen-ios#1069]
**Is your feature request related to a problem? Please describe.**
Is it possible to add a border all around the textField's and not have it be just a line below the text? Modify all of the input field's properties? 

**Describe the solution you'd like**
If not, I think providing users the ability to adjust the input field's borders would be great or at least offer different UI templates, if you don't want users to have full control. 

**Describe alternatives you've considered**
No alternatives from what I can see. I can adjust font, tintColor, textAlignment, and such, but I can't modify the border.

**Additional context**
I'm pretty sure this isn't possible after looking at the code, but wanted to check here and submit a feature request in case it isn't. @neelSharma12

**Comment by descorp** [comment]
Hey @lpuentes19 

Thanks for suggestion!
Could you provide some samples of what do you mean?

Our UIs are based on our corporate design guidelines. So our design team will evaluate new additions.

From where we stands - it is not only about the border alone, but there also will be padding, thickness, colour(s) e.t.c
Also, providing boarder will lead to a massive(?) redesign.
Despite that we are always keen to help our merchants to achieve the desired UI, we do not want to open a pandora box of providing all possible UI customization. 

I can suggest you to fork our code. If you think the result is easily achievable - you are absolutely welcome to create a PR and we will incorporate those UI changes.

**Comment by lpuentes19** [comment]
@descorp Yeah, I understand this may be a heavy lift and require input & collaboration with other teams. No worries if this can't be implemented, just wanted to suggest having different flavors of UI we can choose from, assuming Adyen would prefer us to not have complete control in modifying the UI. 

Thank you for the suggestion. I will take a look and definitely keep that in mind.

**Comment by descorp** [comment]
@lpuentes19 

I hope my previous message did not discourage you :)
We are still very curious to see wireframes / concept of what you are trying to accomplish, so our design team can evaluate it.

Any ideas are always welcome 💚
