### ISSUE TITLE
3DS2 component calling functions on the wrong thread

### ISSUE THREAD

**Issue by xzoky** [Adyen/adyen-ios#1086]
**Describe the bug**
I'm seeing several runtime issues (purple warnings) with the 3DS2 SDK.

**To Reproduce**
1. Using the Drop-in
2. Perform a 3DS2 flow with challenge

**Expected behavior**
No warnings appear

**Screenshots**
<img width="1029" alt="Screen Shot 2022-11-25 at 14 23 06" src="https://user-images.githubusercontent.com/339784/204044716-3d896a29-d721-4906-99b1-3c0761300630.png">
<img width="1038" alt="Screen Shot 2022-11-25 at 14 23 27" src="https://user-images.githubusercontent.com/339784/204044720-beb06a5a-9f6c-42c6-ae21-7b9696c6796a.png">

**Smartphone (please complete the following information):**
 - Device: Simulator (iPhone 14 Pro)
 - OS: iOS 16.1
 - SDK Version: 5.0.0

**Additional context**
On my machine, the issues appeared while I was running a UI test. Maybe the issue is specific to that sort of testing environment, but I doubt it.

**Comment by mohammedDehairy** [comment]
@xzoky Thanks for flagging this issue, we'll look into it.

FYI, this warning is originating from the 3DS2 SDK unfortunately, so maybe it makes more sense to add the issue in the 3ds2 SDK repo?
https://github.com/Adyen/adyen-3ds2-ios/issues

**Comment by xzoky** [comment]
@mohammedDehairy ah sorry about that, I didn't realize the 3DS2 SDK had its own repo 😅
I've moved the issue there: https://github.com/Adyen/adyen-3ds2-ios/issues/29

**Comment by mohammedDehairy** [comment]
Thanks @xzoky ! :-)
