### ISSUE TITLE
Card component: broken UI test

### ISSUE THREAD

**Issue by xzoky** [Adyen/adyen-ios#1087]
**Describe the bug**

In a UI test, I'm attempting to fill out the credit card form:
```swift
staticTexts["AdyenDropIn.PaymentMethodListComponent.Credit Card.titleLabel"].tap()
typeText(creditCard.number.removingCharactersNotIn(set: .decimalDigits))
textFields["AdyenCard.CardComponent.expiryDateItem.textField"].tap()
typeText(creditCard.expiration.removingCharactersNotIn(set:. decimalDigits))
textFields["AdyenCard.CardComponent.securityCodeItem.textField"].tap()
typeText(creditCard.securityCode)
```

After typing the expiration date, the UI test hangs and this gets printed to the console:
```
t =    26.95s    Wait for com.busbud.busbud.alpha to idle
t =    86.99s    App animations complete notification not received, will attempt to continue.
```

<details>
<summary>Full log</summary>
<pre><code>
t =    23.37s Fill out credit card information
t =    23.37s     Tap "AdyenDropIn.PaymentMethodListComponent.Credit Card.titleLabel" StaticText
t =    23.37s         Wait for com.busbud.busbud.alpha to idle
t =    23.40s         Find the "AdyenDropIn.PaymentMethodListComponent.Credit Card.titleLabel" StaticText
t =    23.45s         Check for interrupting elements affecting "AdyenDropIn.PaymentMethodListComponent.Credit Card.titleLabel" StaticText
t =    23.50s         Synthesize event
t =    23.82s         Wait for com.busbud.busbud.alpha to idle
t =    24.32s     Type '5212345678901234' into Target Application 'com.busbud.busbud.alpha'
t =    24.32s         Wait for com.busbud.busbud.alpha to idle
t =    24.38s         Find the Target Application 'com.busbud.busbud.alpha'
t =    24.46s         Check for interrupting elements affecting "Busbud α" Application
t =    24.52s         Synthesize event
t =    24.55s             Get number of matches for: Elements containing elements matching predicate 'hasKeyboardFocus == 1'
t =    25.09s         Wait for com.busbud.busbud.alpha to idle
t =    25.16s     Tap "AdyenCard.CardComponent.expiryDateItem.textField" TextField
t =    25.16s         Wait for com.busbud.busbud.alpha to idle
t =    25.41s         Find the "AdyenCard.CardComponent.expiryDateItem.textField" TextField
t =    25.49s         Check for interrupting elements affecting "AdyenCard.CardComponent.expiryDateItem.textField" TextField
t =    25.55s         Synthesize event
t =    25.87s         Wait for com.busbud.busbud.alpha to idle
t =    26.23s     Type '0330' into Target Application 'com.busbud.busbud.alpha'
t =    26.23s         Wait for com.busbud.busbud.alpha to idle
t =    26.49s         Find the Target Application 'com.busbud.busbud.alpha'
t =    26.53s         Check for interrupting elements affecting "Busbud α" Application
t =    26.59s         Synthesize event
t =    26.61s             Get number of matches for: Elements containing elements matching predicate 'hasKeyboardFocus == 1'
t =    26.95s         Wait for com.busbud.busbud.alpha to idle
t =    86.99s     App animations complete notification not received, will attempt to continue.
t =    86.99s     Tap "AdyenCard.CardComponent.securityCodeItem.textField" TextField
t =    86.99s         Wait for com.busbud.busbud.alpha to idle
t =   147.05s     App animations complete notification not received, will attempt to continue.
t =   147.05s         Find the "AdyenCard.CardComponent.securityCodeItem.textField" TextField
t =   147.15s         Check for interrupting elements affecting "AdyenCard.CardComponent.securityCodeItem.textField" TextField
t =   147.20s         Synthesize event
t =   147.52s         Wait for com.busbud.busbud.alpha to idle
Test Case '-[BusbudUITests.CheckoutTests test3DSPurchaseFlow]' exceeded execution time allowance of 3 minutes. The test may have hung; check Xcode's test report for additional diagnostics. If the test requires additional time, use -[XCTestCase executionTimeAllowance] or one of xcodebuild's command-line overrides.
</code><pre>
</details>

**To Reproduce**
1. In a UI test
2. Navigate to the drop-in's Card component
3. Attempt to fill out the card number, expiration date, and security code

**Expected behavior**
As part of a UI test, I should be able to programatically fill out the card form

**Screenshots**
While the UI test runner waits for the app's animation complete notification, this is what the app looks like:

<img src="https://user-images.githubusercontent.com/339784/204054249-071657a4-8bc4-4269-bfd2-9b3b1256cb1f.png" width=393pt>

**Smartphone (please complete the following information):**
 - Device: Simulator (iPhone 14 Pro)
 - OS: iOS 16.1
 - SDK Version: 5.0.0

**Additional context**
Perhaps there's a `UIView` animation block somewhere that never finishes?

I think whatever mechanism is used to automatically switch the keyboard focus to the security code field when the last digit of the expiration date is typed might have something to do with this issue.
With version 4.x.x of the SDK, I was able to do this:
```swift
textFields["AdyenCard.CardComponent.expiryDateItem.textField"].tap()
typeText((creditCard.expiration + creditCard.securityCode).removingCharactersNotIn(set: .decimalDigits))
```
However, as of 5.0.0 this seems to fail on my CI environment (Circle CI).

**Comment by descorp** [comment]
Hey @xzoky 

> App animations complete notification not received, will attempt to continue.

Indeed, there is an infinite "blinking" animated icon on CVC field that `XCTestCase` keeps awaiting.

For me on v5 passing combined value of Expiration date and CVC works as expected:

```swift
        wait(for: [app.textFields["1234 5678 9012 3456"]])

        app.textFields["1234 5678 9012 3456"].typeText("5454545454545454")
        wait(for: [app.textFields["MM/YY"]]) // Delay here is necessary

        app.textFields["MM/YY"].tap()
        app.textFields["MM/YY"].typeText("330737") // here date is 03/30 and CVC 737

        app.buttons["Pay €174.08"].tap()
```

We will investigate possibility of adding `-UITests` flag to CVC field to disable the animation.
Thank you for feedback!

**Comment by Swaxer** [comment]
@xzoky Hey! We got around this by adding this to our app view. Where `UITEST_DISABLE_ANIMATIONS` is set to true when we run our tests
```
.onAppear(perform: {
        // HACK: The Adyen drop-in modal is currently lagging with UI tests causing the purchase test to take up to 1min
        // This disables the animation for the app, hence reducing the test time
        if (ProcessInfo.processInfo.environment["UITEST_DISABLE_ANIMATIONS"] == "YES") {
          UIView.setAnimationsEnabled(false)
        }})
```
