### ISSUE TITLE
No way of removing stored cards(?) from Drop-In component

### ISSUE THREAD

**Issue by nyaray** [Adyen/adyen-ios#1099]
**Is your feature request related to a problem? Please describe.**
When a customer has stored a card, they might sometimes want to remove it (lost, changed jobs, etc), but can't do it.

**Describe the solution you'd like**
There should be an option to remove your stored cards.

**Comment by mohammedDehairy** [comment]
@nyaray ,

Thanks for reaching out!

This feature already exist (depending on what version of the SDK you're using), you can enable this feature by setting 
- `dropInConfiguration.paymentMethodsList.allowDisablingStoredPaymentMethods` to `true`,
-  implement the `StoredPaymentMethodsDelegate` and assign the `dropInComponent.storedPaymentMethodsDelegate`
- in the implementation of `StoredPaymentMethodsDelegate` , you need to call [the API endpoint `Recurring/v69/disable`](https://docs.adyen.com/api-explorer/Recurring/68/post/disable)

**Comment by nyaray** [comment]
@mohammedDehairy thank you for the clarification, could you point me to where I can find out about this, I couldn't find any documentation when search both through google and the pages. I must've just not looked in the right place.

**Comment by erenbesel** [comment]
Hello @nyaray, in the docs it's under [Tokenization](https://docs.adyen.com/online-payments/tokenization/managing-tokens#disable-stored-details) so it may not be the easiest to find :) 

You can also see the delegate's usage in our sample project in the file [IntegrationExampleDropIn](https://github.com/Adyen/adyen-ios/blob/4.10.2/Demo/Common/IntegrationExampleDropIn.swift#L111-L128).

Hope this helps, let us know if you have more questions!

**Comment by nyaray** [comment]
Hi,

It would be good if there was something that described this in the vicinity of https://docs.adyen.com/payment-methods/cards/ios-drop-in?tab=stored-4_2#stored-card-payments, which is where I happened to end up when looking for documentation about this. It doesn't exactly help that something one would consider "removing" or "deleting" is named "disabling", which harms the, eh, findability of the functionality. I didn't do the initial implementation and hadn't read up as much as my implementing colleague did, so I wasn't aware.

Thanks again for the pointers and help!

/Emilio
