### ISSUE TITLE
unexpectedData

### ISSUE THREAD

**Issue by MaeseppTarvo** [Adyen/adyen-ios#11]
Can anyone please explain me what is the "unexpectedData" error? I tried every possible secret key or api key but the response is always "unexpectedData". What should you do? It is happening even with the demo application.

**Comment by joostvandijk** [comment]
Hey @MaeseppTarvo,

It seems like we're currently experiencing some issues with our demo server. I'll let you know when it's fixed!

Kind regards,
Joost

**Comment by joostvandijk** [comment]
Hi @MaeseppTarvo,

The demo server should be back online. Could you check again?

Kind regards,
Joost

**Comment by MaeseppTarvo** [comment]
Hey @joostvandijk,

Yep, now it is working well :)

**Comment by joostvandijk** [comment]
@MaeseppTarvo Great! Let us know if you run into any further issues.

**Comment by loveuqian** [comment]
@joostvandijk 

![image](https://user-images.githubusercontent.com/9745332/33471462-2856c226-d633-11e7-88b6-42a85a32a682.png)

**Comment by joostvandijk** [comment]
Hi @loveuqian,

Can you show us the data you get returned from the `/setup` call made to the Checkout API or demo server?
