### ISSUE TITLE
ApplePayComponent not working "out of the box"

### ISSUE THREAD

**Issue by d4rkd3v1l** [Adyen/adyen-ios#110]
In `paymentRequest` the `ApplePayComponent` accesses a `payment` property, which is nil for me, and therefore leads to errors, as indeed the `countryCode` and `currencyCode` are not being set.
My "solution" is now to manually create a `Payment`, setting those values accordingly, and then assigning it to the components `payment` property.

I don't think it is intended to use it like that, is it? It would be nice if anything, needed to make to component work at all, will be "requested" by it's initializer. I think that's actually already the case for any other component.

Another issue is, that it seems like `stopLoading` must be called in order to finish the payment process here, which feels quite unintentionally for me.

**Comment by joostvandijk** [comment]
Hi @d4rkd3v1l,

The way you described is indeed how it's intended to work right now. You have to create a `Payment` structure describing the payment and then set it to the `payment` property. However, it clearly should be in the initialiser instead.

I'll make the change and ship it with the next release.

The `stopLoading` is needed because Apple Pay requires the invocation of a completion handler in order to finish.

Best,

Joost

**Comment by d4rkd3v1l** [comment]
@joostvandijk Thanks for you response. Good to hear that it seems like I did everything correctly.

I would be awesome if you could outline this in your docs, or give a hint about it in a `///`-comment that it's necessary to call `stopLoading`. 
The Payment necessity should already be clear, once added to the initializer. :+1:

**Comment by joostvandijk** [comment]
@d4rkd3v1l We're working on per-component documentation pages! In the meanwhile, I'll add a note to the in-code comments. Thanks for your feedback!

**Comment by joostvandijk** [comment]
Add the initializer in 3.1.3. :) New docs page is in the works!

**Comment by strobec** [comment]
Are there any examples of code for the use of ApplePayComponent (particularly the requirement of stopLoading() )?

**Comment by d4rkd3v1l** [comment]
Prior to 3.1.3 you had to create a `Payment` instance and assign this to the `ApplePayComponent`.

Something like this:
```
let items: [PKPaymentSummaryItem] = ... // create them like described by apple docs
let payment = Payment(amount: ..., currencyCode: ...)// provide amount and currency code
let component = ApplePayComponent(paymentMethod: applePayPaymentMethod, merchantIdentifier: "your.merchant.id", summaryItems: items)
component.payment = payment
```

And then call `stopLoading` after one of the `PaymentComponentDelegate` or `ActionComponentDelegate` was being called and you got an answer/failure from your BE.
