### ISSUE TITLE
Cyclic dependency in XCode

### ISSUE THREAD

**Issue by erik-kallen** [Adyen/adyen-ios#1100]
I'm not sure if Adyen is really to blame here, but the problem started happening after we upgraded to version 5 of this package.

We are using React Native, and the second time I build my project, I get a cyclic dependency error.

**To Reproduce**
1. Build my project in XCode
2. Build my project again
3. I get an error saying this

**Expected behavior**
The build should work

**Actual behavior**
```
Cycle in dependencies between targets 'ExpoAdapterGoogleSignIn' and 'AdyenNetworking'; building could produce unreliable results.
Cycle path: ExpoAdapterGoogleSignIn → ExpoModulesCore → React-Core → RCT-Folly → DoubleConversion → AdyenNetworking → ExpoAdapterGoogleSignIn
Cycle details:
→ Target 'ExpoAdapterGoogleSignIn': Libtool /Users/erikkallen/Library/Developer/Xcode/DerivedData/myapp/Build/Products/Debug-iphoneos/ExpoAdapterGoogleSignIn/libExpoAdapterGoogleSignIn.a normal
○ Target 'ExpoAdapterGoogleSignIn' has compile command with input '/Users/erikkallen/source/nyapp/ios/Pods/Target Support Files/ExpoAdapterGoogleSignIn/ExpoAdapterGoogleSignIn-dummy.m'
○ Target 'ExpoAdapterGoogleSignIn' has dependency on Target 'ExpoModulesCore' via the “Target Dependencies“ build phase
○ That command depends on command in Target 'ExpoModulesCore': script phase “Copy generated compatibility header”
→ Target 'ExpoModulesCore'
→ Target 'React-Core'
→ Target 'RCT-Folly' has dependency on Target 'DoubleConversion' via the “Target Dependencies“ build phase
→ Target 'DoubleConversion' has compile command with input '/Users/erikkallen/source/myapp/ios/Pods/Target Support Files/DoubleConversion/DoubleConversion-dummy.m'
○ That command depends on command in Target 'AdyenNetworking': script phase “Copy generated compatibility header”
→ Target 'AdyenNetworking' has compile command with input '/Users/erikkallen/source/myapp/ios/Pods/Target Support Files/AdyenNetworking/AdyenNetworking-dummy.m'
○ Target 'AdyenNetworking' has Swift tasks blocking downstream compilation
```

Have the dependencies for AdyenNetworking changed in some way?

**Comment by descorp** [comment]
Hey @erik-kallen 

It is quite unexpected that `AdyenNetworking` have dependency on `ExpoAdapterGoogleSignIn` 😅

> the second time I build my project, I get a cyclic dependency error.

So if you clean up dependencies(delete `.lock` files and `node_module` folders) it works again?

---

FYI we have [Drop-in and Components for React Native](https://github.com/Adyen/adyen-react-native). It is in BETA state

**Comment by erik-kallen** [comment]
Yes, I don't think the dependency is directly there, that's why I'm super confused. The cyclic dependency seems to have something to do with some “Copy generated compatibility header” action.

Nice, I might check out the react native package, but using that would mean rewriting and retesting code, so I' mot sure when/if we will do that.

**Comment by descorp** [comment]
`Copy generated compatibility header` is Cocoapods header.

There are [similar reports](https://github.com/CocoaPods/CocoaPods/issues/7833) about Cocoapods and `clean build (cmd + shift + K)` seems like a one-time solution.

**Comment by erik-kallen** [comment]
But did something change, in any way, regarding dependencies in AdyenNetworking, that could trigger this Cocoapod issue now but not before?

If not, I am happy to accept that Adyen is innocent.

**Comment by descorp** [comment]
>  did something change

Not really: both [v4](https://github.com/Adyen/adyen-ios/blob/4.10.0/Adyen.podspec#L80) and [v5](https://github.com/Adyen/adyen-ios/blob/5.0.0/Adyen.podspec#L85) rely on the same 1.0.0 version of `AdyenNetworking`.

Maybe the problem caused by CocoaPods cache after updating to `v5`: 
- Expo/React dependency engine on top of Cocoapods are failing to do `pod update` ?

Does it work if you run `pod update` on Xcode project after EXPO generated it?

---

TBH we still lacking understanding of Expo. Even `npm install` causing troubles sometimes.

**Comment by erik-kallen** [comment]
Thank you for your help. I have no idea what really causes it, and my other team members don't seem to get the problem to the same exten.

But if nothing changed in AdyenNetworking, I'm sorry for wasting your time
