### ISSUE TITLE
[BUG] ACHDirectDebit Payment Amount Not Showing

### ISSUE THREAD

**Issue by lpuentes19** [Adyen/adyen-ios#1101]
**Describe the bug**
On the card component, you're able to show the amount on the pay button. On the Direct Debit component, I'm not able to get the amount to show. Because the card component shows it, I assumed that the direct debit component should have it which is why I marked this as a bug and not a feature request. If I need to switch that, please let me know.   

**To Reproduce**
1. Open Direct Debit component and make sure to inject a Payment object into the Adyen Context initializer. 
2. Notice the pay button does not include the payment total.

**Expected behavior**
See the payment total next to the "Pay" text on the button just like the card component. 

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS16
 - SDK Version 5.0.0

**Comment by erenbesel** [comment]
Hello @lpuentes19 
Thanks for reaching out! That's a fair expectation :) 

I will check with our product team and see what they think.

**Comment by erenbesel** [comment]
@lpuentes19 currently this is intended. But we are thinking of adding the ability to modify/hide the pay button in the future. So modifying the title could be a part of it as well.

Sorry for the inconvenience for now :)

**Comment by lpuentes19** [comment]
Sounds good. Thanks for getting back to me on this @erenbesel.
