### ISSUE TITLE
Cannot find type `APIRequest` in Scope

### ISSUE THREAD

**Issue by balaji101010** [Adyen/adyen-ios#1102]
**Describe the bug**
I get this error when I try to run the project

**Expected behavior**

**Screenshots**
![Screenshot 2022-12-15 at 12 50 49 PM](https://user-images.githubusercontent.com/60033899/207797708-21b42c39-de1c-43c3-ac00-8abf2cdf8801.png)

**Comment by erenbesel** [comment]
Hello @balaji101010, is this our Demo app are you using some files on another sample project?

Which version/branch is it?

If our Demo app, do you see the `APIRequest` file? Maybe a full clean and re-build would fix

**Comment by balaji101010** [comment]
Its not demo app

I have integrated adyen in ios side and calling from flutter via platform channel
whenever I run I get this error 
@erenbesel

**Comment by erenbesel** [comment]
@balaji101010 `APIRequest` is created for our Demo App, it is not part of the Adyen Checkout iOS SDK.

To create an API request struct, please conform to the `Request` protocol, not the `APIRequest`.

Hope this helps!

**Comment by balaji101010** [comment]
Ok Thanks for the idea !
