### ISSUE TITLE
iOS Drop-in - 500 Bad request

### ISSUE THREAD

**Issue by anton0243** [Adyen/adyen-ios#1105]
Hello!
i am trying to initialize **drop-in ios 5.0** with **react native** (my custom module) according to this guide:
https://docs.adyen.com/online-payments/ios/drop-in

When I click on the **Pay** button i get error: `500 Bad request`:
![photo_2022-12-16_17-26-02](https://user-images.githubusercontent.com/12491780/208454141-0131e0c4-4cd5-4906-b1ef-b617c7dfa7f2.jpg)

Seems the documentation is not quite correct. 
For example:

Doc:
`let apiContext = APIContext(clientKey: clientKey, environment: Environment.test)`
Xcode says:
`try APIContext(environment: Environment.test, clientKey: clientKey)`

Doc:
```
let configuration = AdyenSession.Configuration(sessionIdentifier: sessionId,
                                               initialSessionData: data,
                                               adyenContext: adyenContext)
```                                   
Xcode says:
```
let configuration = AdyenSession.Configuration(sessionIdentifier: sessionId
                                                   initialSessionData: sessionData,
                                                   context: self.adyenContext!)
```
                                                   
`AdyenSession.initialize` should be wrapped `DispatchQueue.main.async`      

Doc:
`let dropInConfiguration = DropInComponent.Configuration(adyenContext: adyenContext)
`
Xcode says:
`dropInConfiguration = DropInComponent.Configuration()`     

Doc:
```
let dropInComponent = DropInComponent(paymentMethods: session.sessionContext.paymentMethods,
                                      configuration: dropInConfiguration) 
```  
 Xcode says:
`let dropInComponent = DropInComponent(paymentMethods: session!.sessionContext.paymentMethods, context: adyenContext!,configuration: dropInConfiguration!)`      

7. Show Drop-in in your app. This place is not very clear in the documentation.       
`present(dropInComponent.viewController, animated: true)`

I looked at the example in your repository and do it like this:      

```
extension UIViewController {
    internal static var topPresenter: UIViewController? {
        var topController: UIViewController? = UIApplication.shared.keyWindow?.rootViewController
        
        while let presenter = topController?.presentedViewController {
            topController = presenter
        }
        return topController
    }
}

extension AdyenModule: PresentationDelegate {
    internal func present(component: PresentableComponent) {
        self.present(component)
    }
}
```
 in my class:
```
func present(_ component: PresentableComponent) {
    currentPresenter = UIViewController.topPresenter
    currentPresenter?.present(component.viewController, animated: true)
  } 
```
and then:
`present(component: dropInComponent!)`                                               

Help me please, any ideas what could have gone wrong and what should I check again?

**Comment by descorp** [comment]
Hey @anton0243

Great thanks for your feedback! 💚
We will update our documentation accordingly!

---

> Help me please, any ideas what could have gone wrong and what should I check again?

I don't think the problem is with the iOS code. Most likely something is off with a payment method or it's configuration on your CA.

What payment method is this?
Have you tried other payment methods? Credit cards?

---

BTW, we have [Drop-in and Component for React Native](https://github.com/Adyen/adyen-react-native).  
We are working on first public release Q1 2023.

## :warning: 
 
 I would advice against using [sessions](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/sessions) for React Native in favor of [three endpoint integration](https://docs.adyen.com/online-payments/ios/drop-in/integrated-before-5-0-0). 
Our Android SDK does not support 'sessions' yet.

**Comment by anton0243** [comment]
Hey @descorp Thanks for your answers!

```
Great thanks for your feedback! 💚
We will update our documentation accordingly!
```
Thanks!

```
I don't think the problem is with the iOS code. Most likely something is off with a payment method or it's configuration on your CA.

What payment method is this?
Have you tried other payment methods? Credit cards?
```
Yes, I tried to use adyen test cards and my card from the wallet. Same result..
I will try to check CA, thanks.

```
BTW, we have [Drop-in and Component for React Native](https://github.com/Adyen/adyen-react-native).
We are working on first public release Q1 2023.
```
Will it support sessions or only endpoint integration?

```
I would advice against using [sessions](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/sessions) for React Native in favor of [three endpoint integration](https://docs.adyen.com/online-payments/ios/drop-in/integrated-before-5-0-0).
Our Android SDK does not support 'sessions' yet.
```
It is sad. Is there any approximate dates for android?
Do I understand correctly that sessions is more modern implementation that will replace endpoint integration in the future? Or I'm wrong?

**Comment by descorp** [comment]
@anton0243 

> Do I understand correctly that sessions is more modern implementation that will replace endpoint integration in the future?

It will not replace endpoint integration. Both approaches will coexist.

> Will it support sessions or only endpoint integration?

"Drop-in and Component for React Native" does not yet support sessions due to the fact that our native Android SDK
does not support it. We expect it around Q3 2023, but no feasible timeline just yet.

> Yes, I tried to use adyen test cards and my card from the wallet. Same result..

This error could happen if our backend sent a POST redirect instead of GET redirect.
What `returnURL` are you using? "http://" or Custom URL scheme ? 

**UPD**

This description of returnURL is copied from WEB and incorrect for iOS:
https://docs.adyen.com/online-payments/ios/drop-in#create-a-payment-session

You can find out more about `returnURL` here 
https://docs.adyen.com/online-payments/ios/drop-in/integrated-before-5-0-0#step-3-make-a-payment

**Comment by anton0243** [comment]
@descorp 

Got it, thanks a lot for your answers. More clarity now :)

About `returnURL`
```
This error could happen if our backend sent a POST redirect instead of GET redirect.
What returnURL are you using? "http://" or Custom URL scheme ?
```
Yep `http://localhost:3000/#/...`
If I understand correctly, this is not correct?
Should be something like: "my-app://"?

**Comment by descorp** [comment]
> Should be something like: "my-app://"?

This is expected, yes. You can define a [custom URL scheme](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app) for your app.

**Comment by anton0243** [comment]
> 

Got it, thanks, I I'll try and let you know if it's works!

**Comment by descorp** [comment]
This thread is enormous amount of improvements for our documentation 💚
We are grateful for your feedback!

**Comment by anton0243** [comment]
@descorp I return to you after testing. You're right, the reason for the 500 error is an incorrect `returnUrl`.
Thank you very much 🙌
Now I'm stuck on the return screen 🙈 but that's another story 😄

**Comment by descorp** [comment]
@anton0243 

Do you need help with [handling redirect](https://docs.adyen.com/online-payments/ios/drop-in/integrated-before-5-0-0#handling-redirects)?
Could you create a new issue for "return screen problem"?

**Comment by anton0243** [comment]
@descorp I was able to make the payment and get `didComplete` but **webview** still won't close. 
I'll create a new issue if I can't handle it. Thanks :)

**Comment by descorp** [comment]
>  webview still won't close.

What do you mean, on "Cancel" click or after  receiving`didComplete`? 
It would not dismiss itself - we expect you to call `dismiss` on your viewController.

**Comment by anton0243** [comment]
@descorp Sorry, i mean this screen:
![photo_2023-01-11_20-33-31](https://user-images.githubusercontent.com/12491780/211889856-4d2689ee-84ab-42bf-b5c1-130cacc75caa.jpg)
Redirect doesn't happen but I get didComplete.

**Comment by descorp** [comment]
> Redirect doesn't happen but I get didComplete.

~~Sorry,  are you sure it is `didComplete`? Not a `didProvide` ?~~

**Comment by anton0243** [comment]
@descorp yes i get `resultCode` but i can't do redirect. Click on "click here" - same.
I can close everything completely only with `dismiss`.

**Comment by descorp** [comment]
Hey @anton0243 

Sorry for confusion, you are working with `sessions`, so sure - it is `didComplete`.

As mentioned above, Dropin/Component does not dismiss itself - we expect you to call `dismiss` on your viewController whenever payment is conducted (with `didComplete` or `didFail`).

**Comment by anton0243** [comment]
@descorp got it, thanks!
