### ISSUE TITLE
How to get pspReference of a payment?

### ISSUE THREAD

**Issue by balaji101010** [Adyen/adyen-ios#1108]
Hello there,

I successfully get the result code in `AdyenSessionDelegate` 

```
 func didComplete(with resultCode: Adyen.SessionPaymentResultCode, component: Adyen.Component, session: Adyen.AdyenSession) {
        
        print("didComplete")
       // Sending result code to flutter
        AppDelegate.shared().flutterResult!(resultCode.rawValue)
    }
```

Now I am not sure how to get the `pspReference` of the payment
Can you please let me know?

Any help is appreaciated. thanks!

**Comment by erenbesel** [comment]
Hey @balaji101010 ,

The `pspReference` is received via a notification webhook to your server. You can see more in our [docs](https://docs.adyen.com/online-payments/ios/drop-in) 
```
- The shopper goes to the checkout page.
- Your server uses the shopper's country and currency information from your client to create a payment session.
- Your client creates an instance of Drop-in using the session data from the server.
- Drop-in shows the available payment methods, collects the shopper's payment details, handles additional actions, and presents the payment result to the shopper.
- Your webhook server receives the notification containing the payment outcome.
```

Hope this helps!

**Comment by balaji101010** [comment]
I have to send the `pspReference` to my server team api when the payment is successful. 
Is there any way to acheive this? @erenbesel

**Comment by erenbesel** [comment]
In the docs I linked above,`Step 3: Get the payment outcome` should help I believe. Your server will receive the final response via a webhook that contains the pspRef as well.

I recommend reading it all of course, if you haven't :)

**Comment by balaji101010** [comment]
Thanks for your response! .so the client side we can't get the `pspReference` right? @erenbesel 
As far as my understanding, whenever the payment is successful then the webhook will be sent to server.
Is it correct?

**Comment by erenbesel** [comment]
Yes exactly. For security reasons, the pspRef is sent via only backend calls. Not in the client.

**Comment by balaji101010** [comment]
Thanks closing this!
