### ISSUE TITLE
A crash occurred while removing cards from sdk.

### ISSUE THREAD

**Issue by mattiosdev** [Adyen/adyen-ios#111]
Hi,
I had 3 cards saved in the SDK. I started deleting from the last one. After removing the second one a crash occurred on line:

`self?.paymentSession?.paymentMethods.preferred.remove(at: index)`

in func:

`public func deleteStoredPaymentMethod(_ paymentMethod: PaymentMethod, completion: @escaping Completion<Result<Void>>)`

Version: 2.8.4

**Comment by joostvandijk** [comment]
Hi @mattiosdev,

This should have been fixed in yesterday's release. Thanks for your patience!

With kind regards,

Joost
