### ISSUE TITLE
iOS Drop-in RedirectComponent in Objective C++

### ISSUE THREAD

**Issue by anton0243** [Adyen/adyen-ios#1110]
Hello! 
I'm trying to do a `redirect` in `react native` as described in the documentation:
https://docs.adyen.com/online-payments/ios/drop-in/integrated-before-5-0-0#handling-redirects

My UIApplicationDelegate is `.mm` file.

Unfortunately this recommendation does not work for me:
https://github.com/Adyen/adyen-ios/issues/77#issuecomment-503543571

I tried to do it this way:

created class:
```
@objc class AdyenObjectiveCBridge: NSObject {
  
  @objc(applicationDidOpenURL:)
  static func applicationDidOpen(_ url: URL) -> Bool {
    let adyenHandled = RedirectComponent.applicationDidOpen(from : url)
    return adyenHandled
  }
}
```

then in my `AppDelegate.mm`:

```
#import "<my-project-name>-Swift.h"

- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options {
  
  BOOL handledAdyen =[AdyenObjectiveCBridge applicationDidOpenURL:url];

  return handledAdyen;
}
```
But i get an error: 
`Use of undeclared identifier 'AdyenObjectiveCBridge'
`

Is there a way to do this in `AppDelegate.mm`?

**Comment by erenbesel** [comment]
Hey @anton0243 ,

Is the line `#import "<my-project-name>-Swift.h"` as is in the code? The bridging header should have a real name with your project.

Just making sure :)

**Comment by anton0243** [comment]
Hello @erenbesel,
Yes yes, i use the real project name :)

**Comment by anton0243** [comment]
Sorry, i had a problem with `bridging header` file. It works :)

**Comment by descorp** [comment]
Hey @anton0243 

Just for the record, how did you make Swift code work for '.mm' ?

**Comment by anton0243** [comment]
@descorp I deleted all swift files and recreated it, xcode created correct "-Bridging-Header.h" file.
After that the code i showed above works :)
