### ISSUE TITLE
No entitlement for merchant identifier

### ISSUE THREAD

**Issue by mkharibalaji** [Adyen/adyen-ios#112]
Hi Team,
        I am using Adyen 2.8.3 iOS dropin SDK and when i click the Apple Pay after getting the dropinui i am getting this error in XCode 10.3,

**Failed to present in-app payment interface: Error Domain=PKPassKitErrorDomain Code=4 "No entitlement for merchant identifier: 50" UserInfo={NSLocalizedDescription=No entitlement for merchant identifier: 50}**

I had configured MerchantID : **merchant.com.adyen.xxxxx.test** correctly in my XCode and Apple Pay is Enabled in the entitlements ,But I am getting the error with MerchantID : **"50"**

Thanks & regards,
Hari

**Comment by joostvandijk** [comment]
Hey @mkharibalaji,

It sounds like Apple Pay is not configured correctly on your account. Please contact support@adyen.com, they can help you set it up.

Best,

Joost

**Comment by joostvandijk** [comment]
Hi @hannesjung,

The merchant ID is provided from our backend to the SDK. If you're getting back an incorrect merchant ID, it's likely not configured correctly on our side. support@adyen.com can help you with that.

Best,

Joost

**Comment by Assass1n1191** [comment]
I had exactly same issue and the problem was that I had a typo in code, in merchantIdentifier in PKPaymentRequest object
