### ISSUE TITLE
[NEED ASSIST] iOS Drop-in session -  get the payment outcome

### ISSUE THREAD

**Issue by anton0243** [Adyen/adyen-ios#1122]
Hello!

I'm following this guide and I'm having trouble at this point:
https://docs.adyen.com/online-payments/ios/drop-in#get-the-payment-outcome

Can you please explain to me what data I can use to verify the payment. 

For example adyen web has `onAdditionalDetails` that contains `state.data`
Can we use something like this for IOS drop-in? Or do we only have `resultCode`?

What data should I give my server?

**Comment by anton0243** [comment]
Ah, I think I should look at:
https://docs.adyen.com/online-payments/ios/drop-in/additional-use-cases/additional-actions

I close it for now.

**Comment by anton0243** [comment]
Hello again!
I am working with session and trying to get the `data` in `didProvide` from `AdyenSessionDelegate`.
But `didProvide` is never called.

I found this example in the doc but I don't quite understand what `myPaymentDetailsHandlerInstance` is and how to work with it: 
```
// Create a type that conforms to AdyenSessionPaymentDetailsHandler.
 
// Implement this in AdyenSessionDelegate.
func handlerForAdditionalDetails(in component: ActionComponent,
     session: AdyenSession) -> AdyenSessionPaymentDetailsHandler? {
        if component is ThreeDS2Component {
            // This instance has the didProvide method that the AdyenSession calls.
            return myPaymentDetailsHandlerInstance
        }
     // AdyenSession handles the flow. No additional API request.
     return nil
     }
```

Also in `handlerForAdditionalDetails` component always is `Adyen.RedirectComponent`
It's never `ThreeDS2Component`

There is another doc page. Nothing about `handlerForAdditionalDetails`:
https://docs.adyen.com/online-payments/3d-secure/redirect-3ds2/ios-drop-in#handle-the-redirect-result

I do a `redirect` and I get `didComplete` with `resultCode` but `didProvide` doesn't work for me.

Help me please. 
Should I use `handlerForAdditionalDetails` for session or did I do something wrong?
How can i get the `data` to complete the third step from the doc **(Step 3: Get the payment outcome)**?

**Comment by anton0243** [comment]
I think I partially solved it.
Maybe it will be useful for someone. It looks something like this:

```
extension MyClass: AdyenSessionDelegate {
  func handlerForAdditionalDetails(in component: ActionComponent, session: AdyenSession) -> AdyenSessionPaymentDetailsHandler?
  {
    return self
  }
  ...
```
and:
```
extension MyClass: AdyenSessionPaymentDetailsHandler {
  func didProvide(_ actionComponentData: ActionComponentData,
                  from component: ActionComponent,
                  session: AdyenSession) {
    ...
  }
}
```

But I still don't understand how I can determine in `handlerForAdditionalDetails` when I should call `didProvide` and when `didComplete`

**Comment by erenbesel** [comment]
Hello @anton0243, sorry for the late reply!
To try and explain it a bit; kindly check `AdyenSessionDelegate` first. There you will see it has 2 optional methods for the advanced use cases. (one for you to make the `/payments` call and another for `/payment/details` call.
`handlerForPayments` and `handlerForAdditionalDetails`, their descriptions also may be helpful.

(The code samples are just samples, the `ThreeDS2Component` is just an example to show how you can implement these methods :) )

So when you return a non-nil object from these handlers, that means you have an object conforming to their corresponding protocols (`AdyenSessionPaymentsHandler` for payments and `AdyenSessionPaymentDetailsHandler` for the details call).
And these protocols require the `didProvide` and `didSubmit` functions which the SDK calls to notify you to initiate the payments and/or details calls from your backend.

Sorry for the confusion, I hope it is more clear now.

```
/// Describes the interface to take over the step where additional data is provided for making the payment details call.
public protocol AdyenSessionPaymentDetailsHandler {
    
    /// Invoked when there is new data provided that is required for the payment details call.
    ///
    /// - Parameters:
    ///   - actionComponentData: The data supplied by the action component.
    ///   - component: The component that handled the action.
    func didProvide(_ actionComponentData: ActionComponentData, from component: ActionComponent, session: AdyenSession)
}
```

**Comment by anton0243** [comment]
Hello @erenbesel thanks for your reply! Yes, I've spent some time on this and now it's more clear for me and I managed to get `actionComponentData`.

But in `handlerForAdditionalDetails` how can I determine what should i return (`nil` or for example `self`)
When I try to make a payment with 3d secure in `handlerForAdditionalDetails` **ActionComponent** always is `Adyen.RedirectComponent` instead of `ThreeDS2Component`

This means that I can't do the check like in the documentation:
```
if component is ThreeDS2Component {
            // This instance has the didProvide method that the AdyenSession calls.
            return myPaymentDetailsHandlerInstance
        }
```
Can I somehow check this for drop-in session?

**Comment by descorp** [comment]
Hey @anton0243 

> ActionComponent always is Adyen.RedirectComponent instead of ThreeDS2Component

This is most likely fallback to 3DS1.
You can find more details on how to run 3DS2 via `ThreeDS2Component` [in our docs](https://docs.adyen.com/online-payments/3d-secure/native-3ds2/ios-component). 

If you still have an issues with this - you can always reach out to [Adyen Support](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420) - they will help you out  💚

**Comment by anton0243** [comment]
@descorp Hello! Thank you.
But I only work with ios drop-in session.
Sorry, but there is still thing's I don't understand.
After doing some experiments, I found out that if I call `didProvide` - `didComple` will never be called.

What is the correct flow for a session?
If I use `didComple` - I will never get `additional data` from `didProvide` 
If I understand correctly, I should only use `didProvide` if I need `additional data`?
But what happens if `additional data` is empty in `didProvide`?
Or `didProvide` always have some value?

**Comment by erenbesel** [comment]
Hey @anton0243 
Exactly, `didProvide` is called when there is additional action is required and the `actionComponentData` property will contain the info needed to make the `payment/details` call. It won't be empty.

`didComplete` is the final step. If it is called, it means the flow is finished. Either `AdyenSession` handled the `didProvide` internally or there was no `didProvide` step (depending on the payment method etc).

And for clarification, you are not calling `didProvide` yourself, right? You are referring to the moment it is invoked by this SDK?

**Comment by anton0243** [comment]
@erenbesel Hello!
>And for clarification, you are not calling didProvide yourself, right? You are referring to the moment it is invoked by this SDK?

When I do testing with an Adyen test credit card - it's always `didComplete` with `resultCode`.
`didProvide` from `AdyenSessionDelegate` - never called automatically (although, I pass additional verification with a password and then redirect back).
When I checked the source code `AdyenSessionDelegate` - it doesn't have `didProvide`, only `handlerForAdditionalDetails`.

I'm not sure I know a way to make didProvide be called automatically.

When I added `handlerForAdditionalDetails` to `MyClass`:

```
extension MyClass: AdyenSessionDelegate {
  func handlerForAdditionalDetails(in component: ActionComponent, session: AdyenSession) -> AdyenSessionPaymentDetailsHandler?
  {
    return self
  }
  ...
```
and:

```
extension MyClass: AdyenSessionPaymentDetailsHandler {
  func didProvide(_ actionComponentData: ActionComponentData,
                  from component: ActionComponent,
                  session: AdyenSession) {
    ...
  }
}
```

Now always called only `didProvide` and i get additional data for request `payment/details`
But I'm guessing it's wrong to always return `self` because it will always be `didProvide` and if the user selects a payment method that does not require additional actions - I will not be able to get `didComplete` with `resultCode`.

How to properly handle both cases for sessions? Can I automatically call didComplete or didProvide?
Maybe my concept is wrong? Or should I change my code in some way?

**Comment by erenbesel** [comment]
Hey @anton0243 
If you are making the details call, then there will not be any need for `didComplete`, since `didComplete` is our way of notifying you if you choose not to do these calls. So `didComplete` won't be called if you make the details call yourself. You will have the `resultCode` from the details call response as described [here](https://docs.adyen.com/online-payments/ios/drop-in/additional-use-cases/additional-methods-for-sessions-flow/additional-actions)

>because it will always be didProvide and if the user selects a payment method that does not require additional actions - I will not be able to get didComplete with resultCode.

If a payment method does not require additional actions, meaning there is no need to make a details call, the SDK will call `didComplete` or `didFail` with the result of the payments call (Assuming you are not making payments call yourself, in which case you will have the full response at your hand anyway).

Hopefully it is more clear. Our documentation main page can hopefully provide more details as well.

**Comment by anton0243** [comment]
@erenbesel Thanks a lot for all your answers. 
One last question.
I don't have the opportunity to test the payment methods right now (which does not require additional steps)
I can only get now `didComplete` with `refused`.

Just want to make sure.
This code does not block `didComplete` call for payment methods that do not need additional steps.  
Do I understand correctly?

```
extension MyClass: AdyenSessionDelegate {
  func handlerForAdditionalDetails(in component: ActionComponent, session: AdyenSession) -> AdyenSessionPaymentDetailsHandler?
  {
    return self
  }
  ...
```

**Comment by erenbesel** [comment]
@anton0243 That is correct. The code you shared means you will handle the flow yourself for all payment methods that require an additional action (details call). 
(You can customize this function to return self or `nil` based on your requirements)
For the rest, `AdyenSession` will handle the flow and call `didComplete` or `didFail` etc. (Assuming you are not returning `self` from `handlerForPayments(in component: PaymentComponent, session: AdyenSession) -> AdyenSessionPaymentsHandler?` )

That being said, we definitely recommend you test those methods yourself when you have the chance.

**Comment by anton0243** [comment]
@erenbesel Hmm.. Then my code example is blocking `didComplete`.
But it's a little weird. I always return `self` in `AdyenSessionPaymentsHandler` and if i use invalid test card i still get `didComplete` with `resultCode: refused`.
I thought there is a way to do this automatically, SDK understands which payment method was selected and depending on this, `didProvide` or `didComplete / didFail` is called.

>self or nil

i have only `Adyen.RedirectComponent` in `AdyenSessionPaymentsHandler`. How can I understand that I should return `self` or `nil` if I don't know what the user has chosen?

**Comment by erenbesel** [comment]
If you are returning self from `handlerForPayments(....` as well, that means you are also making the `/payments` call yourself right?
In that case didComplete should not be called at all since you handle the flow by making the payments call.

**Comment by anton0243** [comment]
>If you are returning self from handlerForPayments(.... as well, that means you are also making the /payments call yourself right?

Yes.

>In that case didComplete should not be called at all since you handle the flow by making the payments call.

Got it, thank you so much!
