### ISSUE TITLE
[NEED ASSIST] PayPal redirect not working

### ISSUE THREAD

**Issue by oezguercelebi** [Adyen/adyen-ios#1129]
**Describe the challenge**
Hi there,
we should update Adyen integration to support PayPal. But the redirect back on iOS is not working.

We are using drop-in UI on testing env. Somehow, the redirect is not working on iOS.
What we did:
- Enabled PayPal payment option on our testing env.
- BE added our own returnURL
- I added URL type and checked if that works when put into the Safari browser which tries to open the app
- Android PayPal drop in worked after backend implementation out of the box

I noticed the different Tags, so which Tag should we use? Its a bit confusing because 5.0.0 is older than 4.10.3

**Comment by descorp** [comment]
Hey @oezguercelebi 

> I noticed the different Tags, so which Tag should we use? Its a bit confusing because 5.0.0 is older than 4.10.3

We continue to support V4 and provide patches.

> we should update Adyen integration to support PayPal. But the redirect back on iOS is not working.

Does redirect work for other payment methods?
Have you tried cards, klarna ?

**Comment by oezguercelebi** [comment]
We also planned to add Klarna, but because of the industry, we are in. We cant create a merchant account. But I have found the issue. The scenedelegate method is called `scene(_:openURLContexts:)` and not the one from the appdelegate `application(_:open:options:)` which I assumed. Thanks
