### ISSUE TITLE
Build Failure 3.1.3

### ISSUE THREAD

**Issue by strobec** [Adyen/adyen-ios#113]
Build fails with 3.1.3 with the error:

Use of unresolved identifier 'isModalInPresentation'

In ComponentViewController:

if #available(iOS 13.0, *) {
            isModalInPresentation = true
        }

Using Xcode 10.2, Swift 4.2

**Comment by joostvandijk** [comment]
@strobec As of 3.1.3, Xcode 11 is required as it contains the iOS 13 SDK. If you can't update your Xcode, you can use 3.1.2.

**Comment by strobec** [comment]
Thanks. Is there any documentation available that shows the requirements of each release?

**Comment by joostvandijk** [comment]
Not at the moment, but I'll add it to the README for the next release.

**Comment by strobec** [comment]
Thanks.
