### ISSUE TITLE
[NEED ASSIST] How to show the checkbox for asking to store card details in Drop-In component v5?

### ISSUE THREAD

**Issue by charlotte-nextapps** [Adyen/adyen-ios#1144]
I'm trying to to the checkbox for asking the user to store the card details for future use in the Drop-in component v5.

My Android and Web colleagues are using the Card component and have a boolean `enableStoreDetails` that they can set to true to show the checkbox, but unfortunately, I do not find such setting on the Drop In component v5 for iOS.

Is there a way to do this? I don't find anything related in the documentation.

Thanks in advance!

**Comment by descorp** [comment]
Hey @charlotte-nextapps 

Thanks for reaching out!
Unfortunately, the naming is not always aligned across platforms 😅

On iOS we have [showsStorePaymentMethodField](https://github.com/Adyen/adyen-ios/blob/develop/AdyenCard/Components/Card/CardComponentConfiguration.swift#L59) in `CardComponent.Configuration`
it is 'true' by default, hence no extra action is required to see toggle

**Comment by charlotte-nextapps** [comment]
@descorp Hi, thanks for the quick response! 

Unfortunately, I do not see a checkbox when setting `showsStorePaymentMethodField` to true. Where should I see this checkbox?

![iOS Drop-In component 1](https://user-images.githubusercontent.com/84064799/217777228-c5bcfab7-2596-4eca-8b5d-61f5e4cb5026.jpg)

![iOS Drop-In component 2](https://user-images.githubusercontent.com/84064799/217777234-a8867cf9-26ae-4194-b065-65ac71052a0f.jpg)

**Comment by erenbesel** [comment]
Hey @charlotte-nextapps 
The above solution is for v4 and v5 (without the `/sessions` call). 
If you are using v5 starting with `/sessions` call, then this is only possible on API v70 and above through the request of this `/sessions` call:
- You need to set the [storePaymentMethodMode](https://docs.adyen.com/api-explorer/Checkout/70/post/sessions#request-storePaymentMethodMode) to `askForConsent` to show the checkbox or `enabled` to set it to true without showing the checkbox at all.
- You need to add the property [recurringProcessingModel](https://docs.adyen.com/api-explorer/Checkout/70/post/sessions#responses-201-recurringProcessingModel) with one of its values.

Sorry the docs aren't updated for these. v70 is a new release as well and we are working to update the iOS documentation. Hope this helps!

**Comment by charlotte-nextapps** [comment]
Hi @erenbesel,

Thanks for the explanation! We're using the API v69 indeed, so that explains why it wasn't working. 

Thanks for the quick response!
