### ISSUE TITLE
iOS 13 Challenge drag to dismiss

### ISSUE THREAD

**Issue by IbrahimalKhayat** [Adyen/adyen-ios#115]
Hi, 

We are using the native integration for 3D. We are currently facing an issue with iOS 13 modal presentation. The challenge is dismissible by iOS13 new pull to dismiss gesture. According to the release notes from v3.1.3 this was disabled, however it seems that the fix doesn't work for our case, as the gesture still works after updating to v3.1.3

The problem is mostly due to the fact that didFail is not called which breaking our UI flow. I would appreciate it if you point us in the right direction, for now we are only calling _handle(action)_ on an instance of _ThreeDS2Component_

**Comment by joostvandijk** [comment]
Hi @IbrahimalKhayat,

Since our 3D Secure 2.0 flow is contained in a separate SDK (https://github.com/adyen/adyen-3ds2-ios), the fix from 3.1.3 doesn't apply to this SDK. We'll publish an update soon to fix this for 3DS as well.

Best,

Joost
