### ISSUE TITLE
[NEED ASSIST] Tap to pay SDK

### ISSUE THREAD

**Issue by sger** [Adyen/adyen-ios#1154]
**Describe the challenge**
Hello I'm following the steps in this page https://docs.adyen.com/point-of-sale/ipp-mobile/tap-to-pay/integration-ttp to integrate tap to pay SDK but I can't find any link to the SDK?

can you help?

**Comment by kaphacius** [comment]
@sger hi Spiros.
thanks for contacting us.
the sdk is not available to the general public at the moment. you can get it via your Account Manager or Integration Manager at Adyen.

**Comment by sger** [comment]
thank you @kaphacius but first we need to apply for the service somewhere because can't find anything related for my test account do you have any doc link?

**Comment by kaphacius** [comment]
@sger [here](https://docs.adyen.com/get-started-with-adyen) is the link about setting up your test account. if you have any specific you can contact support@adyen.com

**Comment by Rashmi2410** [comment]
@sger : Were you able to integrate the sdk to your ios app?,Could you please help me with steps u followed?
