### ISSUE TITLE
[NEED ASSIST] What Live Environment To Use

### ISSUE THREAD

**Issue by rcbello** [Adyen/adyen-ios#1159]
What should we check to know what live environment we can use?

We're currently using `.liveAustralia` environment but we recently noticed the SDK is returning an error for payments that require 3DS2, error code `14_0401` (we've filed a help ticket, #3652802). 
They are working okay when we're using `.live` environment, though.
Will there be a functional difference if we use the `.live` environment instead?

This documentation states that we should match the environment with our live endpoints, https://docs.adyen.com/online-payments/ios/drop-in#test-and-go-live. Where can we check in our account to know which environment we can use?

iOS SDK version: 4.10.2

**Comment by erenbesel** [comment]
Hey @rcbello ,

The deprecated `live` points to `liveEurope` so I wouldn't suggest changing your region if you are in Australia. The issue could be backend and/or Customer Area related, but hopefully should be picked up by our support soon to be resolved.

**Comment by descorp** [comment]
Hey @rcbello 

Is it possible that the `/payments` request initiated in EU, then submit device finger print in Australia (or other way around)? 

~~We would like you to contact [Adyen Support](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420) and provide a **pspreference** (you can find one in header of network response from our API). Please add reference to this thread.~~

Sorry, I see that you have already filed a ticket. We will continue investigating. If your ticket do not have **pspreference** - please 
provide one :)

**Comment by rcbello** [comment]
Hi @descorp

Yup, this seems to be what is happening. Closing this ticket. Thanks!
