### ISSUE TITLE
Swift Compiler Error

### ISSUE THREAD

**Issue by maggialejandro-rp** [Adyen/adyen-ios#116]
![Screen Shot 2019-10-10 at 16 17 01](https://user-images.githubusercontent.com/50118796/66599413-89624600-eb79-11e9-823b-7fb6ad3c3791.png)

_Colors.swift_ throw errors on 3.1.4
_ComponentViewController.swift_ on 3.1.3
https://github.com/Adyen/adyen-ios/blob/63af913eff67660eae2816ecdc23254edfd77445/Adyen/UI/Controller/ComponentViewController.swift#L25-L27

XCode 10.2.1

Version 3.1.2 works fine.

**Comment by joostvandijk** [comment]
Hi @maggialejandro-rp,

The latest version requires Xcode 11 (iOS 13) to compile. If you can't upgrade your Xcode yet, it's fine to use 3.1.2.

Best,

Joost
