### ISSUE TITLE
[NEED ASSIST] Error in Card3DS2Authenticator while adding Adyen package

### ISSUE THREAD

**Issue by Cernius** [Adyen/adyen-ios#1161]
I've tried to add Adyen to my XCode project via CocoaPods and Swift Package Manager, but either of them shows the same errors in "Card3DS2Authenticator" file while building. Have I missed something while installing the package?

Errors: 
Cannot convert value of type 'ADYServiceParameters' to expected argument type 'ADYService'
Extra arguments at positions #2, #3 in call
Cannot assign value of type '_' to type 'ADYTransaction'

Swift Package Manager import:
<img width="624" alt="Screenshot 2023-02-23 at 14 54 57" src="https://user-images.githubusercontent.com/55694545/220912254-4d8a5d26-54a3-42b6-a12b-997ce3ecef62.png">

Error screenshot:  
<img width="802" alt="image" src="https://user-images.githubusercontent.com/55694545/220911307-19e45b4e-08d1-418a-8563-c315f7be2f1a.png">

**Comment by descorp** [comment]
Hey @Cernius 

Could you try using "version 5.1.0" instead of "develop" ?
Does it have same error?

**Comment by Cernius** [comment]
Right now I fixed it by only importing the pods I need:
  pod 'Adyen/Encryption'
  pod 'Adyen/Card'
