### ISSUE TITLE
ADYCard file issue  in iOS project

### ISSUE THREAD

**Issue by Bemisal** [Adyen/adyen-ios#117]
Hi 
I have upgraded my Adyen framework to 3.1.3 and now when I am trying to create an instance of **ADYCard** for encoding card details but getting below error . 
Use of unresolved identifier 'ADYCard' 
I have also imported Adyen and Adyen3DS2 frameworks . 
FYI : I am using Xcode Version 11.0

**Comment by joostvandijk** [comment]
From what version were you upgrading? Since quite some time, you can use the [`CardEncryptor`](https://adyen.github.io/adyen-ios/Docs/Classes/CardEncryptor.html) utility and it's `Card` structure to encrypt cards.

**Comment by Bemisal** [comment]
I am upgrading from 1.4.0 to 3.1.3 . if **ADYCard** is no more in use than why it is in new framework? 
**Second thing kindly help me out in Recurring Payment Procedure**
**MY APPROACH** 
For Shopper second time transaction , his card details would be saved so all I have to do is to hit PAYMENT API(https://checkout-test.adyen.com/v49/payments) and in PaymentMethod I will pass **recurringDetailReference** and **cvc** parameters else(if no recurring) shopper have to provide his full card details .

kindly correct me if I am wrong somewhere .

**Comment by joostvandijk** [comment]
ADYCard has been replaced by native Swift types. You can use those, they provide the same functionality.
Regarding the recurring flow, yes, that is the correct approach.

**Comment by Bemisal** [comment]
Hi thanks above issue is fixed . 

Now I have to change my test environment to live environment . can you please explain how I can change my test endpoints to live endpoints 
**Test ENDPOINT**
https://checkout-test.adyen.com/v50/paymentMethods
**LIVE ENDPOINT CREATED BY ME** 
https://1797a841fbb37ca7-Bounce-checkout-live.adyenpayments.com/checkout//v49/paymentMethods

But my live endpoint is not working Could not get any response . 
I have made this live endpoint following these steps . (https://docs.adyen.com/development-resources/live-endpoints) 


kindly correct me if I am wrong somewhere .

**Comment by joostvandijk** [comment]
Hi @Bemisal,

It would be best to contact support@adyen.com regarding this matter. I don't have sufficient access to look into your account to see if anything is still to be configured.

Best,

Joost

**Comment by Bemisal** [comment]
ok thanks ..
