### ISSUE TITLE
[NEED ASSIST] AdyenSession.initialize error:  "countryCode" is missing

### ISSUE THREAD

**Issue by norbertlorinczi** [Adyen/adyen-ios#1170]
Hello there!

I'm trying to implement the iDEAL and the Bancontact component using the Adyen session.
The /sessions call is executed on our server and it is passing me the id and the session data from the response, and I'm using those values to initailize the AdyenSession.
But I'm getting a DecodingError as a result from AdyenSession.initialize(): "No value associated with key CodingKeys(stringValue: \"countryCode\", intValue: nil) (\"countryCode\")."

It seems that the sessions setup call which is executed by the Adyen sdk is successful but the decoding of the response fails since it does not contain any "countryCode".
The country code is specified in the payment object which is used for creating the AdyenSession.Configuration object.
This issue only occurs on iOS, our web and Android implementations works with the session data and id which we receive from the /sessions.

I tried to execute the /sessions call on my side to investigate the issue, it seems if the "countryCode" parameter is missing from the /sessions call we get this behaviour.
Is there a reason why the ios sdk requires the country code to be specified as a param for the /sessions call?(it is just an optional parameter https://docs.adyen.com/api-explorer/Checkout/70/post/sessions#request-countryCode)

**Comment by descorp** [comment]
Hey @norbertlorinczi 

Thanks you for your feedback!
Indeed, it is a bug on SDK side

**Comment by descorp** [comment]
#1171 fixed in this PR

**Comment by naxel** [comment]
When will it be released?

**Comment by descorp** [comment]
@naxel 

it will be part of v5.2.0
In a meanwhile, you can pass a country code from your backend as a workaround.

**Comment by descorp** [comment]
Hey @naxel 

We are still assessing the impact of this.
To understand the priority of this issue, could you describe your use case and why your integration does not provide a `countryCode` value?
Is it possible from your side to provide it as a workaround?

**Comment by norbertlorinczi** [comment]
Hi @descorp !
I see that this was not part of v5.2.0.
Any news on this issue? Or an estimate when it will be released?
Unfortunately sending the "countryCode" from our BE is not possible at the moment.

**Comment by descorp** [comment]
Hey @norbertlorinczi 

There is fundamental issue on iOS SDK that we lately noticed.
Currently, `countryCode` must be provided on backend.

We are considering [a workaround](https://github.com/Adyen/adyen-ios/pull/1171): it will allow BE to skip `countryCode`, but then it must be set on client side.
However it is not final.

**Comment by descorp** [comment]
This issue was addressed in [5.3.0](https://github.com/Adyen/adyen-ios/releases/tag/5.3.0)
