### ISSUE TITLE
Adyen 2.8.5 Compatible with SWift 5.1 - Xcode 11 Support - Cocoapods

### ISSUE THREAD

**Issue by mkharibalaji** [Adyen/adyen-ios#118]
Hi Team,
          Currently we are in a position on not able to use the 3.X version of Adyen.We are in a mode to shift our project to XCode 11 - I heard lot of issues in porting to Xcode 11 with Swift 5.0.1 with the following error
 
 "Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler"

Would like to check whether Adyen 2.8.5 is compatible via Cocoapods in XCode 11 ?

**Comment by joostvandijk** [comment]
HI @mkharibalaji,

Yes, 2.8.5 is compatible with Xcode 11. However, I would strongly recommend to go for 3.x, as 2.x will not receive major updates anymore.

Best,

Joost

**Comment by mkharibalaji** [comment]
Thanks a lot @joostvandijk - You made my day !!!!
