### ISSUE TITLE
[BUG] SearchViewController Dark Appearance

### ISSUE THREAD

**Issue by norbertlorinczi** [Adyen/adyen-ios#1180]
Hello again 😄 

In the iDeal component I found a small UI issue: the SearchViewController, the view controller that is provided by the IdealComponent, in dark appearance the search bar is not changing it's background color.

Steps to reproduce:
1. Set the device/simulator to dark appearance
2. Initialize the AdyenSession
3. Create IdealComponent
4. Present the view controller from the component

![Simulator Screen Shot - iPhone 14 - 2023-03-17 at 12 05 04](https://user-images.githubusercontent.com/60603222/225878022-975df067-9cba-48c1-a7c4-7f1cb84ccb05.png)

**Comment by erenbesel** [comment]
Hey again @norbertlorinczi  :)

We noticed this and fixed already in https://github.com/Adyen/adyen-ios/pull/1162
5.2.0 will have the fix!

Feel free to keep it open till 5.2.0 or close :)

**Comment by norbertlorinczi** [comment]
Great @erenbesel ! 😄 
Thank you!

**Comment by descorp** [comment]
Just to keep it visible..

**Comment by descorp** [comment]
@norbertlorinczi 

Released on [5.2.0](https://github.com/Adyen/adyen-ios/releases/tag/5.2.0)
Please confirm if this one doing the trick for you.

**Comment by descorp** [comment]
I am going to close this ticket for now.
Feel free to reopen or continue the discussion here.
