### ISSUE TITLE
[Docs] Carnet card is not supported on mobile SDK

### ISSUE THREAD

**Issue by sumitbansalhm** [Adyen/adyen-ios#1183]
**Is your feature request related to a problem? Please describe.**
Yes, We can see the Carnet Card in Mexico market for Production. And as per the request [#3677394], Adyen SDK for APP does not support the Cartnet card. This means, if the users have saved the Carnet card in web and try to use the same in APP (native checkout), then /proceed will throw the error.

**Describe the solution you'd like**
support the carnet card for Adyen SDK as well.

**Comment by erenbesel** [comment]
Hey @sumitbansalhm , some more information would be better. 
`CardType` enum has a `.other(String)` case which acts as a fallback mechanism for any card type that is not in its list.

Could you explain what is not working by also showing screenshots of any unexpected step? (remember to hide the card number if it's a real card).

Also, what do you refer to by `/proceed`? Our SDK does not have such a method.

**Comment by sumitbansalhm** [comment]
Hi @erenbesel : We are unable to do any carnet card purchases via mobile SDK. We raised the ticket [#3677394] in Adyen support to find out if we are supporting the carnet card in Adyen native mobile SDKs. And we receive a response that it is not supported via mobile SDK and to raise a ticket via Github to let you guys decide if you have the bandwidth to add this to the rollout map. PFA screenshot for reference.

Now the thing is if we are having a saved carnet card working on the web and it is unable to work under mobile SDK, then it will result in a bad user experience. So we are here to know what can be the next steps for this.

<img width="620" alt="Screenshot 2023-04-03 at 1 11 03 PM" src="https://user-images.githubusercontent.com/129264460/229444324-5b551833-b76d-433d-acf2-b7549061aa3d.png">

**Comment by erenbesel** [comment]
@sumitbansalhm thanks for more details!
We will work on adding more card types as always. In the meantime, what was the issue exactly on the iOS? 
Since `CardType` has a fallback case, I would expect it to still work under this case as `.other("carnet")` .

If you could provide where the flow fails with some logs etc (can't see the support ticket), it would be great for us to fix this the right way.

It is our expectation that this should work as is. So we need to know what you have tested so far and where it failed.

**Comment by sumitbansalhm** [comment]
Hi @erenbesel : Thank you for your response and sorry for the late reply, quite busy with some priority work. I do not have any details handy right away but I can surely reach out to our backend team. 

Meanwhile, would it be possible to you to share any test carnet card details for testing purposes? We are unable to find any on your portal. Thanks again!!

**Comment by erenbesel** [comment]
Hey @sumitbansalhm 
We have asked for such test cards, does seem hard to find some. We will update you when we could get them!

**Comment by erenbesel** [comment]
@sumitbansalhm 
We have asked for such cards. Seems it is a bit tricky to find some indeed. Will update you when we get them!

**Comment by sumitbansalhm** [comment]
Hi @erenbesel : Sorry, it does took a long time to revert. 

We did have a test carnet card before which we used and unable to make an purchase but we don't have any carnet card now. If you can please arrange a test carnet card for us, that would be great.

**Comment by sumitbansalhm** [comment]
Pinging again. Can Adyen provide carnet test cards to test Adyen Carnet card payments?

**Comment by erenbesel** [comment]
Hey @sumitbansalhm , we are also looking into getting one but I am afraid no luck so far. We will let you know if we can one or please contact [Adyen Support](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420)
