### ISSUE TITLE
[NEED ASSIST] Disable Debit option from ApplePayComponent

### ISSUE THREAD

**Issue by rodrigogirao** [Adyen/adyen-ios#1185]
**Describe the challenge**
I have to disable the Debit option from the ApplePayComponent since my company doesn't support this payment type

**Documentation update (optional)**
I'm using version `5.0.0` and couldn't find this option in the docs

**Screenshots**
![image (13)](https://user-images.githubusercontent.com/2385859/229307855-02076505-d995-4593-8175-115a21e51aab.png)

**Comment by descorp** [comment]
Hey @rodrigogirao 

Indeed, we do not have [this option](https://github.com/Adyen/adyen-ios/blob/develop/AdyenComponents/Apple%20Pay/ApplePayConfiguration.swift#LL85C14-L85C14) and by default transaction [allows both credit and debit cards](https://developer.apple.com/documentation/apple_pay_on_the_web/applepaypaymentrequest/1916123-merchantcapabilities).

Thank you for feedback!
We will look into it in upcoming releases

**Comment by descorp** [comment]
related PR #1186

**Comment by rodrigogirao** [comment]
Thanks @descorp

**Comment by descorp** [comment]
@rodrigogirao 

Released on [5.2.0](https://github.com/Adyen/adyen-ios/releases/tag/5.2.0)
Please confirm if this one doing the trick for you.

**Comment by rodrigogirao** [comment]
@descorp I'm gonna test asap

**Comment by descorp** [comment]
I am going to close this ticket for now.
Feel free to reopen or continue the discussion here.
