### ISSUE TITLE
[NEED ASSIST] How to detect card type base on the card number input from user from 5.0.0? 

### ISSUE THREAD

**Issue by chuck-gnaw** [Adyen/adyen-ios#1191]
**Describe the challenge**
I saw that `AdyenScope` and `AdyenCompatible` etc are marked as `@_spi(AdyenInternal)` since version 5.0.0, then how can we detect card types base on card number? any alternatives?

**Comment by erenbesel** [comment]
Hey @chuck-gnaw 
Those methods are intended for the usage between the modules of the library, thus we marked them with spi.
And the card type functions you refer to are not 100% guaranteed (mainly used as fallback), which is another reason to keep it from public use.

You can check the `CardComponentDelegate`. The`didChangeCardBrand....` method returns the detected brand/type in this delegate.

Hope it helps!
