### ISSUE TITLE
[NEED ASSIST] AcceptHeader is required?

### ISSUE THREAD

**Issue by b7anka** [Adyen/adyen-ios#1193]
**Describe the challenge**
I need the acceptHeader field inside the browserInfo object to allow for the addition of a 3ds card
What steps did you take?
Just implemented drop-in component with all configuration based on the example of this repository and the acceptHeader field is nowhere to be found
What is the expected behavior / API ?
broserInfo object to contain the acceptHeader

**Documentation update (optional)**
[https://docs.adyen.com/online-payments/3d-secure/api-reference](https://docs.adyen.com/online-payments/3d-secure/api-reference)
What would you like to see there?
the updated way to get the acceptHeader field

**Screenshots**
![Captura de ecrã 2023-04-14, às 14 48 35](https://user-images.githubusercontent.com/25281887/232064137-f5dd97b3-6d47-491e-a508-3e0a156f956d.png)

Your own example the browser info object only contains the user agent field. How do I get the accept header field?

**Comment by descorp** [comment]
Hey @b7anka 

Thanks for reaching out!

> Your own example the browser info object only contains the user agent field. How do I get the accept header field?

On mobile it is not necessary while your `returnUrl` is a custom URL scheme.
Example:

```json
"returnUrl": "my-app://payment",
```

This is inconsistency in our documentation. Sorry for that 😕
Our API Explorer and some other documentation were written firstly for the web, where `acceptHeader` effecting POST redirect and is an essential parameter.

> I need the acceptHeader field inside the browserInfo object to allow for the addition of a 3ds card

If you **need** to pass this value from your backend - any value will suffice:
Example:
```
*/*
```

---


FYI, we are currently picking between removing `acceptHeader` from Docs and adding stab `*/*`.
Will keep you posted.

**Comment by b7anka** [comment]
Thank you @descorp for your answer
