### ISSUE TITLE
xcode 9.1 + swift 4 cant build Ayden Sdk that installed from pod

### ISSUE THREAD

**Issue by masiiha** [Adyen/adyen-ios#12]
![photo_2017-11-06_19-31-51](https://user-images.githubusercontent.com/26216784/32450478-8619f88c-c329-11e7-94d8-c6ed7d9ffbbc.jpg)

**Comment by joostvandijk** [comment]
Hi @masiihah,

Is your main target set to use Swift 4.0 in the build settings? If so, a ‘pod install’ should fix this, as it would set the pod’s swift version to 4.0 too.

If not, could you follow the steps detailed here? https://github.com/Adyen/adyen-ios/issues/7#issuecomment-334174277

Let me know if this works for you!

Kind regards,
Joost

**Comment by masiiha** [comment]
Hi @joostvandijk 
It works for me and project was built but it crashes on this line
AppearanceConfiguration.default 
![img_0046](https://user-images.githubusercontent.com/26216784/32562767-bccee7a6-c4c4-11e7-9063-38e240767918.JPG)

**Comment by joostvandijk** [comment]
Hi @masiiha
That’s odd. Could you try replacing ‘.default’ with ‘()’ (to initialize it)?

**Comment by masiiha** [comment]
I tried both AppearanceConfiguration.init() and AppearanceConfiguration() and still nothing

**Comment by joostvandijk** [comment]
Is an exception logged in the console when you run it with breakpoints disabled?

**Comment by derrick-exabytes** [comment]
` 

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        if target.name == 'Adyen'
          target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
          end
        end
      end
    end

`

Add this part to your pod file and run pod install again

**Comment by masiiha** [comment]
@joostvandijk 
![screen shot 1396-08-23 at 17 49 42](https://user-images.githubusercontent.com/26216784/32784587-7cef2854-c964-11e7-9929-b0347a1c768d.png)
no. nothing's logged as you see in the photo.

**Comment by joostvandijk** [comment]
Hi @masiiha,

I'm sorry you're still experiencing this issue. We currently do not have enough information to fix the issue, as we're not able to reproduce it locally. Are you able to provide us with a small sample project in which the issue occurs?

Kind regards,

Joost

**Comment by masiiha** [comment]
Hi @joostvandijk 
I made a sample project and set swift compiler version to 3.2 and app crashed then switched to v4 and problem solved 
thanks for your respond
