### ISSUE TITLE
CardEncryptor.encryptedNumber(SecurityCode/ExpiryMonth/...) functions always return nil

### ISSUE THREAD

**Issue by designkros** [Adyen/adyen-ios#120]
I'm using the Adyen Drop-in component the most basic way I can following the tutorial [here](https://docs.adyen.com/checkout/ios/drop-in). 

The `payments` API returns with `{"status":422, "errorCode":"101","message":"Invalid card number","errorType":"validation"}`. Then I starting digging why that might be and found out that the paymentMethod parameter got from `delegate.didSubmit(_ data: PaymentComponentData, from component: DropInComponent)` contains just `"paymentMethod": ["type": scheme]` and no information about the card.

After setting a few breakpoints I found out that the card data goes just fine into the `CardEncryptor` class but the encrypt methods always return `nil` which I think is the reason of the wrong paymentMethod data.

Am I doing something wrong or is it a problem in the Pod itself?
I'm using pod `Adyen 3.1.4`.

Thank you for any help.

![CardEncryptor_encryptedCard](https://user-images.githubusercontent.com/4900672/68023303-1b57fd00-fca7-11e9-8ae5-055fb15c4e13.png)

![encryptedVariables](https://user-images.githubusercontent.com/4900672/68023302-1b57fd00-fca7-11e9-91a1-a35c3f263461.png)

**Comment by joostvandijk** [comment]
Hi @designkros,

This could be an issue with the public key you're setting. In most cases, it starts with `10001|`. Can you verify this?

Best,

Joost

**Comment by designkros** [comment]
Hi @joostvandijk, un/fortunately the problem really was a wrong public key string I got from my colleague. Thank you very much for your prompt answer.

After spending several hours debugging this, I would recommend raising an error when the public key is invalid instead of just returning nil.

**Comment by joostvandijk** [comment]
Hi @designkros,

I agree. We should provide better error handling. I'll keep this issue open until it's resolved.

Best,

Joost

**Comment by joostvandijk** [comment]
Hi @designkros,

We have published an update with the improved error handling.

Best,

Joost
