### ISSUE TITLE
[BUG] iOS Dropin Component does not appear on M1/M2 Laptops, Designed for iPad apps

### ISSUE THREAD

**Issue by jnorman-control4** [Adyen/adyen-ios#1205]
**Describe the bug**
When invoking the DropInComponent on iOS when running on a MacBook Pro (M1/M2), (Designed for iPad), the component does not appear.   The following constraint issues appear in the xCode console debugging window:

2023-05-08 10:42:07.609253-0600 TestApp[64836:4184664] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x14a283bf0 Adyen.ModalToolbar:0x13c0b06b0.height == 62.5   (active)>",
    "<NSLayoutConstraint:0x14a283ca0 UIView:0x13c0d4a30.height == 0.5   (active)>",
    "<NSLayoutConstraint:0x14b3669a0 Adyen.FormView:0x13aa11a00.top == UILayoutGuide:0x14b38dda0'UIViewSafeAreaLayoutGuide'.top   (active)>",
    "<NSLayoutConstraint:0x14b366af0 Adyen.FormView:0x13aa11a00.bottom == UILayoutGuide:0x14b38dda0'UIViewSafeAreaLayoutGuide'.bottom   (active)>",
    "<NSLayoutConstraint:0x14a21ffb0 V:|-(0)-[UIStackView:0x14a23c550]   (active, names: '|':UIView:0x14977ec80 )>",
    "<NSLayoutConstraint:0x14a26d830 UIStackView:0x14a23c550.bottom == UIView:0x14977ec80.bottom   (active)>",
    "<NSLayoutConstraint:0x14a277b20 UIView:0x14977ec80.bottom == UIView:0x14977ccb0.bottom   (active)>",
    "<NSLayoutConstraint:0x14a26dd00 V:|-(1269)-[UIView:0x14977ec80]   (active, names: '|':UIView:0x14977ccb0 )>",
    "<NSLayoutConstraint:0x13c0d0300 'UISV-canvas-connection' UIStackView:0x14a23c550.top == Adyen.ModalToolbar:0x13c0b06b0.top   (active)>",
    "<NSLayoutConstraint:0x13c0c02d0 'UISV-canvas-connection' V:[UIView:0x13c0d4d60]-(0)-|   (active, names: '|':UIStackView:0x14a23c550 )>",
    "<NSLayoutConstraint:0x13c0d3340 'UISV-spacing' V:[Adyen.ModalToolbar:0x13c0b06b0]-(0)-[UIView:0x13c0d4a30]   (active)>",
    "<NSLayoutConstraint:0x13c0d46d0 'UISV-spacing' V:[UIView:0x13c0d4a30]-(0)-[UIView:0x13c0d4d60]   (active)>",
    "<NSLayoutConstraint:0x13c0c8160 'UIView-Encapsulated-Layout-Height' UIView:0x14977ccb0.height == 1324   (active)>",
    "<NSLayoutConstraint:0x14b378b30 'UIViewSafeAreaLayoutGuide-bottom' V:[UILayoutGuide:0x14b38dda0'UIViewSafeAreaLayoutGuide']-(0)-|   (active, names: '|':UIView:0x13c0d4d60 )>",
    "<NSLayoutConstraint:0x149428bf0 'UIViewSafeAreaLayoutGuide-top' V:|-(0)-[UILayoutGuide:0x14b38dda0'UIViewSafeAreaLayoutGuide']   (active, names: '|':UIView:0x13c0d4d60 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x14b366af0 Adyen.FormView:0x13aa11a00.bottom == UILayoutGuide:0x14b38dda0'UIViewSafeAreaLayoutGuide'.bottom   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2023-05-08 10:42:07.610887-0600 TestApp[64836:4184664] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x14a283bf0 Adyen.ModalToolbar:0x13c0b06b0.height == 62.5   (active)>",
    "<NSLayoutConstraint:0x14a283ca0 UIView:0x13c0d4a30.height == 0.5   (active)>",
    "<NSLayoutConstraint:0x14a21ffb0 V:|-(0)-[UIStackView:0x14a23c550]   (active, names: '|':UIView:0x14977ec80 )>",
    "<NSLayoutConstraint:0x14a26d830 UIStackView:0x14a23c550.bottom == UIView:0x14977ec80.bottom   (active)>",
    "<NSLayoutConstraint:0x14a277b20 UIView:0x14977ec80.bottom == UIView:0x14977ccb0.bottom   (active)>",
    "<NSLayoutConstraint:0x14a26dd00 V:|-(1269)-[UIView:0x14977ec80]   (active, names: '|':UIView:0x14977ccb0 )>",
    "<NSLayoutConstraint:0x13c0d0300 'UISV-canvas-connection' UIStackView:0x14a23c550.top == Adyen.ModalToolbar:0x13c0b06b0.top   (active)>",
    "<NSLayoutConstraint:0x13c0c02d0 'UISV-canvas-connection' V:[UIView:0x13c0d4d60]-(0)-|   (active, names: '|':UIStackView:0x14a23c550 )>",
    "<NSLayoutConstraint:0x13c0d3340 'UISV-spacing' V:[Adyen.ModalToolbar:0x13c0b06b0]-(0)-[UIView:0x13c0d4a30]   (active)>",
    "<NSLayoutConstraint:0x13c0d46d0 'UISV-spacing' V:[UIView:0x13c0d4a30]-(0)-[UIView:0x13c0d4d60]   (active)>",
    "<NSLayoutConstraint:0x13c0c8160 'UIView-Encapsulated-Layout-Height' UIView:0x14977ccb0.height == 1324   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x14a283bf0 Adyen.ModalToolbar:0x13c0b06b0.height == 62.5   (active)>

**To Reproduce**
Implement the iOS Dropin Component as outlined in the documentation.   
Invoke the dropIn, ie:  hostingViewController.present(dropInComponent.viewController, animated: true)

**Expected behavior**
The dropIn should appear as it does on iPhone and iPad.

**Smartphone (please complete the following information):**
 - Device: Macbook Pro (Designed for iPad) app
 - OS: iOS 15.x
 - SDK Version 5.1.0

**Comment by descorp** [comment]
Hey @jnorman-control4 

Indeed, we never tested our DropIn as Mac app.
DropIn, in fact, appears as on a screen, it is just too "narrow" 😅 
We will see what we can do about it..


https://github.com/Adyen/adyen-ios/assets/2648655/cd0675c5-3ebd-4eb8-b471-c458c9bda94d

**Comment by descorp** [comment]
So the problem is that DropIn uses `UIScreen.main.bounds` to reference "app" window size. 
However, for mac app `UIScreen.main` is your physical dimension..

**Comment by descorp** [comment]
BTW @jnorman-control4 

Since our iOS DropIn was never tested for "Mac (Designed for iPad)" use, some flows are not working as expected, for ex redirect flow opens up the system browser (not in-app browser) and results in DropIn dismissing "loading state" on payment list (or issuer list). That could result in shopper paying twice and\or a conversion drop.

**Comment by descorp** [comment]
@jnorman-control4 

This PR should fix it #1219

**Comment by jnorman-control4** [comment]
@descorp, thanks for the fix!   Let me know when it's available in develop.

**Comment by descorp** [comment]
@jnorman-control4 

Released on [5.2.0](https://github.com/Adyen/adyen-ios/releases/tag/5.2.0)
Please confirm if this one doing the trick for you.

**Comment by jnorman-control4** [comment]
@descorp,  I pulled in 5.2 and tried it out.   It's working as expected.  Thanks!
