### ISSUE TITLE
Multiple clicks on pay button - multiple reponses in didSubmit

### ISSUE THREAD

**Issue by dragantr-intertec** [Adyen/adyen-ios#121]
If a user taps multiple on pay button on drop-in component, app get multiple responses in:
func didSubmit(_ data: PaymentComponentData, from component: DropInComponent)

and creates multiple payments in Adyen. 
<img width="665" alt="Screenshot 2019-11-04 at 11 40 52" src="https://user-images.githubusercontent.com/49029730/68115158-07570a00-fef8-11e9-8cf1-23ba8fb065ac.png">

Thanks

**Comment by joostvandijk** [comment]
Hi @dragantr-intertec,

We'll take a look. I'll update you when we have a solution.

Best,

Joost

**Comment by joostvandijk** [comment]
Hi @dragantr-intertec,

We can not locally reproduce the issue: the submit button is disabled during loading. Are you calling `stopLoading()` before the payment request is completed? If not, please provide us with the version of our SDK and the version of iOS used.

Best,

Joost
