### ISSUE TITLE
[NEED ASSIST] problems loading the library when running the app with M1

### ISSUE THREAD

**Issue by danieRG** [Adyen/adyen-ios#1211]
**Describe the challenge**
The problem started a few weeks ago and when I started compiling the iOS app it threw me that error.

It is worth mentioning that it worked correctly and out of nowhere it began to show the error and no changes or pod updates had been made. 
I was using the latest version of xcode when the error started, so I downgraded to Version 14.2 (14C18) and the error remains.
I'm not sure if the problem is independent of Adyen or my device.

**Screenshots**
<img width="571" alt="Captura de pantalla 2023-05-11 a la(s) 12 30 14 p m" src="https://github.com/Adyen/adyen-ios/assets/22716800/336c52c4-ba24-424c-b061-a1171c4ac244">

**Comment by b7anka** [comment]
Hello @danieRG I don't work for adyen but I had a similar problem (I'm also on an M1) and i'm using Xcode 14.3 and I've managed to solve the problem running the emulator using rosetta previous to Xcode 14.3 you would do the following, right click on the xcode shortcut and checking the box that says open using rosetta on the newer version Apple changed that and now you got do this:
<img width="1680" alt="Captura de ecrã 2023-05-16, às 16 18 49" src="https://github.com/Adyen/adyen-ios/assets/25281887/d0cd8b22-4743-4132-bd7d-d5cb6347c1dd">

**Comment by descorp** [comment]
Hey @danieRG,  @b7anka 

What dependency management system are you using?

**Comment by b7anka** [comment]
Hi @descorp, i'm using SPM.

**Comment by descorp** [comment]
Thanks @b7anka 
We will run local tests and will get back to you!

**Comment by descorp** [comment]
Hey @b7anka @danieRG 

FYI, I wasn't able to reproduce localy:
both "Rosete" and "Apple Silicon" simulators works as expected on blank SPM project.
Xcode 14.3. Mac M1.

#worksonmymachine 🤔

**Comment by danieRG** [comment]
> Hey @b7anka @danieRG
> 
> FYI, I wasn't able to reproduce localy: both "Rosete" and "Apple Silicon" simulators works as expected on blank SPM project. Xcode 14.3. Mac M1.
> 
> #worksonmymachine 🤔

It's weird, I've been testing it on other devices and it works the same for them, there are 3 particular cases that stopped working and suddenly showed that error (I include myself) I tried to change to rosette but the error changed to "#error unsupported Swift architecture|unsupported Swift architecture"

**Comment by danieRG** [comment]
> What dependency management system are you using?

I'm using brew

**Comment by brurend** [comment]
The problem appears to be with the WeChatPayInternal package, we don't need it and don't use it, but even if we don't select it when installing the SPM it still gets added to the project

**Comment by descorp** [comment]
> The problem appears to be with the WeChatPayInternal package

@danieRG @b7anka  could you check if this is the case for you as well?

**Comment by danieRG** [comment]
> > The problem appears to be with the WeChatPayInternal package
> 
> @danieRG @b7anka could you check if this is the case for you as well?

It didn't work for me, I still have the same problem

**Comment by brurend** [comment]
Is there anyway to not load WeChat together with the rest if we don't use it?

**Comment by danieRG** [comment]
Hi, I bring new news about the problem. I just updated the entire project to RN 0.72.4. and several dependencies and it still shows the same error.
Is there an Expo library that this could be affecting?

**Comment by danieRG** [comment]
Hello, I managed to solve that problem I just had to add this line in the podfile `config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'`. Previously I tried the same thing but it didn't work but now it is possible that updating my dependencies also had an influence.

Thank you all!
