### ISSUE TITLE
[NEED ASSIST] Apple Pay v3.6.0

### ISSUE THREAD

**Issue by lhao80761** [Adyen/adyen-ios#1214]
I want to implement Apple Pay with iOS; 
Using the Drop - in method, reference documentation address: https://docs.adyen.com/payment-methods/apple-pay/ios-drop-in?tab=required-config-4_2#api-reference

After I configured Apple Pay, I pulled up the payment box and only showed the credit payment method, without showing the Apple Pay button. The payment code is as follows:
{
"groups":[
{
"name":"Credit Card",
"types":[
"visa",
"mc",
"amex"
]
}
],
"paymentMethods":[
{
"configuration":{
"merchantDisplayName":"xxxx",
"merchantIdentifier":"merchant.com.adyen.xxxxxx"
},
"details":[
{
"key":"applepay.token",
"type":"applePayToken"
}
],
"name":"Apple Pay",
"supportsRecurring":true,
"type":"applepay"
},
{
"brands":[
"visa",
"mc",
"amex"
],
"details":[
{
"key":"encryptedCardNumber",
"type":"cardToken"
},
{
"key":"encryptedSecurityCode",
"type":"cardToken"
},
{
"key":"encryptedExpiryMonth",
"type":"cardToken"
},
{
"key":"encryptedExpiryYear",
"type":"cardToken"
},
{
"key":"holderName",
"optional":true,
"type":"text"
}
],
"name":"Credit Card",
"supportsRecurring":true,
"type":"scheme"
}
]
}

But when I pulled up the Pay popup, only the credit card payment method was displayed, not the Apple Pay button; As shown below：
![1](https://github.com/Adyen/adyen-ios/assets/52558961/02ed8fd6-ae39-48d5-ab62-4538d835aa24)

**Comment by descorp** [comment]
Hey @lhao80761 

Have you also [enable Apple Pay in your app](https://docs.adyen.com/payment-methods/apple-pay/enable-apple-pay?tab=i_os_2#process-overview-1)?

You can also enable `AdyenLogging` to see the reason why DropIn is not able to initiate Apple Pay:

```swift
        #if DEBUG
            AdyenLogging.isEnabled = true
        #endif
```

**Comment by lhao80761** [comment]
> Hey @lhao80761
> 
> Have you also [enable Apple Pay in your app](Enable Apple Pay in your app)?
> 
> You can also enable `AdyenLogging` to see the reason why DropIn is not able to initiate Apple Pay:
> 
> ```swift
>         #if DEBUG
>             AdyenLogging.isEnabled = true
>         #endif
> ```

Thank you for your reply. I have enabled Apple Pay and successfully completed the payment process on the web page. It just can't be dialed up in the App.

**Comment by descorp** [comment]
Sorry @lhao80761 

I have updated link in my previous comment.
Process of configuring Apple Pay for web and iOS app is different. 
Make sure you correctly [enable Apple Pay in your app](https://docs.adyen.com/payment-methods/apple-pay/enable-apple-pay?tab=i_os_2#process-overview-1) and that you providing correct `merchantID` to `ApplePayComponent.Configuration`.

```swift
var config = ApplePayComponent.Configuration(payment: applePayPayment,
                                             merchantIdentifier: ConfigurationConstants.applePayMerchantIdentifier)
 
//Assign the Apple Pay configuration object you created to your instance of Drop-in.
dropInConfiguration.applePay = applePayConfiguration
```

**Comment by lhao80761** [comment]
> 对不起@lhao80761
> 
> 我在之前的评论中更新了链接。 为 Web 和 iOS 应用程序配置 Apple Pay 的过程是不同的。 确保[在您的应用程序中正确启用 Apple Pay](https://docs.adyen.com/payment-methods/apple-pay/enable-apple-pay?tab=i_os_2#process-overview-1)并提供正确`merchantID`的`ApplePayComponent.Configuration`.
> 
> ```swift
> var config = ApplePayComponent.Configuration(payment: applePayPayment,
>                                              merchantIdentifier: ConfigurationConstants.applePayMerchantIdentifier)
>  
> //Assign the Apple Pay configuration object you created to your instance of Drop-in.
> dropInConfiguration.applePay = applePayConfiguration
> ```

As I know, the certificate of iOS needs to use our own certificate. I have configured the certificate according to this process and configured it on the merchant side.Configuration as shown below:
![1](https://github.com/Adyen/adyen-ios/assets/52558961/3df22400-4749-421a-bf44-468516cfc756)
![2](https://github.com/Adyen/adyen-ios/assets/52558961/fa9e9f06-cb5f-46fc-85e0-9e73bdd2048e)

**Comment by descorp** [comment]
Hey @lhao80761 

This is all correct.

I am referring to [Apple App ID configuration](https://developer.apple.com/help/account/manage-identifiers/enable-app-capabilities#enable-apple-pay) or alternatively [Xcode configuration of ApplePay](https://developer.apple.com/documentation/xcode/configuring-apple-pay-support). Do you have it configured?

**Comment by lhao80761** [comment]
> 嘿@lhao80761
> 
> 这都是正确的。
> 
> 我指的是[Apple App ID 配置](https://developer.apple.com/help/account/manage-identifiers/enable-app-capabilities#enable-apple-pay)或[ApplePay 的 Xcode 配置](https://developer.apple.com/documentation/xcode/configuring-apple-pay-support)。你配置了吗

Thank you for your patient reply. I have made the configuration, as shown in the picture
![3](https://github.com/Adyen/adyen-ios/assets/52558961/74564c42-273e-46f9-a93a-ea593c6e060a)
![4](https://github.com/Adyen/adyen-ios/assets/52558961/998d501e-bba6-4333-9ca5-671b3a602401)

**Comment by descorp** [comment]
Silly question:

You use same `merchantIdentifier` as set in "Entitlments"?

```swift
var config = ApplePayComponent.Configuration(payment: applePayPayment,
                                             merchantIdentifier: "merchant.com.adyen.####")
 
dropInConfiguration.applePay = applePayConfiguration
```

---

If you enable `AdyenLogging`, does it print out anything in Xcode console?

**Comment by lhao80761** [comment]
> 愚蠢的问题：
> 
> 您使用`merchantIdentifier`与“Entitlments”中设置的相同吗？
> 
> ```swift
> var config = ApplePayComponent.Configuration(payment: applePayPayment,
>                                              merchantIdentifier: "merchant.com.adyen.####")
>  
> dropInConfiguration.applePay = applePayConfiguration
> ```
> 
> 如果启用`AdyenLogging`，它会在 Xcode 控制台中打印出任何内容吗？

Yes, it's the same

> Silly question:
> 
> You use same `merchantIdentifier` as set in "Entitlments"?
> 
> ```swift
> var config = ApplePayComponent.Configuration(payment: applePayPayment,
>                                              merchantIdentifier: "merchant.com.adyen.####")
>  
> dropInConfiguration.applePay = applePayConfiguration
> ```
> 
> If you enable `AdyenLogging`, does it print out anything in Xcode console?

Yes, it's the same

**Comment by lhao80761** [comment]
> Silly question:
> 
> You use same `merchantIdentifier` as set in "Entitlments"?
> 
> ```swift
> var config = ApplePayComponent.Configuration(payment: applePayPayment,
>                                              merchantIdentifier: "merchant.com.adyen.####")
>  
> dropInConfiguration.applePay = applePayConfiguration
> ```
> 
> If you enable `AdyenLogging`, does it print out anything in Xcode console?

Confirm a question, does SDK version 3.6 work with Apple Pay?

**Comment by descorp** [comment]
> Confirm a question, does SDK version 3.6 work with Apple Pay?

Apple pay was supported on v3.6 and we expect it work.

Main difference is that for [3.6.0](https://github.com/Adyen/adyen-ios/blob/3.6.0/AdyenUIHost/Domains/Components/ComponentsViewController.swift#LL95C1-L96C81) apple pay requires `merchantIdentifier`, `payment` and `summaryItems`:

```swift
        configuration.applePay.merchantIdentifier = Configuration.applePayMerchantIdentifier
        configuration.applePay.summaryItems = Configuration.applePaySummaryItems

        dropInComponent.payment = payment
```

**Comment by lhao80761** [comment]
> > Confirm a question, does SDK version 3.6 work with Apple Pay?
> 
> Apple pay was supported on v3.6 and we expect it work.
> 
> Main difference is that for [3.6.0](https://github.com/Adyen/adyen-ios/blob/3.6.0/AdyenUIHost/Domains/Components/ComponentsViewController.swift#LL95C1-L96C81) apple pay requires `merchantIdentifier`, `payment` and `summaryItems`:
> 
> ```swift
>         configuration.applePay.merchantIdentifier = Configuration.applePayMerchantIdentifier
>         configuration.applePay.summaryItems = Configuration.applePaySummaryItems
> 
>         dropInComponent.payment = payment
> ```

Hello, I have tried for many times, but I still cannot call Apple Pay. My code is as follows. Could you please check it for me?
![5](https://github.com/Adyen/adyen-ios/assets/52558961/825aedea-c1cb-4b0c-b85a-23ad81266341)

**Comment by descorp** [comment]
Hey @lhao80761 

I believe you are missing the `countryCode` from payment. 
Try:

```swift
dropInComponent.payment = Payment(amount: Amount(value: value,
                                                 currencyCode: currencyCode),
                                   countryCode: countryCode)
```

**Comment by descorp** [comment]
BTW, `amountValue` in **Payment** and in **PKSummaryItem** are different:

Adyen's `Payment` expects amount in **minor units** 
(ex. "100 dollars and 5 cents" = `Amount(value: 10005, currencyCode: "USD")`).

However Apple Pay expects `NSDecimalNumber`
(ex. "100 dollars and 5 cents" = `NSDecimalNumber(100.05)`).

**Comment by lhao80761** [comment]
> BTW, `amountValue` in **Payment** and in **PKSummaryItem** are different:
> 
> Adyen's `Payment` expects amount in **minor units** (ex. "100 dollars and 5 cents" = `Amount(value: 10005, currencyCode: "USD")`).
> 
> However Apple Pay expects `NSDecimalNumber` (ex. "100 dollars and 5 cents" = `NSDecimalNumber(100.05)`).

Thank you for your answer. At present, I have completed the password input step and obtained the JSON data returned by SDK, but failed to use token payment.
This is the json string returned by the sdk after the IOS app apple pay is completed:
![6](https://github.com/Adyen/adyen-ios/assets/52558961/a97b0353-0456-4b59-bba1-332ebdd837ee)

API request paymentSession, use the data field in the token object in the json passed from IOS as the value of the token, change the value of the amount in the API to 1 or 100, and report The provided SDK token could not be parsed.
![7](https://github.com/Adyen/adyen-ios/assets/52558961/c354e2f0-f0e9-47dc-bef0-0e8e3892d622)

**Comment by descorp** [comment]
Hey @lhao80761 

What Adyen API version you backend is using?

The second screenshot you have provided is a deprecated [/paymentSession](https://docs.adyen.com/api-explorer/Checkout/70/post/paymentSession) API endpoint.
I believe you are looking for [/payment](https://docs.adyen.com/api-explorer/Checkout/70/post/payments#request-paymentMethod-ApplePayDetails) API endpoint.

Example:
```json
{
  "amount": {
    "currency": "USD",
    "value": 1000
  },
  "reference": "Your order number",
  "paymentMethod": {
    "type": "applepay",
    "applePayToken": "VNRWtuNlNEWkRCSm1xWndjMDFFbktkQU..."
  },
  "returnUrl": "myapp://payment",
  "merchantAccount": "YOUR_MERCHANT_ACCOUNT"
}
```

**Comment by lhao80761** [comment]
> Hey @lhao80761
> 
> What Adyen API version you backend is using?
> 
> The second screenshot you have provided is a deprecated [/paymentSession](https://docs.adyen.com/api-explorer/Checkout/70/post/paymentSession) API endpoint. I believe you are looking for [/payment](https://docs.adyen.com/api-explorer/Checkout/70/post/payments#request-paymentMethod-ApplePayDetails) API endpoint.
> 
> Example:
> 
> ```json
> {
>   "amount": {
>     "currency": "USD",
>     "value": 1000
>   },
>   "reference": "Your order number",
>   "paymentMethod": {
>     "type": "applepay",
>     "applePayToken": "VNRWtuNlNEWkRCSm1xWndjMDFFbktkQU..."
>   },
>   "returnUrl": "myapp://payment",
>   "merchantAccount": "YOUR_MERCHANT_ACCOUNT"
> }
> ```
Hello, I request the payment interface, prompting Invalid Apple Pay Token
![10](https://github.com/Adyen/adyen-ios/assets/52558961/2ea8e7a2-29ff-4400-bebf-a83182fd64de)

**Comment by lhao80761** [comment]
> > Hey @lhao80761
> > What Adyen API version you backend is using?
> > The second screenshot you have provided is a deprecated [/paymentSession](https://docs.adyen.com/api-explorer/Checkout/70/post/paymentSession) API endpoint. I believe you are looking for [/payment](https://docs.adyen.com/api-explorer/Checkout/70/post/payments#request-paymentMethod-ApplePayDetails) API endpoint.
> > Example:
> > ```json
> > {
> >   "amount": {
> >     "currency": "USD",
> >     "value": 1000
> >   },
> >   "reference": "Your order number",
> >   "paymentMethod": {
> >     "type": "applepay",
> >     "applePayToken": "VNRWtuNlNEWkRCSm1xWndjMDFFbktkQU..."
> >   },
> >   "returnUrl": "myapp://payment",
> >   "merchantAccount": "YOUR_MERCHANT_ACCOUNT"
> > }
> > ```
> 
> Hello, I request the payment interface, prompting Invalid Apple Pay Token ![10](https://user-images.githubusercontent.com/52558961/241219494-2ea8e7a2-29ff-4400-bebf-a83182fd64de.png)

I am using adyen-java-api-library 10.1.0 in the background

**Comment by descorp** [comment]
What value are you sending in `applePayToken `?

Value expected there is a Base64 encrypted JSON string of a [ApplePay Payment token](https://developer.apple.com/documentation/passkit/apple_pay/payment_token_format_reference#3949537)

**Comment by lhao80761** [comment]
> 您要发送什么值`applePayToken `？
> 
> 预期值是[ApplePay 支付令牌的 Base64 加密 JSON 字符串](https://developer.apple.com/documentation/passkit/apple_pay/payment_token_format_reference#3949537)

This is the data returned by the sdk after the iOS app uses the ayden sdk for Apple payment. I use the data field in the token object in Json as the value of the token, and as the value of the /payment api token. Do I want to encrypt or decrypt it? 
![11](https://github.com/Adyen/adyen-ios/assets/52558961/09fb57a7-9966-415e-b037-0aa995da5b8e)

**Comment by lhao80761** [comment]
> 您要发送什么值`applePayToken `？
> 
> 预期值是[ApplePay 支付令牌的 Base64 加密 JSON 字符串](https://developer.apple.com/documentation/passkit/apple_pay/payment_token_format_reference#3949537)

This is the data returned by the sdk after the iOS app uses the ayden sdk for Apple payment. I use the data field in the token object in Json as the value of the token, and as the value of the /payment api token. Do I want to encrypt or decrypt it? 
![11](https://github.com/Adyen/adyen-ios/assets/52558961/09fb57a7-9966-415e-b037-0aa995da5b8e)

**Comment by descorp** [comment]
> I use the data field in the token object in Json as the value of the token

This is incorrect. 

Value expected there is a Base64 encrypted JSON string of a full [ApplePay Payment token](https://developer.apple.com/documentation/passkit/apple_pay/payment_token_format_reference#3949537) object:

```swift
"""
{
    "data":"...",
    "signature":"...",
    "version":"..",
    "header":{
        "applicationData":"...",
        "ephemeralPublicKey":"...",
        "wrappedKey":"...",
        "publicKeyHash":"...",
        "transactionId":"..."
    }
}
""".data(using: .utf8).base64EncodedString()
```

--- 

Version [3.6.0](https://github.com/Adyen/adyen-ios/blob/3.6.0/Adyen/Components/Apple%20Pay/ApplePayComponent.swift#L269) will provide `token` value as a encoded string. You can use it "as is" or decode with `.data(using: .utf8).base64EncodedString()`

**Comment by lhao80761** [comment]
> > I use the data field in the token object in Json as the value of the token
> 
> This is incorrect.
> 
> Value expected there is a Base64 encrypted JSON string of a full [ApplePay Payment token](https://developer.apple.com/documentation/passkit/apple_pay/payment_token_format_reference#3949537) object:
> 
> ```swift
> """
> {
>     "data":"...",
>     "signature":"...",
>     "version":"..",
>     "header":{
>         "applicationData":"...",
>         "ephemeralPublicKey":"...",
>         "wrappedKey":"...",
>         "publicKeyHash":"...",
>         "transactionId":"..."
>     }
> }
> """.data(using: .utf8).base64EncodedString()
> ```
> 
> Version [3.6.0](https://github.com/Adyen/adyen-ios/blob/3.6.0/Adyen/Components/Apple%20Pay/ApplePayComponent.swift#L269) will provide `token` value as a encoded string. You can use it "as is" or decode with `.data(using: .utf8).base64EncodedString()`

Hello, when we decrypt, we found that the data version returned by the client is EC_v1, but the certificate we generated is RSA. How should we unify the two encryption methods?

![01](https://github.com/Adyen/adyen-ios/assets/52558961/031aaa0f-facc-47ee-bdf5-e35bb8cb376e)
![02](https://github.com/Adyen/adyen-ios/assets/52558961/ff163534-b7da-49e4-931e-568e7a746ed2)

**Comment by descorp** [comment]
Hey @lhao80761 

To make successful payment via [\payments](https://docs.adyen.com/api-explorer/Checkout/68/post/payments#request-paymentMethod-listOfValues-ApplePayDetails_applePayToken) Adyen API use the stringified and base64 encoded `paymentData` you retrieved from the Apple framework.
Our backend can decrypt the token and proceed the payment via [Payment Processing Certificate](https://docs.adyen.com/payment-methods/apple-pay/enable-apple-pay?tab=i_os_2#create-payment-processing-certificate).

> we found that the data version returned by the client is EC_v1, but the certificate we generated is RSA. How should we unify the two encryption methods?

This question is outside of the iOS SDK scope.
Please reach out Adyen [support team](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420).

**Comment by descorp** [comment]
Hey @lhao80761 

Were you able to resolve the issue?

**Comment by descorp** [comment]
I am going to close this ticket for now.
Feel free to reopen or continue the discussion here.
