### ISSUE TITLE
[NEED ASSIST] Localization issue in AppStore version of the app

### ISSUE THREAD

**Issue by sainianil** [Adyen/adyen-ios#1220]
**Describe the challenge**
I'm facing issue of localization only in the AppStore version of the app, it works fine in other environments and running from XCode.
I'm using DropIn UI SDK version 5.1.0 and following is the code for localization:

```
var dropInComponentStyle = DropInComponent.Style()
        dropInComponentStyle.formComponent.mainButtonItem.button.backgroundColor = .black
        dropInComponentStyle.formComponent.textField.separatorColor = .black
        dropInComponentStyle.formComponent.textField.tintColor = .black
    
        let configuration = DropInComponent.Configuration(
            style: dropInComponentStyle,
            allowsSkippingPaymentList: false,
            allowPreselectedPaymentView: false
        )
        configuration.card.billingAddress.mode = .none
        configuration.card.showsStorePaymentMethodField = false
        configuration.paymentMethodsList.allowDisablingStoredPaymentMethods = true
        
        // Localize the text on the Adyen SDK UI, my app localization is in the dev pod with bundle name localization
        let localizationParameters = LocalizationParameters(bundle: Bundle.localization, tableName: "Localizable")
        configuration.localizationParameters = localizationParameters
        
        let adyenAmount = Adyen.Amount(value: 0, currencyCode: currencyCode)
        let adyenPayment = Adyen.Payment(amount: adyenAmount, countryCode: countryCode)
        let adyenContext = AdyenContext(apiContext: apiContext, payment: adyenPayment)
        let component = DropInComponent(paymentMethods: paymentMethod,
                                        context: adyenContext,
                                        configuration: configuration,
                                        title: components.app.name)
        
        component.delegate = self
        component.cardComponentDelegate = self
        self.dropInComponent = component
```

I overrode only three keys as below and they were translated as expected in the AppStore version of the app:

```
"adyen.paymentMethods.title" = "Select Payment Method";
"adyen.submitButton" = "Add Card";
"adyen.confirmPreauthorization" = "Add Card";
```

However, other DropIn card fields such as card number, cvv and expiry title and placeholder text are not localized as expected instead of translated text I'm seeing keys on the UI.

**Screenshots**
<img width="415" alt="Screenshot 2023-05-23 at 14 23 03" src="https://github.com/Adyen/adyen-ios/assets/10446286/6298c861-b41f-44c6-ba60-e6731147e4f8">

**Comment by goergisn** [comment]
Hi @sainianil,
Thank you for getting in touch!
Were you able to isolate the issue in a basic sample app?

To be able to reproduce the problem, can you tell a bit more about your development setup?
- Package management system (SPM, Cocoapods, Carthage)
- Development Machine (Intel/M1 & Mac OS Version)
- Xcode version

**Comment by sainianil** [comment]
Hi @goergisn, 
Can't upload basic sample app to AppStore as this issue is reproducible only in AppStore version i.e. TestFlight and App in the AppStore.

Following are the configurations:
- Package management system - Cocoapods - Adyen SDK version 5.1.0
- Development Machine - M1 (Ventura - 13.3.1)
- Xcode version - 14.3 (14E222b)

**Comment by goergisn** [comment]
Hi @sainianil,

Unfortunately it was not possible for us to replicate the described behavior with the given the information.

Overall I can confirm that we don’t have any debug/release specific behavior inside the SDK.

It is however strange that instead of falling back to the default localization it shows the localization keys. 
**Are you doing any kind of processing when archiving for the AppStore, like - for example - removing strings or generating missing strings?**

**Comment by sainianil** [comment]
Hi @goergisn 
Nops, not doing any kind of processing however could you have a look at below lines of code:

```
// Localize the text on the Adyen SDK UI, my app localization is in the dev pod with bundle name localization
let localizationParameters = LocalizationParameters(bundle: Bundle.localization, tableName: "Localizable")
configuration.localizationParameters = localizationParameters
```

Can it cause due to tableName as default table name is "Localizable" and as I also have default table name I'm passing table name as "Localizable"?

**Comment by goergisn** [comment]
I tried to replicate the setup as close to what you provided and also used the same localization file name and a bundle to get it from but did not run into any similar issues.

Maybe good to do some troubleshooting:
- Could you try building for Release (instead of Debug) and see if you observe the same behavior?
- Could you rename the file (from Localizable to Translations for example) to see if you’re still getting the same effects
- Do you use different targets for debugging/release with different target membership configurations?
- Is the Adyen dependency in your `Podfile` or is it part of a `.podspec` of another (development) pod?

**Comment by sainianil** [comment]
Following are the responses to your queries:

- Could you try building for Release (instead of Debug) and see if you observe the same behavior?
  - Tried already, this issue happens only in TestFlight build
- Could you rename the file (from Localizable to Translations for example) to see if you’re still getting the same effects
  - Can't test this as it requires me to upload the build to TestFlight to test the changes 
- Do you use different targets for debugging/release with different target membership configurations?
  - Yes, we do have different targets 
- Is the Adyen dependency in your Podfile or is it part of a .podspec of another (development) pod?
  - Dependency is in my Podfile

**Comment by goergisn** [comment]
Hi @sainianil,

we took another look at the issue - with the provided information - but still unfortunately can’t find a way to reproduce the described behavior. Did it work for you with a previous version of the Adyen SDK? (If yes, which one)

You’re saying that your release target is different from the development target. 
So might it be that the release target has a different configuration that could cause this issue?
Or a `post_install` rule in your Podfile that replaces/overrides strings?

One thing I’d suggest is to build a small sample app that is as close to the setup of your main app and upload that to TestFlight to verify if the issue still occurs.

**Comment by sainianil** [comment]
Not sure about trying the sample app on TestFlight however other things will try.
