### ISSUE TITLE
Display amount in pay button

### ISSUE THREAD

**Issue by Gp2mv3** [Adyen/adyen-ios#123]
In Android, we can specify the amount, currency and user's locale to the DropIncomponent.
This allows us to display the price in the payment button, but also select the right payment providers to display.
In iOS, how can I provide that info to the Component?

Thanks a lot!

**Comment by joostvandijk** [comment]
Hi @Gp2mv3,

You can use the `payment` variable on the `DropInComponent` to set relevant payment information. The amount will then be displayed on the button.

Best,

Joost

**Comment by Gp2mv3** [comment]
Thanks a lot, I didn't see it.
This variable is unfortunately in any docs or example. 

Also, for the the country code, what value should I use for Belgium? Nor BE nor BEL works: I still have PaySafecard and Sofort methods displayed and I have no Bancontact/Maestro.

Regards,

Nicolas

**Comment by joostvandijk** [comment]
Hi Nicolas,

The payment methods are localized and filtered based on the information in the `/paymentMethods` request. If you change the country code there, you will see the payment methods change.
The country code in the `payment` structure is only used when needed clientside, which is currently only the case with Apple Pay.

I agree that this property could use with some more documentation. I'll make sure that gets added.

Best,

Joost

**Comment by Gp2mv3** [comment]
Yes, that's what I also thought. `/paymentMethods` includes bcmc so it should display Bancontact right?
I'll double-check that everything is passed to the DropInComponent.

Thanks for your help!

**Comment by joostvandijk** [comment]
Well, yes, sort of. If there is a component for it, the drop in will render the payment method. Unfortunately, there is no component yet for BCMC, but we're working to add it.
