### ISSUE TITLE
Apple pay wont show in dropincomponent 

### ISSUE THREAD

**Issue by assembleMHN** [Adyen/adyen-ios#1238]
Hi all.

We have been struggeling with an issue for a couple of days now. We are trying to show Apple pay through the iOS SDK DropInComponent

We have setup certificate and identifier in Apple developer portal, we have added the ids to the entitlement file and added the apple pay capability, we have setup the applePay component in the config, we have added apple pay to the payment methods in ayden and setup the certificate from Apple developer portal (we also have the same issue with ACH, we cannot get this to show).

see below code for presenting the component, We have tried both the way from the documentation and from the example implementation in github, both does not work for us. We are completely lost and have no idear how to move forward.

```
        Requests.adyneSession { sessionData in
            
        #if DEBUG
          AdyenLogging.isEnabled = true
        #endif
            
            if let sessionId = sessionData.sessionId, let data = sessionData.sessionData{
                
                let apiContext = try! APIContext(environment: Environment.test, clientKey: clientKey)
                let context = AdyenContext(apiContext: apiContext,payment: nil)
                let sessionConfig = AdyenSession.Configuration(sessionIdentifier: sessionId, initialSessionData: data,context: context)
                
                AdyenSession.initialize(with: sessionConfig, delegate: self, presentationDelegate: self) { [weak self] result in
                    switch result {
                    case let .success(session):
                        self?.adyneSession = session
                        
                        let dropInConfig = DropInComponent.Configuration()
                        
                        //Setup Apple pay
                        let amount = Amount(value: 0, currencyCode: currencyCode)
                        let payment = Payment(amount: amount, countryCode: countryCode)
                        if let applePayPayment = try? ApplePayPayment(payment: payment,brand: "BRAND NAME") {
                            let emailField = PKContactField(rawValue: "email")
                            let phoneField = PKContactField(rawValue: "phone")
                            
                            dropInConfig.applePay = .init(payment: applePayPayment,merchantIdentifier: "identifier")
                            dropInConfig.applePay?.requiredBillingContactFields = [ emailField, phoneField ]
                            dropInConfig.applePay?.requiredShippingContactFields = [ emailField, phoneField ]
                        }
                        
                        let dropInComponent = DropInComponent(paymentMethods: session.sessionContext.paymentMethods,
                                                              context: context,
                                                              configuration: dropInConfig)
                        
                        //Setup DropIn Component (Keep instance to avoid it being destroyed)
                        self?.dropInComponent = dropInComponent
                        
                        // Set session as the delegate for Drop-in
                        dropInComponent.delegate = session
                        dropInComponent.partialPaymentDelegate = session
                        presenter.present(dropInComponent.viewController, animated: true)
```

Hoping somebody have an idear of what we could try :)

EDIT:
It seems that only card is working, we cannot get Apple Pay or ACH to work. The PaymentMethods array that comes with the session from our API only contains card, is this the reason, and if so how do we make the SDK/API return the required PaymentMethods ?

Best Regards
Morten

**Comment by descorp** [comment]
Hey @assembleMHN 

If [/paymentMethods](https://docs.adyen.com/api-explorer/Checkout/68/post/paymentMethods) JSON response doesn't contain those payment methods - they will not appear in DropIn.
You need to configure those payment methods for your merchant account.
Please reach out to [Adyen Support](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420) team for help.

**Comment by assembleMHN** [comment]
Hi @descorp 

thank you very much for you reply, we already configured them, we setup ARC, Credit Card and Apple Payment, but only Credit Card are being returned in PaymentMethods when we create the Session through the iOS SDKs.

<img width="599" alt="Screenshot 2023-06-06 at 15 07 04" src="https://github.com/Adyen/adyen-ios/assets/30831333/933eb983-b40a-4437-9df9-0b3e4d27cc50">

<img width="1230" alt="Screenshot 2023-06-06 at 15 07 56" src="https://github.com/Adyen/adyen-ios/assets/30831333/bdf15c18-ecb0-4a7a-a58e-8be5462b218b">

thank you again for your reply, we also did write support, but we are trying everywhere to get help, as this is a task we need done asap :)

**Comment by assembleMHN** [comment]
Ok we figured out something.

when the amount is set to 0 in the session request, then apple pay and ACH will not show. If its set to 2$ then both of them shows. But as we use dropin to add a default payment type we need it set to 0. Why does only google pay and credit card work when setting amount to 0 ?

We cant find anything in the documentation, and support is very slow at answering.

Thanks

**Comment by descorp** [comment]
Hey @assembleMHN 

Unfortunately, this question is way outside of the scope of iOS SDK.
I can only suggest you reach out to the [Adyen Support](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420) team for help.

**Comment by assembleMHN** [comment]
@descorp thank you very much for your reply. I will leave the question open a couple of days to see if anybody has experienced the same and can give a pointer. We have already reached out to the support several days ago, sadly they response time is slow.

Thanks again.
Best Regards
Morten

**Comment by descorp** [comment]
Hey @assembleMHN 

Were you able to resolve the issue ?

**Comment by descorp** [comment]
I am going to close this ticket for now.
Feel free to reopen or continue discussion here.
