### ISSUE TITLE
SEPA: Country is not defined

### ISSUE THREAD

**Issue by Gp2mv3** [Adyen/adyen-ios#124]
How can we create SEPA payment?

I always receive `'HTTP Exception: 422. Unprocessable Entity: Country is not specified',` from the `/payment/payments`.

Do I need to send something different in the payload?

**Comment by joostvandijk** [comment]
Hi @Gp2mv3,

Are you following the API request as specified [here](https://docs.adyen.com/payment-methods/sepa-direct-debit#integrate-with-api)?

With questions related to your backend API integration, I would suggest contacting support@adyen.com. They can have a more in depth look at your account configuration as well as the requests you send.

Best,

Joost

**Comment by Gp2mv3** [comment]
I use the DropIn integration so normally everything is handled by the SEPA Component, no?

**Comment by joostvandijk** [comment]
The drop-in only handles getting the payment details, you are still responsible for building a backend that takes the details from the client-side and submit them to the Adyen API. See [this](https://docs.adyen.com/checkout/drop-in-web#how-drop-in-works) graph.

**Comment by Gp2mv3** [comment]
Yes, it's exactly what I want to do: Getting the payment details from the User to perform a SEPA payment. I don't really understand why the SEPA component doesn't ask for payment info before sending the request to the server.

I'll contact the support too.

Thanks
