### ISSUE TITLE
XCode 10.3 + Adyen 3.1.4 -> “if (@available(iOS 13.0, *))” doesn't compile in Xcode 10.3

### ISSUE THREAD

**Issue by mkharibalaji** [Adyen/adyen-ios#126]
Hi Team,
           When i tried to run the project with Adyen 3.1.4 with Xcode 10.3,it is throwing error as seen in the screenshot below,

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/5992474/68517855-3df1a380-02af-11ea-80ee-44829456a74f.png">

Could you please help me out on how to solve this ?

A related link to the above issue w.r.to Objective C
https://stackoverflow.com/questions/58083310/if-availableios-13-0-doesnt-compile-in-xcode-10-3

**Comment by joostvandijk** [comment]
Hi @mkharibalaji,

It appears our README is out of date, as the latest release requires Xcode 11, since that contains the iOS 13 SDK. We'll update the README. If you are unable to update Xcode, you can use an earlier version of our library.

Best,

Joost

**Comment by mkharibalaji** [comment]
@joostvandijk - Thank you and which version of adyen 3.X.X would you recommend to try with XCode 10.3

**Comment by joostvandijk** [comment]
Hi @mkharibalaji,

3.1.2 should work well with Xcode 10.3.

**Comment by mkharibalaji** [comment]
Thanks @joostvandijk
