### ISSUE TITLE
[NEED ASSIST]  how to automatically close the PayPal webview on IOS

### ISSUE THREAD

**Issue by ngmiduc** [Adyen/adyen-ios#1261]
**Describe the challenge**
I am using an IOS native Drop In to display the Adyen widget in our IOS app.
We offer Paypal payments and it is also working. 
My problem is now that I am not sure what return URL I should use so that the PayPal web view is closing again after a successful payment. Or how can I close the web view automatically after the payment is succeeded?

Shouldn't the webview be closed automatically on a native device when the payment went through with success?

**Comment by descorp** [comment]
Hey @ngmiduc 

We have some information about it in [our docs](https://docs-admin.is.adyen.com/online-payments/build-your-integration/additional-use-cases/advanced-flow-integration?tab=v67-actions_2&platform=iOS&integration=Drop-in&version=5.1.0#handling-redirects).

In general, one can use [Custom URL Scheme](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app) or [Universal Link](https://developer.apple.com/documentation/xcode/supporting-universal-links-in-your-app).

One also need to provide the received URL to `RedirectComponent.applicationDidOpen(from: url)`.

In case of Custom URL Scheme you can listen for in in `AppDelegate`:
```swift
    internal func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool {
        return RedirectComponent.applicationDidOpen(from: url)
    }
```

Or to `SceneDelegate`:

```swift
    internal func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
        guard let url = URLContexts.first?.url else { return }
        RedirectComponent.applicationDidOpen(from: url)
    }
```

**Comment by ngmiduc** [comment]
Hi @descorp !!
Thanks for the advice!

I now added a custom URL scheme which works when I open my appURL in Safari.
I changed my returnURL to that `appURL://` and added the changes in `AppDelegate`. I checked my created sessions and it looks correct:

```
{
  "amount":{"currency":"EUR","value":200},
  "countryCode":"DE",
  "expiresAt":"2023-07-03T18:39:17+02:00", "id":"CSA383D408C4D987F4",
  "merchantAccount":"...",
  "reference":"...",
  "returnUrl":"appURL://",
  "shopperLocale":"de-DE",
  "shopperReference":"...",
  "mode":"embedded",
  "sessionData":"..."
}
```

Somehow, after I have successfully paid via PayPal the webview won't redirect and stays with a loading indicated on the webview site. I don't get any errors inside xcode - so I am not sure what to do in this state. I tried as returnURL a standard website URL like "https://google.com" and this worked, but when I add a custom scheme URL it stops redirecting.

showing dropIn             |  select PayPal  |  result
:-------------------------:|:-------------------------:|:-------------------------:
  <img width="428" alt="Screenshot 2023-07-03 at 11 40 09" src="https://github.com/Adyen/adyen-ios/assets/22853830/270d9248-a1f2-4c2c-8b93-f438a60618bd"> | <img width="438" alt="Screenshot 2023-07-03 at 11 39 52" src="https://github.com/Adyen/adyen-ios/assets/22853830/5498281e-13cc-45cd-a550-cdc827995a91"> | <img width="445" alt="Screenshot 2023-07-03 at 11 40 42" src="https://github.com/Adyen/adyen-ios/assets/22853830/c90945de-2ff1-4f69-92f3-b909a40526bf"> 

Additional notes:
- We are using an ionic app with capacitor in angular.
- Adyen is implemented via a capacitor plugin for IOS.
- AdyenIOS version: 5.1.0

**Comment by descorp** [comment]
Hey @ngmiduc 

> I now added a custom URL scheme which works when I open my appURL in Safari.
I changed my returnURL to that appURL:// and added the changes in AppDelegate.

You also need to call `RedirectComponent.applicationDidOpen(from: url)` so it trigger the `didProvide` callback, and then dismiss the DropIn.

I am not 100% sure how it will work with capacitor, but if you have access to AppDelgate - this should be possible.
Make sure that `RedirectComponent.applicationDidOpen(from: url)` is reachable by debugger when you redirect.

**Comment by ngmiduc** [comment]
Hi!

Ok thanks, I found my mistake.
In the AppDelegate file provided by Capacitor/Ionic there are multiple `internal func application` (there are three). I put the `RedirectComponent.applicationDidOpen(from: url)` into the wrong one. 

Thanks, it works now.

**Comment by descorp** [comment]
Thanks for confirming @ngmiduc 

I am going to close this ticket.
