### ISSUE TITLE
How to set localised text to the DropIn - Help

### ISSUE THREAD

**Issue by mkharibalaji** [Adyen/adyen-ios#127]
Hi Team,
          Any help on how to set localised text for the DropIn Component and for other components as well.

**Comment by joostvandijk** [comment]
Hey @mkharibalaji,

You can take a look at our Localizable.strings file to see which strings are localized. You can then override these by including the keys with a custom translation in your own localization file. Our components look in the app's bundle for translations first, and then look at their own included translations.

Best,

Joost

**Comment by mkharibalaji** [comment]
Thanks @joostvandijk
