### ISSUE TITLE
[NEED ASSIST] ApplePayComponentDelegate functions not being called

### ISSUE THREAD

**Issue by MewanWA** [Adyen/adyen-ios#1279]
Implementing ApplePayComponent and listen to ApplePayComponentDelegate to update the shipping address and return the latest delivery methods back to ApplePayComponent.

What steps did you take?
Ran the Demo project on the repository with our Adyen test account details to test the ApplePayComponentAdvancedFlowExample.

What is the expected behavior / API ?
Got the component showing up and working as expected.
However, when we change the address/shipping method from the ApplePay component, the functions in ApplePayComponentDelegate are not being called.

**Comment by descorp** [comment]
Hey @MewanWA 

Indeed, we have missed `applePayDelegate`
#1280

Thank for pointing out! 💚

**Comment by descorp** [comment]
Fixed on `develop`.

**Comment by descorp** [comment]
Fix was released on [5.3.0](https://github.com/Adyen/adyen-ios/releases/tag/5.3.0)
