### ISSUE TITLE
Problem setting delegate

### ISSUE THREAD

**Issue by brurend** [Adyen/adyen-ios#128]
I'm trying to use the card component but its delegate methods are not being called, neither didSubmit nor didFail. Every now and then, if I set a breakpoint right after I present the component they do work, even if I made no changes to my code. Thats my code:

```
let cardComponent = CardComponent(paymentMethod: (unwrappedResponse.paymentMethods?.first)!, publicKey: "MY_API_KEY")
                cardComponent.environment = .test
                cardComponent.showsStorePaymentMethodField = false
                cardComponent.showsHolderNameField = true
                cardComponent.viewController.modalPresentationStyle = .fullScreen
                cardComponent.delegate = self
                present(cardComponent.viewController, animated: true, completion: nil)
```

![IMG_E2F4C850BE0F-1](https://user-images.githubusercontent.com/6145411/68880635-6122b580-06ea-11ea-97b6-0f07471b897b.jpeg)

**Comment by nnarayann** [comment]
Hello!. I think it could be because the cardComponent is being deallocated before the callback triggers. Try and declare it as a property of the viewController to hold the reference and it should work.

**Comment by brurend** [comment]
That was the problem, its working now. Thanks a lot

**Comment by joostvandijk** [comment]
Thanks @nnarayann!
