### ISSUE TITLE
[BUG] ApplePayComponentDelegate didUpdate contact function missing data

### ISSUE THREAD

**Issue by MewanWA** [Adyen/adyen-ios#1285]
**Describe the bug**
I am using the Apple Pay component to make a payment. Everything works as expected, but the applePayDelegate function does not seem to be returning all the information entered in the Apple Pay address. I have attached screenshots below of what is typed in the fields, and what the `public func didUpdate(contact: PKContact, for payment: Adyen.ApplePayPayment, completion: @escaping (PKPaymentRequestShippingContactUpdate) -> Void)` delegate function is returning.

**To Reproduce**
Add card to Apple Pay.
Add atleast 2 addresses.
Switch from one address to another.
Check PKContact returned in  didUpdate-contact delegate function.
Data returned is missing some data that was entered in Apple Pay address fields.

**Expected behavior**
All data entered in the Apple Pay address screen should be returned via PKContact in the delegate function

**Screenshots**
<img width="339" alt="Screenshot 2023-07-25 at 7 34 19 PM" src="https://github.com/Adyen/adyen-ios/assets/134686380/b095dcf4-0d84-4067-bac9-3b6d3b3d9ca4">
<img width="890" alt="Screenshot 2023-07-25 at 7 35 24 PM" src="https://github.com/Adyen/adyen-ios/assets/134686380/43492ad2-d9fc-4e6a-a28a-68ad4dc8c68f">

**Environment**
 - Device: iPhone 14 Pro
 - iOS Version: iOS 16.4
 - SDK Version: 5.0.0
 - Adyen API Version: 69
 - Package management system: Cocoapods
 - Xcode version: 14.2
 - Mac OS type: M1

**Relevant source code**
`public func didUpdate(contact: PKContact, for payment: Adyen.ApplePayPayment, completion: @escaping (PKPaymentRequestShippingContactUpdate) -> Void)`

**Comment by erenbesel** [comment]
Hey @MewanWA 
Apple doesn't provide the user's name related information in this part of the payment. In the delegate method `didSelectShippingContact` the `postalAddress` of the `PKContact` object will be full, but not the `name` field.

The remaining, more sensitive, information will only be available after the payment is authorized via Face ID, Touch ID etc.
So in the `didSubmit` delegate method of the `ApplePayComponent`, the `ApplePayDetails` object should contain such information in the `shippingContact` property.

Let us know if this helps!

**Comment by MewanWA** [comment]
@erenbesel Understood. 

What about the missing postal address data? As you can see, I have entered Netherpark Crescent as the street. But in the delegate method this is not returned under _street_. Even the Postcode as LA12 2NP only has LA12 returned.

**Comment by erenbesel** [comment]
It's also part of Apple's security reasoning, I'm afraid. The full address is only available after the payment is authorized. 
(We directly pass the `contact` object from that delegate to our method without any modification)

You can find online many posts about this limitation as well.
