### ISSUE TITLE
[NEED ASSIST] Apple Pay component doesn't show up anymore

### ISSUE THREAD

**Issue by erlandrolniji** [Adyen/adyen-ios#1288]
**Context**
Hi, I'm integrating Adyen Apple Pay Component in my app. I'ved configure everything in my Adyen account, my session is well created and I can see Apple Pay in my available payment method. But when I present the component it dosen't show it up on physical device. However it's working on simulator. I don't know what's going wrong cause I have no log / no error in my xcode log or in PresentationDelegate.

**To Reproduce**
1. Setup a test environment to make apple pay payment
2. Configure an ApplePayComponent 
3. Try to present the ApplePayComponent
4. Component is not showing up

**Expected behavior**
It supposed to show the component to finalize the payment.

**Environment**
 - Device: [e.g. iPhone7]
 - iOS Version: [e.g. iOS 15.7.7]
 - SDK Version: [e.g. 5.0.0]
 - Adyen API Version: [e.g 70]
 - Xcode version: [e.g 14.3]
 - Mac OS type: [e.g. M1 / Intel]

**Relevant source code**
Here is the PresentationDelegate implementation
```
extension TotalPriceViewController: PresentationDelegate {
  internal func present(component: PresentableComponent) {
    if let paymentComponent = component as? PaymentComponent {
      paymentComponent.delegate = adyenSession
    }

    // Keep the component instance to avoid it being destroyed after the function is executed.
    if let applePayComponent = component as? ApplePayComponent {
      currentComponent = applePayComponent
    }

    // Check if component can be presented as is or needs extra navigation layer.
    guard component.requiresModalPresentation else {
      present(component.viewController, animated: true)
      return
    }

    let navigation = UINavigationController(rootViewController: component.viewController)
    component.viewController.navigationItem.rightBarButtonItem = .init(barButtonSystemItem: .cancel,
                                                                       target: self,
                                                                       action: #selector(cancelApplePayComponentPressed))
    present(navigation, animated: true, completion: nil)
  }
}
```

Here is how I configure ApplePayComponent and present it 
```
func showApplePayComponent() {
    guard let configuration = AdyenApplePayManager.shared.getConfiguration() else {
      return
    }
        
    AdyenSession.initialize(with: configuration, delegate: self, presentationDelegate: self) { [weak self] result in
      switch result {
      case let .success(session):
        // Store the session object.
        self?.adyenSession = session
        if let applePayComponent = self?.createApplePayComponent() {
          self?.present(component: applePayComponent)
        }
      case let .failure(error):
        self?.presentApplePayAlert(false, error.localizedDescription)
      }
    }
  }
    
  /// Creates Adyen Apple Pay component.
  func createApplePayComponent() -> ApplePayComponent? {
    guard let payment = AdyenApplePayManager.shared.getPayment(),
          let paymentMethods = adyenSession?.sessionContext.paymentMethods,
          let paymentMethod = paymentMethods.paymentMethod(ofType: ApplePayPaymentMethod.self),
          let context = AdyenApplePayManager.shared.getAdyenContext() else { return nil }
    if let applePayment = try? ApplePayPayment(payment: payment, brand: AdyenConfigurationConstants.merchantAccount) {
      var applePayComponentConfiguration = ApplePayComponent.Configuration(payment: applePayment,
                                                                           merchantIdentifier: AdyenConfigurationConstants.applePayMerchantIdentifier)
      applePayComponentConfiguration.allowOnboarding = true
      // Check that the payment method is supported and context before showing the Component.
      do {
        let applePayComponent = try ApplePayComponent(paymentMethod: paymentMethod,
                                                      context: context,
                                                      configuration: applePayComponentConfiguration)
        return applePayComponent
      } catch {
        presentApplePayAlert(false, error.localizedDescription)
      }
    }

    return nil
  }
```

Thanks for your help 🙏

**Comment by descorp** [comment]
Hey @erlandrolniji 

> I don't know what's going wrong cause I have no log / no error in my xcode log

To enable SDK's logs, set 

```swift
#if DEBUG
    AdyenLogging.isEnabled = true
#endif
``` 

> However it's working on simulator. 

To make ApplePay work - make sure to follow all [steps](https://docs.adyen.com/payment-methods/apple-pay/enable-apple-pay/?tab=i_os_2) on Docs:

1. App Bundle must have MerchantID
2. MerchantID must be present on `.entitlemnts` file in your project
3. MerchantID must be send to `ApplePayComponent.Configuration`
4. Device must have at least one supported card in a wallet

**Comment by erlandrolniji** [comment]
Hi @descorp 
Thanks for your quick anwser, I can display correctly the component now but I have an error when I make the payement : 
```
Not allowed to store Payout Details
```
This means I used a wrong Apple card ? I'm not sure about what this error really means. Can you clarify it for me please ? 
I'm using those card from Apple Sandbox website : 

5204 2452 5305 0839
Expiration Date: 12/2024
CVC: 111

5204 2452 5471 8095
Expiration Date: 12/2024
CVC: 111

**Comment by descorp** [comment]
Hey @erlandrolniji 

This error probably has nothing to do with Apple Pay or iOS SDK 🤔

I would recommend contacting our [support team](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420) since the solution will require a more secure channel of communication then a public GitHub Issue 😄

**Comment by erlandrolniji** [comment]
Alright thanks for your help

**Comment by descorp** [comment]
Hey @erlandrolniji 

[160 - Not allowed to store Payout Details](https://docs.adyen.com/development-resources/error-codes/#160-not-allowed-to-store-payout-details)

This error is usually caused by sending enablePayout: true on [`\payments`](https://docs.adyen.com/api-explorer/Checkout/70/post/payments#request-enablePayOut) or [`\sessions`](https://docs.adyen.com/api-explorer/Checkout/70/post/payments#request-enablePayOut) API requests without permission for it on your `ws user`.
However, it is better to discuss with support the reason for sending or not sending this flag..
