### ISSUE TITLE
PaymentMethod encrypted data empty

### ISSUE THREAD

**Issue by brurend** [Adyen/adyen-ios#129]
After submitting the card information using the iOS component I'm receiving nil in the information I'm supposed to send to my server. I believe my code is almost the same as the documentation, not sure whats going wrong

```
paymentMethod : CardDetails
    - type : "scheme"
    - storedPaymentMethodIdentifier : nil
    - encryptedCardNumber : nil
    - encryptedExpiryMonth : nil
    - encryptedExpiryYear : nil
    - encryptedSecurityCode : nil
    ▿ holderName : Optional<String>
      - some : "J. Smith"
  - storePaymentMethod : false
```

**Comment by joostvandijk** [comment]
Hi @brurend,

This is likely the result of an invalid public key. Please make sure you specify the correct card encryption public key. We are working on improving the error handling on this.

Best,

Joost

**Comment by brurend** [comment]
That was the problem, I was using the API key instead of the encryption key. Thank you.
