### ISSUE TITLE
[BUG] Demo App can't be built then crashes with Xcode 14.3 / Ventura 13.4.1 - SPM

### ISSUE THREAD

**Issue by axc921** [Adyen/adyen-ios#1291]
**Describe the bug**
Attempting to build the Demo app, I've run into several problems ultimately leading to a crash.

Logistics:  Xcode 14.3 (14E222b) 
M1 Mac - Ventura 13.4.1
iPhone12 - iOS 16.5.1

**To Reproduce**

1. Fork the iOS Repo (this one up to the latest commit in develop from 7/27/23: 4cd3bab ), 
2. Go to 'Configuration.swift' - Fill out static lets - clientKey, demoServerAPIKey, applePayMerchantIdentifier, merchantAccount, appleTeamIdentifier

4. Modify targets to point to my bundle identifiers and provisioning

Issue# 1:  For Aidan Actions:  ThreeDS2ComponentChallengeToken.swift - "No Such Module 'Ayden3DS2': 

![Screenshot 2023-07-28 at 2 44 09 PM](https://github.com/Adyen/adyen-ios/assets/110916458/3488a9bc-6772-4854-8287-b1be90127c83)

Remediation: I then when into Aidan Actions target, and manually Added "Adyen3DS2"  in the Link Binary with Libraries:

![Link Binaries](https://github.com/Adyen/adyen-ios/assets/110916458/6996a7fe-2910-4247-b4ed-fecee9b747e0)

Clean, build, re-run - then received this crash:

![Crash](https://github.com/Adyen/adyen-ios/assets/110916458/f5a23df7-7c01-40b2-bff2-d0abcd196c19)

Debugger output:

dyld[1330]: Library not loaded: @rpath/Adyen.framework/Adyen
  Referenced from: <F52EDB40-5304-3FEA-BB24-3E1785B9579C> /private/var/containers/Bundle/Application/51CF6ACE-1EBF-4AA1-9842-6FAA683F3D5C/AdyenSwiftUIHost.app/AdyenSwiftUIHost
  Reason: tried: '/usr/lib/swift/Adyen.framework/Adyen' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/Adyen.framework/Adyen' (no such file), '/private/var/containers/Bundle/Application/51CF6ACE-1EBF-4AA1-9842-6FAA683F3D5C/AdyenSwiftUIHost.app/Frameworks/Adyen.framework/Adyen' (no such file), '/Users/achin/Library/Developer/Xcode/DerivedData/Adyen-gznuwtaxwwpwzmgigfkdijxzvkdy/Build/Products/Debug-iphoneos/PackageFrameworks/Adyen.framework/Adyen' (no such file), '/private/preboot/Cryptexes/OS/Users/achin/Library/Developer/Xcode/DerivedData/Adyen-gznuwtaxwwpwzmgigfkdijxzvkdy/Build/Products/Debug-iphoneos/PackageFrameworks/Adyen.framework/Adyen' (no such file), '/usr/lib/swift/Adyen.framework/Adyen' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/Adyen.framework/Adyen' (no such file), '/private/var/containers/Bundle/Application/51CF6ACE-1EBF-4AA1-9842-6FAA683F3D5C/AdyenSwiftUIHost.app/Frameworks/Adyen.framework/Adyen' (no such file), '/Users/achin/Library/Developer/Xcode/DerivedData/Adyen-gznuwtaxwwpwzmgigfkdijxzvkdy/Build/Products/Debug-iphoneos/PackageFrameworks/Adyen.framework/Adyen' (no such file), '/private/preboot/Cryptexes/OS/Users/achin/Library/Developer/Xcode/DerivedData/Adyen-gznuwtaxwwpwzmgigfkdijxzvkdy/Build/Products/Debug-iphoneos/PackageFrameworks/Adyen.framework/Adyen' (no such file), '/System/Library/Frameworks/Adyen.framework/Adyen' (no such file, not in dyld cache)

Then I realized that the Packages that were included in the Adyen.xcodeproj were older than the latest and maybe not all were there.   Here's what I have currently on the project:

Adyen3DS2 2.32
AdyenAuthentication 1.1.2
AdyenNetworking 2.0.0
AdyenWeChatPayInternal 2.1.0
PayKit 0.3.0
swift-snapshot-testing 1.11.1
SwiftGenPlugin 6.6.2

I'm about to update delete the package dependancies and add back to the latest versions, but I don't believe the targets would work correctly.
 
Are there any dev best practices here or on the documentation site, or  for running the Demo App?
Or quick steps for getting Adyen to work in a brand new app using SPM, Xcode 14.3, M1 Ventura?

I left another [NEED ASSIST] ticket earlier this morning.

**Expected behavior**
Run the app and demo the Adyen iOS features

**Screenshots**

**Environment**
 - Device: iPhone 12
 - iOS Version:  16.5.1
 - SDK Version:  What's currently on the Project in Git
 - Adyen API Version: What's currently on the Project in Git
 - Package management system: SPM
 - Xcode version: 14.3 (14E222b) 
 - Mac OS type:  M1   Ventura 13.4.1

**Relevant source code**
Add any source code causing the problem here.

**Additional context**

**Comment by descorp** [comment]
Hey @axc921 

I wasn't able to reproduce this on a clean VM.
This could be a result of a dev bias (#workonmymachine), however I am inclining that this is your local setup issue.

Project expected to work out of the box.
I guess somehow SPM was not correctly fetched.
I can only suggest "Reseting SPM Caches".

Do you or other developers face this issue on other laptops?

**Comment by axc921** [comment]
Hey @descorp,

Thanks for getting back to me.   I'm trying a few things, per my [NEED ASSIST] ticket #1289, our team is looking to implement into a SwiftUI app.  An app that already has SPM for other dependancies, and some UIViewRepresentables to support UIKit views.

My first step in evaluating Adyen was to run your demo to un-cover best practices, etc. 

I have re-set packages in this project and it displays this with no Adyen, but Adyen3DS2, and some others...:

![Screenshot 2023-07-31 at 9 19 07 AM](https://github.com/Adyen/adyen-ios/assets/110916458/da51e8ad-d1a3-49f9-86b7-1a862dac5943)

In your demo, should I re-install packages to the latest (per the documentation)?

Example:  On a new setup of a fresh sample app of my own it displays as such with Adyen 5.2.0, etc...:

![Screenshot 2023-07-31 at 9 20 38 AM](https://github.com/Adyen/adyen-ios/assets/110916458/a26230af-49f6-4630-8760-8f60cc7cd79a)

I could have other team members give running your demo a try, however this is a Spike ticket (exploratory) at this point.  

Thoughts?

**Comment by goergisn** [comment]
Hi @axc921 
I was able to reproduce the issue with a clean build.
I have a PR ready with a fix: https://github.com/Adyen/adyen-ios/pull/1292

Temporary workarounds:
1) build the `AdyenUIHost` target first and then the `AdyenSwiftUIHost` or
2) Add the 3DS2 framework to the `AdyenSwiftUIHost`

<img width="916" alt="Screenshot 2023-07-31 at 15 23 35" src="https://github.com/Adyen/adyen-ios/assets/4838877/e2ce9262-0be3-4834-b75a-c07145750b8c">

**Comment by axc921** [comment]
Hi @goergisn, thanks for the steps!    Just to make sure....Quick question:   Will this only run on a device?..  I'll need to change all the targets bundle id's to my company, etc..

**Comment by goergisn** [comment]
Both `AdyenUIHost` and `AdyenSwiftUIHost` can run on the Simulator. 
Are you running into any specific issues?

**Comment by axc921** [comment]
Hi Alex (@goergisn)

Thanks for the feedback re-simulator.   I am making progress based on your past note, thanks!....
I'll give simulator a try later...

I did however get a crash using the AdyenSwiftUIHost target.  on a device see this screen shot:
"Library not loaded"... I believe I need to replace this "empty" item...

Thoughts?

![Screenshot 2023-07-31 at 10 10 33 AM](https://github.com/Adyen/adyen-ios/assets/110916458/8adf8361-6f19-4aa3-93df-567f2cba825c)

**Comment by goergisn** [comment]
@axc921 The fix was just merged into develop - could you please verify if it fixes your issue? (It also removes the null framework in the list)

You might want to clear your derived data and do a clean build.

**Comment by axc921** [comment]
@goergisn  - Yes this fixes the issues above!   Thanks!   I'm able to run on Simulator.    Have a great day @goergisn!
