### ISSUE TITLE
[NEED ASSIST] I'm wondering why 'showInstallmentPrice' is disable in iOS

### ISSUE THREAD

**Issue by shayan77** [Adyen/adyen-ios#1296]
**Describe the challenge**
I'm implementing installments for iOS and I can see in the SDK the option for enabling "show installment price" is disabled.

`/// Determines whether to show the money amount in the installment selection.
    /// For example, "3 months X 500 USD" or "3 months".
    /// For now it is disabled due to making the dividing calculations in the client.
    @_spi(AdyenInternal)
    public let showInstallmentPrice: Bool`
    
First I want to know why this is disable from SDK and do we have any other option to show installment price in the picker?

**Comment by erenbesel** [comment]
Hi @shayan77 
The price shown in there may not be the correct one as with installments the monthly amount may change with an added interest based on the card scheme's policy. 

Therefore it is not enabled as of yet. For now, no other option is available either.

**Comment by shayan77** [comment]
Hi @erenbesel do you have any plan to fix it? We don't have any interest rate and also our web team enabled this option, Also I can see some other apps have this option too.

**Comment by erenbesel** [comment]
We will discuss internally about the possibility. No definite plan yet.

**Comment by shayan77** [comment]
Hi @erenbesel just want to follow up do you have any news about the installment topic?
