### ISSUE TITLE
Credit Card Checkout button for recurring payments

### ISSUE THREAD

**Issue by herrreiprich** [Adyen/adyen-ios#13]
![img_6db4f9b89b33-1](https://user-images.githubusercontent.com/6965151/32726260-a1352638-c878-11e7-9ec5-231942ce31ea.jpeg)

I want to make a 0€ transaction fo adding a credit card as a recurring payment method. The checkout button displays "Pay 0,00€“ (in german 0,00€ bezahlen). Actually, verifying a credit card for recurring payments is not a payment. In this case, button should not display "pay". 

Any chance to change this or add a custom string here?

**Comment by joostvandijk** [comment]
Hi @herrreiprich,

The UI in the Quick Integration is specifically designed for checkouts. If you're looking to use our SDK to store cards for recurring payments, I'd currently suggest you implement your own UI via our Custom Integration methods.

Please let me know if you have any further questions.

Kind regards,

Joost

**Comment by herrreiprich** [comment]
Hi Joost,

good to know. I assumed the SDK will deliver full Adyen feature set. Would be great if you add a brief note about the restrictions of the SDK in the documentation.

Kind Regards
Julian
