### ISSUE TITLE
Localized String potentially missing

### ISSUE THREAD

**Issue by brurend** [Adyen/adyen-ios#130]
Hi, I couldn't find which localized string would be the "Credit Card" title, it's still in English while the rest is in Portuguese. 

Also, is it possible to change the color of the blue "Pay" button? And is it possible to  change the button back to its original state (stop the activity indicator) if there is any failure in the request?

![IMG_2E8EE15AC6A1-1](https://user-images.githubusercontent.com/6145411/69176754-15ef1500-0ae5-11ea-9cf6-23217e150490.jpeg)

**Comment by joostvandijk** [comment]
Hi @brurend,

The name of the payment method is localized by our backend. Provide a `shopperLocale` value in your `/paymentMethods` request, and the titles will be localized.

The submit button's color is derived from the `tintColor` set in your view hierarchy. You can set it on your window, the presenting view controller or the component's view controller.

Best,

Joost

**Comment by brurend** [comment]
Hi,

I managed to change the tintColor, working as expected.

I wasn't able to get the localized payment method though, I tried providing "shopperLocale": "pt-BR", but still had the same English result

**Comment by joostvandijk** [comment]
Hey @brurend,

Just checked this, appears you also need to send `countryCode`:
```json
{
	"countryCode": "BR",
	"shopperLocale": "pt_BR"
}
```

**Comment by brurend** [comment]
@joostvandijk 

Its working now, thank you!
