### ISSUE TITLE
Unable to get pay button response in card component method ios

### ISSUE THREAD

**Issue by ecco-karanjaiswal** [Adyen/adyen-ios#1302]
I am using version 4.10.3 adyen payments in ios application as Demo 
I have a test account and client key
I am able to open card controller view in app but the pay button is start showing indicator on click and always gives didfail() and error is 500 http error.
this is my code. 

```swift
//
//  ViewController.swift
//  
//
//  Created by Admin on 14/07/23.
//

import UIKit
import Adyen
import Combine


class ViewController: UIViewController, PaymentComponentDelegate {
   
   // let clientKey = ""
    let clientKey =  "" // I have passed client key.
    var apiContext: APIContext?
    @IBOutlet weak var currencyTF: UITextField!
    @IBOutlet weak var AmountTF: UITextField!
    var cardPaymentMethod: CardPaymentMethod!
    var payment: PaymentMethodsResponse!
    var cardDetails = [String]()
    var cardName = String()
    weak var cardComponentDelegate: CardComponentDelegate?
    var formButton: FormButtonItem?
    var cardComponentG: CardComponent?

    
    
    func didSubmit(_ data: Adyen.PaymentComponentData, from component: Adyen.PaymentComponent) {
      print("Success")
    }
    
    func didFail(with error: Error, from component: Adyen.PaymentComponent) {
        print("failure -->", error)
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        self.cardComponentG?.delegate = self
        let cartID = "33938f63-3abd-485f-9ad7-ed99981e9381" // Replace with your cartID
        let token = "hGgmd1q9gIIznCEVGnRf7opnjbiLVyPM" // Replace with your actual token
        self.hitAPI(cartID: cartID, token: token)
    }
    
    
    @IBAction func paymentCheckout(_ sender: Any) {
        self.test()
    }
    
    func test() {
        
        let apiContext = APIContext(environment: Environment.test, clientKey: clientKey)
        // Add additional required parameters if needed and inject the instance of `APIContext`.
        let confg = CardComponent.Configuration(showsHolderNameField: true, showsStorePaymentMethodField: false)
        let paymentMethod = MyCardPaymentMethod(type: "scheme", name: cardName, brands: cardDetails, fundingSource: .credit)
        let styleBlack =  FormComponentStyle(tintColor: .black)
        
        let cardComponent = CardComponent(paymentMethod: paymentMethod, apiContext: apiContext, configuration:confg, style: styleBlack)
        cardComponent.delegate = self
        // cardComponent.style.backgroundColor = .blue
        
        // Keep the component instance to avoid it being destroyed after the function is executed.

        // Optional. In this example, the Pay button will display 10 EUR.
        if let price = AmountTF.text {
            let amount = (Int(price) ?? 1) * 100
            cardComponent.payment = Payment(amount: Amount(value: amount, currencyCode: "INR"), countryCode: "IN")
        } else {
            cardComponent.payment = Payment(amount: Amount(value: 0,currencyCode: "INR"), countryCode: "IN")
        }
        
        self.cardComponentG = cardComponent
        DispatchQueue.main.async {
            let presentedViewController = cardComponent.viewController // Replace with your view controller
            let transitioningDelegate = BottomPartialTransitioningDelegate()

            presentedViewController.modalPresentationStyle = .formSheet
            presentedViewController.transitioningDelegate = transitioningDelegate

            // Present the view controller
            self.present(presentedViewController, animated: true, completion: nil)
            self.cardComponentG = cardComponent
        }
        self.cardComponentG = cardComponent
    }
}


extension ViewController {
    
    func hitAPI(cartID: String, token: String) {
        let baseURLString = "https://eccobffqaapp.azurewebsites.net/v1/checkout/paymentMethods/"
        let cartIDPathComponent = "\(cartID)"
        let urlString = baseURLString + cartIDPathComponent

        guard let apiURL = URL(string: urlString) else {
            print("Invalid URL")
            return
        }

        var request = URLRequest(url: apiURL)
        request.httpMethod = "GET"
        request.addValue("Bearer \(token)", forHTTPHeaderField: "Authorization")

        // Make the API request using URLSession
        let task = URLSession.shared.dataTask(with: request) { data, response, error in
            if let error = error {
                print("Error: \(error.localizedDescription)")
                return
            }

            if let httpResponse = response as? HTTPURLResponse {
                if httpResponse.statusCode == 200 {
                    if let data = data {
                        // Process the response data (if needed)
                        do {
                            let responseJSON = try JSONSerialization.jsonObject(with: data, options: [])
                            print("Response JSON: \(responseJSON)")
                            let paymentM = try JSONDecoder().decode(PaymentMethodsResponse.self, from: data)
                            self.payment = paymentM
                            for paym in self.payment.data {
                                self.cardDetails.append(contentsOf: paym.brands)
                                self.cardName = paym.name
                            }
                        } catch {
                            print("Error parsing response data: \(error)")
                        }
                    }
                } else {
                    print("API request failed with status code: \(httpResponse.statusCode)")
                }
            }
        }

        task.resume()
    }
}

struct MyCardPaymentMethod: AnyCardPaymentMethod {
    var type: String

    var name: String

    func buildComponent(using builder: PaymentComponentBuilder) -> PaymentComponent? {
        builder.build(paymentMethod: self)
    }
    var brands: [String]
    var fundingSource: CardFundingSource?
    // Add other required properties and methods as needed
}

// MARK: - Payment Methods
struct PaymentMethodsResponse: Codable {
    let statusCode: Int
    let success: Bool
    let message: String
    let data: [PaymentMethodRes]
}

// MARK: - Datum
struct PaymentMethodRes: Codable {
    let brands: [String]
    let name, type: String
}

class BottomPartialPresentationController: UIPresentationController {
    override var frameOfPresentedViewInContainerView: CGRect {
        // Adjust the frame to control the presentation's height from the bottom
        let containerViewBounds = containerView?.bounds ?? CGRect.zero
        let presentedViewHeight: CGFloat = 300 // Adjust this to your desired height
        let yOrigin = containerViewBounds.height - presentedViewHeight
        return CGRect(x: 0, y: yOrigin, width: containerViewBounds.width, height: presentedViewHeight)
    }
    // You can also implement other methods for animations and interactions if needed
}

class BottomPartialTransitioningDelegate: NSObject, UIViewControllerTransitioningDelegate {
    func presentationController(forPresented presented: UIViewController, presenting: UIViewController?, source: UIViewController) -> UIPresentationController? {
        return BottomPartialPresentationController(presentedViewController: presented, presenting: presenting)
    }
}
```

please I need assisatance as soon as possible @joostvandijk help me out on this.

**Comment by descorp** [comment]
Hey @ecco-karanjaiswal 

Is this a [same question](https://github.com/Adyen/adyen-ios/issues/86#issuecomment-1670909395) ?

---

My guess - your `clientKey` is incorrect.

---

What is the `error`?
If you need more details -  enable logs by calling
```swift
        #if DEBUG
            AdyenLogging.isEnabled = true
        #endif
```

**Comment by ecco-karanjaiswal** [comment]
I think am providing the correct client key , if there is any possibility to check this please tell me.
this is my error log.
---- Request (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
---- Request base url (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
https://checkoutshopper-test.adyen.com/
---- Request Headers (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
["Content-Type": "application/json"]
---- Request query (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
["clientKey": "test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M"]
2023-08-09 15:04:09.384332+0530 EccoCheckoutProcess[19897:245250] Can't find keyplane that supports type 11 for keyboard iPhone-PortraitChoco-NumberPad; using 27303_PortraitChoco_iPhone-Simple-Pad_Default
2023-08-09 15:04:09.412348+0530 EccoCheckoutProcess[19897:245250] API error: <_UIKBCompatInputView: 0x12bd3f3c0; frame = (0 0; 0 0); layer = <CALayer: 0x60000086f240>> returned 0 width, assuming UIViewNoIntrinsicMetric
2023-08-09 15:04:09.412426+0530 EccoCheckoutProcess[19897:245250] API error: <_UIKBCompatInputView: 0x12bd3f3c0; frame = (0 0; 0 0); layer = <CALayer: 0x60000086f240>> returned 0 width, assuming UIViewNoIntrinsicMetric
---- Response Headers (//checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
[AnyHashable("Content-Type"): text/html, AnyHashable("traceparent"): 00-e0ce52ecc4a8311a0a588e7d05295a5a-4fc9ea05ce19f324-01, AnyHashable("Content-Length"): 1022, AnyHashable("Date"): Wed, 09 Aug 2023 09:34:08 GMT]
---- Response (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Unknown error - Adyen</title>
        <link href="/checkoutshopper/css/checkout-error-page.css" rel="stylesheet">
    </head>
    <body>
        <div class="app__main-container">
            <div class="robot-page">
                <div class="robot-page__image">
                    <img src="../images/checkout-error-robot.gif"/>
                </div>
                <div class="robot-page__content">
                    <h1 class="adl-heading margin-left-16 margin-right-16">500 - Bad request</h1>
                    <p class="adl-paragraph margin-left-16 margin-right-16">The page you're looking for seems to be having some issues.</p>
                    <p class="adl-paragraph margin-left-16 margin-right-16">Try refreshing this page or navigate back to previous pages if the problem persists.</p>
                </div>
            </div>
        </div>
    </body>
</html>

---- Request (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
---- Request base url (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
https://checkoutshopper-test.adyen.com/
---- Request Headers (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
["Content-Type": "application/json"]
---- Request query (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
["clientKey": "test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M"]
---- Response Headers (//checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
[AnyHashable("Content-Type"): text/html, AnyHashable("Content-Length"): 1022, AnyHashable("Date"): Wed, 09 Aug 2023 09:34:09 GMT, AnyHashable("traceparent"): 00-b6287ccaccee115fcc6fd5bb5dc9c444-8962ed96b8f793e9-01]
---- Response (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Unknown error - Adyen</title>
        <link href="/checkoutshopper/css/checkout-error-page.css" rel="stylesheet">
    </head>
    <body>
        <div class="app__main-container">
            <div class="robot-page">
                <div class="robot-page__image">
                    <img src="../images/checkout-error-robot.gif"/>
                </div>
                <div class="robot-page__content">
                    <h1 class="adl-heading margin-left-16 margin-right-16">500 - Bad request</h1>
                    <p class="adl-paragraph margin-left-16 margin-right-16">The page you're looking for seems to be having some issues.</p>
                    <p class="adl-paragraph margin-left-16 margin-right-16">Try refreshing this page or navigate back to previous pages if the problem persists.</p>
                </div>
            </div>
        </div>
    </body>
</html>

**Comment by ecco-karanjaiswal** [comment]
> Hey @ecco-karanjaiswal
> 
> Is this a [same question](https://github.com/Adyen/adyen-ios/issues/86#issuecomment-1670909395) ?
> 
> My guess - your `clientKey` is incorrect.
> 
> What is the `error`? If you need more details - enable logs by calling
> 
> ```swift
>         #if DEBUG
>             AdyenLogging.isEnabled = true
>         #endif
> ```

Yes its same question

**Comment by ecco-karanjaiswal** [comment]
am using version 4.10.3
able to click on button , on clicking it loader starts and call backs goes to 
func didFail(with error: Error, from component: Adyen.PaymentComponent) {
        print("failure -->", error)
    }

**Comment by descorp** [comment]
@ecco-karanjaiswal 

What is printed for `print("failure -->", error)` ?

**Comment by ecco-karanjaiswal** [comment]
@descorp 
failure --> HttpError(errorCode: 500, errorMessage: "Http 500 error")

**Comment by aashinisharma2** [comment]
@descorp Can you please look into this? Let us know how we can expedite this with your help as our delivery is at risk because of this.

**Comment by ecco-karanjaiswal** [comment]
@descorp @joostvandijk @adyen-git-manager please look into this I need assistance on this on urgent basis.

**Comment by descorp** [comment]
@ecco-karanjaiswal @aashinisharma2 @bhattal

My guess - your `clientKey` is incorrect.
I would like to check my assumption:

Could you print out this error?
1) make a break point at this line
2) in Xcode terminal performe 
```
po error
```

---

In a meanwhile, please make sure on your [CA](https://ca-test.adyen.com/) that you are using correct [client key](https://docs.adyen.com/development-resources/client-side-authentication/migrate-from-origin-key-to-client-key/#switch-to-using-the-client-key).

**Comment by bhattal** [comment]
@descorp  I have attached the screenshot of this error. You can check.
<img width="506" alt="Screenshot 2023-08-09 at 5 18 19 PM" src="https://github.com/Adyen/adyen-ios/assets/133105791/c3484bdf-134b-4528-a967-52b04208f819">

**Comment by descorp** [comment]
Thanks @bhattal

Sorry, indeed this is not feasible on v4.

Could you do following:

1) make a break point at `print("failure -->", error)` line
2) check debug thead log in Xcode

Is this error coming from `PublicKeyConsumer.fetchCardPublicKey` ?

**Comment by ecco-karanjaiswal** [comment]
This is the Screen shot of that failure debugging.
<img width="752" alt="Screenshot 2023-08-09 at 5 43 23 PM" src="https://github.com/Adyen/adyen-ios/assets/114727184/5d13de2b-5b0a-4e88-9a97-c56380e1e64b">

**Comment by descorp** [comment]
Hey @ecco-karanjaiswal 

I am looking for Thread Log (see example below):

![Screenshot 2023-08-09 at 14 18 16](https://github.com/Adyen/adyen-ios/assets/2648655/2a390ce3-58a7-459d-b5ae-38c342c7e318)

**Comment by ecco-karanjaiswal** [comment]
![Uploading Screenshot 2023-08-09 at 6.02.55 PM.png…]()
This is the required screenshot with threadlogs

**Comment by bhattal** [comment]
@descorp  This is the screenshot of thread logs.


<img width="865" alt="Screenshot 2023-08-09 at 6 07 27 PM" src="https://github.com/Adyen/adyen-ios/assets/133105791/bb0e2beb-f4e3-4340-818b-bc73ad8efc62">

**Comment by descorp** [comment]
@bhattal 

As you can see - it is not able to fetch Public Key. Error triggered by `PublicKeyConsumer.fetchCardPublicKey`.

[Create new Client Key](https://docs.adyen.com/development-resources/client-side-authentication/#get-your-client-key) and try again. Since you have exposed your test key in this public thread - I recommend you to do so regardless of the outcome.
If you have any difficulties getting correct `clientKey`, please reach out [Adyen Support](https://www.adyen.help/hc/en-us/requests/new).

**Comment by ecco-karanjaiswal** [comment]
> 

ok then let me create a new key and then try again

**Comment by descorp** [comment]
You can verify if the key is correct by running in your browser:
https://checkoutshopper-test.adyen.com/checkoutshopper/v1/clientKeys/{YOUR-CLIENT-KEY}

**Comment by ecco-karanjaiswal** [comment]
I have created a new client key there was some issue  in adyen dashboard >> api credential section where I had just provided my app bundle id  in ( origin column ) then the same key worked for me.
thank you for the assistance @descorp

**Comment by descorp** [comment]
Thanks for confirming @ecco-karanjaiswal !
