### ISSUE TITLE
[BUG] Cannot build with Xcode 15.0 beta 6 (15A5219j)

### ISSUE THREAD

**Issue by filipkjamilov** [Adyen/adyen-ios#1311]
**Describe the bug**
Cannot build the project with the latest Xcode 15.0 Beta 6. We are getting ready to use the latest Xcode 15, but it seems that there is an issue building the Adyen SDK with the last Beta release.

**NOTE: This is not the case on Xcode 15.0 Beta 4. 

**To Reproduce**
1. Download Xcode 15 beta 6 release and try to build the SDK.

**Screenshots**
<img width="1710" alt="image" src="https://github.com/Adyen/adyen-ios/assets/37346196/ebbc442f-84c4-4821-9558-8775b3534856">

**Environment**
 - Device: Any [iPhone 14, iPhone 14 Pro Max...]
 - iOS Version: 17.0
 - SDK Version: 4.10.1, 4.10.2, 4.10.3, 4.10.4, 5.2.0
 - Package management system: SPM
 - Xcode version: Xcode 15.0 Beta 6
 - Mac OS type: M1

**Comment by descorp** [comment]
Hey @filipkjamilov 

Thank you for reporting!
We will take a look

**Comment by descorp** [comment]
Hey @filipkjamilov 

We still expecting Beta 6 for verification.
The `@Observable` issue should be fixed on v5 (it was renamed to `@AdyenObservable`). 
Could you verify on 5.3.0?

**Comment by filipkjamilov** [comment]
I just tested on Beta 6 and it's fixed on 5.3.0. 

Thank you 🙏

**Comment by corentios** [comment]
Hello @descorp 

Is it possible to report this change on v4 versions?


Because migrating v4 to v5 introducing breaking changes.

**Comment by filipkjamilov** [comment]
This would be ideal for us as well :)

**Comment by descorp** [comment]
@corentios @filipkjamilov 

It is already done #1326

We will probably wait a bit for more "surprises" from Apple. 
Keep an eye on v4 release!

**Comment by filipkjamilov** [comment]
I can see that the PR was merged into v4. But it got reverted with https://github.com/Adyen/adyen-ios/pull/1328. What's the status here and what really hapend ?

**Comment by erenbesel** [comment]
Version 4.11.0 will include this change, hopefully next week.

**Comment by cameroncooke** [comment]
This is critical now Xcode 15 RC is now considered latest stable version by Xcode Cloud and may well be the release build. It's considered stable and can be used to build apps for the App Store. All our CI builds are failing as they have moved to using Xcode 15 RC as the default Xcode. When can we expect a fix?

**Comment by erenbesel** [comment]
We are planning to release early next week. You can try specifying the Xcode version on your CIs for the moment.

**Comment by cameroncooke** [comment]
Ok thanks. We have about 30 workflows so was hoping to avoid that. 🙂

**Comment by corentios** [comment]
@cameroncooke having the same problematic, if you can't wait you can try set custom commit on SPM for Adyen

v5 fixes Xcode 15 : `a86f5b99e9abdd8ac0f9846685b0be2418eea531` commit
v4 fixes Xcode 15 : `00ec196e9b2845aec2ee4f7130319dabade873eb` commit

It build correctly on Xcode 15 RC for me

**Comment by neelSharma12** [comment]
We have released [4.11.0](https://github.com/Adyen/adyen-ios/releases/tag/4.11.0). Please let us know if you are facing any other issues by creating new ticket.

**Comment by AndyBettisLush** [comment]
I can't build 4.11.0 under Xcode 15 - I get:

The signature of “Adyen3DS2.xcframework” cannot be validated and may have been compromised.
