### ISSUE TITLE
[BUG] Issue with checkoutAttemptId in PaymentMethodDetails

### ISSUE THREAD

**Issue by stomas** [Adyen/adyen-ios#1318]
**Describe the bug**
`PaymentMethodDetails` consist of `checkoutAttemptId` that is under `@_spi(AdyenInternal)`. Problem is when I try to decode to `AnyDecodable` it is appearing in that object, which as I understand not suppose to. This parameter could be found `Details.swift:16`

**Expected behavior**
When trying to decode `PaymentMethodDetails` it should not decode `checkoutAttemptId`. 

**Environment**
 - SDK Version: 5.2.0

**Comment by descorp** [comment]
Hey @stomas 

[`checkoutAttemptId`](https://docs.adyen.com/api-explorer/Checkout/70/post/sessions#request-fundRecipient-paymentMethod-checkoutAttemptId) is expected to be sent to our API. This property allows Adyen API to provide [analytics](https://docs.adyen.com/online-payments/analytics-and-data-tracking/).

**Comment by descorp** [comment]
I am going to close this ticket due to lack of activity.
Please feel free to continue here.
