### ISSUE TITLE
[BUG] UIHostingController disappears if payment fails

### ISSUE THREAD

**Issue by VPavelDm** [Adyen/adyen-ios#1324]
**Describe the bug**
I use `AdyenSwiftUI.present(viewController:)` modifier inside `SwiftUI.ContentView` to present Drop In Popup. 
`SwiftUI.ContentView` is a part of `UIHostingController` which is presented from UIViewController.
I present UIHostingController using `UIViewController.present(_:, animated:)` method. 
If the user uses 3ds credit card and payment fails, next time when the user initiates payment, UIHostingController disappears instead of presenting Drop In popup. 

**To Reproduce**

To reproduce the bug you can update demo app or you can use [my changes](https://github.com/VPavelDm/adyen-ios/tree/presentSwiftUI). 

1. Pull my changes and run AdyenSwiftUIHost application
2. Click Start Flow button
3. Switch Off "Using Session toggle" 
4. Click "Drop In" button
5. Choose Credit Card
6. Enter 3ds card details (i.e. 5454 5454 5454 5454, 03/30, 737)
7. Click "Pay" button
8. Enter code - 1234
9. Click "Submit" button
10. Error popup appears (I throw an error to display the error popup), click "OK" button
11. Click "Drop In" button 

**Expected behavior**
Drop In popup appears.

**Actual behaviour**
UIHostingController disappears. 

**Screenshots**
[Video of the bug](https://drive.google.com/file/d/1jsocw09Vvd-PB0HXLivxaBoSKpBRgYPA/view?usp=share_link)

**Environment**
 - Device: iPhone 14
 - iOS Version: 16.4
 - SDK Version: 4.10.3
 - Package management system: SPM
 - Xcode version: 14.3.1
 - Mac OS type: M1

**Comment by descorp** [comment]
Hey @VPavelDm 

Thanks for feedback.

Indeed, there is unexpected behaviour on [SwiftUI helper](https://github.com/Adyen/adyen-ios/blob/develop/AdyenSwiftUI/Present%20View%20Controller/FullScreenViewControllerPresenter.swift): when presenting UIAlertController it dismisses itself and causing "unpredictable" state.

---

PR #1325

**Comment by VPavelDm** [comment]
Hey @descorp 
Thank you for your reply, when can I expect the fix on prod?

**Comment by descorp** [comment]
[5.4.0](https://github.com/Adyen/adyen-ios/releases/tag/5.4.0) was released.

@VPavelDm please confirm it resolves the issue

**Comment by descorp** [comment]
I am going to close this ticket due to lack of activity.
Please feel free to continue here.
