### ISSUE TITLE
RedirectPaymentMethod + details not supported?

### ISSUE THREAD

**Issue by dragomir-ivanov-212** [Adyen/adyen-ios#133]
Are there plans for supporting redirect methods (via the RedirectComponent), that require details (e.g. giropay with required bic details)?

Here's the payment methods response for such combination:
`{
	"paymentMethods": {
		"paymentMethods": [{
			"details": [{
				"key": "bic",
				"type": "text",
			}],
			"name": "GiroPay",
			"supportsRecurring": true,
			"type": "giropay"
		}]
	},
	"publicKey": "public key",
	"cardHolderPrefill": "Card Holder"
}`

The way [this if-else](https://github.com/Adyen/adyen-ios/blob/master/Adyen/Core/Payment%20Methods/PaymentMethods.swift#L122-L128) is setup, such methods are not supported. Is there a particular reason they are skipped during decoding - the redirect URL itself seems to work fine on the test environment?

**Comment by joostvandijk** [comment]
Hi @dragomir-ivanov-212,

Thanks for reporting this. We'll see if we can fix this in an upcoming update - Giropay indeed doesn't require the details so it should also function in the redirect component.

Best,

Joost

**Comment by mohammedDehairy** [comment]
@dragomir-ivanov-212 , this issue should be fixed with version 3.3.0.

**Comment by mohammedDehairy** [comment]
@dragomir-ivanov-212 any payment method for which all details are not required ({optional: true} explicitly) including giropay should work now with the RedirectComponent, starting from SDK version 3.3.0.
