### ISSUE TITLE
[BUG] No Callback fired when Adding a 3DS2 card using ThreeDS2Component

### ISSUE THREAD

**Issue by mohamed-sqaure1** [Adyen/adyen-ios#1338]
Description
On updating the Adyen framework to the latest version 5.3.0, the ability to add a 3DS2 card no longer works. The callback from the framework never returns.

To Reproduce

Use any 3DS2 card and try to authenticate it using AdyenActions.ThreeDS2Component
On receiving a fingerprint challenge, call `adyenThreeDS2Component.handle(action)`
Wait for delegate callback methods` didComplete(:), didProvide(:) or didFail(:)` to execute
Expected behavior
Delegate methods `didComplete(:), didProvide(:) or didFail(:) `are expected to be called by the framework

Steps from our side:
I debugged the fellow after calling the `adyenThreeDS2Component.handle(action) ` and then I made some breakpoints to check the flow and the results was that the flow was being broken after calling `transaction.performChallenge(with: challengeParameters)` **(there's no callback from it even in the error state)** in the handle function which is made by the Adyen3DS2 library so can you please check from your side?

Actual behavior
Delegate methods are not called.

Device: iPhone11
OS: iOS16.6
SDK Version 5.3.0

**Comment by descorp** [comment]
Hey @mohamed-sqaure1 

do you persist instance of `adyenThreeDS2Component` ?

---

You can use `AdyenActionComponent` - it is umbrella class of all action handlers. It loads everything lazily, so no impact on memory consumption.

**Comment by mohamed-sqaure1** [comment]
> 
yes I am already using persist instance of `adyenThreeDS2Component`

**Comment by descorp** [comment]
Could you share a code snippet of how you instantiate `ThreeDS2Component`?

**Comment by mohamed-sqaure1** [comment]
Hello @descorp I fixed the issue from our side thanks a lot for your support, so I will close the issue

**Comment by descorp** [comment]
@mohamed-sqaure1 

For the record: what was an issue?
