### ISSUE TITLE
Unable to delete payment method in 5.3.0

### ISSUE THREAD

**Issue by Natelegreat1** [Adyen/adyen-ios#1340]
**Describe the bug**
Since updating from 4.10.1 to 5.3.0, we can no longer delete/disable/remove a stored payment method.

**To Reproduce**
- Open DropIn
- Select "Change payment method"
- See list of Stored payment methods
- Try to swipe left to delete
- Nothing happens

**Expected behavior**
As with version 4.10.1, we are expecting it to still be possible to slide to delete stored payment methods.

**Screenshots**
Here is a video of me desperately trying to swipe or long press unsuccessfully:
[Watch here](https://github.com/Adyen/adyen-ios/assets/2666640/f8c7ff1f-ba98-4c04-80c3-7daf02de17d7)

**Environment**
 - iOS Version: iOS 15, 16, 17
 - SDK Version: 
 - Adyen API Version: [e.g 67]
 - Package management system: SPM
 - Xcode version: Xcode 14.3.1 & Xcode 15 beta 7
 - Mac OS type: M1 Ventura 13.4.1

**Relevant source code**
- We configured the DropIn Configuration:
```
let configuration = DropInComponent.Configuration()
configuration.paymentMethodsList.allowDisablingStoredPaymentMethods = true
```

- We set the `storedPaymentMethodsDelegate`:
 `dropIn.storedPaymentMethodsDelegate = self`

- We implemented the `StoredPaymentMethodsDelegate`:
`func disable(storedPaymentMethod: Adyen.StoredPaymentMethod, completion: @escaping Adyen.Completion<Bool>)`

**Comment by erenbesel** [comment]
Hello @Natelegreat1 the video seems unplayable but is your delegate method `disable(storedPaymentMethod....` triggered at all?

**Comment by Natelegreat1** [comment]
> Hello @Natelegreat1 the video seems unplayable but is your delegate method `disable(storedPaymentMethod....` triggered at all?

I'll try to figure out why video is not working. 

Correct, the delegate method is not triggered... because there is no longer any CTA to trigger it.

**Comment by erenbesel** [comment]
I debugged our demo app and If `storedPaymentMethodsDelegate` is not nil and `configuration.paymentMethodsList.allowDisablingStoredPaymentMethods` is `true`, I am seeing the `Edit` button on the right and can trigger the delegate method.

Maybe the video will provide more info

**Comment by Natelegreat1** [comment]
> I debugged our demo app and If `storedPaymentMethodsDelegate` is not nil and `configuration.paymentMethodsList.allowDisablingStoredPaymentMethods` is `true`, I am seeing the `Edit` button on the right and can trigger the delegate method.
> 
> Maybe the video will provide more info

The video is now just a hyperlink button to view. Not sure why embed does not work on this repo. When I swipe left on 5.3.0, I do not see the Edit button... Can you please share an image of what it is now supposed to look like?

**Comment by erenbesel** [comment]
<img width="350" alt="Screenshot 2023-09-05 at 15 45 41" src="https://github.com/Adyen/adyen-ios/assets/5565908/2ba50888-926e-4924-a99c-3e306b522736">

If what I said above is implemented, this Edit button becomes visible.

Also make sure you initialize dropIn after setting the configuration flag, not before and store the dropIn property (I imagine you are already but still)

**Comment by Natelegreat1** [comment]
> <img alt="Screenshot 2023-09-05 at 15 45 41" width="350" src="https://user-images.githubusercontent.com/5565908/265719140-2ba50888-926e-4924-a99c-3e306b522736.png">
> If what I said above is implemented, this Edit button becomes visible.
> 
> Also make sure you initialize dropIn after setting the configuration flag, not before and store the dropIn property (I imagine you are already but still)

Strange... that is exactly the experience we had up until the update to v5.3.0.

Here is a screenshot of the Drop-in UI since updating and you should be able to click on [this link](https://github.com/Adyen/adyen-ios/assets/2666640/f8c7ff1f-ba98-4c04-80c3-7daf02de17d7) to view the video.
<img src=https://github.com/Adyen/adyen-ios/assets/2666640/449192b2-2be2-4576-b6ad-39c2faf9703b width=200>
Note the Edit and swipe-ability is missing.

If you're saying the UI _should_ not have changed, I'll double-check to see if something went funky in the process of refactoring our code to conform to latest version of the SDK. 🤔

**Comment by erenbesel** [comment]
It's more likely that something happened on your refactor as we have not heard of any similar issue and the demo app is working :/

**Comment by Natelegreat1** [comment]
> It's more likely that something happened on your refactor as we have not heard of any similar issue and the demo app is working :/

Sure enough, it was something that went wrong with the reactor of the new `DropInComponent` init! Thank you for confirming that everything was working properly on your end. 😄
