### ISSUE TITLE
[BUG] Rename  Observer to AdyenObserver in version 4.*

### ISSUE THREAD

**Issue by wohral** [Adyen/adyen-ios#1344]
**Describe the bug**

Unable to build application using new XCode15-beta8.  @Observable should be renamed

**To Reproduce**
Try to run application with adyen-ios 4.10.4 on XCode15-beta8

**Expected behavior**
Version 4.* should be buildable on XCode15-beta8 

**Screenshots**
![image](https://github.com/Adyen/adyen-ios/assets/2254382/b9fbc801-2f21-46ad-9bd4-dc11abced6d1)

**Environment**
 - Device: iPhone XR
 - iOS Version: iOS 17
 - SDK Version: 4.10.4
 - Adyen API Version: [e.g 67]
 - Package management system: SPM
 - Xcode version: 15 beta 8
 - Mac OS type: M1 Ventura

**Request**
Same as was done in 5.0.0 release https://github.com/Adyen/adyen-ios/releases/tag/5.0.0, is it possible to also rename 
Observer to AdyenObserver to avoid potential conflicts in adyen-ios 4.* version? MIgration to 5.* is now quite complicated and for long time process.

**Comment by descorp** [comment]
Hey @wohral 

We have open PR #1329 to fix this.
Will keep you posted.

**Comment by neelSharma12** [comment]
@wohral  We have released [4.11.0](https://github.com/Adyen/adyen-ios/releases/tag/4.11.0). Please let us know if you are facing any other issues by creating new ticket.
