### ISSUE TITLE
[BUG] Xcode 15 beta 7, Adyen 4.10.X SDK not working

### ISSUE THREAD

**Issue by sumitbansalcse** [Adyen/adyen-ios#1345]
With Xcode 15 beta 7, Adyen 4.10.X series SDK throws some errors. Can you guys please have a look? 

**Screenshots**
<img width="1016" alt="MicrosoftTeams-image" src="https://github.com/Adyen/adyen-ios/assets/143060924/5e34a093-8bc0-405f-bcba-f9645556f023">

**Comment by descorp** [comment]
Hey @sumitbansalcse 

Thanks for feedbqaack.
We have similar ticket #1345 - I'll close this one for now.
