### ISSUE TITLE
[NEED ASSIST] Shipping and billing address not returned after Apple Pay authorised with FaceID

### ISSUE THREAD

**Issue by MewanWA** [Adyen/adyen-ios#1347]
**Describe the bug**

I am using the Apple Pay component to make a payment. Everything works as expected however at the final step where I scan my Face and authorize the payment via ApplePay, in the `func didSubmit(_ data: Adyen.PaymentComponentData, from component: Adyen.PaymentComponent) ` I am getting the billing and shipping address as null. In the ApplePayComponent.Configuration I have already set the postalAddress and phoneNumber as required fields. 

Version: 5.0.0

Update: Seems like the shipping and billing address is present in the `func paymentAuthorizationViewController(_ controller: PKPaymentAuthorizationViewController,  didAuthorizePayment payment: PKPayment, completion: @escaping (PKPaymentAuthorizationStatus) -> Void)` function, but after it calls the delegate function `submit(data: PaymentComponentData(paymentMethodDetails: details, amount: applePayPayment.amount, order: order))`, the billing/shipping address is null.

<img width="783" alt="image" src="https://github.com/Adyen/adyen-ios/assets/134686380/4f54c728-85a7-46ed-9cea-c5b8fda508cc">

**Comment by descorp** [comment]
Hey @MewanWA 

if billing and/or shipping were provided with `PKPayment` - it would be added to `ApplePayDetails`.
You can get one from `PaymentComponentData.paymentMethod` on `didSubmit`

```swift
func didSubmit(_ data: PaymentComponentData, from component: PaymentComponent) {
        let applePayDetails = (data.paymentMethod as? ApplePayDetails)
        // Use applePayDetails?.billingContact
    }
```

**Comment by MewanWA** [comment]
Thank you! I was using PaymentMethodDetails earlier which returned null for it. Works now!
