### ISSUE TITLE
[NEED ASSIST] Stand-alone Apple Pay integration

### ISSUE THREAD

**Issue by alex-tiqets** [Adyen/adyen-ios#1348]
Hello,

Our app has an App Clip that is limited to 15MB binary size, and it is not possible to import `AdyenDropIn`. We are thinking of doing a native Apple Pay integration (as this is the payment method for majority of the orders) and redirecting to `adyen-web` for all other payment methods.

Is it possible to use the native "Pay with Apple Pay" button with our existing Adyen infrastructure without importing the `AdyenDropIn`?

Thanks

**Comment by descorp** [comment]
Hey @alex-tiqets 

One can use `AdyenComponents` or even fork our code and go API-only.
