### ISSUE TITLE
AmountFormatter, maximumFractionDigits for COP should be 2

### ISSUE THREAD

**Issue by fiatdv** [Adyen/adyen-ios#135]
Thanks for all your support. We are using your pod to format currency in our app, among other things. For Colombia, country code COP, iOS is returning 0 but it should be 2 according to https://en.wikipedia.org/wiki/ISO_4217. I believe that we need to add an entry for COP on your maximumFractionDigits as follows to fix the iOS COP error. Please advise. Thanks again.

maximumFractionDigits -

        case "COP":
            // iOS returns 0 instead.
            return 2

**Comment by mohammedDehairy** [comment]
@fiatdv this issue should be solved with current version, will close the issue if you don't mind.
