### ISSUE TITLE
iOS 13.1 Fatal Error when selecting payment method

### ISSUE THREAD

**Issue by Tbruni85** [Adyen/adyen-ios#137]
Hi, I'm trying to test your SDK with a test payment following your documentation 
(https://docs.adyen.com/checkout/ios/drop-in)

For some reason I get a fatal error when selecting payment method form your ListViewController:
`Fatal error: Attempted to read an unowned reference but object 0x6000032730f0 was already deallocated2020-01-15 00:00:14.592501+0000 AdyenTest[1925:9418908] Fatal error: Attempted to read an unowned reference but object 0x6000032730f0 was already deallocated`

<img width="1071" alt="Screenshot 2020-01-15 at 00 03 25" src="https://user-images.githubusercontent.com/13588914/72393335-7b98ff80-372a-11ea-9a1d-23446970e1b5.png">

I've checked and the parameters are correctly passed after the first POST request is sent to obtain the list of available payments methods.

The target for my test project is iOS 13.1

Thank you

**Comment by joostvandijk** [comment]
Hey @Tbruni85,

Can you verify if you are retaining the component whilst it's in use?

Best,

Joost

**Comment by Tbruni85** [comment]
Hi @joostvandijk 
thank you for your quick reply.
I initialise the view as you described in your documentation

```
private func lauchPaymentUI() {
        
        configuration.card.publicKey = AdyenConfiguration().PUBLIC_KEY
        let dropInComponent = DropInComponent(paymentMethods: paymentMethods,
                                              paymentMethodsConfiguration: configuration)
        dropInComponent.delegate = self
        dropInComponent.environment = .test
        DispatchQueue.main.async {
            self.present(dropInComponent.viewController, animated: true)
        }
    }
```

I call this when the payment methods response is correctly parsed:

```
do {
       self?.paymentMethods = try JSONDecoder().decode(PaymentMethods.self, from: data)
       self?.lauchPaymentUI()
} catch {
       print(error)
}
```

**Comment by joostvandijk** [comment]
Hi @Tbruni85,

Please store the `dropInComponent` in a variable to create a strong reference:
```swift
private let dropInComponent: DropInComponent?

private func lauchPaymentUI() {
        
        configuration.card.publicKey = AdyenConfiguration().PUBLIC_KEY
        let dropInComponent = DropInComponent(paymentMethods: paymentMethods,
                                              paymentMethodsConfiguration: configuration)
        dropInComponent.delegate = self
        dropInComponent.environment = .test
        self.dropInComponent = dropInComponent
        DispatchQueue.main.async {
            self.present(dropInComponent.viewController, animated: true)
        }
    }
```

**Comment by Tbruni85** [comment]
Thank you @joostvandijk 
that solved the issue
