### ISSUE TITLE
need assistance for currency issue on pay button in UI component method.

### ISSUE THREAD

**Issue by ecco-karanjaiswal** [Adyen/adyen-ios#1372]
1. currently am in india region and providing malaysian country and currency code in payment component but it reflects "₹" as according to india
but when am setting region from my phone to "malaysia" then its showing accordingly
please provide me solution that how could I show a constant currency in any region on pay button.
-----> CODE
cardComponent.payment = Payment(amount: Amount(value:   2000.00 , currencyCode: "RM"), countryCode: "MYR")
@descorp please look into this need urgent assistance on this

**Comment by erenbesel** [comment]
@ecco-karanjaiswal Don't set the `payment` property directly. The `AdyenContext` `context` object while creating the component must have the correct payment object

**Comment by ecco-karanjaiswal** [comment]
Hi @descorp 
am creating the component like this
func cardComponentCheckOut() {
        let confg = CardComponent.Configuration(showsHolderNameField: true, showsStorePaymentMethodField: false)
        let styleBlack =  FormComponentStyle(tintColor: .black)
        for paymentMth in viewModal.paymentMethodModal {
            let paymentMethod = MyCardPaymentMethod(type: paymentMth.type ?? "scheme", name: paymentMth.name ?? "Credit card", brands: paymentMth.brands ?? ["mc", "visa"], fundingSource: .credit)
            let cardComponent = CardComponent(paymentMethod: paymentMethod, apiContext: apiContext!, configuration: confg, style: styleBlack)
            cardComponent.delegate = self
            cardComponent.payment = Payment(amount: Amount(value: viewModal.updateAddressPrice.price ?? 1, currencyCode: "RM"), countryCode: "MY")
            DispatchQueue.main.async {
                let presentedViewController = cardComponent.viewController // Replace with your view controller
                presentedViewController.modalPresentationStyle = .automatic
                self.present(presentedViewController, animated: true, completion: nil)
                self.cardComponentG = cardComponent
            }
        }
    }
    as I am already requesting /paymentsMethods api request before this and on basis of that am paasing the data  in this function.
    So, if am not passing here payment object then only "pay" is showing on the button but I also need to show the amount coming from the backend on it.
    Therefore am trying doing so ,
    In this case am stuck with currency issue.
    if "MYR" is set as currency then it's showing "MYR" everywhere whether if am changing the region from device.
    but same not happening with "RM" it's changing according to region. like "$" in USA

**Comment by goergisn** [comment]
Hi @ecco-karanjaiswal, which SDK version are you using?
The `Amount` has a `localeIdentifier` to force formatting using a specific locale:
e.g. `Amount(value: 17408, currencyCode: "INR", localeIdentifier: "ms_MY")` -> `₹174.08`
