### ISSUE TITLE
[BUG] 3DS2 authentication fails: Message versions for 3DS2 app flow in CReq And AReq don't match

### ISSUE THREAD

**Issue by rajvy1** [Adyen/adyen-ios#1374]
**Describe the bug**

When authenticating a 3DS2 test card using `ThreeDSComponent`, and CHALLENGE_SHOPPER and IDENTIFY_SHOPPER challenges are thrown, the modal pop-up for authentication never appears,
and 3DS2 authentication fails with error:

`Message versions for 3DS2 app flow in CReq And AReq don't match.`

Adyen test cards:
`4035 5014 2814 6300` | `03/2030` | `737`
`4917 6100 0000 0000` | `03/2030` | `737`

*Additional info:*
In the network logs for
 https://pal-test.adyen.com/threeds2simulator/services/ThreeDS2Simulator/v1/handle/f2382b75-5411-44cf-8ccb-66e3ad8bf1a6
 
 The following response is seen:
```
{
  "messageType": "Erro",
  "messageVersion": "2.1.0",
  "threeDSServerTransID": "108cfca2-c58e-4c25-b4e7-b2e5b212ec16",
  "acsTransID": "f2382b75-5411-44cf-8ccb-66e3ad8bf1a6",
  "errorCode": "203",
  "errorComponent": "A",
  "errorDescription": "Message versions for 3DS2 app flow in CReq And AReq don't match.",
  "errorDetail": "unknown",
  "sdkTransID": "0c94f8f5-aec1-4895-9edb-4d90dddd689c"
}

```

**Expected behavior**
The 3DS2 authentication web pop-up should be shown. The authentication should not fail.

**Screenshots**

**Environment**
 - Device: Simulator 
 - iOS Version: iOS 16.4
 - SDK Version: 3.8.3
 - Adyen API Version: [e.g 67]
 - Package management system: Carthage
 - Xcode version: 14.3
 - Mac OS type: M1

**Comment by rajvy1** [comment]
Actually, It seems like we're not able to add any test `3DS2` cards anymore with Adyen sdk version `3.8.3`.

Could it be related to how these [test cards ](https://docs.adyen.com/development-resources/testing/test-card-numbers/#test-3d-secure-2-authentication)are configured, are they not backward compatible with older SDK versions?

**Comment by rajvy1** [comment]
Also, I found the following description of the error code `203` thrown by the SDK. Not sure if these are up-to date or applicable.

https://docs.adyen.com/development-resources/error-codes/#203-invalid-bank-account-holder-name

> 203 - Invalid Bank account holder name
> 
> Cause:
> 
>     Account holder name is inconsistent with FATF 16 recommendations.
>     Name may not contain numbers.

**Comment by robertdalmeida** [comment]
I think in your integration the `messageVersion` field is being hardcoded to 2.2.1, which is why there is a mismatch. The initiated version is 2.2.0. 

Can you check in your stack(Backend/Frontend) if this field is being set to any value?
