### ISSUE TITLE
Tint colour 3.3.0

### ISSUE THREAD

**Issue by brurend** [Adyen/adyen-ios#138]
I didn't quite understand how its supposed to customize the colours in the new version, is there any example or guide about it?

**Comment by joostvandijk** [comment]
Hi @brurend,

Customization is done by passing a style structure in the initializer of a component:
```swift
var style = FormComponentStyle()
style.footer.button.backgroundColor = .red

let component = CardComponent(paymentMethod: paymentMethod,
                                                          publicKey: Configuration.cardPublicKey,
                                                          style: style)
```

More documentation will follow - for now I suggest you explore the API reference ([list style](https://adyen.github.io/adyen-ios/Docs/Structs/ListComponentStyle.html) & [form style](https://adyen.github.io/adyen-ios/Docs/Structs/FormComponentStyle.html)).

Best,

Joost

**Comment by brurend** [comment]
I managed to do it now, thank you for the help
