### ISSUE TITLE
The code does not build with Xcode 15

### ISSUE THREAD

**Issue by AndyBettisLush** [Adyen/adyen-ios#1382]
**Describe the bug**

There are compiler errors when trying to build a project that contains the Adyen code. Errors are in FormCardNumberItem and FormCardNumberContainerItem.

**To Reproduce**

Attempt to build a project containing the Adyen package.

**Expected behavior**

It should build.

**Screenshots**

![Screenshot 2023-09-19 at 09 38 00](https://github.com/Adyen/adyen-ios/assets/129517128/786de0cb-3098-4914-b7d0-178e8898380c)

**Environment**
 - Device: Mac
 - iOS Version:17.0
 - SDK Version: 4.10.4
 - Xcode version: 15
 - Mac OS type: M1 Max

**Comment by goergisn** [comment]
Hi @AndyBettisLush,
we are currently preparing a release for v4 that address these issues 👌 

The errors you're running into are related to:
- https://github.com/Adyen/adyen-ios/issues/1344
- https://github.com/Adyen/adyen-ios/issues/1311

**Comment by neelSharma12** [comment]
Hi @AndyBettisLush We have released [4.11.0](https://github.com/Adyen/adyen-ios/releases/tag/4.11.0). Please let us know if you are facing any other issues by creating new ticket.

**Comment by AndyBettisLush** [comment]
Hi Neelam,

Trying to build with 4.11.0:

￼


Andy

**Comment by descorp** [comment]
Hey @AndyBettisLush 

any progress?

**Comment by AndyBettisLush** [comment]
Hiya,

Apologies, all good now - the reissue of 4.11.0 fixed it.

Andy

**Comment by descorp** [comment]
Thanks for letting us know! 💚
