### ISSUE TITLE
[BUG] 4.11 / The signature of 'Adyen3DS2.xcframework cannot be verified

### ISSUE THREAD

**Issue by corentios** [Adyen/adyen-ios#1383]
**Describe the bug**
Tried to update to 4.11 to build on Xcode 15, I have this error when trying to run the app.

**To Reproduce**
1. Build app
2. See the error

**Screenshots**
<img width="528" alt="image" src="https://github.com/Adyen/adyen-ios/assets/43886135/f9fb493b-2aba-4899-a8c3-0187548b08fe">

**Environment**
 - Package management system: SPM 4.11
 - Xcode version: 15.0 RC
 - Mac OS type: M1

**Additional context**
I tried delete DerivedData, clear build folder.. etc
By using this commit I don't have this problem : 00ec196e9b2845aec2ee4f7130319dabade873eb
(v4 fixes for Xcode 15)

**Comment by piercifani** [comment]
Same here!

**Comment by JeanAzzopardi** [comment]
Same here on 4.11

**Comment by filipkjamilov** [comment]
Having the same issue. We were looking forward for this release and it's pretty important for us to get it ASAP. Is there any chance we can get a working release until end of this week, latest mid next week ? https://github.com/Adyen/adyen-ios/issues/1311

**Comment by goergisn** [comment]
Hi there, thank you for reporting this issue so quickly!

There was an issue on our side with the signature inside of the `Adyen3DS2.xcframework` which was just resolved.

It was fixed without updating the version number so you might need to delete the SPM cache at `~/Library/Caches/org.swift.swiftpm` and maybe restart Xcode and reload the SPM packages.

Let us know if this resolves the issues.
Sorry for the inconvenience.

**Comment by corentios** [comment]
Thanks @goergisn, it works perfectly !
