### ISSUE TITLE
[NEED ASSIST]  Help migrate from 3.9.1 to 5.3.0

### ISSUE THREAD

**Issue by theomendes** [Adyen/adyen-ios#1387]
**Describe the challenge**
Hello, everyone. Good afternoon.

I'm uncertain if this is the most suitable platform to address my query, but I couldn't find an alternative means. We have a customized implementation of Adyen within our application, employing our own user interface and the library's encryption function. We transmit this data to our backend, where it communicate with Adyen.

Due to the current issue of version 3.9.1 not building on XCode 15, we found ourselves compelled to upgrade. During the migration process, I observed that the method `CardEncryptor.encryptedCard(for: cardObject, publicKey: self.PUBLIC_KEY)` no longer exists; it appears to have been replaced by `CardEncryptor.encrypt(card: cardModel, with: publicKey)`. However, this new method does not generate a hash in the same format as the previous version of the iOS library. I reached out to the Android team, and their most recent version indeed generates it in the anticipated format.

The format we are expecting includes the prefix `adyenan0_1_1$` in the hash. I have confirmed this by consulting the Custom Card Integration documentation, which still references code from the old library.

I have attempted various solutions, yet I haven't come across any resources explaining this change or providing an alternative.

Can anyone assist me with this?

Thank you!

**Documentation update (optional)**
https://docs.adyen.com/payment-methods/cards/custom-card-integration/?tab=i_os_2

**Comment by erenbesel** [comment]
Hey @theomendes ,

You can use the `CardEncryptor` without any concern. The documentation seems out of date, apologies for the inconvenience.

The current encryption uses JWE encryption since version [4.2.0](https://github.com/Adyen/adyen-ios/releases/tag/4.2.0) and the generated object with your public key will be recognized by Adyen backend without any issue.

**Comment by theomendes** [comment]
Hey @erenbesel,

Thank you for your response and clarification!

On Friday, I continued debugging, and it appears that our backend, in order to validate the token, checks if it begins with `adyenan`. Since it didn't start with that, it was already returning an error to us, and it didn't even proceed to make the request to Adyen itself. We'll be working on this migration during the upcoming week.

**Comment by erenbesel** [comment]
Glad to hear it! Closing this, good luck on the migration!
