### ISSUE TITLE
[NEED ASSIST] 

### ISSUE THREAD

**Issue by axc921** [Adyen/adyen-ios#1388]
**Describe the challenge**
Greetings, 

With the current iOS Demo on your repo, is it possible to test Apple Pay (Adyen Apple Pay Component),
with Simulator to my Adyen Test account?

I've got the demo working for cc payments, and have everything configured minus the Apple Pay cert I tried configuring, but the instructions were confusing.    I'm doing this work ahead of our up coming implementation - for demoing.

The error I'm getting is "CardPaymentMethod is not available in payment methods response." which makes me believe the test account isn't set up yet as the primary reason.   I thought I'd ask prior to stepping thru and setting break points/print statements.

Thanks,
Adam Chin
Lead iOS Developer
The Sherwin-Williams Company 

**Documentation update (optional)**
If applicable, attach a link to documentation page that wasn't helpful / missing information.
What would you like to see there?

**Screenshots**
![Screenshot 2023-09-22 at 2 31 09 PM](https://github.com/Adyen/adyen-ios/assets/110916458/a86d7137-58b4-49d2-8d41-5fa166d1fd82)

**Comment by descorp** [comment]
Hey @axc921 

> "CardPaymentMethod is not available in payment methods response."

Thank for pointing this one out - message is indeed incorrect.
#1390 

> is it possible to test Apple Pay (Adyen Apple Pay Component), with Simulator to my Adyen Test account?

Apple Pay is not properly testable on Simulator since `PKPaymentAuthorizationViewController` does not provide any `token`.

> have everything configured minus the Apple Pay cert I tried configuring, but the instructions were confusing

Check how to [Enable Apple Pay with your own certificate](https://docs.adyen.com/payment-methods/apple-pay/enable-apple-pay/?tab=i_os_2#process-overview-1). 

If you facing any difficulties - feel free to reach out to [Adyen Support](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420)

**Comment by axc921** [comment]
Hey @descorp

Thanks for clarifying the message and the bug, as well as the need to test on device (sans token).  
Big time saver for me!

Cheers,
Adam

**Comment by axc921** [comment]
Hi @descorp,

Sorry to bother you... I have another question. 

The documentation on the Support site is mis-leading or out of date for Enabling Apple Pay with your own Cert.

Unfortunately, no one responds to tickets I create on my test account ¯\_(ツ)_/¯ .

Doc Link:  [Apple Pay Cert](https://docs.adyen.com/payment-methods/apple-pay/enable-apple-pay/?utm_source=ca_test&tab=i_os_2#create-merchant-identity-certificate)

Apple only accepts CSRs with RSA(2048) now, and the portal isn't providing that that when you download the CSR.
Here's the Error that Apple reports:

<img width="640" alt=" CSR Error on Apple Pay Merch ID CSR upload" src="https://github.com/Adyen/adyen-ios/assets/110916458/dee644c7-62f1-4dc6-b661-ac1b797a7e71">

Would you happen to know the "way" forward for integrating Apple Pay to Adyen- Minimally speaking?

Thanks,
Adam

**Comment by descorp** [comment]
Hey @axc921 

Are you sure you following instructions correctly?
You need to create Apple Pay Payment Processing Certificate by uploading [ECC 256 certificate signing request](https://developer.apple.com/help/account/create-certificates/create-a-certificate-signing-request) generated by Adyen CA portal.

**Comment by axc921** [comment]
> Hey @axc921
> 
> Are you sure you following instructions correctly? You need to create Apple Pay Payment Processing Certificate by uploading [ECC 256 certificate signing request](https://developer.apple.com/help/account/create-certificates/create-a-certificate-signing-request) generated by Adyen CA portal.

Yes, when I generate the request from the portal (web), it outputs a CSR that when bringing it back into Apple, this way, it generates the error.   If I could use a command line tool against the test site, I could direct the output to give me ECC 256, but there's no option to change that in the web gui.

Per what apple recommends in the bottom of the article:
Since it's a test site here's the image again with my merchID, test env showing..

![CSR Error](https://github.com/Adyen/adyen-ios/assets/110916458/474961dc-5bf5-4637-ae51-272d7f18ca96)

This should help as well.   I'm entering via the green box on the apple side, and the cert you see there is one I created (non Adyen), and i'm trying to replace it.

![Apple Edit or COnfigure Merch ID](https://github.com/Adyen/adyen-ios/assets/110916458/b930a38a-0603-4855-9477-a39c1d42cc8c)

Thanks for any insight you might have :)

**Comment by descorp** [comment]
Hey @axc921 

Are you operating exclusively in China mainland?

![Screenshot 2023-09-28 at 12 11 14](https://github.com/Adyen/adyen-ios/assets/2648655/685fb34d-d439-4aec-b792-839ae8ca86fe)

**Comment by axc921** [comment]
> Hey @axc921
> 
> Are you operating exclusively in China mainland?
> 
> ![Screenshot 2023-09-28 at 12 11 14](https://user-images.githubusercontent.com/2648655/271249083-685fb34d-d439-4aec-b792-839ae8ca86fe.png)

Hey @descorp  - Actually no, entirely in the USA.  I selected No on that option

**Comment by descorp** [comment]
@axc921 

According to Apple docs - non-china certificates need ECC 256. I asume evrything else (china-exclusively) work via RSA.

![Screenshot 2023-09-28 at 12 54 34](https://github.com/Adyen/adyen-ios/assets/2648655/795df295-2583-423e-b9f5-b0e78efc1147)

Could you double check / create new processing certificate with "exclusively in China" set to "No" ?
If no luck - I recommend contacting Apple Support

**Comment by axc921** [comment]
@descorp  - Thanks for spending a few minutes on this.

Yes, I selected No for that.    We're talking about two different issues here for configuration.
If you could take 5 more minutes to read below, it would be greatly appreciated :)

**First Issue :**

The issue is when we download the .cer from the Adyen Customer area, And upload that to Apple, it throws the error.
![image](https://github.com/Adyen/adyen-ios/assets/110916458/fdc450d1-b25a-4d57-a426-ae0a97032b51)

We inspected the .cer that gets output from the Customer Area, and it's SHA256.
This was the main issue I was speaking of.


**Second Issue:**

Related to your message above, I can create ECC 256 CSR easily, and create a cert on Apple, that works like a charm actually, and it's based on a .cer I generated locally.

Now, if I take that cert go back into the customer area:

![New Apple Pay Cert](https://github.com/Adyen/adyen-ios/assets/110916458/b16d7796-2291-44a0-b97e-ad1aac02f335)

Upload it, I get this error:

![Error uploading cert to Cust Area](https://github.com/Adyen/adyen-ios/assets/110916458/523be38a-f88e-4a64-b6ae-ae6b07e015da)

I understand why this would error - because the .csr generated was from the site itself, and it's clearly wrong.

What's confusing is the actual steps to take to configure Adyen Customer site.

**Two Scenarios:**

1) If we where using the cert I created locally via my Keychain, and Apple exclusively, how is this to be configured back
on the Adyen Customer site?


2) If we were using Adyen's .csr generated from the Adyen Customer site, how is that configured given the output is SHA256?  

Thanks so much!

**Comment by descorp** [comment]
Hey @axc921 

> If we where using the cert I created locally via my Keychain, and Apple exclusively, how is this to be configured back
on the Adyen Customer site?

You don't need to create certificate yourself.

> The issue is when we download the .cer from the Adyen Customer area

Adyen CA portal generates unique signing certificates **(.csr)** for specific ws user and MerchantID:
```
MY-MERCHANT-ID_MY-WS-USER_merchant.com.MY-ID.csr
```
One needs to generate **"non China Exclusive"** Payment Processing Certificate on Apple portal by uploading the signing certificate.
Later on this signing certificate would be used by Adyen's backend to decrypt ApplePay tokens generated by your app.

> And upload that to Apple, it throws the error.

Error "CSR algorithm/size incorrect. Expected: RSA(2048)" appear when attempting to upload "ECC 256" private key to **"China Exclusive"** Payment Processing Certificate.

> We inspected the .cer that gets output from the Customer Area, and it's SHA256.

If you believe there is something wrong with Adyen Customer Area Portal - please reach out to [Adyen Support](https://www.adyen.help/hc/en-us/requests/new?ticket_form_id=360000705420).

**Comment by axc921** [comment]
Hey @descorp,

I'll double check / confirm / try non China Exclusive again just to be sure, then reply back.

Thanks for spending the extra time on this :)

Adam
