### ISSUE TITLE
Protocol error when trying to encode PaymentDetails

### ISSUE THREAD

**Issue by SMJ93** [Adyen/adyen-ios#140]
I've managed to get most of the Adyen iOS drop in flow working, but I can't `encode` the `details` part of the `payment/details` request:

```
internal struct PaymentDetailsRequest: Encodable {
  
  internal let details: AdditionalDetails
  internal let paymentData: String
  
  internal func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    
    // This errors with: Protocol type 'Any' cannot conform to 'Encodable' because only concrete types can conform to protocols
    try container.encode(details.dictionaryRepresentation, forKey: .details)
    try container.encode(paymentData, forKey: .paymentData)
  }
  
  private enum CodingKeys: String, CodingKey {
    case details
    case paymentData
  }
}
```

It is complaining about the type `[String: Any]` for the `dictionaryRepresentation`.

How have other people managed to get around this?

I've not done much swift before so apologies if I am missing something stupid!

**Comment by mohammedDehairy** [comment]
Hi @SMJ93, Thanks for reaching out.

This is definitely something that we should make it easier in the future.

But for now, in the AdyenUIHost example code you'll find this KeyedEncodingContainer extension:

```
extension KeyedEncodingContainer {
    /// Encodes the given value for the given key.
    ///
    /// - parameter value: The value to encode.
    /// - parameter key: The key to associate the value with.
    /// - throws: `EncodingError.invalidValue` if the given value is invalid in
    ///   the current context for this format.
    mutating func encode(_ value: [String: Any], forKey key: KeyedEncodingContainer.Key) throws { // swiftlint:disable:this explicit_acl
        var container = nestedContainer(keyedBy: JSONCodingKeys.self, forKey: key)
        
        try value.forEach { (key: String, value: Any) in
            let codingKey = JSONCodingKeys(value: key)
            
            switch value {
            case let boolValue as Bool:
                try container.encode(boolValue, forKey: codingKey)
            case let stringValue as String:
                try container.encode(stringValue, forKey: codingKey)
            case let intValue as Int:
                try container.encode(intValue, forKey: codingKey)
            case let doubleValue as Double:
                try container.encode(doubleValue, forKey: codingKey)
            case let nestedDictionary as [String: Any]:
                try container.encode(nestedDictionary, forKey: codingKey)
            default:
                let context = EncodingError.Context(codingPath: codingPath, debugDescription: "Failed to encode dictionary value.")
                
                throw EncodingError.invalidValue(value, context)
            }
        }
    }
    
}
```

if you add this code and make sure this extension is accessible from where PaymentDetailsRequest is declared, then it should work.

The extension basically gets around the fact that type `Any` in `[String: Any]` cannot conform to encodable.

**Comment by SMJ93** [comment]
Hi @mohammedDehairy, thanks for getting back to me! 

I managed to get it working with `AnyEncodable` - found [here](https://forums.swift.org/t/how-to-encode-objects-of-unknown-type/12253/11
)

```
extension Encodable {
  fileprivate func encode(to container: inout SingleValueEncodingContainer) throws {
    try container.encode(self)
  }
}

internal struct AnyEncodable : Encodable {
  var value: Encodable
  init(_ value: Encodable) {
    self.value = value
  }
  func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    try value.encode(to: &container)
  }
}
```

And then if there is a type of `[String: Any]` e.g. `details` use:

```try container.encode(AnyEncodable(details), forKey: .details)```

Why do you use `[String: Any]` and not fully type it?

**Comment by mohammedDehairy** [comment]
Hi @SMJ93 ,

 We are using a [String: Any] because every component has different PaymentMethodDetails fields, so [String: Any] would normalize the "payment details" for all of them, and at the same time we want to use the same PaymentComponentDelegate for every component, but of course as you can see this creates a problem when encoding the PaymentMethodDetails by the merchants.

 We are thinking how to solve this normalization problem, and the same time make it much easier for the merchants to deal with PaymentMethodDetails including encoding.

 So if you happen to have a suggestion, please let us know.

**Comment by SMJ93** [comment]
Hi @mohammedDehairy, I see! Makes sense. 

It might be worth adding something to the docs as I am sure a lot of other users will encounter / get frustrated by this

**Comment by mohammedDehairy** [comment]
@SMJ93 with version 3.4.0+ this issue should be solved using a solution similar to the one you suggested, will close this issue, and you can reopen it if you still having a problem.
