### ISSUE TITLE
[BUG] Drop-In ApplePay controller is not dismissed on x button tap

### ISSUE THREAD

**Issue by dsk1306** [Adyen/adyen-ios#1405]
**Describe the bug**

I've encountered a problem with the Drop-In ApplePay integration.

When I try to cancel the payment and tap the 'x' button on the Apple Pay controller, the view is not dismissed and the interface becomes unresponsive. `AdyenSessionDelegate.didComplete` and `.didFail` aren't called either.

https://github.com/Adyen/adyen-ios/assets/9428706/5b75e549-57d2-4b74-9ac6-a4617fc9cd01

If I don't cancel and finish the payment, the flow works fine (by throwing an error on simulator and finishing the payment on a real device).

https://github.com/Adyen/adyen-ios/assets/9428706/a398c6f2-1055-499c-9279-bdb59797f441

Am I missing something? Do I need to do extra configuration for ApplePay?

**Environment**
 - iOS Version: 17.0
 - SDK Version: 5.4.0
 - Package management system: SPM
 - Xcode version: 15.0
 - Mac OS type: M1

**Comment by descorp** [comment]
Hey @dsk1306 

Indeed this is bug on our side 😅

Will keep you posted

**Comment by goergisn** [comment]
Hi @dsk1306 thank you again for reporting this issue 🙏 

Quick update from our side:
We have a fix ready that is going to be shipped within the next days. (See: https://github.com/Adyen/adyen-ios/pull/1408)

Sorry for the inconvenience and confusion it might have caused.

**Comment by goergisn** [comment]
Hi @dsk1306, we just released `5.4.1` as a patch for your described issue.

Thank you again for reporting.

**Comment by azatgoktass** [comment]
Hello @goergisn , we have the same issue for version 4.11.0. Is there going to be another release for 4.xx versions?

**Comment by goergisn** [comment]
Hi @azatgoktass 
The reported bug was introduced in 5.4.0 and should not happen on 4.11.0 🤔 

Do you mind creating a new Github-issue describing your issue?
