### ISSUE TITLE
[NEED ASSIST] How to get the Logo URL for a PaymentMethod in v. 5.3.0?

### ISSUE THREAD

**Issue by miklselsoe** [Adyen/adyen-ios#1415]
**Describe the challenge**
I am migrating from version 4.x to version 5.3 and I need to be able to get the PaymentMethod logo URL. In version 4.x, I could get it from the LogoURLProvider, by passing the PaymentMethod directly, but that is no longer possible in v. 5.3.0. Instead you have to pass a `name` as a String to `LogoURLProvider` to get the URL. The documentation for `LogoURLProvider` doesn't specify what name to provide or where to get it. 

`Displayinformation` has a `logoName` property, but that's internal. And all functions to get a `DisplayInformation` value also seem to be internal? 

So the question basically is: How do I get a logo URL for a PaymentMethod?

**Comment by erenbesel** [comment]
Hi @miklselsoe 
I will investigate the reason behind these changes. Meanwhile, could you provide some more details for your case?
(Which payment method, why do you need to use the URL provider yourself etc)
Normally the SDK prepares the URLs itself.

**Comment by miklselsoe** [comment]
Hi @erenbesel 
Thank you. I am using a components based implementation with a custom UI. I am fetching a list of available payment methods from my backend to display to the user. Additionally I am showing a list payment methods, stored by the user, that they can reuse (fx. VISA). For these stored payment methods I would like to show fx. the VISA logo if the user stored a VISA card etc. 

Once I initiate the actual payment, I rely on the SDK to show logos etc.

**Comment by erenbesel** [comment]
I see. Logo names are mostly created from `paymentMethod.type.rawValue` with some exceptions. One such exception is Stored card payment methods. For type `StoredCardPaymentMethod`, you can use the `brand.rawValue` as the name for the URL provider. If there are other stored payment methods, `type.rawValue` should work.

Will also see if we can/should add back the previous method with the payment method as the parameter.

**Comment by miklselsoe** [comment]
Thank you. That seem to work. An improved interface and/or documentation would be appreciated though. 👍
