### ISSUE TITLE
Different Payment Options Available for iOS & Android

### ISSUE THREAD

**Issue by nidhinprathap** [Adyen/adyen-ios#142]
I'm using Adyen Drop In across the iOS & Android.
In iOS we are seeing a CVV field visible for user, but for Android the CVV field isn't visible. As per configuration the CVV shouldn't be visible in the app. Both are using same Configuration Key. But the Drop In component is showing different behaviour on Both the platforms.

Can i get a clarity why the platforms are showing different behaviour in Drop In Component for the same Configuration.

**Comment by descorp** [comment]
Hi @nidhinprathap 

On iOS, CVV is visible for CardComponent and hidden for BCMCComponent.
It does not depend on a Configuration, but internal property `showsSecurityCodeField` of CardComponent.

Similar for Android: layout for CardComponent includes CVV field, but on BCMCComponent layout, it is not present.

Could you provide more information about what version of checkout SDK you are using and what payment method is not acting as you expect?

**Comment by nidhinprathap** [comment]
The issue was there in Drop In SDK Version 3.1.2. Updated to SDK 3.3.0 & its working fine.
Thanks for the support.
