### ISSUE TITLE
[BUG] Attempting to confirm a saved credit card on an M1/M2 app designed for iPad renders a dialog without a Ok, or Pay Button

### ISSUE THREAD

**Issue by jnorman-control4** [Adyen/adyen-ios#1435]
Describe the bug
When invoking the DropInComponent on iOS when running on a MacBook Pro (M1/M2), (Designed for iPad),  attempting to use a previous/stored credit card presents a popup to confirm the CVC.   There is a Cancel button but no button to confirm or pay.   The user must add a new card to process the transaction.

<img width="785" alt="Screenshot 2023-11-02 at 4 46 05 PM" src="https://github.com/Adyen/adyen-ios/assets/67032874/38b4914c-2e7f-4381-ab9f-2a83c99bb80e">

To Reproduce
Implement the iOS Dropin Component as outlined in the documentation.
Invoke the dropIn, ie: hostingViewController.present(dropInComponent.viewController, animated: true)
Select a previous/stored card.

Expected behavior
The dropIn should appear as it does on iPhone and iPad.

Smartphone (please complete the following information):

Device: Macbook Pro (Designed for iPad) app
OS: iOS 17.x
SDK Version 5.2.0

**Comment by goergisn** [comment]
Hi @jnorman-control4,

Thank you for reporting.

Can you confirm that `Pay $992.25` is not clickable/enabled?
It ~~might~~ does not look like a button but that is how `Designed for iPad` Alerts get rendered unfortunately.

For context: There is no complicated logic behind enabling/disabling that button as it's just checking if the payment method is AMEX (4 digit CVC) or not (3 digit CVC).

Best,
Alex

**Comment by jnorman-control4** [comment]
Hi Alex,
Thanks for the quick reply.  You are correct.   Once the CVC is entered the Pay 992.25 becomes active.
