### ISSUE TITLE
UIWebView reference in Adyen 1.18.x

### ISSUE THREAD

**Issue by otaviocc** [Adyen/adyen-ios#144]
Hi there!

Is there any plans to maintain Adyen 1.x or is it completely deprecated? I'm asking this question for two reasons:

1. Apple requires `UIWebView` references to be completely removed from applications starting April this year
2. We use Adyen 1.x. If Adyen 1.x is deprecated we'll have to migrate to 2.x or 3.x.

In case 1.x is still maintained (Mobile SDK and/or Service), the following patch removes the `UIWebView` reference.

```diff
diff --git a/Pods/Adyen/Adyen/Core/PaymentServer.swift b/Pods/Adyen/Adyen/Core/PaymentServer.swift
index 48f0dfe78..5b6e3bc79 100644
--- a/Pods/Adyen/Adyen/Core/PaymentServer.swift
+++ b/Pods/Adyen/Adyen/Core/PaymentServer.swift
@@ -5,6 +5,7 @@
 //
 
 import Foundation
+import WebKit
 
 /// Used for requests made to the CheckoutShopper API.
 internal class PaymentServer {
@@ -23,15 +24,16 @@ internal class PaymentServer {
         // In the browser the user agent corresponds to Safari, whereas the default user agent corresponds to the app.
         
         let configuration = URLSessionConfiguration.default
-        
         let semaphore = DispatchSemaphore(value: 0)
         var safariUserAgent: String?
         
         DispatchQueue.main.async {
             // Web view can only be created on main thread. Otherwise app crashes.
-            let webView = UIWebView()
-            safariUserAgent = webView.stringByEvaluatingJavaScript(from: "navigator.userAgent")
-            semaphore.signal()
+            let webView = WKWebView()
+            webView.evaluateJavaScript("navigator.userAgent") { string, error in
+                safariUserAgent = string as? String
+                semaphore.signal()
+            }
         }
         
         semaphore.wait()
```

Additionally, if 1.x is maintained, should I open a PR?

Thanks!

**Comment by joostvandijk** [comment]
Hi @otaviocc,

We are not planning to make updates to v1. You can update to v2 with relatively few client and backend changes. Some steps can be found in the [migration document](https://github.com/Adyen/adyen-ios/blob/v2/MIGRATION.md). Alternatively, you can make the change yourself in a local copy of the v1 SDK.

Best,

Joost

**Comment by otaviocc** [comment]
Hi @joostvandijk, thanks for you reply. Unfortunately we use the `CardType` in our application and, on version 2.x, `CardType` is internal. It was public in 1.x and back to public to 3.x. Unfortunately we cannot migrate to 3.x yet.
