### ISSUE TITLE
[NEED ASSIST]  Change localization keys

### ISSUE THREAD

**Issue by b7anka** [Adyen/adyen-ios#1445]
**Describe the challenge**
I need to change these keys
adyen.submitButton from Pay to Add
adyen.submitButton.formatted from Pay €20.00  to  Top up €20.00
What steps did you take?
I added those keys to my app target with the texts that I need
What is the expected behavior / API ?
Your keys would be overridden by mine  

**Screenshots**
The problem that I have is that your keys are not being overridden by mine. Is there any alternative to change those keys?

![Captura de ecrã 2023-11-08, às 10 44 04](https://github.com/Adyen/adyen-ios/assets/25281887/b819c6ef-df0c-4ed7-a678-4a9f1d41f078)
![Captura de ecrã 2023-11-08, às 10 47 31](https://github.com/Adyen/adyen-ios/assets/25281887/dcfb0cf0-bf77-49a7-9907-8c1ebbb6c5a0)

**Comment by descorp** [comment]
Hey @b7anka 

In ".string" file **Key** is surrounded with **""**
See [Localization](https://github.com/Adyen/adyen-ios/blob/develop/Adyen.docc/Localization.md) doc

**Comment by b7anka** [comment]
@descorp thanks for the response, I've surrounded the keys with the "" but still it does not work. I have 2 string files on for all english variations which is only (en) no country code and another for all portuguese variations again no country code and they work correctly for the app as you can see from the screenshot even without the quotes surrounding the keys. I also created another string file this time en-US to see if it would work but still no luck.

**Comment by goergisn** [comment]
@b7anka the way you are setup is actually correct. 

Unfortunately there is currently a bug on the latest release that prevents the localization overrides to be read from the main bundle.

I created a PR that contains the fix.

Thank you for reporting!

**Comment by b7anka** [comment]
@goergisn thanks for the response i didn't specify the version of sdk but it is the latest one 5.4.1 that I am using.

**Comment by goergisn** [comment]
I assume you are using the `CardComponent`?

A workaround in the meantime would be providing localization parameters in the `CardComponent.Configuration` using the default init on `LocalizationParameters()`

```swift
var configuration = CardComponent.Configuration()
configuration.localizationParameters = LocalizationParameters()
let component = CardComponent(
    paymentMethod: paymentMethod,
    context: context,
    configuration: configuration
)
```

Let me know if this works for you for now.

**Comment by b7anka** [comment]
@goergisn I'm using the drop-in, does this work using the drop-in?

**Comment by b7anka** [comment]
@goergisn thanks so much I've tried your solution with the drop-in and it works :D

![Simulator Screenshot - iPhone 14 Pro - 2023-11-08 at 16 53 31](https://github.com/Adyen/adyen-ios/assets/25281887/8e293f0b-0bc8-46f3-8a2d-a86c0b7561b6)
![Simulator Screenshot - iPhone 14 Pro - 2023-11-08 at 16 54 40](https://github.com/Adyen/adyen-ios/assets/25281887/babb7a4b-f139-4137-b846-3e320cb0e256)
