### ISSUE TITLE
[BUG] SPM AdyenActions not compiling when using AdyenAuthentication > 1.1.3

### ISSUE THREAD

**Issue by soucolline** [Adyen/adyen-ios#1454]
**Describe the bug**
When using both Adyen SDK + AdyenAuthentication on a project, the file `ThreeDS2PlusDACoreActionHandler.swift` doesn't compile because it's using some API's that where changed from v1.1.3 on Adyen Authentication

**To Reproduce**
1. Create a project and import both Adyen and AdyenAuthentication SDK from SPM
2. Try to compile 

**Expected behavior**
Project should compile

**Screenshots**

![Screenshot 2023-11-13 at 2 16 39 PM](https://github.com/Adyen/adyen-ios/assets/8956641/f272e075-cd84-40e9-9561-00b95c2ce31f)
![Screenshot 2023-11-13 at 2 16 50 PM](https://github.com/Adyen/adyen-ios/assets/8956641/20c8b736-aa95-49e6-ae0e-e9a99ecb2f58)

**Environment**
 - Device: Any simulator
 - iOS Version: 17
 - SDK Version: Adyen 5.4.1 and AdyenAuthentication 2.0.0
 - Adyen API Version: -
 - Package management system: SPM
 - Xcode version: 15.0.1
 - Mac OS type: M1

**Relevant source code**
ThreeDS2PlusDACoreActionHandler.swift

**Additional context**
Using AdyenAuthentication SDK 1.1.2 works

**Comment by erenbesel** [comment]
Hey @soucolline 
Are you integrating the Authentication SDK for the delegated authentication feature? Since it's an optional module, I just want to make sure you need it.

But in any case, unfortunately as you stated, you will need to use 1.1.3 or lower for the time being. We are checking ways to prevent these mismatches in the future.

**Comment by soucolline** [comment]
Hey @erenbesel thanks for the answer, yes i'm using AdyenAuthentication for out-of-band authentication with cards issued by Adyen. Could it be that you update to the latest version on the Adyen SDK each time there is an update on the Authentication SDK so this way there will be no mismatch as long as you are using the latest version on both ?

**Comment by erenbesel** [comment]
@soucolline , with https://github.com/Adyen/adyen-ios/pull/1456, we are looking to set the version of the Authentication SDK inside our SDK ourselves, to prevent these mismatches on future versions.

**Comment by soucolline** [comment]
Great news thanks

**Comment by soucolline** [comment]
Hey @erenbesel is saw that the PR was merged, do you have a date for when it's going to be released ? 🙏

**Comment by goergisn** [comment]
@soucolline we just released [5.5.0](https://github.com/Adyen/adyen-ios/releases/tag/5.5.0) let us know if this is resolving your issue.

**Comment by soucolline** [comment]
Hey @goergisn, working fine for me thanks, closing the issue
