### ISSUE TITLE
[NEED ASSIST] implement apple pay to drop-in

### ISSUE THREAD

**Issue by ngmiduc** [Adyen/adyen-ios#1457]
**Describe the challenge**
Based on the docs (https://docs.adyen.com/payment-methods/apple-pay/ios-drop-in/) - I am having troubles in adding apple pay to my drop in configuration.

I am not sure how to implement `applePayment` that is used in the docs example below. It is missing an example I think inside the docs. 

```
//Initialize a Drop-in configuration object.
let dropInConfiguration = DropInComponent.Configuration()
//Set configuration for Apple Pay.
dropInConfiguration.applePay = .init(payment: applePayment,
                               merchantIdentifier: YOUR_APPLE_PAY_MERCHANT_ID,
                               requiredBillingContactFields: ... , //Your required billing contact fields.
                               requiredShippingContactFields = ... ) //Your required shipping contact fields.

```

I am also wondering, what are the accepted values for `requiredBillingContactFields` and `requiredShippingContactFields`. 

Do I miss something or is there any other information documented?

I would appreciate some help.

**context**
- hybrid app with ionic and capacitor
- adding Apple Pay to the native DropIn that is implemented as capacitor plugin
- sdk v5.1.0

**Comment by erenbesel** [comment]
Hi @ngmiduc, what version of our SDK are you using?
Starting from [v5.3.0](https://github.com/Adyen/adyen-ios/releases/tag/5.3.0), Apple Pay configuration has a new init that takes the `PKPaymentRequest` that you prepare yourself. (we will update our docs with this too)

So you can create your `PKPaymentRequest` yourself (with all the required parameters based on your cases) and supply it to the configuration like so:
```
dropInConfiguration.applePay = .init(paymentRequest: *yourPaymentRequestObject*)
```
without having to create any `ApplePayPayment`

As for `requiredBillingContactFields`, it depends on what info you need from your shopper. Refer to [Apple Pay documentation](https://developer.apple.com/documentation/passkit/pkpaymentrequest#:~:text=var%20requiredBillingContactFields%3A%20Set%3CPKContactField%3E) for more info

**Comment by ngmiduc** [comment]
Hi,

thanks yes, that worked out!
The DropIn shows now the Apple Pay option. 
It just fails inside the emulator with a test payment. 
It throws an error because the Token is invalid. 
I imagine, that this is normal since I am not running on a real device?

**Comment by erenbesel** [comment]
Exactly, test Apple Pay on a real device to be able to debug your implementation. 

Glad it worked!
