### ISSUE TITLE
CardComponent style customisation

### ISSUE THREAD

**Issue by NicolasJellab** [Adyen/adyen-ios#147]
Hi,

I have been integrating Adyen in my iOS app using `CardComponent` and I want to customise it so it fits the rest of the app's theme.

So far, I have been able to change background and text colours as I wanted but as I tried to go further and set switch default values or `textField` title and text colour on `TouchDown`, I dont find anything related in the documentation.

Is it possible to do that level of customisation with `CardComponent`? Is there something I should change to my current code to make it work ?

```
let blackColor = UIColor(red:0.10, green:0.10, blue:0.13, alpha:1.0)
        let greenColor = UIColor(red:0.84, green:0.93, blue:0.12, alpha:1.0)
        let whiteColor = UIColor(red:1.00, green:1.00, blue:1.00, alpha:1.0)
        let greyColor =  UIColor(red:0.62, green:0.63, blue:0.70, alpha:1.0)
        
        var formStyle = FormComponentStyle()
        formStyle.backgroundColor = blackColor
        
        formStyle.switch.backgroundColor = blackColor
        formStyle.switch.title.color = whiteColor
        
        formStyle.textField.title.color = greyColor
        formStyle.textField.text.color = greyColor
        formStyle.textField.placeholderText = TextStyle(font: .systemFont(ofSize: 17.0), color: greyColor, textAlignment: .natural)
        formStyle.textField.backgroundColor = blackColor
    
        formStyle.header.title.color = whiteColor
        formStyle.header.backgroundColor = blackColor
        
        formStyle.footer.backgroundColor = blackColor
        formStyle.footer.button.backgroundColor = greenColor
        formStyle.footer.button.title.color = blackColor
        
        let navigationStyle = NavigationStyle()
        cardComponent = CardComponent(paymentMethod: paymentMethods!.regular.first! as!  AnyCardPaymentMethod, publicKey: publicKey, style: formStyle, navigationStyle: navigationStyle)
```

**Comment by mohammedDehairy** [comment]
Hi @NicolasJellab ,

Thanks for reaching out.

The TextField title color when it becomes first responder as well as the textField line beneath it follows the view tintColor, so you can customize this using the NavigationStyle:

```
let navigationStyle = NavigationStyle()
navigationStyle.tintColor = [Your custom color]
```
This should change the TextField highlight color (title and the underline).

 But Switch default values is not supported at the moment, maybe when we get enough requests from users.

Best regards

Mohamed

**Comment by NicolasJellab** [comment]
Thank you very much for the quick answer @mohammedDehairy .
It solved the problem so I am going to close the issue.

Best regards,

Nicolas
