### ISSUE TITLE
[Need Assist]  OC Project integrate Adyen SDK

### ISSUE THREAD

**Issue by ZengYao0206** [Adyen/adyen-ios#1477]
It seems very unfriendly for OC project to integrate this Adyen SDK (swift), do you have any suggests?

**Comment by erenbesel** [comment]
Hey @ZengYao0206 
If you need to use our SDK in your Objective C project, you can create a swift class inheriting `NSObject`, and access our SDK in this class. Then use this new class in your Objective C code.

**Comment by ZengYao0206** [comment]
> Hey @ZengYao0206
> If you need to use our SDK in your Objective C project, you can create a swift class inheriting `NSObject`, and access our SDK in this class. Then use this new class in your Objective C code.

hello, erenbesel:

I  pod 'Adyen' to my OC project, and create a swift as a bridge (AdyenManager.swift),  and access adyen api in this class.  I  do it   according to README,  make DropInComponent to be a propertys, But after I tap "cancel", then  it was still nil， I want to know what I did wrong?  thanks！
![Uploading 2023.jpg…]()

<img width="941" alt="截屏2023-12-07 20 10 59" src="https://github.com/Adyen/adyen-ios/assets/13979518/65af5a1e-fecd-4cd0-b725-9ac2de8ee73d">
<img width="954" alt="截屏2023-12-07 20 11 58" src="https://github.com/Adyen/adyen-ios/assets/13979518/037bd45e-bdd2-4b95-9650-7578c6ecf413">

**Comment by ZengYao0206** [comment]
![Uploading 截屏2023-12-07 20.24.50.png…]()

**Comment by erenbesel** [comment]
It could be that the `AdyenManager` that holds `dropInComponent` as a property is not stored. So when it is gone, dropin property will also be nil.

Unfortunately we can't debug your code but you can try to debug your classes like `AdyenManager`

**Comment by ZengYao0206** [comment]
> It could be that the `AdyenManager` that holds `dropInComponent` as a property is not stored. So when it is gone, dropin property will also be nil.
> 
> Unfortunately we can't debug your code but you can try to debug your classes like `AdyenManager`

hi, erenbesel:
The previous problem has been solved。 but now, when I tap "KakaoPay", it respond me "Safari Browser can't open this web link, for it's invalid".   I want know what it mean?  and how to solve it ?  many thanks !

  below  SCREENSHOTS
![WechatIMG60012](https://github.com/Adyen/adyen-ios/assets/13979518/6ee0cc91-2fa4-4f16-abf3-9308ed8b53a6)


![WechatIMG60010](https://github.com/Adyen/adyen-ios/assets/13979518/0e95486e-ac92-49b3-864a-a51249edf379)


![WechatIMG60011](https://github.com/Adyen/adyen-ios/assets/13979518/63605f51-01c3-44cc-a4a3-64900b74285d)

**Comment by ZengYao0206** [comment]
<img width="936" alt="截屏2023-12-13 14 19 24" src="https://github.com/Adyen/adyen-ios/assets/13979518/f9b1ce8b-2042-49f3-adb7-6f9c16d20b23">

**Comment by erenbesel** [comment]
@ZengYao0206 seems you don't have the KakaoPay app in your device.

**Comment by ZengYao0206** [comment]
@erenbesel  I install KakaoPay app in my iPhone, it works same as before.

**Comment by ZengYao0206** [comment]
![WechatIMG60208](https://github.com/Adyen/adyen-ios/assets/13979518/a3825233-44f5-47bd-b232-9e38f43ce0f3)

**Comment by erenbesel** [comment]
Please refer to our docs for more info and contact our support if needed
https://docs.adyen.com/payment-methods/kakaopay/ios-drop-in/#test-and-go-live
