### ISSUE TITLE
[NEED ASSIST] ShopperInteraction for Saved Card 

### ISSUE THREAD

**Issue by MewanWA** [Adyen/adyen-ios#1479]
**Describe the challenge**
Recently Adyen had communicated to our client regarding payments using a Saved Card from the DropIn component were incorrect (as reported by MasterCard). Adyen team asked us to send 'ContAuth' as the ShopperInteraction when using Saved Cards instead of 'Ecommerce'.

However, according to this [comment](https://github.com/Adyen/adyen-ios/issues/97#issuecomment-522889402) from a past issue, seems like we are expected to send 'Ecommerce' ShopperInteraction even when using a Saved Card from the DropIn since the user is present during the payment.

I am opening an issue here just to confirm that our current implementation is correct for sending 'Ecommerce' value for ShopperInteraction when making a payment using a Saved Card from the DropIn component.

**Comment by erenbesel** [comment]
Hey @MewanWA 
Sorry for missing this. Maybe a misunderstanding but you are correct. Payments made via our SDK dropin/components with Stored Payment methods have the shopper always present, so sending `Ecommerce` is the correct option
