### ISSUE TITLE
UIWebView reference in Adyen 2.8.x

### ISSUE THREAD

**Issue by jjoelson** [Adyen/adyen-ios#149]
Hi! We are using Adyen 2.8.4, and App Store connect shows the following warning when uploading our app:
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.

It seems the culprit is the WeChat SDK used by Adyen:
```
$ grep "UIWebView" -r .
Binary file ./AdyenWeChatPay/WeChatSDK/libWeChatSDK.a matches
```
Is there any plan to update the 2.8.x version to address this so it continues working beyond Apple's April 2020 deadline?

Thanks!

**Comment by joostvandijk** [comment]
Hi @jjoelson,

Are you using WeChat Pay in your app as a payment method? If not, you can simply leave out the `AdyenWeChatPay` module (or `WeChatPay` subspec when using CocoaPods). This should resolve the issue.

Best,

Joost

**Comment by jjoelson** [comment]
Good to know we can safely remove `AdyenWeChatPay` if we don't require WeChat Pay! Removing it fixed the deprecation warning. 👍 

Thanks for your speedy response @joostvandijk!
