### ISSUE TITLE
[BUG] Protocol requirement 'context' cannot be declared '@_spi' without a default implementation in a protocol extension

### ISSUE THREAD

**Issue by thulasiPret** [Adyen/adyen-ios#1492]
**Describe the bug**
Trying to build Adyen latest 5.4.1 but i am facing the above issue in my project. But when we install on demo without any module dependencies framework is building fine. Seems this issue is happening with modules(with linker). Earlier we were using 4.7.1, without an issue. Any help much appreciated.

My Pod file 
===========================================================================
source 'https://cdn.cocoapods.org/'

plugin "cocoapods-binary-cache"

config_cocoapods_binary_cache(
  xcframework: true,
  device_build_enabled: true,
  bitcode_enabled: true,
  cache_repo: {
    "default" => {
      "remote" => "git@github.com:pretamanger/mobile-ios-cocoapods-binary-cache.git",
      "local" => "~/.cocoapods-binary-cache/prebuilt-frameworks"
    }
  },
  prebuild_config: "Lab Debug",
   build_args: {
     :simulator => [
       "ARCHS='x86_64 arm64'",
       "BUILD_LIBRARY_FOR_DISTRIBUTION=YES"
     ]
   }
)

platform :ios, '14.0'

inhibit_all_warnings!

 project 'Pret-iOS', {
   "Debug" => :debug,
   "Lab Debug" => :debug,
   "Lab Release" => :release,
   "Local" => :debug,
   "Release" => :release  
 }

workspace 'Pret-iOS.xcworkspace'
project 'Pret-iOS.xcodeproj'
project 'Modules/PretCommon/PretCommon/PretCommon.xcodeproj'
project 'Modules/PretFeatures/PretFeatures/PretFeatures.xcodeproj'
project 'Modules/PretKitchen/Pret-Kitchen.xcodeproj'
project 'Modules/PretDesignSystem/PretDesignSystem.xcodeproj'

def common_pods

  pod 'Adjust', '4.33.4', :binary => true
  pod 'Introspect', '0.1.4', :binary => true
  pod 'KeychainAccess', '4.2.2' , :binary => true
  pod 'Kingfisher', '7.6.2', :binary => true
  pod 'Auth0', '2.3', :binary => true
  pod 'JWTDecode', '3.0', :binary => true
  pod 'LaunchDarkly', '8.0.1', :binary => true
  pod 'lottie-ios', '3.2.3', :binary => true
  pod 'SwiftUIPager', '2.3.1', :binary => true
  pod 'Adyen', :binary => true
  pod 'LifetimeTracker', '1.8.0', :binary => true
  pod 'Sentry', '8.1.0', :binary => true
  pod 'GooglePlaces', '7.4.0', :binary => true
  pod 'SimpleKeychain', '~> 1.0', :binary => true
  pod 'BrazeKit', '6.2.0', :binary => true
  pod 'BrazeUI', :binary => true
  pod 'SDWebImage', :binary => true
end

target 'Pret-iOS' do

  use_frameworks!
  project 'Pret-iOS.xcodeproj'
  common_pods
  target 'Pret-iOSTests' do
    inherit! :search_paths
  end

  target 'Pret-ContractTests' do
    inherit! :search_paths
  end
  
  target 'Pret-iOSUITests' do
    pod 'TABTestKit', '1.8.0', :binary => true
    pod 'WiremockClient', '1.4.0', :binary => true
  end
end

target 'PretDesignSystem' do
  use_frameworks!
  project 'Modules/PretDesignSystem/PretDesignSystem.xcodeproj'
  common_pods

  target 'PretDesignSystemTests' do
    inherit! :search_paths
    common_pods
  end

end

target 'PretFeatures' do
  use_frameworks!
  project 'Modules/PretFeatures/PretFeatures/PretFeatures.xcodeproj'
  common_pods

  target 'PretFeaturesTests' do
    inherit! :search_paths
    common_pods
    pod 'SnapshotTesting', '1.9.0', :binary => true
  end

end

target 'PretCommon' do
  use_frameworks!
  project 'Modules/PretCommon/PretCommon/PretCommon.xcodeproj'
  common_pods
  target 'PretCommonTests' do
    inherit! :search_paths
    common_pods
  end

end

post_install do |installer|
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
             config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
             config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
             config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
             config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
             config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
         end
     end
 end
======================================

**Screenshots**

<img width="640" alt="Screenshot 2023-12-11 at 12 52 09 PM" src="https://github.com/Adyen/adyen-ios/assets/105490711/3d330d2a-ebff-4acc-8ae9-16a7f97c5c57">

**Environment**
 - Device: iPhone15
 - iOS Version: 17.0.1
 - SDK Version: iOS17
 - Adyen API Version: 5.4.1
 - Package management system: [e.g. SPM]
 - Xcode version: 15.0.1
 - Mac OS type: M1

**Relevant source code**
Add any source code causing the problem here.

**Additional context**

**Comment by goergisn** [comment]
Hi @thulasiPret,

This is due to the 5.4.1 not supporting Library Evolution aka `BUILD_LIBRARY_FOR_DISTRIBUTION=YES`

We just released [5.5.0](https://github.com/Adyen/adyen-ios/releases/tag/5.5.0) that adds support for it.
Please let us know if this fixes your issue :)

Best,
Alex

**Comment by thulasiPret** [comment]
@goergisn Thanks for the swift response, and the issue got resolved. Cheers :) 🍻
