### ISSUE TITLE
[Feature] Autocomplete when entering credit card details

### ISSUE THREAD

**Issue by miklselsoe** [Adyen/adyen-ios#1493]
Not sure if Apple allows this, but I am missing the option to autocomplete credit card details from the iOS Keychain. Is this possible? Could you support it in the future? I am using the components solution.

**Comment by goergisn** [comment]
Hi @miklselsoe,

Unfortunately the autocomplete only works on Safari even though there is a `UITextContentType.creditCardNumber` available on UITextField.

Here a radar from 2018 https://openradar.appspot.com/40609671

Best,
Alex
