### ISSUE TITLE
[NEED ASSIST] 3DS flow implementation

### ISSUE THREAD

**Issue by Mihailo94** [Adyen/adyen-ios#1495]
**Describe the challenge**

Hi, I little bit stuck with 3DS flow implementation.

When I get response from `authorize` API call from our backend I pass action data from response to `AdyenActionComponent` as it says in [documentation](https://docs.adyen.com/online-payments/build-your-integration/additional-use-cases/advanced-flow-integration/?platform=iOS&integration=Components&version=5.3.0&tab=v66-actions_2#additional-client-app). When opened the `AdienActionComponent` shows that text message is sent to registered mobile number ending with 5329. Do you know where is that number registered?  I get in `authorize` response  the same phone number as I send but in `AdyenActionComponent` is different.

**Screenshots**
<img width="415" alt="Screenshot 2023-12-13 at 12 46 59" src="https://github.com/Adyen/adyen-ios/assets/148769359/be9b3ed7-634b-444b-b813-98099efc60ef">

**Comment by LFMAKER** [comment]
Try this:

> When prompted for 3D Secure 2 text challenges, use the following credentials to authenticate:
> 
> For native mobile integrations, use password: 1234
> For web and mobile browser integrations, use password: password

**Comment by leofolive** [comment]
@Mihailo94 Try this:

> When prompted for 3D Secure 2 text challenges, use the following credentials to authenticate:
> 
> For native mobile integrations, use password: 1234
> For web and mobile browser integrations, use password: password

https://docs.adyen.com/development-resources/testing/test-card-numbers/#test-3d-secure-2-authentication

**Comment by erenbesel** [comment]
Thanks @LFMAKER !
Yes @Mihailo94 since these are test cards, they all have the same password for 3ds flows.

**Comment by Mihailo94** [comment]
@LFMAKER @erenbesel thank you guys!
