### ISSUE TITLE
[BUG] Submit action is still disabled after CVC is filled

### ISSUE THREAD

**Issue by JoeCiou** [Adyen/adyen-ios#1498]
**Describe the bug**
When I use stored Visa card and filled 3 number for CVC, the submit action of the CVC alert will be enabled and immediately disabled, this issue only happened on iOS 17 and the device with Traditional Chiniese Caontonese keyboard.
I think `textField(_:shouldChangeCharactersIn:replacementString:)` is called twice and the second time has wrong range, please check [the issue on Apple Developer Forums](https://developer.apple.com/forums/thread/741038)

**To Reproduce**
1. Prepare a iOS 17 device and only with Traditional Chiniese Caontonese keyboard
2. Open Adyen Drop-in and select stored visa card
3. Filled 3 number for CVC
4. The submit action will be enabled and immediately disabled

**Expected behavior**
The submit action of the CVC alert will be enabled

**Screenshots**

https://github.com/Adyen/adyen-ios/assets/8978926/99cacad1-49d9-484b-933c-7c625bf5dac3

**Environment**
 - Device: any
 - iOS Version: iOS 17 and later
 - SDK Version: any
 - Adyen API Version: any
 - Package management system: 
 - Xcode version: 15
 - Mac OS type: any

**Comment by goergisn** [comment]
Hi @JoeCiou,

Thank you for reporting 🤝  
We identified a solution and created a PR for it.

Best,
Alex

**Comment by goergisn** [comment]
Reopening for confirmation after release

**Comment by JoeCiou** [comment]
@goergisn thanks for you helping, when would you release a version for this issue?

**Comment by JoeCiou** [comment]
@goergisn Hello, I see there is an update(5.6.0) including the fixing, would you also do a update for 4.x.x?

**Comment by goergisn** [comment]
Hi @JoeCiou, we're trying to keep changes to v4 to a minimum as we'd like to focus our efforts on improving the latest version. 
Is there a way for you to update to v5?

**Comment by goergisn** [comment]
Hi @JoeCiou because it was a rather quick fix we just released `4.11.2` let us know if this fixes your issue :)

**Comment by JoeCiou** [comment]
@goergisn Thanks! it's fixed on 4.11.2.
