### ISSUE TITLE
Demoserver Broken

### ISSUE THREAD

**Issue by ThinkBIG-Company** [Adyen/adyen-ios#15]
The demo server can no longer be used.
Since yesterday I get a server error 500.

The URL that was used is right below:
https://checkoutshopper-test.adyen.com/checkoutshopper/demoserver/setup

Only for the Web-SDK it works properly !

**Comment by joostvandijk** [comment]
Hi @ThinkBIG-Company,

We're currently looking into it, and we'll update you when we have resolved the issue.

Kind regards,
Joost

**Comment by joostvandijk** [comment]
Hi @ThinkBIG-Company,

The issues with the demo server has been resolved. Please let us know if you run into anything else!

Kind regards,
Joost
