### ISSUE TITLE
Apple Privacy Manifest File

### ISSUE THREAD

**Issue by mattiacantalu** [Adyen/adyen-ios#1506]
**Is your feature request related to a problem? Please describe.**
> Third-party software development kits (SDKs) can provide great functionality for apps; they can also have the potential to impact user privacy in ways that aren’t obvious to developers and users. As a reminder, when you use a third-party SDK with your app, you are responsible for all the code the SDK includes in your app, and need to be aware of its data collection and use practices [...]

> [Privacy manifest files](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests) outline the privacy practices of the third-party code in an app, in a single standard format. When you prepare to distribute your app, Xcode will combine the privacy manifests across all the third-party SDKs used by your app into a single, easy-to-use report. With one comprehensive report that summarizes all the third-party SDKs found in an app, it will be even easier for you to create more accurate Privacy Nutrition Labels.

> Starting in spring 2024, you must include the privacy manifest for any SDK listed below when you submit new apps in App Store Connect that include those SDKs, or when you submit an app update that adds one of the listed SDKs as part of the update. 

**Describe the solution you'd like**
Any update about the [privacy manifest file](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests)?

**Comment by descorp** [comment]
Thanks @mattiacantalu 

Currently we have article about [Analytics and data tracking](https://docs.adyen.com/online-payments/analytics-and-data-tracking/#data-we-are-collecting) in our official docs.

We will provide `manifest file`.

**Comment by corentios** [comment]
Following this, @descorp let us know which version will including please 🙏 

Thanks!

**Comment by BarisSenliol** [comment]
+1

**Comment by JeanAzzopardi** [comment]
Is there any news about this @descorp ?

**Comment by salvatoreboemia** [comment]
News? the deadline is 1st of May 2024

**Comment by goergisn** [comment]
Hi @salvatoreboemia & @JeanAzzopardi 

There is currently an open [PR](https://github.com/Adyen/adyen-ios/pull/1543) that will add a PrivacyInfo file.

Judging from reading this [document](https://developer.apple.com/news/?id=3d8a9yyh) the Adyen Checkout is not part of the [commonly used SDKs](https://developer.apple.com/support/third-party-SDK-requirements/) so the May 1st deadline should not apply to it.

> Starting May 1: You’ll need to include approved reasons for the listed APIs used by your app’s code to upload a new or updated app to App Store Connect. If you’re not using an API for an allowed reason, please find an alternative. And if you add a new third-party SDK that’s on the list of commonly used third-party SDKs, these API, privacy manifest, and signature requirements will apply to that SDK

However we're planning to ship a new version including the privacy manifest soon.
Sorry for any inconvenience this might have caused.

**Comment by JeanAzzopardi** [comment]
@goergisn thanks for the update - will this also be in v4?

**Comment by goergisn** [comment]
Re-opening to allow confirmation on release.

**Comment by goergisn** [comment]
@JeanAzzopardi yes we're also planning to release this fix for v4.

The release is planned before end of the month.

**Comment by goergisn** [comment]
@mattiacantalu, @JeanAzzopardi & @salvatoreboemia 

We just released [5.7.0](https://github.com/Adyen/adyen-ios/releases/tag/5.7.0) and [4.12.0](https://github.com/Adyen/adyen-ios/releases/tag/4.12.0) that include the Privacy Manifest.

I'm closing this issue for now but please let us know if this is resolving the issue and feel free to re-open or create a new issue if you run into any issues.

Best,
Alex
