### ISSUE TITLE
Apple Pay Component - Delegate Method & Close Button Issue

### ISSUE THREAD

**Issue by lpuentes19** [Adyen/adyen-ios#1528]
**Describe the bug**

I want to be able to use the `PaymentComponentDelegate` method called `didSubmit` with the Apple Pay Component. If I set the applePayComponent delegate to my `viewController` which conforms to the PayComponentDelegate, it works, but at the expense of not being able to close out the Apple Pay Component. The 'x' close button doesn't work. 

Now, if I set the applePayComponent delegate to my `session`, I can close out the Apple Pay Component just fine, but no longer get to use the `didSubmit` delegate method. I've supplied some code below. Am I doing something wrong? Or is there a bug with the close button? Any help would be appreciated.

**Code**

```
let applePayPayment = try ApplePayPayment(payment: payment, brand: companyName)
var config = ApplePayComponent.Configuration(payment: applePayPayment, merchantIdentifier: merchantId)
                        
config.allowOnboarding = true

// Create a configuration object for the Apple Pay Component
let applePayComponent = try ApplePayComponent(paymentMethod: paymentMethod, context: adyenContext, configuration: config)
presenter?.applePayComponent = applePayComponent

// Set required Apple Pay configuration parameters.
config.requiredBillingContactFields = [.postalAddress]

 // Set the session as the delegate
presenter?.applePayComponent?.delegate = session // Close button works on the Apple Pay Component

// Set myViewController as the delegate
presenter?.applePayComponent?.delegate = myViewController // `didSubmit` delegate is called, but the close button on the Apple Pay Component does not work
                        
myViewController?.present(presenter?.applePayComponent?.viewController ?? UIViewController(), animated: true, completion: nil)
```

**Environment**
 - iOS Version: iOS 16
 - SDK Version: 5.6.0
 - Package management system: SPM
 - Xcode version: 15.0
 - Mac OS type: M1

**Comment by descorp** [comment]
Hey @lpuentes19 

This seems like you are loosing reference to delegate.

1) What is `presenter` in your code snippet?
2) How do you implement `PaymentComponentDelegate.didFail` ?

**Comment by lpuentes19** [comment]
There was some confusion on my end. I was setting a breakpoint on the wrong delegate method (facepalm)... When setting the component delegate to my viewController, the `didSubmit` and `didFail` methods do get triggered. Thank you for your help!
