### ISSUE TITLE
[NEED ASSIST] Pay button action

### ISSUE THREAD

**Issue by Mihailo94** [Adyen/adyen-ios#1529]
**Describe the challenge**
Hello, I have Checkout screen where I have table view. One of the cells should be CardComponent. I have a custom button at the end of a table view and I want to do the same action when the custom button is tapped as when the Pay button is tapped (I know that the appearance and text of the Pay button can be changed, but that is not the solution for me). Is it possible to do?
Thanks in advance

**Comment by erenbesel** [comment]
Hey @Mihailo94 
Unfortunately that is not possible. You can't use a custom button or hide the button of the card component. 
We are thinking of changing this on the next major version but that is still not in the near future.
