### ISSUE TITLE
[NEED ASSIST] Prefilling card data

### ISSUE THREAD

**Issue by Mihailo94** [Adyen/adyen-ios#1530]
**Describe the challenge**
Hello, I have one case for the my app that maybe can be improved so I would ask if it is possible to do. When I open CardComponent and filled up card data, click on Pay button I dismiss CardComponent and show the error that I get from the backend. Is it possible to prefill card data when I open CardComponent again with data that I entered when I get an error?

**Comment by descorp** [comment]
Hey @Mihailo94 

You can't pre-fill the Card Component, but you can keep the component on screen and call `cardComponent.stopLoading()`, which will reactivate the UI and allow the shopper to try again.
