### ISSUE TITLE
No back button at CardComponent

### ISSUE THREAD

**Issue by brurend** [Adyen/adyen-ios#154]
When using `cardComponent.viewController.modalPresentationStyle = .fullScreen` there is no way to leave the view without registering a new card.

![IMG_0582](https://user-images.githubusercontent.com/6145411/79154047-4a6db100-7da5-11ea-99b3-a64a2e6e12e0.PNG)

**Comment by descorp** [comment]
Hi @brurend 

Thanks for reaching out!

Starting from version 3.4+, we have changed an approach to allow the presentation of basic components without constraining the view structure. 
`PresentableComponent.viewController`  is no longer wrapped into UINavigationController under the hood.

You can add a _back_ or _cancel_ button like this:

    let viewController = component.viewController
    let navigationController = UINavigationController(rootViewController: viewController)
    viewController.navigationItem.leftBarButtonItem = .init(barButtonSystemItem: .cancel,
                                                                         target: self,
                                                                         action: #selector(cancelDidPress))
    present(navigationController, animated: true) 

Full implementation on `UIHost` [could be found here](https://github.com/Adyen/adyen-ios/blob/master/AdyenUIHost/Domains/Components/ComponentsViewController.swift#L68-L77):

**Comment by brurend** [comment]
Thank you @descorp !!
