### ISSUE TITLE
[NEED ASSIST] Invalid transStatus

### ISSUE THREAD

**Issue by Mihailo94** [Adyen/adyen-ios#1545]
**Describe the challenge**
Hello, I'm trying to make payment with my VISA card and I'm getting error `Invalid transStatus`

I implemented Adyen components Advanced flow. What happens to me is when I enter card details on CardComponent and submit, delegate method occured:
`func didSubmit(_ data: Adyen.PaymentComponentData, from component: Adyen.PaymentComponent)`. I pass that data to our backend and if I get in response `action` I setup and open ActionComponent or RedirectComponent. From some reason` func didProvide(_ data: Adyen.ActionComponentData, from component: Adyen.ActionComponent)` method occurs  before I setup ActionComponent in my case and I get ThreeDS2Details which I pass to our backend for additional-detals API call which returns me Invalid transStatus error. 

When I tested with test cards on staging I didn't get this error. Any thoughts  on this?

**Comment by atmamont** [comment]
Hi @Mihailo94,

We analyzed this issue and we advice to jump on a line with our [customer support](https://www.adyen.help/hc/en-us/requests/new). We expect the behaviors to be aligned between staging and live.

**Comment by Mihailo94** [comment]
Hi @atmamont,

Thank you for response. I asked customer support and still waiting for response. In meantime I tried to setup and open ActionComponent so when I call `adyenActionComponent.handle(action)` nothing happens(spinner for loading data is shown). On staging I have the same action properties with similar values. Can you maybe help me with this or I need to ask customer support also?

**Comment by erenbesel** [comment]
Hey @Mihailo94 
Indeed that is also a technical support area. Here the aim is more towards fixing bugs, listening to feedback or recommendations from the developer community.

For integration steps, implementation details etc, technical support is the go to place 🙏
