### ISSUE TITLE
[BUG] Crash after paying by CardComponent

### ISSUE THREAD

**Issue by tanterry** [Adyen/adyen-ios#1553]
**Describe the bug**
We recently updated our code to incorporate some feature changes and migrated the `CardComponent` within our project. Subsequently, we observed an increasing number of crashes occurring in `FormViewController.didUpdatePreferredContentSize()` on our Crashlytics dashboard:
> Crashed: com.apple.main-thread
> SIGABRT ABORT 0x00000001cf193cf4
> 
> FormViewController.swift - Line 132
> FormViewController.didUpdatePreferredContentSize() + 132

There was a notable peak on March 10 with 7 crashes, which decreased after the day to an average of 1-2 crashes per day (sometimes none).

**To Reproduce**
We could not reproduce it on our side, but regarding the crash logs, we understand that the crashes happened when users tried to finalize the payment.

1. Open the card component and fulfill the card information
2. Click on pay
2.1. Close the card page and open the redirect component if it requires 3DS authentication
3. Call our service to validate the payment
4. App crashes

**Expected behavior**
The Adyen payment page should be closed and we navigate users to the confirmation page.

**Environment**
 - Device: Any devices
 - iOS Version: Can be on any versions, iOS 15, 16, 17
 - SDK Version: 4.11.2
 - Adyen API Version: 51
 - Package management system: SPM
 - Xcode version: 15.2
 - Mac OS type: M2 pro

**Relevant source code**
A simple version of our usage:
```swift
func finalizePayment(isAuthorized: Bool) {
    component.finalizeIfNeeded(with: isAuthorized) { [weak self] in
        self?.viewController.dismiss()
    }
    if isAuthorized {
        showSuccess()
    } else {
        showFailure()
    }
}
```

**Comment by erenbesel** [comment]
Hi @tanterry 

We haven't such an issue before, but looking at your finalize example, one thing that strikes me is the attempt to show success/failure while the component dismiss may also be in progress.
I would suggest putting the show success/failure block inside the completion block of the viewController dismiss.
```
component.finalizeIfNeeded(with: isAuthorized) { [weak self] in
        self?.viewController.dismiss { 
               self?.showSuccess/failure
        }
    }
```

Hope it helps!

**Comment by tanterry** [comment]
Hi @erenbesel 

Sorry for the late reply. We also found this to be suspicious but didn't fully understand why the issue suddenly happened on that day. We are planning to update it anyway since it seems that the previous implementation wasn't correct.

Thanks again for your help!
