### ISSUE TITLE
Make PreselectedPaymentMethodStyle public 

### ISSUE THREAD

**Issue by LucasAssisRo** [Adyen/adyen-ios#156]
The DropInComponent allows styling of everything but the preselected payment part of the flow. Is there any special reason for it to be internal?

**Comment by descorp** [comment]
Hi @LucasAssisRo 

That is indeed our oversight, thanks for pointing out!
We will fix it in the next release.

**Comment by mohammedDehairy** [comment]
Hi @LucasAssisRo ,

We released 3.5.0, in which you can modify the preselected payment screen through `FormComponentStyle` and `ListComponentStyle` in `DropInComponent.Style`.
