### ISSUE TITLE
Application get hang with apple pay

### ISSUE THREAD

**Issue by tejasdthanki** [Adyen/adyen-ios#157]
Application becomes hang with following step.
1.Load payment methods in drop-in
2.click on apple pay
3.close popup/sheet by clicking on cancel button
now again if you click  on apple pay button it is not woking.
please refer attached video (Adyen_apple_pay.mov.zip)

[Adyen_apple_pay.mov.zip](https://github.com/Adyen/adyen-ios/files/4474870/Adyen_apple_pay.mov.zip)

**Comment by mohammedDehairy** [comment]
Hi @tejasdthanki ,

Thanks a lot for contacting us.

 This is indeed a bug introduced since 3.4.0, we'll fix it and release as soon as possible.

Mohamed

**Comment by mohammedDehairy** [comment]
Hi @tejasdthanki,

We released 3.5.0 with a fix for the Apple Pay component, can you check if it's fixed?.

Mohamed

**Comment by tejasdthanki** [comment]
Hello @mohammedDehairy ,
Thanks. Now this issue is fix in updated version.
