### ISSUE TITLE
[BUG] Giftcard payment method not shown in dropin

### ISSUE THREAD

**Issue by MewanWA** [Adyen/adyen-ios#1584]
**Describe the bug**
We are adding giftcard support to our existing DropIn implmentation. I have implemented the GiftCard delegate and its relevant functions. The issue right now is that the giftcard payment method does not appear on the DropIn. The payment methods json we are passing is below:

```
{
  "paymentMethods": [
    {
      "name": "Credit Card",
      "brands": [
        "visa",
        "mc",
        "amex",
        "jcb"
      ],
      "type": "scheme"
    },
    {
      "name": "PayPal",
      "type": "paypal"
    },
    {
      "name": "Pay later with Klarna.",
      "type": "klarna"
    },
    {
      "name": "Apple Pay",
      "brands": [
        "amex",
        "jcb",
        "mc",
        "visa"
      ],
      "type": "applepay"
    },
    {
      "name": "Pay over time with Klarna.",
      "type": "klarna_account"
    },
    {
      "name": "Valuelink",
      "type": "giftcard"
    }
  ],
  "storedPaymentMethods": [],
  "additionalData": null
}
``` 

In Android SDK we are able to see the giftcard appearing in dropin with the same payment methods response.

**To Reproduce**
1. Make sure giftcard payment method is there in the payment methods json
2. Launch dropin
3. You will notice that Giftcard payment method is not shown

**Expected behavior**
1. Make sure giftcard payment method is there in the payment methods json
2. Launch dropin
3. You should see all payment methods in the list.

**Screenshots**

**Environment**
 - iPhone 15
 - iOS Version: iOS 17.0.1
 - SDK Version: 5.0.0 and 5.6.0 (Tested on both)
 - Adyen API Version: 69
 - Package management system: Cocoapods
 - Xcode version: 15.1
 - Mac OS type: M1

**Relevant source code**
I suspect the issue is from here, but I am unable to get breakpoints to work on the SDK code.
```swift
    internal func build(paymentMethod: GiftCardPaymentMethod) -> PaymentComponent? {
        guard let amount = context.payment?.amount, partialPaymentEnabled else { return nil }
        return GiftCardComponent(paymentMethod: paymentMethod,
                                 context: context,
                                 amount: amount,
                                 style: configuration.style.formComponent,
                                 showsSecurityCodeField: configuration.giftCard.showsSecurityCodeField)
    }
``` 

**Additional context**
From my investigation, what I noticed is that when we try to convert the JSON to PaymentMethods object type, all the other payment methods are returned in PaymentMethods except Giftcard. I am guessing there is some error when trying to decode the value. I also noticed in the GiftCardComponent builder there is a check for partialPaymentEnabled which is from the ComponentManager. Could it not be returning the method because this is false?

**Comment by erenbesel** [comment]
Hey @MewanWA 

You are on the right track! `partialPaymentEnabled` returns false if you haven't set  the `partialPaymentMethodDelegate` property of the DropInComponent.

Hope this helps!

**Comment by MewanWA** [comment]
Hey @erenbesel. Thank you for your quick response. I am setting the delegate already. 

<img width="788" alt="image" src="https://github.com/Adyen/adyen-ios/assets/134686380/d63cb928-b412-4e03-8ec9-99de082dde89">

Upon further investigation, I noticed that I am unable to decode the above json to the PaymentMethods object completely. Everything decodes as required, but the giftcard method is not present. Is there anything wrong with the giftcard payment method in the json I posted at first? Seems correct to me.

<img width="807" alt="image" src="https://github.com/Adyen/adyen-ios/assets/134686380/dd5d8ba2-a148-4c95-b2bc-d01ce14c50c9">

**Comment by MewanWA** [comment]
@erenbesel Seems like the issue was due to the json not containing the brand of the giftcard. Once its being returned, it works and shows up in the dropin as expected. I will close this ticket as it shows as required. Thank you for your help!
