### ISSUE TITLE
Remember for next time toggle does nothing

### ISSUE THREAD

**Issue by designkros** [Adyen/adyen-ios#159]
Hi,

I have implemented the Drop-In and found out that the `Remember for next time` toggle does nothing and the credit card does not get saved for next payment. Unfortunately I couldn't find any setting that could have any impact on this.

Could you please help me make this work?

Thanks.

**Comment by descorp** [comment]
Hi @designkros 

What version of SDK are you using?

**Comment by designkros** [comment]
Now I'm on 3.3.0 since it's the latest with working keyboard but it behaved the same on 3.1.4 and on 3.4.0 and 3.4.1 in Simulator (because of the keyboard I cannot get past the credit card form).

**Comment by descorp** [comment]
@designkros 
thanks for the fast response.

The SDK is propagating the toggle value to a [`PaymentComponentData.storePaymentMethod`](https://github.com/Adyen/adyen-ios/blob/master/AdyenCard/CardComponent.swift#L141-L144). You can verify that the toggle value passed to your app on [`PaymentComponentDelegate.didSubmit`](https://github.com/Adyen/adyen-ios/blob/master/AdyenUIHost/Domains/Components/ComponentsViewController.swift#L253)

Make sure that you are generating a correct `PaymentRequest` and then correctly serializing it into a JSON. [See example here](https://github.com/Adyen/adyen-ios/blob/master/AdyenUIHost/Domains/Components/ComponentsViewController.swift#L148)

Also, make sure that your backend is handling it correctly 
https://docs.adyen.com/checkout/tokenization/create-and-use-tokens#save-for-one-off

**Comment by designkros** [comment]
Thank you for your response and provided resources. Looks like we haven't been doing it right.
