### ISSUE TITLE
CheckoutViewController unresponsive after payment error

### ISSUE THREAD

**Issue by hannesjung** [Adyen/adyen-ios#16]
After there was a payment error, the user can go back to the overview of payment methods, but nothing happens when selecting an option.

![error](https://user-images.githubusercontent.com/1379354/35288097-26b48844-0064-11e8-9607-0729c0e686ea.gif)

**Comment by guillermomuntaner** [comment]
@hannesjung I'm not related to Adyen in any way, I just have implemented their SDK. Also had some similar issues, and the conclusion is that you should always dismiss the full checkout view controller after a didFinishWith callback. If its a failure, then inform the user and let them reopen it again.

**Comment by joostvandijk** [comment]
Hi @hannesjung,

Sorry for the late reply. The CheckoutViewController is not designed to handle multiple payments, so when one fails, you’re expected to dismiss it and present an error to your user. Thanks for helping @guillermomuntaner!

Kind regards,

Joost

**Comment by hannesjung** [comment]
Thanks for your replies! Implemented it this way and it's working.
