### ISSUE TITLE
Can't select payment method

### ISSUE THREAD

**Issue by PeterDolenec** [Adyen/adyen-ios#160]
Hi,
I am using the dropInComponent. After I receive payment methods from server I present the dropInComponent viewController. To here, everything works fine, but when I try to select one of the options nothing happens. I tried to debug the problem and I found out that the function "tableView didSelectRowAt indexPath" in class "ListViewController" is called and it triggers selection handler on selected component. But then in class "PaymentMethodListComponent" where selection handler should trigger delegate's function "didSelect" (in line 46), the delegate is nil, so the function is not triggered. Also the close button is not working. The problem is clearly seen in the attached gif (you can see the press event and that it doesn't open the next screen).

**Expected behavior**
It should display form for selected credit card.

**Screenshots**
![Adyen](https://user-images.githubusercontent.com/17315818/80291591-16a06d00-874f-11ea-8e9f-ede397430492.gif)

**Smartphone**
 - Device: iPhoneX
 - OS: iOS 13.4.1
 - iOS SDK Version 3.5.0
 - Xcode version 11.4

**Comment by mohammedDehairy** [comment]
Hi @PeterDolenec ,

 Thanks for reaching out.

 Are you retaining the `DropInComponent` instance strongly?, the only reason I can think of for this behavior is that the `DropInComponent` instance is not retained, so it gets deallocated, since the `DropInComponent` instance is set as the delegate for the `PaymentMethodListComponent`, and `PaymentMethodListComponent` doesn't retain it to prevent a retain cycle.

**Comment by PeterDolenec** [comment]
Hi @mohammedDehairy 

Thanks for quick reply.

You were right. Setting strong retention to `DropInComponent` solved the problem. A rookie mistake. 🤦‍♂️ 

Thanks again.

**Comment by yuchuanxing** [comment]
I'm retaining the DropInComponent instance strongly, but when I click the Payment method Icon or the area
except the UIStackView of the ListCell, it works,

**Comment by descorp** [comment]
Hey @yuchuanxing 

I am not sure that I understand your message correctly.
Could you provide more details and attach a Video / GIF ?

**Comment by alinant87** [comment]
Hi ‪+31 6 13274489‬ Dis is my Number Telegram whatapp contact me if you whant make Good money

**Comment by ronakcc** [comment]
> Hi @mohammedDehairy
> 
> Thanks for quick reply.
> 
> You were right. Setting strong retention to `DropInComponent` solved the problem. A rookie mistake. 🤦‍♂️
> 
> Thanks again.


How to set DropInComponent as strong retention?

Thanks
![S1](https://user-images.githubusercontent.com/4251737/155159945-d745e090-28f0-4bb1-9de9-50b72f01ca13.png)

**Comment by mohammedDehairy** [comment]
Hi @ronakcc ,

you need to retain the `dropInComponent` instance to a property in the same class for example, i.e `self.dropInComponent  = DropInComponent()`

Mohamed

**Comment by ronakcc** [comment]
Thanks for quick reply
