### ISSUE TITLE
[ISSUE/BUG] Redirect component not loading URL

### ISSUE THREAD

**Issue by basheer411** [Adyen/adyen-ios#161]
**Description**:  
I am trying to Implement iDeal payment in my iOS app using **Components**. 
successfully loaded a list of banks using IdealComponent. 
The ideal component delegates (`PaymentComponentDelegate`) has been called on clicking an issuer and /payments API has the `action` object and contains `"type" = "redirect"`

**Issue**: 
As per the `type` I have initiated `RedictComponent` but Couldn't able to load the URL from `action` 
_Code_
### private func presentRedirectComponent(with action: RedirectAction) {
        let component = RedirectComponent(style: redirectComponentStyle)
        component.delegate = delegate
        component.presentingViewController = presentedViewController
        redirectComponent = component
        component.handle(action)
}

### Redirect action contains : 
RedirectAction(url: https://test.adyen.com/hpp/redirectIdeal.shtml?brandCode=ideal¤cyCode=EUR&issuerId=1154&merchantAccount=JD_Netherlands&merchantIntegration.type=CHECKOUT_GENERIC&merchantIntegration.version=51&merchantReference=FF3200D7D391413D8616C247133080AE&merchantReturnData=851588015323003K&merchantSig=O9PdKwUzESfFGVbUbOccDzmfZljSOYdm3xfzXc5tXh0%3D&paymentAmount=900&resURL=https%3A%2F%2Fcheckoutshopper-test.adyen.com%2Fcheckoutshopper%2Fservices%2FPaymentIncomingRedirect%2Fv1%2FlocalPaymentMethod%3FmerchantAccount%3DJD_Netherlands%26returnURL%3Dadyencheckout%253A%252F%252Foneiota.e.jd.jdsports&sessionValidity=2020-04-27T20%3A22%3A03Z&skinCode=pub.v2.8215608476001941.fgGgndLKppaK9faX0qtzje0uaX7iIQ5Fb8YsOLIo7YA,
paymentData: "Ab02b4c0!BQABAgBbSQMh6ghWUDgycBFzR3qRK59utcWkyU6vemMSH68PqFyAoKMz+NZ0IvM0G+eE0VEZy0c8sNIhxzNmnIIASRQrFE2UD9GGMJgSxfQEMpE+ruue6D/TslHmcRyCtNSDS8N/jsdk539BBfpooNFANGjTqYPJBYPUyPmb95LmbtztSDqlcWMy01HHydr7yvrTLWxefNcCcjiN3iOpcFOs77CsW7r3ALEFS2RDU1X4feuqkPpvKG3q0+BfodxQnP15fxZsfGbwIrWZs+6gLFZoZ5c0iw10tEpJ+rCjl7RGcCxPUPZ2Tj0xdAEPSjeiyiuHXkyT0rxwFdyJ0RL2vZIzaKB9d+veMKcxtDaMa3PFIzzZeEmiZW19OpMcays++xGRlLJHUy/96r1OROEDTKVEkv1fGp4Rx6Ju1SXkqUah5XnmrJ3IQSjXRlQtmToUBBuNvo2ykVqME2qllaBJu/djIg3agRPPrne94KMawO5Fkb5S0tTLVxyc83jdmX5zR0QD+bSn7oSlbFN0jbKHuWgN1p9m0xeSSTHcGMlepdy/9HU0ZF20N64ahSCBQIsOcsfu7deFjarVPqMpgMEWaLFlTD9P31xvg04ol9xgti8jBqTgakGYjuhl818w4M0TTmZTQ7jwpBJxXLvVa3a8414pDfvFx8b7TMXhGIslQwyFp2nfRhCVIuSokr88YOohCC01RQcvAEp7ImtleSI6IkFGMEFBQTEwM0NBNTM3RUFFRDg3QzI0REQ1MzkwOUI4MEE3OEE5MjNFMzgyM0Q2OERBQ0M5NEI5RkY4MzA1REMifZokiaLRVQEo70K6qMdwU/WKlefh+fb+lDCQjQClOXWJZxq4pQ/zDjyUr8l5U9+H45i9l/sUy1b7IdEMM0W5jgo/KEjUWYW96zJ9/JzqkonhmPLeAddv3zOB4BJWPFWHN9fdicZsEJc1hmKAxfTBQ6Khd4/c3lLzC5yLtjR/2abVQXO6WgLc9SVDs8+68i4yEu+M7e3/RiWy3+msATcqa5h9cfVgDPZVskwYw3gUIXYTU8mZyyYoUcHRtsVOD9yCGsIn6k/AjWM3MbAcIZDrAOVbUrL5MyNvOkWjPrkiGZZ+aqDVLq7/gRlntTPW1rYPHceJWg5fZmcZ/SwVXCiDCo4Kdllk7rncRXZMruV4cFEU3LqqeIhF9bdZ+Jw1qJINIrd764crDD5GXl1VXNBjivm/RNEnQr7H00b998VhzXGK04JlwV6kujTWqeK+vuBidniDOaBuRoECMGcvbXqB7U25R5EwMS2y8OD5pRJe6VEbtwrYE0ERYF2nb3bc/0uD70mtCfbX8xcxjcWzlkUjWYxrktQCYKwYOgOgXB2W9Zrz118Q/URc4cRurJDeu1CZDo1tV4ygjzThIxihlARtYoGsAhkhYyN6PDBaJwsc4GrlQUgEDd7WN/uExEGxOdVokKpSLIKuCUs0eE6J4xjazHQkx0OYK5FFCGtOMGLLIoA+n+aPKun7xBFocmBruuSaifiQ3odz33RDA3/lwoN5HGSG6sUPe9wiTUJMVT81nG597YIB1EYFv35M1kL2CQSmDh9kzegIqDhBHq8CzbPlpwNVasdga7NGtAX0zjm9qve2Qxp9jl/5CdvJwYZ0lv0uVhoStzyiK0ioaPN1ssxAsV2sOxqYrAQ=")
    
**Result**: `RedictComponent` presenting but URL from action object is not loading 
**Expected result**: `RedictComponent` should present by loading URL. 

could uou please assist with expected result.

**Comment by descorp** [comment]
Hi @basheer411 

Thanks for reaching out.
Could you provide more information:
 
1) What version os SDK are you using?

2) How do you mean "not loading"?  Could you share a screenshot or a video? 
Are you able to open the same link in your browser?

3) Could you provide an `action` object you have received from a [/payments](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/payments__section_resParams) response?

From where I can see it:
Make sure that `action` object is correctly passed to the app.
There are unexpected symbols in example above.

iDEAL component documentation [link](https://docs.adyen.com/payment-methods/ideal/ios-component#make-a-payment).

**Comment by basheer411** [comment]
Hi @descorp 

1. versions 
    iOS : 11.0 later (ran in 12.2 & 13.0)
    Xcode: 11.0
    Adyen : latest (3.5.0)

2. video is here : 
    ![Ideal](https://user-images.githubusercontent.com/10904991/81102374-2da04580-8f2d-11ea-8d63-9e03b2c413ed.gif)
    Yes, I can able to open same link in browser. 

3. here is `action` object from /payments response :
    [ActionObject.docx](https://github.com/Adyen/adyen-ios/files/4583027/ActionObject.docx)
    _note : I have pasted only `action` object here, not a total /payments response_

My code after receiving a response from /payments 

<img width="701" alt="Screenshot 2020-05-06 at 12 32 05 AM" src="https://user-images.githubusercontent.com/10904991/81105154-224f1900-8f31-11ea-8f00-dd7aa684a2d9.png">


here [RedirectAction.docx](https://github.com/Adyen/adyen-ios/files/4583138/RedirectAction.docx) is passing `component.handle(action)`

**problem**: couldn't able to load the URL as shown in the gif.

**Comment by descorp** [comment]
Hi @basheer411 

The gif stops on a stage when a new view controller appears.
Does it stay like this indefinitely? (loading a link could take  up to 30 seconds)

The URL in `Action` and `RedirectAction` seems correct and indeed opens in a browser.
I can only assume that something unexpected is happening with the presented SFSafariViewController.

Could you verify with View Hierarchy Debugger that the top view controller is indeed an SFSafariViewController?
If so, could you run on a real device, connect with a Safari debugger and check if the content is loaded and if something happens in debug console?

**Comment by descorp** [comment]
@basheer411  small update.

I have noticed a behavior similar to the one on a GIF on an iPhone 8 Simulator.
Simple Simulator->Hardware->Restart fixed it.

Please let me know whether the following behavior recorded on a Simulator or a physical device?

**Comment by basheer411** [comment]
Hi @descorp 
I have tried `Simulator->Hardware->Restart` is not solved the issue. 
re Above verified View Hierarchy Debugger and the presented controller is  `SFBrowserRemoteViewController` on top of `SFSafariViewController`
<img width="1256" alt="Screenshot 2020-05-12 at 11 58 21 PM" src="https://user-images.githubusercontent.com/10904991/81731964-613f1a80-94ad-11ea-8ed7-a1f71237ca1b.png">

**Comment by descorp** [comment]
Thanks for a quick reply!

Were you able to reproduce the same behaviour on a real device?

---
From a GIF I could suggest that you are presenting `IdealComponent` as a `UIModalPresentationStyle.fullScreen` ?
There is a reported [OpenRadar bug](https://openradar.appspot.com/29108332) in `SFSafariViewController`.

However, it is from iOS 10 and I wasn't able to reproduce this bug on my side.

**Comment by basheer411** [comment]
@descorp same behavior in a real device too 

I am presenting `IdealComponent` as a Navigationcontoller and tried with/without  ``UIModalPresentationStyle.fullScreen` no change is UI behavior 

<img width="845" alt="Screenshot 2020-05-14 at 3 15 37 PM" src="https://user-images.githubusercontent.com/10904991/81920192-796e8100-95f6-11ea-8a82-9fde45f8b852.png">

**Comment by descorp** [comment]
@basheer411 

Thanks for a feedback.

According to my experiments, the reported OpenRadar bug not reproduces on iOS 13.
Plausible, multiple conditions could lead to a blank `SFSafariViewController.`

Are you presenting a `navigation` from a descendent viewController of a key window's rootViewController?
The `self,` from where the NavigationController presented, should be the same as `redirectComponent.presentingViewController.`

---

I am trying to reproduce the same behavior on our site, so we can confirm the fix when found.
To do so, I would like to understand if the issue is in SDK itself or some external factors cause it.
Could you try to simplify your solution?

E .x. instead of an `IdealComponent` present a blank view controller that pushes an SFSafariViewController with a random link? 
Does the issue remain?

**Comment by basheer411** [comment]
I will check and update

**Comment by descorp** [comment]
Hi @basheer411 

> I am presenting the Ideal component as new navigation which is not descendent navigation Controller because the Ideal component delegates are not responding if it is not a navigation VC

The `Ideal component` is a UIViewController, so it is intended to be wrapped in UINavigationController or presented in any other manner (e.x. as modal popup or embedded view controller) on implementor's side.

What do you mean by `Ideal component delegates are not responding`? 

---

`RedirectComponent` under the hood uses [similar technique](https://github.com/Adyen/adyen-ios/blob/master/Adyen/Helpers/UIViewControllerHelpers.swift#L19) to gather top viewController. You don't have to provide `topest` UINavigationController to `component.presentingViewController`; any descendent from `keyWindow` will be sufficient.

---

> facing an issue on dismissing RedirectComponent leading a blank screen.

What do you see in View Hierarchy Debugger?
Could you provide listing of `cancelDidPress` method?

Judging by a GIF, your application swapping a key window or replacing keyWindow.rootViewController when presenting iDEAL Component. 
To help with this, I would like to have better understanding of topology of your app.

---

> On the next step of success encountered an issue as "Safari can not open as the address is invalid" (pfa) - which I suspect its URI schema issue, any alternative ways other than URI Schema?

Could you open another issue for this? Would be more straightforward to communicate on two separate topics.

**Comment by basheer411** [comment]
Hi @descorp 

> What do you mean by `Ideal component delegates are not responding`?

 `Idealcomponent` delegate methods are not called if it's not wrapped in `UINavigationController/Modal popup` - no issues here

> RedirectComponent under the hood uses similar technique to gather top viewController. You don't have to provide topest UINavigationController to component.presentingViewController; any descendent from keyWindow will be sufficient.

I think the issue might be here: ` component.presentingViewController = presentedViewController 
` resulted a blank page leading to provide `topest` UINavigationController

> Could you open another issue for this? Would be more straightforward to communicate on two separate topics.

As advised, I have raised another issue for URI schema here: https://github.com/Adyen/adyen-ios/issues/167

**Comment by descorp** [comment]
Hi @basheer411 

> Idealcomponent delegate methods are not called if it's not wrapped in UINavigationController/Modal popup - no issues here

What do you mean by "delegate methods are not called"?
Which delegate? `PaymentComponentDelegate`?

If IdealComponent is persisted, IdealComponent.viewController could be pushed into existing UINavigationController the same way you present other viewControllers in your checkout.

No need to create `navigationController` and present it.

**Comment by descorp** [comment]
Hi @basheer411 

I am going to close this ticket due to a lack of activity.
If you have any questions or new details regarding this issue - please feel free to reopen or follow up..
