### ISSUE TITLE
[BUG] ThreeDS2Component action handle type

### ISSUE THREAD

**Issue by gbmiranda** [Adyen/adyen-ios#162]
Hello,

I'm trying to use the 3DS but after making the action decoder I can't move to the component's handle. I am following the documentation, is any adjustment necessary?

![WhatsApp Image 2020-05-09 at 17 20 04](https://user-images.githubusercontent.com/8632216/81568496-3e5d1b00-9374-11ea-8c07-d3359298b31d.jpeg)

**Comment by mohammedDehairy** [comment]
Hi @gbmiranda ,

 Thanks for reaching out.

 The `JSONDecoder` decodes an object of type `Action` which is an `enum`, for which each enum case holds the concrete action object as a parameter, so you will have to do a switch case statement to extract the concrete action object like follows:

```
let action = try JSONDecoder().decode(Action.self, from: actionData)
switch action {
    case let .redirect(redirectAction):
        perform(redirectAction)
    case let .threeDS2Fingerprint(fingerprintAction):
         // You have to retain the `ThreeDS2Component` instance.
        self.threeDS2Component = ThreeDS2Component()
        self.threeDS2Component.delegate = self
        self.threeDS2Component.handle(fingerprintAction)
    case let .threeDS2Challenge(challengeAction):
        // You have to retain the `ThreeDS2Component` instance.
        self.threeDS2Component = ThreeDS2Component()
        self.threeDS2Component.delegate = self
        self.threeDS2Component.handle(challengeAction)
    case let .sdk(sdkAction):
        perform(sdkAction)
}
```

and its important to note that all is handled by the `DropInComponent` out of the box -if you're using DropIn-, and also by the `DropInActionComponent`.

**Comment by gbmiranda** [comment]
thank you @mohammedDehairy

**Comment by gbmiranda** [comment]
@mohammedDehairy I'm having trouble decoding the action. Would you help me?

Error -> Unhandled Exception: type 'String' is not a subtype of type 'Map<dynamic, dynamic>' in type cast

<img width="645" alt="Captura de Tela 2020-05-11 às 15 17 57" src="https://user-images.githubusercontent.com/8632216/81596805-1339f200-939b-11ea-9830-3f94cd6aff69.png">
<img width="360" alt="Captura de Tela 2020-05-11 às 15 19 57" src="https://user-images.githubusercontent.com/8632216/81596812-159c4c00-939b-11ea-9043-595204ab3a22.png">

**Comment by mohammedDehairy** [comment]
@gbmiranda ,

I can't reproduce the error, can you give some more details? `Map<dynamic, dynamic>` doesn't match any `Swift` type that I know of.

1. Are you developing a native Swift application with Xcode?
2. Maybe send the `action` JSON.
3. Which version of the Adyen iOS SDK are you using?
