### ISSUE TITLE
[NEED ASSIST] - ApplePayComponent - support for disabling ApplePayLaterAvailability ??

### ISSUE THREAD

**Issue by axc921** [Adyen/adyen-ios#1629]
**Describe the challenge**

Does ApplePayCompoonent.Configuration support disabling **ApplePayLater** availability?

More specifically, we would like to **disable** showing the Apple Pay later **tab**.  We are using your ApplePayComponent.  See screen shot below showing the Apple Pay later tab.

PKPaymentRequest() started supporting this feature in iOS 17.

Native Swift short example:

  let paymentRequest = PKPaymentRequest()

        if #available(iOS 17.0, *) {
            paymentRequest.applePayLaterAvailability = .unavailable(.itemIneligible)
        } else {
            // Fallback on earlier versions
        }

If YES, what's the recommendation for implementation specifically for  **ApplePayComponent**?    

Thanks in advance for your support / feedback!

**Screenshots**

![image](https://github.com/Adyen/adyen-ios/assets/110916458/1afc80de-517d-402f-9352-fe4426d91f37)

**Comment by erenbesel** [comment]
Hey @axc921 

ApplePay configuration has a new [initializer](https://github.com/Adyen/adyen-ios/blob/052839c7fe088433b00fbc2ca65793029b52bb73/AdyenComponents/Apple%20Pay/ApplePayConfiguration.swift#L96) available from v5.3.0 and above that allows you to pass the PKPaymentRequest yourself, which also allows for any future additions to this object by Apple to be included.

So if you use this init and pass the request with that property set, it should work.

Let us know if it helps!

**Comment by axc921** [comment]
That's great @erenbesel!  Thanks for sharing!  We're currently at 5.2.0, and this motivates us to bump up to 5.3.0 at least.   Are there any version release notes, or history of release notes available?

**Comment by erenbesel** [comment]
Of course! 
https://github.com/Adyen/adyen-ios/releases

**Comment by axc921** [comment]
Awesome, thank you @erenbesel !

**Comment by axc921** [comment]
Awesome, thank you @erenbesel !   - I'll close this one, have a great one!
