### ISSUE TITLE
[Feature] Make the Style of preffered Credit Card Form cangeable

### ISSUE THREAD

**Issue by AMiketta** [Adyen/adyen-ios#164]
It seems that it's not possible to change the Button and the Label style of the attached view.
![Bildschirmfoto 2020-05-15 um 13 54 17](https://user-images.githubusercontent.com/15369316/82047888-e005a480-96b3-11ea-95e7-d06321efbb8a.png)

**Comment by mohammedDehairy** [comment]
Hi @AMiketta ,

 You can through the `DropInComponent.Style.formComponent.mainButton/secondaryButton` and `DropInComponent.Style.listComponent.listItem`.

**Comment by descorp** [comment]
Hi @AMiketta 

This feature is available in 3.5.0.
If you have any difficulties with customising style of PreselectedPaymentMethodComponent, please let us know.

In a meanwhile, we are planing to improve our documentation regarding styleing and customisations.

I am closing this issue for now.
