### ISSUE TITLE
[BUG] URGENT: Invalid API reason declaration in 5.7.0 blocking submissions from May 1

### ISSUE THREAD

**Issue by miklselsoe** [Adyen/adyen-ios#1650]
**Describe the bug**
When submitting builds to App Store Connect, we are starting to receive this validation error:

> ITMS-91055: Invalid API reason declaration - The PrivacyInfo.xcprivacy for the “Frameworks/Adyen3DS2.framework/Adyen3DS2” file contains “CA92.1 ” as the value for a NSPrivacyAccessedAPITypeReasons key instead of a valid reason code for using an API in the NSPrivacyAccessedAPICategoryUserDefaults category. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, values for NSPrivacyAccessedAPITypeReasons keys in your app’s privacy manifest must be valid reason codes for the corresponding API category. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

It seems like you are using an invalid combination of keys and values in your privacy manifest. 

**This is an urgent issue as it blocks os from submitting new version on our app from May 1**

Please provide an updated version of the Adyen SDK ASAP.

**Comment by nauaros** [comment]
Hi @miklselsoe!

Thanks for reporting this. We're gonna take a look at it and provide a solution to address the issue as soon as possible.

**Comment by erenbesel** [comment]
Hey @miklselsoe 

While we are working on a fix for this, can you try adding this key on your app's own privacy manifest file and see if you are still getting the same warning or not?

**Comment by miklselsoe** [comment]
We already have the NSPrivacyAccessedAPICategoryUserDefaults key in our app manifest so it seems like we can't fix it by overriding this key. It has to be fixed in the Adyen SDK, adding to the urgency of this issue.

**Comment by icecoffin** [comment]
There's a new 2.4.2 release at https://github.com/Adyen/adyen-3ds2-ios which should fix the issue, but this repository depends on version 2.4.1, so we can't update yet. Could we get a new release here?

**Comment by nauaros** [comment]
Hi @icecoffin - We're working on a new release that includes the latest version of the 3DS2 SDK. It will be available as of today.

**Comment by ionsilviumihai** [comment]
@nauaros Will version 4 receive updates as well?
Thank you!

**Comment by nauaros** [comment]
Hi there!

We released [v5.7.1](https://github.com/Adyen/adyen-ios/releases/tag/5.7.1) and [v4.12.1](https://github.com/Adyen/adyen-ios/releases/tag/4.12.1) where the 3DS2 SDK version has been updated to [v2.4.2](https://github.com/Adyen/adyen-3ds2-ios/releases/tag/2.4.2) 🚀

Thank you for the help, and sorry for the inconvenience! 💚

**Comment by miklselsoe** [comment]
Thank you for acting fast. We've updated the SDK and expect no issues on the next submission.
