### ISSUE TITLE
[Feature] Card brand name 

### ISSUE THREAD

**Issue by badredaha** [Adyen/adyen-ios#166]
I need card brand (such as : visa, mc,ect) to send to our ERP to indicate which brand the user had use to pay.

Any suggestions ?

**Comment by mohammedDehairy** [comment]
Hi @badredaha ,

 I don't think detecting the card brand with 100% accuracy is possible at the moment in the SDK, as the card brand detection in the SDK is done for pure UI reasons using regex's that is not 100% accurate, and the actual card brand is determined for sure by Adyen backend.

**Comment by badredaha** [comment]
I need card brand to send to our API for multiples reasons. Because our ERP system need to now exactly wish card brand !

And our API communicate with Adyen Backend. Is there any solution ? if not can i ask API team to get this brand from Adyen API SDK ?

Thx :)

**Comment by badredaha** [comment]
And why this feature is available in Web drop-in integration and not iOS/Android Drop-in integration ?

**Comment by mohammedDehairy** [comment]
There are endpoints in Adyen API that determines the card brand from a card number, and this one is supported by web drop-in, but not by Android and iOS until this moment.

 And don't think your backend have access to the un-encrypted card number, the iOS SDK doesn't expose the un-encrypted card number, otherwise the merchant app/backend has to comply to PCI to be able to deal with plain text card numbers.

**Comment by mohammedDehairy** [comment]
In the response of the `/payments` endpoint after the payment is authorized, the card brand is returned back to the merchant server with key `cardPaymentMethod`.

maybe this helps?

**Comment by badredaha** [comment]
@mohammedDehairy thx :)

we will check this

**Comment by descorp** [comment]
Hi @badredaha  

3.6.0 is released. You can now use `onBrand ` following this steps:

1. Provide delegate to CardComponent [like this](https://github.com/Adyen/adyen-ios/blob/master/AdyenUIHost/Domains/Components/ComponentsViewController.swift#L112)
2. Listen for events [like this](https://github.com/Adyen/adyen-ios/blob/master/AdyenUIHost/Domains/Components/ComponentsViewController.swift#L267-L275)

I am going to close this ticket for now.
Please feel free to let any comments and idea about new API, or ask if you have any questions.

**Comment by badredaha** [comment]
Yess 👯 👯 👯. Thx

**Comment by badredaha** [comment]
How i can use with DropInComponent ?

**Comment by mohammedDehairy** [comment]
Hi @badredaha ,

 You can't use it with `DropInComponent` for now, because `DropInComponent` is an umbrella for lots of payment methods like WeChat, PayPal, Apple Pay, etc, but maybe in the future we would find a generic way to provide the Card brand to the `DropInComponentDelegate`.

**Comment by badredaha** [comment]
@mohammedDehairy ,

Happy to see that version 4.0.0 is released :) big up team.

The cardType is now available? and from which object I can get it the value ?

**Comment by descorp** [comment]
Hey @badredaha 

I believe you were interested in `DropInComponent.cardComponentDelegate`, right?

**Comment by badredaha** [comment]
Hey @descorp 

Yes. I can get the cardType @mohammedDehairy had given me the answer.

**Comment by descorp** [comment]
oh, nice :)

Just to help everyone else who might following this thread:
On v4 [CardComponentDelegate](https://github.com/Adyen/adyen-ios/blob/develop/AdyenCard/Components/Card/CardComponent.swift#L12-L23) is available via [DropInComponent](https://github.com/Adyen/adyen-ios/blob/develop/AdyenDropIn/DropInComponent.swift#L73)

**Comment by badredaha** [comment]
Thank you a lot @descorp and all Adyen team.

**Comment by badredaha** [comment]
Hi Teams,

Any news for getting with easy way the card brand/type ("mc", "visa","amex",....."ideal", etc...)

**Comment by erenbesel** [comment]
Hi @badredaha,

This has been possible for some time in version 4+ of the SDK via `CardComponentDelegate`.

`func didChangeCardBrand(_ value: [CardBrand]?, component: CardComponent)` method provides the brand(s) detected for the entered number.

Is this what you are referring to?

**Comment by badredaha** [comment]
Hi @erenbesel 

Which value?  form the Array ? or from CardComponent? if so which attribute from the object?

**Comment by erenbesel** [comment]
The card may be dual-branded that's why it is an array of `CardBrand`. But you can see the type of the brand in `brand.type.rawValue`. 

I guess you were already doing this so if I misunderstood your question, please let me know.

**Comment by badredaha** [comment]
I use this:

        func didChangeCardBrand(_ value: [CardBrand]?, component: CardComponent) {
                guard let cardTypeValue = value, let ct = cardTypeValue.first?.type.rawValue else{
                    return
                }
                Logger.log("didChangeCardBrand : \(cardType)")
        } 

and to get brand from stored payment method I use this (private method):

             private func getCardTypeFromPaymentMethod(paymentMethod:PaymentMethod) -> String?{
            
            //Workaround to get cardType from Stored Card
            if let storedCardType = paymentMethod as? StoredCardPaymentMethod{
              return storedCardType.brand
            }
            
            //Workaround to get cardType from iDeal
            if let iDealIssuerCardType = paymentMethod as? IssuerListPaymentMethod{
              return iDealIssuerCardType.type
            }
            
            // /!\/!\/!\ Workaround to get cardType from ExpressPay and AliPay
            // cup -> ExpressPay
            // alipay -> AliPay
            if(paymentMethod.type == "alipay" || paymentMethod.type == "cup"){
              return paymentMethod.type
            }
            
            return nil
          }

**Comment by badredaha** [comment]
for the visa classic card test : 4111 1111 1111 1111 we get always empty value from `value: [CardBrand]` ?

**Comment by erenbesel** [comment]
In the test environment, some card numbers may not return a value. With many other test numbers you should be able to get accurate results

**Comment by descorp** [comment]
Hey @badredaha 

You can try `5454 5454 5454 5454` or `4111 0000 0000 0008`

**Comment by badredaha** [comment]
Ok and for the Prod env ? can I have your confirmation that we won't get this in Prod ?

**Comment by mohammedDehairy** [comment]
@badredaha ,

if there was an issue on bin lookup on production we would have definitely known about it by now, since bin lookup if buggy can cause serious issues and block payments, so yes I am pretty sure on production it should work fine, but of course production works with real cards not test cards :-).

**Comment by badredaha** [comment]
top!

**Comment by badredaha** [comment]
Hi Team,

@mohammedDehairy @descorp @erenbesel can you confirmed to me that our implementation is Good ?

I use this:

    func didChangeCardBrand(_ value: [CardBrand]?, component: CardComponent) {
            guard let cardTypeValue = value, let ct = cardTypeValue.first?.type.rawValue else{
                return
            }
            Logger.log("didChangeCardBrand : \(cardType)")
    } 
and to get brand from stored payment method I use this (private method):

         private func getCardTypeFromPaymentMethod(paymentMethod:PaymentMethod) -> String?{
        
        //Workaround to get cardType from Stored Card
        if let storedCardType = paymentMethod as? StoredCardPaymentMethod{
          return storedCardType.brand
        }
        
        //Workaround to get cardType from iDeal
        if let iDealIssuerCardType = paymentMethod as? IssuerListPaymentMethod{
          return iDealIssuerCardType.type
        }
        
        // /!\/!\/!\ Workaround to get cardType from ExpressPay and AliPay
        // cup -> ExpressPay
        // alipay -> AliPay
        if(paymentMethod.type == "alipay" || paymentMethod.type == "cup"){
          return paymentMethod.type
        }
        
        return nil
      }

**Comment by mohammedDehairy** [comment]
@badredaha ,

Looks good to me, which version of the SDK do you have?, the last time I checked `StoredCardPaymentMethod.brand` is not private, if its public and you can access then sure feel free to use it.

BTW in v5 the `PaymentMethod.type` is going to be a type safe enum instead of strings, so you don't have to use string comparison, so stay tuned :-D

**Comment by badredaha** [comment]
thx @mohammedDehairy 

I use v 4.2.0
