### ISSUE TITLE
[Feature] Add support for Basque (Euskera)

### ISSUE THREAD

**Issue by sebastianvarela** [Adyen/adyen-ios#1666]
**Is your feature request related to a problem? Please describe.**
We need to translate the drop-in component to Basque since new regulations have arised in
the Basque Country that enforces services and apps to be translated to both Spanish and
Basque.

**Describe the solution you'd like**
We'd like the drop-in component to support Basque

**Describe alternatives you've considered**
Add the new language to the assets

**Additional context**
We can provide the translations if you are OK with that. Thanks

Related: https://github.com/Adyen/adyen-android/issues/1622

**Comment by atmamont** [comment]
Hi @sebastianvarela 
Indeed, we do not have in-built support for Basque at the moment. However, you can always provide your own translations.
Please find steps to do so [here](https://github.com/Adyen/adyen-ios/blob/develop/Adyen.docc/Localization.md#adding-a-locale)
