### ISSUE TITLE
[NEED ASSIST] AdyenSessionDelegate not getting called while trying to implement ApplePayComponent

### ISSUE THREAD

**Issue by anaskhraza** [Adyen/adyen-ios#1669]
**Describe the challenge**
I am trying to implement apple pay component, but the AdyenSessionDelegate methods "didFail" or "didComplete" is not getting called. Following is the code that I have tried

```swift
var paymentRequest = PKPaymentRequest()
paymentRequest.merchantIdentifier = ""
paymentRequest.paymentSummaryItems = [PKPaymentSummaryItem(label: "Payment", amount: NSDecimalNumber(value: 5))]
paymentRequest.countryCode = "US"
paymentRequest.currencyCode = "USD"
let paymentNetworks = [PKPaymentNetwork.amex, .discover, .masterCard, .visa]
paymentRequest.merchantCapabilities = PKMerchantCapability(arrayLiteral: [PKMerchantCapability.capabilityCredit, PKMerchantCapability.capabilityDebit, PKMerchantCapability.capability3DS, PKMerchantCapability.capabilityEMV])
paymentRequest.supportedNetworks = paymentNetworks

var config =  try ApplePayComponent.Configuration(paymentRequest: paymentRequest)
config.shippingType = .delivery
config.requiredShippingContactFields = [.postalAddress]
config.requiredBillingContactFields = [.postalAddress]

let component = try ApplePayComponent(paymentMethod: paymentMethod,
                                      context: context,
                                      configuration: config)

component.delegate = session
```
        
But if I try the advance flow, the PaymentComponentDelegate, didSubmit and didFailed do get called over there with the context.delegate set self.
        
Is this expected the AdyenSessionDelegate will not be triggered with ApplePayComponent?

**Comment by atmamont** [comment]
Hi @anaskhraza 
From the sample it looks like you're not storing the `component` so our guess it's just being released so you never receive the delegate callback.
Let us know if this helps!

**Comment by anaskhraza** [comment]
Yes I figure that out, session was not persistent. After making it persistent, delegates started to work
