### ISSUE TITLE
[NEED ASSIST] - Edit card [Show component with pre loaded data]

### ISSUE THREAD

**Issue by abhishek-1-simform** [Adyen/adyen-ios#1672]
I want to provide a way for users to add, and edit cards in the app, and I will make payments from my server using your SDK,
for adding a card I can find the components in your SDK which provides UI and provides me the card details in encrypted form to send to my server.
However, I can not find any component that lets me edit the card. In your example also I am not able to find any feature that allows me to edit cards.
Could you please guide me if I want to show the card component with preloaded data to let users edit the card?

**Comment by goergisn** [comment]
Hi @abhishek-1-simform,

Can you explain in more detail what you mean by "editing cards"?
Is this about editing details of an already tokenized card?

Edit: I see you mention "Show component with pre-loaded data" in the title. Right now the only information you can prefill is the card holder name using the `CardInformation` inside of the `PrefilledShopperInformation` which you can set in the configuration of the `CardComponent`.

**Comment by goergisn** [comment]
Closing the ticket due to inactivity.
Feel free to re-open or create a new ticket for additional questions.
