### ISSUE TITLE
[NEED ASSIST] Card validators are not accessible anymore because of @_spi

### ISSUE THREAD

**Issue by soucolline** [Adyen/adyen-ios#1698]
Hello,

We've been using card validators on our app to validate card informations. Since version 5.8.0 or 5.9.0 they have been marked as @_spi(AdyenInternal) which block us from using them. 
Is there an existing alternative or can it be reverted to non @_spi ?

Thanks

**Comment by erenbesel** [comment]
Hey @soucolline 

The validators were not meant to be for external use as their primary usage is via the `CardComponent`. We can and do change or improve the logic in these classes so we made them spi.

I assume you are using your own UI and do the validation with these classes? In which case you can copy paste the code from them and create your own class.

**Comment by soucolline** [comment]
Hi @erenbesel,

Thanks for the answer, as you mention it's because we are using our own UI. For sure we could copy the files in the worst case scenario but it would be nice to have the updates without having to check at each release if there are any changes

Could it be possible to have an optional throwable init on the `Card` struct that would call the internal validators ? This way it would remain private for the SDK but we would still be able to know if there is an issue that we need to alert the user about

**Comment by erenbesel** [comment]
The validators were never created with external usage in mind but it's a valid point. However, since we aim to improve these areas, making them public may not be the best approach at the moment.

I didn't quite get the second part. The validators and that struct are agnostic of each other but if you could explain a bit more (with a code sample maybe) we can try to understand and help if possible.

**Comment by soucolline** [comment]
Sure, currently our use case is that users enter their card info on a screen to register it on our app. We get the values from the form, check that they are valid with the validators then create the `Card` object that we encrypt with `CardEncryptor` ( code bellow)

```
let cardValidator = CardNumberValidator(isLuhnCheckEnabled: false, isEnteredBrandSupported: true)
let expiryValidator = CardExpiryDateValidator()
let securityCodeValidator = CardSecurityCodeValidator()
                
if cardValidator.isValid(cardNumber) == false {
    throw CardEncryptor.Error.invalidBin
}

if expiryValidator.isValid(expMonth + expYear) == false {
    throw CardEncryptor.Error.invalidExpiryYear
}
                
if securityCodeValidator.isValid(cardCvv) == false {
    throw CardEncryptor.Error.invalidSecureCode
}
                
let cardObject = Card(
    number: cardNumber,
    securityCode: cardCvv,
    expiryMonth: expMonth,
    expiryYear: String(cardExpirationYear)
)

let encryptedCard = try CardEncryptor.encrypt(card: cardObject, with: publicKey)
```

I'm thinking about adding another `init` on `Card` that would use the validators to check for the card info and throw an error if there is an issue. This way the validators can be internal to the library but we would still be able to know there is an issue without having to copy-paste the code from the validators.
The only issue is that it would create a dependency to the validators

**Comment by erenbesel** [comment]
Ah I see.  Indeed, it would create a dependency.
But we may think of other ways of achieving this in the future (not as near I'm afraid). We are planning on improving the validations to be more descriptive (not just valid/invalid but with reasons) which could also include exposing a way for API-only users to get the validation result.

Hope this helps for now and thanks for letting us know!
