### ISSUE TITLE
[BUG] 3DS2 Challenge loading indefinitely

### ISSUE THREAD

**Issue by brurend** [Adyen/adyen-ios#171]
**Describe the bug**
After presenting the challenge it starts loading and it keeps going forever, also I can't dismiss the view, the button cancel doesn't work.

**Screenshots**
https://imgur.com/SoV3GSk

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 13.5
 - SDK Version 3.5.0

**Additional context**
I'm using the classic integration, not the component.

**Comment by descorp** [comment]
Hi @brurend 

What version of `adyen-3ds2-ios` are you using?

Does this behavior reproduces with all cards or something specific? you can find list of testing cards [in our documentation](https://docs.adyen.com/development-resources/test-cards/test-card-numbers?query=ios#test-3d-secure-2-authentication).

---
> I'm using the classic integration, not the component.

you mean you are not using DropInComponent?

---
> I can't dismiss the view

Is "Cancel" button clickable?
Does your `ThreeDS2Component` persisted locally and have a delegate?

Clicking "Cancel" button triggers `ActionComponentDelegate.didFail(with error: Error, from component: Adyen.ActionComponent)`. You should dismiss presented component manually.
