### ISSUE TITLE
[Feature] onBinValue

### ISSUE THREAD

**Issue by kkdayitbobson** [Adyen/adyen-ios#173]
**Is your feature request related to a problem? Please describe.**
Web contains `onBinValue`  (Provides the BIN Number of the card (up to 6 digits), called as the user types in the PAN.)

But iOS SDK can't get it

**Comment by descorp** [comment]
Hi @kkdayitbobson 

Thanks for pointing out!

We will add it to a next release scope.

**Comment by descorp** [comment]
Hi @kkdayitbobson 

3.6.0 is released. You can use `onBinValue ` following this steps:

1. Provide delegate to CardComponent [like this](https://github.com/Adyen/adyen-ios/blob/master/AdyenUIHost/Domains/Components/ComponentsViewController.swift#L112)
2. Listen for events [like this](https://github.com/Adyen/adyen-ios/blob/master/AdyenUIHost/Domains/Components/ComponentsViewController.swift#L267-L275)

I am going to close this ticket for now.
Please feel free to let any comments and idea about new API, or ask if you have any questions.
