### ISSUE TITLE
[BUG] Checkout SDK v2 takes too much time to show 3DS challenge

### ISSUE THREAD

**Issue by abdulmannanbutt** [Adyen/adyen-ios#174]
in iOS SDK, when we hit the pay button, SDK is taking so much time to show 3DS challenge. During that user can hit the *Pay* button again. Please see the videos here

https://drive.google.com/drive/folders/15J6fPsHxd6eYoqpJ63CQDthlj-9UeM2v?usp=sharing

Please help to resolve it. BTW, What is the latest version available for Checkout SDK (we are using 2.8.1)?

**Smartphone (please complete the following information):**
 - Device: iphone XR
 - iOS version: 13.4.1 ,13.5
 - SDK Version 2.8.1

**Comment by descorp** [comment]
Hi @abdulmannanbutt 

Unfortunately, latency is not something that we can control. 
You can refer to [this ticket](https://github.com/Adyen/adyen-ios/issues/172) for more details.

The current version is 3.5.0. The latest v2 version is 2.8.5.
The Pay button bug fixed on v3, so I recommend you consider an update.

I am afraid there is no easy way to work around a Pay button issue on v2: 
One possible option is recursively get topmost viewController and set `topmostViewController.view.isUserInteractionEnabled` to **false**; when ThreeDS2ChallengeAction received set it back to **true**.

**Comment by theanh90** [comment]
@descorp 
In this case, we need to disable user interaction after user first click on "Pay button".
But how can I know if user clicked on the first time?

**Comment by abdulmannanbutt** [comment]
@descorp , we can't upgrade to V3 for now as it requires lots of changes to the backend as well. We are looking to resolve it in the Checkout SDK. please see if you can help.

Regarding your solution 

_One possible option is recursively get topmost viewController and set topmostViewController.view.isUserInteractionEnabled to false; when ThreeDS2ChallengeAction received set it back to true._

It will create a problem if user clicks on Pay Button before 3DS challenge. Please see the video with SDK-2.8.5 but still has the multiple tap issue.
https://drive.google.com/file/d/1gJNR-7jVIAUXbEZZ9N5IXjpw87AWY0tm/view?usp=sharing

BTW, For 2.8.5 github releases page states that It has been resolved. Was it a different issue?
![adyen-m-tap](https://user-images.githubusercontent.com/960569/83992243-16f47080-a969-11ea-893b-e2ce649cda40.JPG)

**Comment by theanh90** [comment]
Hi @descorp 
Do we have any callback when Adyen start/progressing/end doing 3Ds?

**Comment by descorp** [comment]
Hi @theanh90 

Are you asking about v2 or v3 ?

**Comment by theanh90** [comment]
> Hi @theanh90
> 
> Are you asking about v2 or v3 ?

I'm asking about v2. 

About this suggest: "One possible option is recursively get topmost viewController and set topmostViewController.view.isUserInteractionEnabled to false; when ThreeDS2ChallengeAction received set it back to true."
I want to disable user interaction after user first click on "Pay button".
But currently I can't find any callback to know if user first click on this button.

**Comment by descorp** [comment]
Hi @theanh90 and @abdulmannanbutt 

Sorry for misinformation, unfortunately in v2 there is no callbacks that could be used for 3DS.

We've added "Pay button" issue in our backlog.

**Comment by mohammedDehairy** [comment]
Hi @theanh90 , @abdulmannanbutt ,

This problem should have been solved since `2.8.5`, the latest v2 release is `2.8.6`, `2.8.5` solves this problem by disabling clicking on the `submit` button while processing the payment.

I will close this issue and feel free to reopen it if its still a problem.

Mohamed
