### ISSUE TITLE
[NEED ASSIST] How to present Card Component as Half Sheet ?

### ISSUE THREAD

**Issue by winstoncex7** [Adyen/adyen-ios#1745]
Our UI requires the card component to be presented as half screen instead of taking over the whole screen. So is there any way to present the same ? ( as the documentation isn't updated with such requirement ).

**Comment by erenbesel** [comment]
@winstoncex7 The SDK provides the view controller of the component via `component.viewController` property. You can customize this as you would any other `UIViewController` in iOS.
(This [link](https://developer.apple.com/documentation/uikit/uiviewcontroller/3850571-sheetpresentationcontroller) from Apple could be useful for half sheet modals)
