### ISSUE TITLE
[NEED ASSIST] How can i show saved card component with prefilled card fields and empty cvv  ?

### ISSUE THREAD

**Issue by winstoncex7** [Adyen/adyen-ios#1753]
**Describe the challenge**
After following [link](https://docs.adyen.com/payment-methods/cards/ios-component/?tab=stored-4_2) was able to show below UI. How can i show a card component with prefilled data ? 

![Simulator Screenshot - iPhone 15 - 2024-07-22 at 12 08 36](https://github.com/user-attachments/assets/b6fdae2f-3ee3-4da3-afc9-f5482216625c)

**Comment by nauaros** [comment]
Hi @winstoncex7! At the moment we don't offer the option to pre-fill the card component with a tokenized card as the information you get from the payment methods response only includes the las 4 PAN digits and the expiration date. It is possible to pre-fill shopper information (e.g. shopper's name, postal code, etc.)

By the way, from the the image you sent, it looks like like you're using the `StoredPaymentMethodComponent`. For a stored card, you should be using the `CardComponent`.

Cheers,
Naufal

**Comment by winstoncex7** [comment]
Okay thanks for input. Will check this 👍

**Comment by winstoncex7** [comment]
After following your previous suggestion was able to show below UI. Now how do i customize this as half sheet card component ?

![Simulator Screenshot - iPhone 15 - 2024-07-23 at 19 32 06](https://github.com/user-attachments/assets/3141753f-4cb4-445c-9e51-e3e3d24e312e)

**Comment by nauaros** [comment]
Hi @winstoncex7! At the moment, we only offer this design as a stored card. We're considering a different design in the future where a sheet is presented, but displaying the same information we do now.

As I said earlier, the card component cannot be prefilled with PAN number, expiry date or CVV. If what you want is to present a card component prefilled, then we recommend doing your own implementation of the card component. In any case, I will share this idea with our product team.

**Comment by winstoncex7** [comment]
Okay

**Comment by winstoncex7** [comment]
Sorry to bug . But how do i extract following params - encryptedCardNumber , encryptedExpiryMonth , encryptedExpiryYear.. from **func didSubmit(_ data: Adyen.PaymentComponentData, from component: any Adyen.PaymentComponent)** ? Currently it provides only component.data

**Comment by nauaros** [comment]
Hi @winstoncex7!

Yes, it is possible. `PaymentComponentData` has a property called `paymentMethod: PaymentMethodDetails`.
Since what you expect is card details, you can cast it to `CardDetails` which also conforms to `PaymentMethodDetails`.

You can find `CardDetails` model [here](https://github.com/Adyen/adyen-ios/blob/develop/AdyenCard/Components/Card/CardDetails.swift).

```swift
    func didSubmit(_ data: Adyen.PaymentComponentData,
                   from component: any Adyen.PaymentComponent) {
        let cardDetails = data.paymentMethod as? CardDetails
        ...
        performPayment(with: data, from: component)
    }
```

**Comment by winstoncex7** [comment]
Thanks a lot 👍
