### ISSUE TITLE
[BUG] threeds2.challengeResult

### ISSUE THREAD

**Issue by badredaha** [Adyen/adyen-ios#176]
**Describe the bug**
Hi,

It is normal that some time i receive : threeds2.challengeResult rather "resultCode" ?

When i make some search, i found that "threeds2.challengeResult" is not in documentation for iOS but For Android ?

**Comment by mohammedDehairy** [comment]
Hi @badredaha ,

 Yes its normal, this key is not only for Android, its the standard key for the 3DS2 challenge result that you need to send to the `payments/details` endpoint through your server.
