### ISSUE TITLE
[NEED ASSIST] iDEAL component returns missing issuer details

### ISSUE THREAD

**Issue by winstoncex7** [Adyen/adyen-ios#1764]
**Describe the challenge**
After following [this](https://docs.adyen.com/payment-methods/ideal/ios-component/) getting missing issuer details error. How to pass issuer details to iDEAL component ?

The document is insufficient to understand this issue.

**Comment by goergisn** [comment]
Hi @winstoncex7,

Can you please answer following questions?

**Environment**
 - iOS Version: [e.g. iOS8.1]
 - SDK Version: [e.g. 3.3.0]
 - Adyen API Version: [e.g 67]

In the last SDK version the way of integrating iDEAL changed so this additional information would help.

**Comment by winstoncex7** [comment]
Hi,

Environment : Test
iOS Version: 17.4
Xcode Version : 15.3
SDK Version: 5.9.0
Adyen API Version: 71

**Comment by goergisn** [comment]
Can you confirm that you're using following way of integrating?

```
let paymentMethods = session.sessionContext.paymentMethods
// Check that the payment method is supported before showing the Component.
guard let paymentMethod = paymentMethods.paymentMethod(ofType: .ideal) else { return }
let component = InstantPaymentComponent(paymentMethod: paymentMethod,
    context: context,
    order: nil
)
self.currentComponent = component
// Set the session as the delegate.
component.delegate = session
component.initiatePayment()
```

The iDealComponent was removed in `5.9.0` because of the switch to `iDEAL 2.0` which uses a different flow.

**Comment by winstoncex7** [comment]
Yes

**Comment by winstoncex7** [comment]
Getting below data in `didSubmit(_ data: Adyen.PaymentComponentData, from component: any Adyen.PaymentComponent)`

PaymentComponentData(amount: Optional(Adyen.Amount(value: 17408, currencyCode: "EUR", localeIdentifier: nil)), paymentMethod: Adyen.InstantPaymentDetails(checkoutAttemptId: nil, type: Adyen.PaymentMethodType.ideal), storePaymentMethod: nil, order: nil, installments: nil, supportNativeRedirect: true, browserInfo: Optional(Adyen.BrowserInfo(userAgent: Optional("Mozilla/5.0 (iPhone; CPU iPhone OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"))))

**Comment by goergisn** [comment]
This might be because iDeal 2.0 is not setup on your merchant account yet.
See: https://github.com/Adyen/adyen-ios/releases/tag/5.9.0

Could you please get in touch with [Support](https://ca-test.adyen.com/ca/ca/contactUs/support.shtml?form=other) to check if it is enabled / to get it enabled?

**Comment by winstoncex7** [comment]
Thank you got it.
