### ISSUE TITLE
[NEED ASSIST] How do i create a custom view like this for saved card ?

### ISSUE THREAD

**Issue by winstoncex7** [Adyen/adyen-ios#1776]
**Describe the challenge**
Need to create a custom view as attached below for saved card component. The current code in document presents an alert controller with cvv textfield. Pls guide.

**Screenshots**
![Saved cards-Photoroom](https://github.com/user-attachments/assets/e6c4d855-63d0-46c4-9f78-5fb71356ece5)

**Comment by nauaros** [comment]
Hi @winstoncex7 

Is the screenshot correct? It looks like an Android development.

Cheers

**Comment by nauaros** [comment]
Sorry @winstoncex7, I misunderstood your question. Unfortunately, on iOS we have a different behavior and we don't support a stored card where the card component is being prefilled like on Android.

At the moment, it's not possible to pre-fill PAN number, expiry date. Only shopper information such as shopper's name, email, etc. can be pre-filled.

We will move this request to our product side in order to consider it for future developments.

**Comment by winstoncex7** [comment]
yes the screenshot is of android. Okay do we have any work around for the same in iOS ?

**Comment by nauaros** [comment]
For the time being, our recommendation to achieve a similar result to the Android version is to build your own custom component where you can display the information sent by the `/paymentMethods` response.

Within the response, you get the stored payment methods. In the case of `scheme` types you have access to the last 4 digits of the PAN number as well as the expiry date, card scheme, etc. Here is an example of such response:

```json
{
      "expiryMonth" : "03",
      "expiryYear" : "30",
      "networkTxReference" : "OXTU6HGO408080808",
      "id" : "SP58JQ8HJRWG58V5",
      "supportedShopperInteractions" : [
        "Ecommerce",
        "ContAuth"
      ],
      "lastFour" : "5454",
      "brand" : "mc",
      "supportedRecurringProcessingModels" : [
        "CardOnFile",
        "Subscription",
        "UnscheduledCardOnFile"
      ],
      "holderName" : "Checkout Shopper PlaceHolder",
      "name" : "MasterCard",
      "type" : "scheme"
    }
```

**Comment by winstoncex7** [comment]
Ok got it but how do i encrypt the cvv for the saved card ?

**Comment by nauaros** [comment]
We provide an encryption class called `CardEncryptor`. This one contains a method to encrypt the CVV:

` public static func encrypt(securityCode: String, with publicKey: String) throws -> String`

**Comment by winstoncex7** [comment]
Thanks 👍
