### ISSUE TITLE
[BUG] Setting barTintColor is not changing the cancel icon color

### ISSUE THREAD

**Issue by ahmetws** [Adyen/adyen-ios#178]
**Describe the bug**
I set the barTintColor on NavigationStyle but it didn't change the cancel icon color

**Expected behavior**
The cancel icon color should be the barTintColor

**Smartphone (please complete the following information):**
 - OS: iOS 13.5
 - SDK Version: 3.5.0

**Additional context**
I tried this code on playground but it didn't change the icon color.
`let button: UIButton = UIButton(type: UIButton.ButtonType.close)
button.tintColor = .red`

If I try this code, it updates the icon color.
`let button: UIButton = UIButton(type: UIButton.ButtonType.detailDisclosure)
button.tintColor = .red`

I think there is an issue with the button type. Is there a way to make this work?

**Comment by descorp** [comment]
Hi @ahmetws 

Thanks for the feedback!

`UIButton.ButtonType.close` suppose to be a grey circle with a cross. It does not support tinting. It is only available on iOS 13+.

<img width="409" alt="Screenshot 2020-06-16 at 11 43 02" src="https://user-images.githubusercontent.com/2648655/84760119-e1ceca80-afc7-11ea-9259-948712f008d9.png">

For iOS version prior 13 we show `UIButton(type: UIButton.ButtonType.system)` with localised 'Cancel' title. 

<img width="376" alt="Screenshot 2020-06-16 at 11 53 04" src="https://user-images.githubusercontent.com/2648655/84760220-fe6b0280-afc7-11ea-81aa-a8f62952e714.png">

What is the result you are trying to achieve?

---

Indeed, the barTint was a bit confusing. 
We changed it to `NavigationStyle.tintColor` in 3.6.0

**Comment by ahmetws** [comment]
What I need is a red cross button here? I can also set an UIImage if possible.

**Comment by descorp** [comment]
Unfortunately, UIKit hides implementation of  UIButton(type: UIButton.ButtonType.close).Even though the cross is a templatable UIImage, it is not tintable. If you know a quick way to tint it - we can still add to current release.

---

Custom image is a good idea.
We will check with our design team and will plan this for next release.

Thanks for your contribution!

**Comment by ahmetws** [comment]
Thanks, would like to have the image option. Where can I find out the release plan?

**Comment by descorp** [comment]
Unfortunately, we do not have release plans in a moment.
But that is another excellent idea. Thanks!

The good news is - from next release (3.6.0, planned this week), we are going to move all development to GitHub. You will have access to our commits, PRs, overall progress and will be able to contribute in all possible manners!

**Comment by ahmetws** [comment]
That sounds great. thanks 👍

**Comment by descorp** [comment]
Hey @ahmetws 

In [this PR](https://github.com/Adyen/adyen-ios/pull/330) we will add a custom cancel icon for DropIn.
Please, feel free to provide your feedback!

**Comment by descorp** [comment]
I am going to close this ticket for now.
Feel free to provide any feedback in this thread.
