### ISSUE TITLE
[Feature] Ability to remove rounded corners on ModalViewController

### ISSUE THREAD

**Issue by ahmetws** [Adyen/adyen-ios#179]
I want to open the drop in component without rounded corners but that's hardcoded inside the `ModalViewController`.

`    public override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        view.round(corners: [.topLeft, .topRight], radius: 10)
    }`

Is there a way to override this functionality?

**Comment by descorp** [comment]
Hi @ahmetws 

Thanks for a feedback!
Not, it is not possible in a moment. Good idea!

I'll put it in a backlog.

**Comment by descorp** [comment]
Hi @ahmetws 

3.6.0 with a fix is released. Could you verify if everything is working fine for you?

I am going to close this ticket for now.
