### ISSUE TITLE
override content string on iOS

### ISSUE THREAD

**Issue by aboyo** [Adyen/adyen-ios#1796]
Hi,

I am developing and app using flutter and the adyen flutter package, I want to change the title of the submit button. I referred to this [doc](https://github.com/Adyen/adyen-android/blob/develop/docs/UI_CUSTOMIZATION.md#overriding-string-resources) for Android. it works fine.

howaver, in the iOS, I have followed this [guide](https://docs.adyen.com/online-payments/build-your-integration/advanced-flow/?platform=iOS&integration=Components&version=5.9.0#localization), and add Localizable.string, but it is not working.

How can I do the in iOS?

**Comment by descorp** [comment]
Hey @aboyo 

You can check our [Localization](https://github.com/Adyen/adyen-ios/blob/develop/Adyen.docc/Localization.md) documentation on GitHub

---

FYI, if you believe something is missing on [Flutter SDK](https://github.com/Adyen/adyen-flutter) - better address it there.

**Comment by aboyo** [comment]
> Hey @aboyo
> 
> You can check our [Localization](https://github.com/Adyen/adyen-ios/blob/develop/Adyen.docc/Localization.md) documentation on GitHub
> 
> FYI, if you believe something is missing on [Flutter SDK](https://github.com/Adyen/adyen-flutter) - better address it there.

yes, I have tried,
I created the Localizable.strings file according the doc. Now it is located at `ios/Runner/en-US.lproj/Localizable.strings`, and I added the `"adyen.card.storeDetailsButton" = "test"`, However it doesn't work.
Is there any part that I missed~?

**Comment by descorp** [comment]
No, nothing is missing from your side.
Our Flutter SDK  using [enforced locale](https://github.com/Adyen/adyen-flutter/blob/fab3a540af43df984219561282c434be8dee7538/ios/Classes/utils/ConfigurationMapper.swift#L15) and it is only searching amongst our internal translation files.

We will add to our backlog to also attempt to search in `main` bundle.

In a meanwhile you can use [\payments](https://docs.adyen.com/api-explorer/Checkout/71/post/payments) flow (aka Advanced flow) and avoid sending `shopperLocal` to SDK.

**Comment by aboyo** [comment]
> No, nothing is missing from your side. Our Flutter SDK using [enforced locale](https://github.com/Adyen/adyen-flutter/blob/fab3a540af43df984219561282c434be8dee7538/ios/Classes/utils/ConfigurationMapper.swift#L15) and it is only searching amongst our internal translation files.
> 
> We will add to our backlog to also attempt to search in `main` bundle.
> 
> In a meanwhile you can use [\payments](https://docs.adyen.com/api-explorer/Checkout/71/post/payments) flow (aka Advanced flow) and avoid sending `shopperLocal` to SDK.

okay, it works if I do not set `shopperLocal`

**Comment by descorp** [comment]
Thanks! Closing the issue.

We will keep working on improving "enforced" locale feature
