### ISSUE TITLE
Error at the end using Quick Integration Example

### ISSUE THREAD

**Issue by razvan-iColdo** [Adyen/adyen-ios#18]
I've set the Checkout Demo Server API Key (x-demo-server-api-key) from my account in the Quick Integration Example "Configuration.swift" file, then ran the example and tried 2 different test cards: a Visa "4111 1111 1111 1111" and the Mastercard used in your GIF example "5555 4444 3333 1111" both with the expiration "08/18" and CVC "737".

In both cases, after going through the purchase flow inside the Quick Integration Example app, at the end after inputting the card details and hitting Purchase and the View Controller dismisses, it says "We were unable to process your payment" and a "Try again" button.

Is there an issue with the Demo Server?

**Comment by joostvandijk** [comment]
Hi @razvan-iColdo,

There are no known issues with the demo server. Could you take a look at the error that is returned? You can do so by setting a breakpoint in ShoppingCartViewController.swift on line 63.

Also, for the future, you can find a useful list of test data on [our website](https://docs.adyen.com/developers/test-cards/test-card-numbers). 

Kind regards,

Joost

**Comment by razvan-iColdo** [comment]
Hi @joostvandijk 

Here's what I get, I placed a breakpoint on line 72 on the `switch error` statement in ShoppingCartViewController.swift:
`(lldb) print error
(Adyen.Error) $R3 = unexpectedError`

The only thing that I did was to do a `pod install` inside the Quick Integration Example folder, then to input my Demo Server API Key in the Configuration.swift file, then just run the project and try to make a purchase using a test credit card.

**Comment by joostvandijk** [comment]
Hi @razvan-iColdo,

It appears that something in your account was accidentally misconfigured. We think we have fixed the issue. Could you try again?

Kind regards,

Joost

**Comment by razvan-iColdo** [comment]
Hi @joostvandijk 

Thank you, I've tried again (placed a breakpoint on line 63 in ShoppingCartViewController.swift) but this time instead of an error I get `payment` object but with `status = refused`. Is that the expected functionality using the Demo Server? Or is this a different issue now?

**Comment by joostvandijk** [comment]
Hi @razvan-iColdo,

This isn't expected behavior with the demoserver. After looking through your account, it appears that our risk system has been enabled, with some fairly strict settings. You can adjust these settings in the Customer Area under "RevenueProtect" -> "Risk Engine Profiles". The risk check that is denying your payment is "Shopper IP originates from high-risk country".

Kind regards,

Joost

**Comment by razvan-iColdo** [comment]
Oh alright, it seems that was it. Thank you so much for your help :)
