### ISSUE TITLE
[BUG] Setting navigation.barTitle.textAlignment doesn't change the alignment

### ISSUE THREAD

**Issue by ahmetws** [Adyen/adyen-ios#180]
When I set the textAlignment to .center it is not changing the alignment of the title.

It should be in the center of the bar.

**Smartphone:**
 - OS: 12.4
 - SDK Version 3.5.0

**Comment by descorp** [comment]
Hi @ahmetws 

This is indeed not possible in 3.5.0. The title and 'Cancel' button of DropIn's NavigationBar are in the same horizontal UIStackView. So '.center' will not be exactly the center.
This sounds like a good improvement!

We will address this idea to out product design team and if applicable - will add in future releases.

Thanks for feedback!

**Comment by descorp** [comment]
Hey @ahmetws 

In [this PR](https://github.com/Adyen/adyen-ios/pull/330) we will add ability to make centered title on DropIn.
Please, feel free to provide any additional feedback!

<img width="444" alt="Screenshot 2021-01-06 at 13 43 54" src="https://user-images.githubusercontent.com/2648655/103867389-8ed57580-50c7-11eb-9598-faa37ba3f4a4.png">

**Comment by descorp** [comment]
I am going to close this ticket for now.
Feel free to provide any additional feedback!
