### ISSUE TITLE
[BUG] Disable button selection style on list component

### ISSUE THREAD

**Issue by ahmetws** [Adyen/adyen-ios#183]
**Describe the bug**
It would be good to have an option to disable the selection style on the list component.

1. Open a Drop-in component
2. Click on any payment method
3. It has a selection style

**Smartphone**
 - OS:  iOS13.5
 - SDK Version: 3.5.0

**Screenshots**

<img width="419" alt="Screenshot 2020-06-18 at 09 34 32" src="https://user-images.githubusercontent.com/1841314/84998014-2df44900-b147-11ea-8b34-5729cb0f5bc2.png">

**Comment by descorp** [comment]
Hi @ahmetws 

this is a bug, introduced in 3.5.0
Fixed in 3.6.0

To work it around:

`dropInComponentStyle.listComponent.listItem.backgroundColor = .clear`

**Comment by ahmetws** [comment]
Thanks @descorp , it looks better now 👍

**Comment by descorp** [comment]
Hi @ahmetws 

3.6.0 with a fix is released. Could you verify if everything is working fine for you?

I am going to close this ticket for now.

**Comment by dhoskins** [comment]
All working great here in 3.6.0.
