### ISSUE TITLE
[BUG] RedirectComponent can't disable swipe to dismiss

### ISSUE THREAD

**Issue by peterwarbo** [Adyen/adyen-ios#184]
**Describe the bug**
I can disable swipe to dismiss on the viewcontroller of RedirectComponent.

**To Reproduce**
```
let vc = redirectComponent.viewController
        
        if #available(iOS 13.0, *) {
            vc.isModalInPresentation = true
        }
        
present(vc, animated: true)
```

**Expected behavior**
I shouldn't be able to swipe down to dismiss it.

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS 13.5.1
 - SDK Version 3.1.4

**Comment by mohammedDehairy** [comment]
Hi @peterwarbo ,

Thanks for reaching out.

This should be already fixed in the latest version of the SDK.

**Comment by peterwarbo** [comment]
@mohammedDehairy Oh I thought it was fixed in 3.1.4 ?

**Comment by mohammedDehairy** [comment]
@peterwarbo 

yes you're right, its should be fixed in 3.1.4, and when I checkout 3.1.4, the redirect component indeed disable interactive swipe to dismiss, so I couldn't reproduce the bug.

can you provide more details on how you use the redirect component? to be able to reproduce the issue?

**Comment by descorp** [comment]
Hi @peterwarbo 

Are you still facing this issue?

**Comment by descorp** [comment]
@peterwarbo 

I am going to close this ticket for now.
Feel free to reopen or continue discussion about related issue here.
