### ISSUE TITLE
Question about deprecated method

### ISSUE THREAD

**Issue by brurend** [Adyen/adyen-ios#185]
Could you please help me fixing the warning: 'dictionaryRepresentation' is deprecated: Use `encodable` property instead.

I tried creating an encodable class but couldn't get it to work.

**Comment by mohammedDehairy** [comment]
Hi @brurend ,

Thanks for reaching out.

`PaymentMethodDetails` used to have a `dictionaryRepresentation` property that was a hassle to encode to JSON to send to your server and then to Adyen Checkout API, so we simplified this by making a `encodable` property of  `PaymentMethodDetails` to be easily encoded into JSON, as follows:

```
try container.encode(paymentMethodDetails.encodable, forKey: .details)
```

In the example application `AdyenUIHost`, you'll find an example in  `PaymentDetailsRequest.swift` and also `PaymentsRequest.swift`.

**Comment by brurend** [comment]
I think I got it now, thank you
