### ISSUE TITLE
Debit card Option when Users doing Payment

### ISSUE THREAD

**Issue by nishanth9493** [Adyen/adyen-ios#191]
When a user is about to perform a payment the user is just shown an option of credit option.

the users are confused if debit cards are accepted.

We understand that credit card option accepts both debit and credit card but it would be better if the user is shown seperate options for credit and debit card.

**Comment by mohammedDehairy** [comment]
Hi @nishanth9493 ,

Thanks for the suggestion.

On Adyen Checkout API v53, you can already send an extra parameter in the `/paymentMethods` request to do exactly that `splitCardFundingSources`, if this parameter is `true` then there would be a separate options for credit and debit card.

we'll update the docs soon to reflect this new option, but you can already use this on iOS SDK.

**Comment by mohammedDehairy** [comment]
Hi @nishanth9493 ,

 The docs are updated [Here](https://docs.adyen.com/payment-methods/cards/ios-drop-in#show-debit-credit-separately).

gonna close the issue, you can reopen it if you're still having problems.

Mohamed
