### ISSUE TITLE
[Feature] Incorporate the "DropInComponent" and/or "CardComponent" for a SwiftUI project

### ISSUE THREAD

**Issue by jzeisweiss** [Adyen/adyen-ios#192]
**Describe the challenge**
My project uses SwiftUI and not UIKit. How can I incorporate the "DropInComponent" and/or "CardComponent" for a SwiftUI project?

Here is the code I am trying to use but when I click the pay button nothing happens:
```
struct PayViewController: UIViewControllerRepresentable {
    @ObservedObject var networkingObservable: NetworkingObervable

    func makeCoordinator() -> Coordinator {
        Coordinator(self)
    }
    
    func makeUIViewController(context: Context) -> UIViewController {
        guard let cardPaymentMethod: CardPaymentMethod = networkingObservable.adyenConfiguration.paymentMethod?.regular[0] as? CardPaymentMethod else {
            return UIViewController()
        }
        
        let cardComponent = CardComponent(paymentMethod: cardPaymentMethod,
                                          publicKey: networkingObservable.adyenConfiguration.publicKey!)
        cardComponent.environment = .test
        // When you're ready to go live, change this to .live
        cardComponent.payment = Payment(amount: Payment.Amount(value: 1000,
                                                                 currencyCode: "US"))
        cardComponent.delegate = context.coordinator
        return cardComponent.viewController
    }
    
    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {
        
    }
    
    class Coordinator: NSObject, PaymentComponentDelegate, UINavigationControllerDelegate {
        func didSubmit(_ data: PaymentComponentData, from component: PaymentComponent) {
            print("didSubmit")
        }
        
        func didFail(with error: Error, from component: PaymentComponent) {
            print("didFail")
        }
                
        var parent: PayViewController
        
        init(_ imagePickerController: PayViewController) {
            self.parent = imagePickerController
        }
    }
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/4261258/85926539-2aab3c80-b86e-11ea-8e98-97e2993e7fba.png)

**Comment by mohammedDehairy** [comment]
Hi @jzeisweiss ,

Thanks for reaching out.

Unfortunately the DropIn/Components SDK wasn't designed with SWiftUI in mind, so using them in a SwiftUI application is really uncharted territory for us as well, we need to investigate this, and maybe make it much easier to be integrated with SwiftUI apps.

**Comment by kesavaj** [comment]
Hi, Any luck with this one yet?. Will be really helpful if this can be pursued.

**Comment by descorp** [comment]
Hi @kesavaj 

Sorry, no updates so far.

BTW, judging by the code snippet from @jzeisweiss it should work. 
The only missing part is the instance of `CardComponent` should be persisted in Coordinator.

**Comment by MattCheetham** [comment]
We've hit this one as well. Expected to be able to just throw up the view and it would behave but no such luck. Presenting it as `.sheet` in SwiftUI results in it not responding to taps on a payment option "Credit Card" for example. Presenting it from a NavigationLink yields better results but the view sizing goes wrong and means you cannot complete a payment.

I've been trying to find a workaround but so far have had no luck. I'll write back if I figure anything out but at the minute we're in a bit of a pickle as it's preventing us from shipping!

**Comment by mohammedDehairy** [comment]
Hi @MattCheetham , @jzeisweiss , @kesavaj 

 Good news!, with the next release we'll be adding a nice helper `View` extension to present any `UIViewController`, that you can use to present any `Component.viewController`.

 You can have a look already at [this closed pull request](https://github.com/Adyen/adyen-ios/pull/231), and maybe try it and provide some feedback before the actual release.

Also in the same PR we added an example SwiftUI application to demonstrate integrating with SwiftUI.

Looking forward to your feedback.

Mohamed

**Comment by descorp** [comment]
3.8.0 is released!

Looking forward for a feedback!

**Comment by descorp** [comment]
Thanks everyone for feedback and support!

I am going to close it for now.
Feel free to provide any additional feedback in this thread or create a new one is necessary.
