### ISSUE TITLE
[NEED ASSIST] how to mask CVV / CVC in card component ?

### ISSUE THREAD

**Issue by winstoncex7** [Adyen/adyen-ios#1929]
**Describe the challenge**
How to mask CVV / CVC in card component. ?

**Comment by nauaros** [comment]
Hi @winstoncex7 - Unfortunately we do not offer this functionality in the card component. The only way to achieve it right now is implementing your own card component. We will take this into consideration for the future.

**Comment by winstoncex7** [comment]
Thanks for the clarification.
