### ISSUE TITLE
[Feature]  Limit input CVC not more than 3 characters

### ISSUE THREAD

**Issue by laohanme** [Adyen/adyen-ios#193]
**Is your feature request related to a problem? Please describe.**
Latest version when in the payment process CVC alert field can input more than 3 characters
![image](https://user-images.githubusercontent.com/18119268/85965915-e09e9400-b9f0-11ea-9450-cdd2dec6b5d1.png)

**Describe the solution you'd like**
Limit to only can input 3 characters

**Comment by mohammedDehairy** [comment]
Hi @laohanme ,

Thanks for reaching out.

 The CVC alert accepts max 4-digits because some cards can accept 4 digits and some accept 3 digits, so limiting the input field to 3 digits would make it impossible to pay with cards who's CVC is 4 digits, and until the latest version of the SDK (3.6.0) its impossible for the SDK (on the client) to recognize how many CVC digits for a specific BIN.

**Comment by laohanme** [comment]
Thanks for your reply @mohammedDehairy 

I understand to the reply and thanks for correct me.
is it possible in the future SDK update can let developer limit the digit in alert field

**Comment by mohammedDehairy** [comment]
Hi @laohanme ,

 Can't think of a use case where this would be useful, can you explain your use case for limiting the digits?.

 Because we try not to accidentally block payments that are otherwise valid, and limiting the CVC digits would block 4 digits Cards.

**Comment by laohanme** [comment]
Thank you @mohammedDehairy 

I also think to that, btw of some special user there are always mistaken to input their digit length this cause if the input wrong digit length submit to server will return the error (CVC is not the right length), then from our system mark the payment as failed, from client site the user still stay in the payment process UI. Therefore we tried to find the way to improve this issue from my client site and we also reference to the android SDK, there have a validation during click pay when user input more than 3 digit.
![image](https://user-images.githubusercontent.com/18119268/86313474-c3b7ca00-bc57-11ea-9142-74084bdd004b.jpeg)

**Comment by mohammedDehairy** [comment]
Hi @laohanme ,

 For the `CardComponent` -Not the stored card component-, we already validate the CVC length before submitting the payment.

 But you're right, we can do the same for stored card alert.

**Comment by descorp** [comment]
Done in [this PR](https://github.com/Adyen/adyen-ios/pull/364)
