### ISSUE TITLE
CardComponent button background color is not changeable.

### ISSUE THREAD

**Issue by armintelker** [Adyen/adyen-ios#195]
Hello :) 
When I try to style the Button from the CardComponent it is not possible for me to change the backgroundColor.

```swift
var style = FormComponentStyle()
style.secondaryButtonItem.backgroundColor = .red
style.secondaryButtonItem.button.backgroundColor = .red

style.mainButtonItem.backgroundColor = .red
style.mainButtonItem.button.backgroundColor = .red

let cardComponent = CardComponent(paymentMethod: cardPaymentMethod, publicKey: "key", style: style)
```

I also tried to use the FormComponentStyle constructor initialization but this is also now working. 

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-08 at 17 27 46](https://user-images.githubusercontent.com/1172261/86938133-5b2d8900-c140-11ea-8111-ac0679fdd350.png)

**Comment by descorp** [comment]
Hi @armintelker 

To change style of Button on CardComponent use `footer` property

```swift
        var style = FormComponentStyle()
        style.footer.backgroundColor = .red
        style.footer.button.backgroundColor = .red
```

Sorry, the API is a bit confusing because of backwards compatibility.
We are planing to mark `footer` property as deprecated and incorporate control of main button style via `mainButtonItem `.

Thank for valuable feedback!

**Comment by armintelker** [comment]
thanks.

**Comment by descorp** [comment]
3.8.0 is released!
FooterStyle was deprecated. 

I am going to close this ticket for now.
Feel free to respond in this thread or provide any additional feedback!
