### ISSUE TITLE
[NEED ASSIST]  Drop-in - Navigation is not working on tapping the payment method

### ISSUE THREAD

**Issue by Karthikeyan-Thiru** [Adyen/adyen-ios#197]
**Drop-in - Navigation is not working on tapping the payment method**
No action is happened on tapping any payment methods (e.g. SEPA Direct or Card). 
Cancel button action also not working. 

**To Reproduce**
1. Present the dropInComponent.viewController
2. Click on 'any Payment methods'

**Expected behavior**
Expected to Navigate to its detail page where the user can give the payment details to proceed further. 
DropInComponentDelegate - didFail(with error: Error, from component: DropInComponent) is not triggered.

**Screenshots**
<img width="784" alt="Screenshot 2020-07-13 at 21 42 09" src="https://user-images.githubusercontent.com/24916825/87328787-a89c6280-c553-11ea-83dd-7838ccfffcdb.png">
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-13 at 21 56 47](https://user-images.githubusercontent.com/24916825/87328865-c7025e00-c553-11ea-8f98-313aa1e6057f.png)

**Smartphone (please complete the following information):**
iPhone and iPad

**Additional context**
Checked in the 3.6.0

**Comment by mohammedDehairy** [comment]
Hi @Karthikeyan-Thiru ,

 Thanks for reaching out.

 From the code snippet that you shared, I can see that the `dropInComponent` instance is not retained, so once the `invokeAdyenPayment` function returns the `dropInComponent` instance is deallocated.

 The dropInComponent should be retained as a `var` or `let` by the caller object/viewController.

**Comment by Karthikeyan-Thiru** [comment]
Thanks, @mohammedDehairy. Working good.

**Comment by 154010** [comment]
You Mean We Have To Decalre DropInComponent Variable as Global in that view Controller Right??

**Comment by mohammedDehairy** [comment]
yes, it should be retained somewhere, otherwise it will get deallocated once the `invokeAdyenPayment(sender:)` returns.

**Comment by 154010** [comment]
Thanks a lot @mohammedDehairy its worked.

**Comment by 154010** [comment]
how to send data.paymentMethods in make payment api
My Response
![Screenshot 2020-07-21 at 2 59 09 PM](https://user-images.githubusercontent.com/36889954/88039311-0557d880-cb65-11ea-867e-5691c6c3a02e.png)

https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/payments

**Comment by mohammedDehairy** [comment]
Hi @154010 ,

 I assume you mean encoding the `CardDetails` object, correct me if I am wrong.

 Any `PaymentMethodDetails` including `CardDetails` has a `.encodable` property, that you can use to encode the object with key `paymentMethod`, in the body of the `/payments` "POST" request.

like this:

```
try container.encode(data.paymentMethod.encodable, forKey: .paymentMethod)
```

you'll find an example in the `PaymentsRequest.swift` file in the `AdyenUIHost` example application.
