### ISSUE TITLE
[NEED ASSIST] Cannot open register card view

### ISSUE THREAD

**Issue by Ganyev** [Adyen/adyen-ios#198]
Hello guys,
I'm integrating Adyen SDK, 
decoded the paymentMethods response with the PaymentMethods structure.
everything is fine and I get this screen:

![Simulator Screen Shot - iPhone 8 - 2020-07-22 at 10 23 37](https://user-images.githubusercontent.com/41617899/88134045-7058ec00-cc05-11ea-84af-57d30396bbc4.png)

But I want to register my card and open this screen with "Register card" button (found in another issue on Github)

![photo_2020-07-22_10-24-43](https://user-images.githubusercontent.com/41617899/88134100-954d5f00-cc05-11ea-9aec-e92af4228f51.jpg)

Also I noticed, that on my screen there is no _Cardholder name_ field

My code looks like:

```
let paymentMethods = try JSONDecoder().decode(PaymentMethods.self, from: jsonData)
guard let cardPaymentMethod = paymentMethods.regular[0] as? CardPaymentMethod else { return}
let cardComponent = CardComponent(paymentMethod: cardPaymentMethod, publicKey: Const.ServiceKey.Adyen)
cardComponent.delegate = self
cardComponent.environment = .test
present(self.cardComponent!.viewController, animated: true)
```

In this [doc](https://docs.adyen.com/checkout/ios/components) didn't find any steps with registering card.
Help me, please

**Comment by mohammedDehairy** [comment]
Hi @Ganyev ,

 Thanks for reaching out.

 For the card holder name, `CardComponent` has a property `showsHolderNameField`, you can set it to `true` before showing the component.

 For registering a card, you send a `payments` request with zero amount, and with the `storePaymentMethod` set to `true`, and also you need to provide `shopperReference` as a unique identifier for the shopper whose card you're registering, and also you might want to set `CardComponent.showsSecurityCodeField` to false, and the `CardComponent.payment` should be `nil`.

https://docs.adyen.com/checkout/tokenization/create-and-use-tokens#create-a-token

**Comment by Ganyev** [comment]
@mohammedDehairy thanks for the answer,

Ok, all this steps we will send from our backend to your server.

I'm implementing UI now, and as I understand, 
Firstly, I should show the view where "Register card" button is shown, user fills all info, then after tapping "Register card" request above will send.

But how to show user the view where "Register card" button is shown? not "Pay" button.

Maybe we don't follow correctly the steps of registering card...

**Comment by mohammedDehairy** [comment]
Hi @Ganyev ,

  The same `CardComponent` can be used to either pay with card or register a card.

  To override the `Pay` string, you can add a custom `Localizable.strings` in your project and override the `adyen.submitButton` localization key, you don't need to override all keys, the SDK falls back to the SDK's internal `Localizable.strings` file in case a key is not found in the host application bundle.

 I know this part is a little awkward, we can maybe make this use case easier in the future, because to be honest the `CardComponent` is not really optimized for registering a card use case, but you can still do it.

**Comment by Ganyev** [comment]
@mohammedDehairy 
Thank you!! You really helped me.
