### ISSUE TITLE
Integrate with Obj-C project

### ISSUE THREAD

**Issue by bmzxd** [Adyen/adyen-ios#2]
I tried to integrate Adyen into an obj-c project with no success. What would you recommend to do besides moving this project to Swift? Your inputs are much appreciated.

**Comment by diegomarcon** [comment]
Hi @bmzxd,

We are adding a Objective-C example on next release. I'll ping you again when it's available.

**Comment by Golotus** [comment]
I also tried to integrate Adyen into an obj-c project, The "Payment Methods" page has been displayed，but none of them clicked， Please give me some recommend or give a obj-c example, thanks a lot

**Comment by Golotus** [comment]
Hi @diegomarcon,
When will you release Objective-C's example? I need it in my project, I need help.

**Comment by diegomarcon** [comment]
Hi @Golotus, @bmzxd 

Objective-C example was added on release 1.5

It's available on the [Examples](https://github.com/Adyen/adyen-ios/tree/master/Examples/)  folder.
