### ISSUE TITLE
[Handle] handle state of Redirection Screen (cancel, add animation to screen)

### ISSUE THREAD

**Issue by badredaha** [Adyen/adyen-ios#203]
Hi,

Can we handle Cancel of redirection Screen? Also, can i have a different state of Redirection Screen (to add animation) ?

Regards,

**Comment by mohammedDehairy** [comment]
Hi @badredaha ,

 Thanks for reaching out.

If you mean the Safari Screen that handles redirect action, yes you can handle cancelation, when user clicks the cancel button of the Safari screen, the `ActionComponentDelegate.didFail(with:,from:)` is called with `ComponentError.cancel` error type.

if you implement the `ActionComponentDelegate` and check the error passed, you can detect when user clicks the cancel button.

but not for the `DropInComponent`, the `DropInComponent` cancel silently when user clicks the cancel button without delegating this event to `DropInComponentDelegate`, this maybe not optimal, but you if you have a good use case for it, we can change this behavior.

About your second question, the redirect component uses `SFSafariViewController`, and it is supposed to be presented modally, not sure if you can use custom animations to present it.

Mohamed

**Comment by mohammedDehairy** [comment]
@badredaha ,

 Its very easy to send the `DropInComponentDelegate.didFail(with:,from:)` with `ComponentError.cancel` for this case, it will be in the next release(s).

 otherwise, if you're in a hurry, the repo is open source :-) , and PR's are encouraged .

**Comment by mohammedDehairy** [comment]
its important to mention that when the `DropInComponent` is dismissed by the user by clicking on the `X` button, the `DropInComponentDelegate.didFail(with:,from:)` is called with `ComponentError.cancel`, maybe this solves your problem?.

**Comment by badredaha** [comment]
i use DropInComponentDelegate.didFail(with:,from:) for the others uses : creditCard but its not work with redirect when its present challenge !

**Comment by badredaha** [comment]
@mohammedDehairy  any news, please ?

**Comment by mohammedDehairy** [comment]
Hi @badredaha ,

We are planning to release soon, on the 1st of October the latest.

**Comment by badredaha** [comment]
👯 thx

**Comment by mohammedDehairy** [comment]
Hi @badredaha ,

You might want to have a look at this [PR](https://github.com/Adyen/adyen-ios/pull/216), to confirm that it solve your problem.

Mohamed

**Comment by badredaha** [comment]
Yes for me as long as the will be in the same level of : didSubmit, didProvide, didFail from **DropInComponentDelegate**

**Comment by badredaha** [comment]
Hi @mohammedDehairy,

i saw that you released the version with the cancel action , the version is 2.8.6 instead 3.6.0 ?

**Comment by mohammedDehairy** [comment]
Hi @badredaha ,

`2.8.6` is something different, it was a bug fix for the old checkout (v2), `3.7.0` will be released today with cancel delegate function.

Mohamed

**Comment by badredaha** [comment]
Hi @mohammedDehairy,

thx 👍

**Comment by mohammedDehairy** [comment]
actually, we might not be able to release today, will release ASAP.

**Comment by mohammedDehairy** [comment]
Hi @badredaha ,

 `3.7.0` is released with the `didCancel` call back in `DropInComponentdDelegate`.

Mohamed

**Comment by badredaha** [comment]
Hi @mohammedDehairy,

works like a charm 👍  🥇 

Thx,
