### ISSUE TITLE
[BUG] Drop-in + Apple Pay in simulator: empty token

### ISSUE THREAD

**Issue by xzoky** [Adyen/adyen-ios#204]
**Describe the bug**
When attempting an Apple Pay payment in the simulator, `PaymentComponentData.paymentMethod.token` is empty. This then results in a "Missing payment method details" error.

**To Reproduce**
1. Use the simulator
2. In the Drop In, select Apple Pay
3. Click "Pay with Passcode"

**Expected behavior**
The token should be set.

**Screenshots**
<img width="454" alt="Screen Shot 2020-08-11 at 6 21 16 PM" src="https://user-images.githubusercontent.com/339784/89954712-99b2d980-dbff-11ea-9c5b-0460d2402e3a.png">
<img width="704" alt="Screen Shot 2020-08-11 at 6 06 07 PM" src="https://user-images.githubusercontent.com/339784/89953996-396f6800-dbfe-11ea-8541-e34f8e8d6796.png">

**Smartphone (please complete the following information):**
 - Device: Simulator
 - OS: iOS 13.6
 - SDK Version: 3.6.0

**Additional context**
I'm using the simulator because I do not have access to a test device.
When running on my personal device, the token is adequately set. However the transaction subsequently fails because "This is not a testCard". Allowing production cards to be used for testing would be an acceptable workaround in my situation.

**Comment by mohammedDehairy** [comment]
Hi @xzoky ,

Thanks for reaching out.

 [unfortunately you can't test full Apple Pay transaction on simulator](https://developer.apple.com/forums/thread/44972), its better to use a real device.

 And for testing on real device with a Test card, [here is how to test Apple Pay as described by apple](https://developer.apple.com/apple-pay/sandbox-testing/).

**Comment by xzoky** [comment]
Thanks @mohammedDehairy! This is unfortunate, but it makes sense 🙂

**Comment by descorp** [comment]
HI @xzoky 

I am going to close this ticket for now.
Feel free to continue discussion here or reopen if necessary.
