### ISSUE TITLE
Preferred payment method on Quick Integration flow

### ISSUE THREAD

**Issue by ochococo** [Adyen/adyen-ios#21]
- Server can send payment setup with only one available payment method, this way we can save the user one useless tap
- Use case: preferred payment method is preselected before Adyen payment was initiated but we want to use Quick Integration
- We can accept only one payment type ex. Apple Pay

**Comment by joostvandijk** [comment]
This has been fixed in 2.4.0.

**Comment by ochococo** [comment]
Thanks @joostvandijk :)
