### ISSUE TITLE
[NEED ASSIST] iOS Drop-In shows payment methods, after that does not respond to input

### ISSUE THREAD

**Issue by hrietman** [Adyen/adyen-ios#219]
After we noticed that we could not use the Web Drop-in with Capacitor on iPhone (due to alllowed-origin, which is capacitor://localhost and not support by Adyen) We created a capacitor plugin that calls the iOS Drop-in variant (pod Adyen version 3.6.0) 

It does show; it shows all payment methods but after that there is no response of the UI when selecting one of the payment methods. 

Payment Method response: 
`
{"paymentMethods":[{"brands":["mc","visa","amex"],"details":[{"key":"encryptedCardNumber","type":"cardToken"},{"key":"encryptedSecurityCode","type":"cardToken"},{"key":"encryptedExpiryMonth","type":"cardToken"},{"key":"encryptedExpiryYear","type":"cardToken"},{"key":"holderName","optional":true,"type":"text"}],"name":"Credit Card","type":"scheme"}],"groups":[{"name":"Credit Card","types":["mc","visa","amex"]}]}
`

Expected result; after selecting "Credit card" the form to enter credit card details should show with a pay button. 

Code (simplified)
`
import Foundation
import Adyen

@objc(CAPAdyenDropInPlugin)
public class CAPAdyenDropInPlugin : CAPPlugin, DropInComponentDelegate {
    
	public func didSubmit(_ data: PaymentComponentData, from component: DropInComponent) {
	    
	}

	public func didProvide(_ data: ActionComponentData, from component: DropInComponent) {
	    
	}

	public func didFail(with error: Error, from component: DropInComponent) {
	    
	}

	var paymentMethods: PaymentMethods?

  @objc public func log(_ call: CAPPluginCall) {

  	// for simplicity provide a simple paymentMethods Response 
    let paymentMethodsResponse = """
      {"paymentMethods":[{"brands":["mc","visa","amex"],"details":[{"key":"encryptedCardNumber","type":"cardToken"},{"key":"encryptedSecurityCode","type":"cardToken"},{"key":"encryptedExpiryMonth","type":"cardToken"},{"key":"encryptedExpiryYear","type":"cardToken"},{"key":"holderName","optional":true,"type":"text"}],"name":"Credit Card","type":"scheme"}],"groups":[{"name":"Credit Card","types":["mc","visa","amex"]}]}
    """.data(using: .utf8)!
    
    do {
        paymentMethods = try JSONDecoder().decode(PaymentMethods.self, from: paymentMethodsResponse)
    } catch {
        CAPLog.print("error decoding")
    }

    let configuration = DropInComponent.PaymentMethodsConfiguration()
    configuration.card.publicKey = "<REMOVED>"
    
    let dropInComponent = DropInComponent(paymentMethods: paymentMethods!,
    paymentMethodsConfiguration: configuration)
   
    dropInComponent.environment = .test
    // When you're ready to go live, change this to .live
    // or to other environment values described in https://adyen.github.io/adyen-ios/Docs/Structs/Environment.html
    dropInComponent.payment = Payment(amount: Payment.Amount(value: 1000,
                                                             currencyCode: "EUR"))
    // Optional. In this example, the Pay button will display 10 EUR.

    dropInComponent.delegate = self
    DispatchQueue.main.async {
        self.bridge.viewController.present(dropInComponent.viewController, animated: true, completion: {
            call.success()
          })
    }
  }
}`

**Comment by mohammedDehairy** [comment]
Hi @hrietman ,

 Thanks for reaching out.

 This issue is duplicated I believe of [this issue](https://github.com/Adyen/adyen-ios/issues/160).

You need to retain the `dropInComponent` instance strongly somewhere, it seems the `dropInComponent` instance is created locally in a function, and when the function returns, the `dropInComponent` is deallocated.

Can you please confirm if this is the problem?.

Mohamed

**Comment by hrietman** [comment]
Hi @mohammedDehairy , that was indeed the issue; it is now displaying correctly. However, still an issue to close it; do we need to handle this our self? Some examples/documentation would be of great help.

BR
Harald

**Comment by mohammedDehairy** [comment]
After the payment is concluded, whether with success of failure, only the client code knows, because the client code is the one that makes the `payments` or the `payments/details` calls, so yes, the client code should dismiss the dropIn when the payment is concluded.

**Comment by hrietman** [comment]
Thanks for the quick response again; yes you are right. If i can just ask you one question; the documentation mentions that for amount is zero; it is a pre-authorization request. In the web component it does change the text on the button to pre-authorization, on the ios-drop-in it still says "Pay 0.00".

**Comment by mohammedDehairy** [comment]
yeah, in iOS SDK, this scenario unfortunately is not straightforward to do, we have been asked this question a lot, and we should make it easier in future releases.

for now, you can include in your `Localizable.strings` file `"adyen.submitButton" = "{Your_custom_string}";`, and pass a `nil` `Payment` instance to the card component or the `dropInComponent`

**Comment by hrietman** [comment]
Thanks, works now; appreciated the help.
