### ISSUE TITLE
Demo server responds with 500

### ISSUE THREAD

**Issue by TimurKhay** [Adyen/adyen-ios#23]
Using Quick Integration Example,
demo server responds with 500 and json:

```
{
	"status": 500,
	"errorCode": "701",
	"message": "Internal Error: initiate 8515235507403867",
	"errorType": "internal"
}
```

**Comment by kornerr** [comment]
Which is obviously wrong. Can you, Adyen guys, fix the error?

**Comment by olutsenko** [comment]
Hi @TimurKhay,

Thanks for reporting this. Turned out to be a configuration issue on your account, which is resolved by now. Can you try again?

Cheers,
Oleg

**Comment by TimurKhay** [comment]
Hi, @olutsenko . Thank you, it works now.
Could you tell what was wrong, so we can avoid it in future during prod integrations?

**Comment by olutsenko** [comment]
Hi @TimurKhay,

There was one step in the configuration that didn't happen our side. We already made changes to prevent this in the future.

Regards,
Oleg
