### ISSUE TITLE
[BUG] Ayen 3.7.0 Client key

### ISSUE THREAD

**Issue by arnauddorgans** [Adyen/adyen-ios#243]
**Describe the bug**
The `clientKey` property of `CardPublicKeyProvider` is not set on `CardComponent` init
The `didSet` on `clientKey` property is not enough, if you want the `didSet` to be called on init you should put the setter into a `defer` block or an other function

**To Reproduce**
Try to use a `CardComponent` with `clientKey` init
Throw a `missingClientKey` error

**Expected behavior**
No error

| Init | Setter |
|------|------|
| ![image](https://user-images.githubusercontent.com/10015557/96732104-45269a00-13b8-11eb-8f77-905b15823684.png) | ![image](https://user-images.githubusercontent.com/10015557/96732165-52dc1f80-13b8-11eb-8b7a-114564d09b64.png) |
| Screenshot proposed solution (quick win) |
| ![image](https://user-images.githubusercontent.com/10015557/96732206-5e2f4b00-13b8-11eb-9743-b8a5118d8df8.png) |

**Comment by mohammedDehairy** [comment]
Thanks @arnauddorgans ,

 Thats indeed a bug 😅 , Thanks for pointing it out, in the meanwhile you can just set the clientKey to the `CardComponent` instance, like this:

```
self.cardComponent = // initialize the cardComponent
self.cardComponent.clientKey = "{YOUR_CLIENT_KEY}"
```

Mohamed

**Comment by arnauddorgans** [comment]
@mohammedDehairy thanks

**Comment by descorp** [comment]
3.8.0 is released!

I am going to close this ticket for now.
Feel free to respond in this thread or provide any additional feedback!
