### ISSUE TITLE
[NEED ASSIST] CardComponent form insets when keyboard changes frame

### ISSUE THREAD

**Issue by nsimunko** [Adyen/adyen-ios#244]
I am using the iOS CardComponent to create a screen for adding a new card. It should behave like the Drop In component, so, a bottom sheet view that adjusts its height based on the embedded children views. 
I'm not using the Drop In because adding cards is only one part of the whole app, and I will need to embed the card component into a more complex screen later. 

What's the issue?

My "bottom sheet" view controller, which holds all the component child controllers, adjusts its height based on the content of the child controller, and the height of the keyboard. This works well when I open the card form and the keyboard shows. But when I tap into the next text field, your FormViewController adjusts its height on a `keyboardWillChangeFrame` notification, and now my sheet VC is taller than it needs to be. 

Maybe it would be nice to be able to turn off that behaviour, or to see if form bottom edge is already above the height of the keyboard.

This is the doc for the CardComponent, and I went into the source code of the `FormViewController` to see where the issue is. 
https://adyen.github.io/adyen-ios/Docs/Classes/CardComponent.html

I'm not sure how to approach this issue. I'm using container views and setting the height to the `preferredContentSize` of the child. I can see that the `FormView` class has this padding and all its parent views are constrained to the bottom of the screen. 

Here are three simulator screenshots and view debugger output of the third case.  

1. The screen is opened and the keyboard is hidden. 
2. You tap on a text field and the keyboard shows up. The screen increases height to keep the form above the keyboard.
3. You move to the next text field and the form adds some bottom inset and the parent view increases its height to the max constraint, and now you have some padding below the input form. 

|![Simulator Screen Shot - iPhone 11 Pro - 2020-10-22 at 17 30 35](https://user-images.githubusercontent.com/22167575/96897926-68704880-148f-11eb-8923-82f8ec1441f1.png)|![Simulator Screen Shot - iPhone 11 Pro - 2020-10-22 at 17 30 38](https://user-images.githubusercontent.com/22167575/96897959-71611a00-148f-11eb-9432-642deb9650a3.png)|![Simulator Screen Shot - iPhone 11 Pro - 2020-10-22 at 17 31 20](https://user-images.githubusercontent.com/22167575/96897972-758d3780-148f-11eb-8f85-4c4af5e6da2d.png)|
|---|---|---|
| | |![Screenshot 2020-10-22 at 17 52 29](https://user-images.githubusercontent.com/22167575/96897980-77ef9180-148f-11eb-81d4-d187ec635469.png)|

**Comment by descorp** [comment]
Hi @nsimunko 

Thanks for your feedback!
Indeed we did not consider such advanced integration scenario 😅

It is great idea to introduce "respondToKeyboardEvents" flag to a FormViewController!

In a meanwhile you could hack it by disabling bottom constraint in FormViewController:

```swift
     // make sure it is loaded first, since SecuredViewController conceals It's child controller until presentation.
     cardComponent.viewController.viewDidLoad() 
            
     guard 
          let vc = cardComponent.viewController.find(type: FormViewController.self), // ((cardComponent.viewController as! Adyen.SecuredViewController).children[0] as! Adyen.FormViewController)
          let bottom = vc.view.constraints.first(where: { $0.priority.rawValue < 1000 }) // bottom NSContstraint
     else { return }

     let fixedBottom = NSLayoutConstraint(item: bottom.firstItem,
                                          attribute: bottom.firstAttribute,
                                          relatedBy: bottom.relation,
                                          toItem: bottom.secondItem,
                                          attribute: bottom.secondAttribute,
                                          multiplier: bottom.multiplier,
                                          constant: 0)
     vc.view.addConstraint(fixedBottom)
     vc.view.removeConstraint(bottom)
```

```swift
extension UIViewController {
    func find<T: UIViewController>(type: T.Type) -> T? {
        if let vc = self as? T {  return vc  }
        for vc in self.children {
            if let vc = vc.find(type: type) { return vc }
        }
        return nil
    }
}
```

**Comment by nsimunko** [comment]
This fixes the `FormView` to the bottom of the screen, and the card form rises to stay above the keyboard when the first `keyboardWillChangeFrame` is fired, but it still keeps going up with every keyboard update. Not sure what is stopping it from going above the screen. Probably my top constraint on the parent sheet view. 

The issue is not FormView going up, but additional bottom inset being added. 
Maybe a good solution for this would be to calculate how much of the `FormView` is under the keyboard and just add that much bottom inset. In my case that would be zero. 

I'll see if I can hack it to work, inside the `keyboardWillChangeFrame` function of the `FormViewController`. 

![Screenshot 2020-10-23 at 18 14 00](https://user-images.githubusercontent.com/22167575/97027925-b6eb1900-155b-11eb-8eb3-11e6ebc5d453.png)

**Comment by nsimunko** [comment]
I think this may be an issue in my parent view, when I increase its height on `keyboardWillShow`. 
I did not know that `keyboardWillShow` gets called even when it's already shown, when you switch to the next input field.
 
I'll let you know as soon as I fix this. I'm doing some constraint magic, so keyboard event aren't working as expected.
Your form might be working as it's supposed to 😄

**Comment by nsimunko** [comment]
Okay, so, the problem was in my code. The way I handled the expansion of the drawer on `keyboardWillShow`. The `FormView` does expand if needed, when keyboard is visible, but doesn't increase the height of my parent view. 

Thanks for you help anyway. As soon as I started debugging the `FormViewController` I realized that it's not issue. 😄

**Comment by descorp** [comment]
Hi @nsimunko 

Nice to hear that you have managed to resolve the issue!

To clarify, disabling a bottom constraint did a job for you, or did you solved it somehow else?

**Comment by nsimunko** [comment]
Nothing was needed to be fixed in your form VC. I basically increased the height of my parent VC, on every keyboardWillShow, but I forgot that willShow is called on every text field responder update.
So, my drawer parent VC was actually pulling the form up, and not the other way round.
