### ISSUE TITLE
[BUG] Xcode 12 Compiler Error "FormViewController"

### ISSUE THREAD

**Issue by omerozk** [Adyen/adyen-ios#257]
**Describe the bug**

On Xcode 12 we are facing a build error as we are implementing Adyen and another lib called Eureka (https://github.com/xmartlabs/Eureka).

Both lib are exposing a class called `FormViewController`. With the new build process of Xcode 12, ObjC generated headers are now entering in conflict which make the compilation fail.

Here you can find more information about this issue: https://developer.apple.com/forums/thread/658012
similar issue on Kingfisher library (conflict with alamofire SessionDelegate): https://github.com/onevcat/Kingfisher/issues/1530

**To Reproduce**
1. launch Xcode 12
2. Add Pods Adyen and Eureka to your podfile
3. install pods
4. build your project
5. this following error occur on complilation: 

> FormViewController has different definitions in different modules; first difference is definition in module 'Adyen.Swift' found method

**Expected behavior**
Successful build!

**Smartphone (please complete the following information):**
 - Device: [iPhone XS]
 - OS: [14]
 - SDK Version [3.7.0]

**Additional context**

2 ways to fix this:

- Do not generate headers for ObjC. SWIFT_INSTALL_OBJC_HEADER = NO
- Set an explicit prefix for ObjC which will resolve namespacing

```
@objc(AdyenFormViewController)
public final class FormViewController { ... }
```

I think the most adapted approach, if ObjC support is required, will be the second approach to fix this issue

**Comment by mohammedDehairy** [comment]
Hi @omerozk ,

Thanks for the report!.

We'll look into it and fix it in the next release.

**Comment by descorp** [comment]
Hey @omerozk 

[This PR](https://github.com/Adyen/adyen-ios/pull/280) should resolve it.

**Comment by descorp** [comment]
3.8.0 is released!

I am going to close this ticket for now.
Feel free to respond in this thread or provide any additional feedback!
