### ISSUE TITLE
[NEED ASSIST] Billing Address Required in iOS SDK

### ISSUE THREAD

**Issue by mjplanet** [Adyen/adyen-ios#258]
How can I enable billingAddressRequired form item in iOS? Our web developer can enable this item in payment, but I can't find anything in iOS documentation.
SDK version: 3.7.0

**Comment by mohammedDehairy** [comment]
Hi @mjplanet ,

We indeed don't support this in iOS Components SDK ATM, but there are plans for it in the coming releases.

**Comment by mjplanet** [comment]
Thank you for your response.

**Comment by gscalzo** [comment]
Hi, @mohammedDehairy do you have any news on the plans?
Is there a workaround available for sending the billing address?

**Comment by mohammedDehairy** [comment]
Hi @gscalzo ,

 We're working on it, it will be released in the near future, will let you know as soon as its released.
