### ISSUE TITLE
[BUG] StoredCardComponent shows "Pay" button without payment amount

### ISSUE THREAD

**Issue by DmytroNosulich** [Adyen/adyen-ios#259]
**Describe the bug**
When using StoredCardComponent it presents UIAlertController to enter CVV code. This alert has "Cancel" and "Pay" buttons. In previous versions "Pay" button displayed also amount of payment like "Pay $11.20". Now it shows "Pay" text only.

**Screenshots**
<img width="370" alt="Screenshot 2020-11-09 at 16 18 12" src="https://user-images.githubusercontent.com/43130558/98552525-3c363380-22a7-11eb-9baf-92b30f99ae75.png">

**Additional context**
Payment amount is visible when pay with new card

**Comment by descorp** [comment]
Hi @DmytroNosulich 

Thanks for your feedback!
Indeed we have missed to passthroughs a payment object to a StoredCardComponent!

Will be fixed in [this PR](https://github.com/Adyen/adyen-ios/pull/260)

**Comment by descorp** [comment]
PR is merged!
Thanks again for pointing out to a bug.

You can check it out from 'develop' branch or wait till next official release.

I am going to close this ticket for now.
Feel free to continue in this thread if you have any additional feedback or any questions!
