### ISSUE TITLE
[Feature] set supportedNetworks automatically

### ISSUE THREAD

**Issue by Geschan** [Adyen/adyen-ios#261]
**Is your feature request related to a problem? Please describe.**
We enabled Apple Pay in our app and shortly after saw a lot of refusals of users who tried to add an Amex creditcard (which we do not support).

**Describe the solution you'd like**
The /paymentMethods endpoint already does deliver a list of supported card networks for credit card payment method.
It would be great if it would do the same for Apple Pay (and I assume there might be the same issue with Google Pay in the adyen-android SDK).
As this kind of configuration is already done for credit card payment, I don't see any reason why it should not automatically do the same for Apple Pay - it would also make the behavior of the SDK more unified and predictable.

**Describe alternatives you've considered**
We know we can use the exclude payment method attribute to exclude specific cards, but I consider this solution only valid if we want to exclude a card that we do actually support and doesn't want to give it as an option anyway. 

**Additional context**
https://github.com/Adyen/adyen-ios/blob/develop/Adyen/Components/Apple%20Pay/ApplePayComponentExtensions.swift#L73-L97

**Comment by descorp** [comment]
Hey @Geschan 

That is a brilliant idea!
I am creating a ticket to our backend team to investigate this idea and make it happen.

Thanks for your feedback!

**Comment by descorp** [comment]
Hey @Geschan 

Thanks again for great idea!

This functionality is available on our API starting from v67 (official docs will be available shortly)
Here is [PR for iOS SDK](https://github.com/Adyen/adyen-ios/pull/332)

**Comment by descorp** [comment]
I am going to close this ticket for now.
Feel free to provide any additional feedback!
