### ISSUE TITLE
[Feature] show different button text when amount is 0

### ISSUE THREAD

**Issue by Geschan** [Adyen/adyen-ios#262]
**Is your feature request related to a problem? Please describe.**
Currently the button shows "Pay 0,00" if the amount is set to 0 (which we do when we use tokenization of a payment method to store it for later use). 
The dropInComponent allows the "payment" attribute to be unset, but in these cases the Apple Pay is not visible anymore (as it always requires an amount, even so it is set to 0).

**Describe the solution you'd like**
If the amount is set to 0, it would be gread if the button only shows "Pay" or better just displays "Save" for saving the payment method.

**Describe alternatives you've considered**
Removing the "payment" attribute does show "Pay" without 0,00 when using credit card, but Apple Pay dissapears from the payment methods list - so it's not an option.

**Additional context**
The adyen-android SDK behaves a little different. There is no "payment" attribute but the "amount" attribute is optional. All payment methods keeps working if "amount" is not set (including Google Pay).

**Comment by mohammedDehairy** [comment]
@Geschan ,

 Thanks for reaching out.

 Why do you need Apple Pay to be shown if the amount is zero or the `Payment` object is `nil`? whenever the shopper wants to save the card for later use, just set the `component.payment` to `nil`, and in this case Apple Pay component won't be shown, because Apple Pay payment method cannot be tokenized, after all apple pay tokenizes the shopper cards anyway.

Mohamed

**Comment by mohammedDehairy** [comment]
it seems I made a mistake, you can make Apple Pay payments with 0.0 amount and make recurring payments later with the token.

so you're right, we'll take this into account in future releases to enable 0.0 payments.

**Comment by mohammedDehairy** [comment]
@Geschan 

You might want to have a look at [this pull request](https://github.com/Adyen/adyen-ios/pull/272) to verify that it solves your problem.

Mohamed

**Comment by Geschan** [comment]
@mohammedDehairy looks promissing, thank you!
I'll try to do some testing as well, but what I can see from the commits it's exactly what I was looking for.

**Comment by descorp** [comment]
3.8.0 is released!

I am going to close this ticket for now.
Feel free to respond in this thread or provide any additional feedback!
