### ISSUE TITLE
[Feature] Localization from different bundles

### ISSUE THREAD

**Issue by nsimunko** [Adyen/adyen-ios#266]
I am building an SDK which uses your pod, for encrypting credit card data. 

I would like to change the title of the submit button in the CardComponent. Localization parameters, which take the name of the `.strings` file only look for translations in `Bundle.main`, that is, the bundle of the app which uses my SDK to handle all credit card & payment related requests. 

I suggest adding an optional parameter to `LocalizationParameters` which takes a `Bundle`, so I can point it to look for strings in my pod project. 

The issue is in `Localization.swift`, `buildPossibleInputs` function, line 53. I want to tell it look in a specific bundle.

**Comment by mohammedDehairy** [comment]
@nsimunko ,

Thanks for the suggestion, this sounds good to me.

**Comment by mohammedDehairy** [comment]
Hi @nsimunko ,

You might want to have a look at [this pull request](https://github.com/Adyen/adyen-ios/pull/273), and see if its solves your problem.

Mohamed

**Comment by nsimunko** [comment]
This looks exactly like what I need. 🚀 

What happens if both the main bundle and the custom bundle provide a translation for the same key? Which bundle has higher priority? It would make sense that the main bundle has higher priority, so the main app can override both yours and mine `.strings`. 
From what I can tell, the `attempt` function will take the main translation if provided. 

Thanks for the express fix 👏 

P.S. I think you forgot to add the parameter documentation on the `LocalizationParameters.init`.

**Comment by mohammedDehairy** [comment]
@nsimunko ,

Thanks for the feedback, will fix the documentation.

Yes, the main bundle take precedence over the custom bundle.

**Comment by descorp** [comment]
3.8.0 is released!

I am going to close this ticket for now.
Feel free to respond in this thread or provide any additional feedback!
