### ISSUE TITLE
[Feature] Make the properties inside the `UILabel` extension internal or subclass `UILabel`.

### ISSUE THREAD

**Issue by thomasneuteboom** [Adyen/adyen-ios#288]
**Is your feature request related to a problem? Please describe.**
The new update (version 3.8.0) adds the following code:   

```
 //...
extension UILabel: AnyFormItemView {
    //...
    public var delegate: FormItemViewDelegate? {
        get {
            objc_getAssociatedObject(self, &UIViewAssociatedKeys.delegate) as? FormItemViewDelegate
        }
        set {
            objc_setAssociatedObject(self,
                                     &UIViewAssociatedKeys.delegate,
                                     newValue,
                                     objc_AssociationPolicy.OBJC_ASSOCIATION_ASSIGN)
        }
    }
```

The `delegate` property is public which causes clashing property names in our build; we also use the property name `delegate` in some of our classes that subclass `UILabel`.

**Describe the solution you'd like**
Adyen's extension of `UILabel` does not explicitly add value to our `UILabel`. And since delegation is commonly used by the community I'd suggest to make the `delegate` property (and other properties too) inside `UILabel` internal. Or subclass the `UILabel`, e.g. `AdyenLabel` and make that internal.

**Comment by descorp** [comment]
Hey @thomasneuteboom 

Good point.  We will path it up!
Sorry for the inconvenience!

**Comment by descorp** [comment]
I am going to close this ticket for now.
Feel free to continue in this thread if you have any additional feedback.
