### ISSUE TITLE
[2.0] Migration notes URL doesn't work

### ISSUE THREAD

**Issue by mmynarski** [Adyen/adyen-ios#293]
**Describe the challenge**
I'm about to update library in my project from old version (1.18.0) to some newer one but I struggle with migration to 2.0. The migration link doesn't work 
[https://github.com/Adyen/adyen-ios/blob/master/MIGRATION.md](url)

Can we get it updated?

**Comment by mohammedDehairy** [comment]
Hi @mmynarski ,

The `MIGRATION.md` is moved to [V2 branch](https://github.com/Adyen/adyen-ios/blob/v2/MIGRATION.md), sorry for the inconvenience.

**Comment by mmynarski** [comment]
Hi @mohammedDehairy ,

thank's for quick response. I think that closes the issue!
