### ISSUE TITLE
Integrate with Obj-C project

### ISSUE THREAD

**Issue by Golotus** [Adyen/adyen-ios#3]
Hello @diegomarcon，

First of all, thank you for sharing. My objc-c through the example you gave through integration, in addition to a question: 
in "Payment  Methods" page, after click the last item "Bancontact Card", the xcode console throw info

`Unknown class _TtC5Adyen15CardNumberField in Interface Builder file`
`Unknown class _TtC5Adyen19CardExpirationField in Interface Builder file`
`Unknown class _TtC5Adyen20CardInstallmentField in Interface Builder file.`

and the source code file  "CardPaymentFieldManager.swift"  line 32 throw error

`Thread 1:EXC_BAD_ACCESS(code=1, address=0x0)`

I'm trying to solve this problem, and it would be better if you could help me.
thank you again

**Comment by olutsenko** [comment]
Hello @Golotus,

Thanks for your request. To understand the issue better, could you please share screenshot of your "Payment Methods" screen?

Thanks,
Oleg

**Comment by Golotus** [comment]
Hello @olutsenko ,
        thank you for your attention.  I‘m sorry that  it looks like we can't share pictures here. It's look like this:

                              Payment Methods


> Your payment methods
`   ▇▇     ****4449`
`   ▇▇     ****0010`
`   ▇▇     *****1111`



> Select other method
`   ▇▇     Bancontact app`
`   ▇▇     Bancontact Card`          >




The examples of diegomarcon sharing worked very well，and integrated into my project, click the last item "  ▇▇     Bancontact Card " ， there will be problems

**Comment by olutsenko** [comment]
@Golotus,

Thanks for finding the way to visualise this!

We’ll need to check your account configuration. Would you be able to send us your merchant account via e-mail: support@adyen.com

Also, include URL to this GitHub issue and mention: “Please forward request to Oleg L.”

Regards,
Oleg

**Comment by Golotus** [comment]
Hello @olutsenko ,
I just used test accounts， I think the problem is probably caused by calling the nib page。
I'm a beginner for swift, and I'm giving you so much trouble. Thank you and @diegomarcon  giving me so much help, I'll try my best to solve the problem on my own.
Thank you again.
Regards

**Comment by Golotus** [comment]
Hi, @olutsenko @diegomarcon ,

Thanks a lot, the problem has been satisfactorily solved. the problem caused by field's custom moudle, It was a small problem, and it really took me a long time  and addad a lot of trouble to you.

Regards

**Comment by olutsenko** [comment]
@Golotus 

Happy to hear you found solution to the issue described above.

Anyway, could you please share your merchant account via support email? We want to check configuration on your account to be confident in the fix. Thanks in advance!

Regards,
Oleg
