### ISSUE TITLE
 Do adyen SDK support iOS 9 at least?

### ISSUE THREAD

**Issue by qinxianjun** [Adyen/adyen-ios#30]
Do Adyen SDK support iOS 9 at least? I want to use adyen SDK in iOS 8.

**Comment by joostvandijk** [comment]
Hi @qinxianjun,

The SDK only supports iOS 9 and later. There are no plans to support earlier versions of iOS.

Kind regards,

Joost

**Comment by qinxianjun** [comment]
OK,ths! I run custom integration demo. why don't show view of adyen methods.
<img width="264" alt="wx20180514-172738 2x" src="https://user-images.githubusercontent.com/14191749/39989292-23a5e320-579c-11e8-8a9a-a588f1d9b521.png">
![image](https://user-images.githubusercontent.com/14191749/39989332-3ab2fc42-579c-11e8-9613-7f97572c9bee.png)
how should I do?

**Comment by joostvandijk** [comment]
Hi @qinxianjun,

Did you put your Demo Server API Key in `PaymentRequestManager.swift`, line 245?

**Comment by qinxianjun** [comment]
![image](https://user-images.githubusercontent.com/14191749/39989706-44e1fa14-579d-11e8-8410-81788dff89d2.png)
Checkout API Key is Server API Key? if it is, I changed.

**Comment by joostvandijk** [comment]
To connect to the demo server, you should use the special Demo Server API Key. You can find this under the web service user settings in the Customer Area. If you need any help with this, please contact support@adyen.com

**Comment by qinxianjun** [comment]
OK, ths! And the "returnUrl" need to change?

**Comment by joostvandijk** [comment]
In the custom integration example, the return URL is already configured properly. It's set to a URL that's registered in the Info.plist. This allows the app to be opened by that URL.
