### ISSUE TITLE
[BUG] FormComponentStyle FormHeaderStyle textAlignment not working

### ISSUE THREAD

**Issue by Kevinvandenhoek** [Adyen/adyen-ios#309]
**Describe the bug**
The FormHeaderStyle allows us to set the textAlignment property for the header label. However the displayed style will always be center aligned, due to the label being centered in layout. The textAlignment property on the label is set, but due to the way the constraints are set it will always shrink to its intrinsic content size, and center itself horizontally.

**To Reproduce**
1. create a `CardComponent` with a custom `FormComponentStyle`
2. set the `FormHeaderStyle` with a `TextStyle` with `textAlignment: .left`
3. present the cardComponent ViewController
4. The header is still centered (and the layout inspector reveals this has to do with the way the constraints are set up).

**Expected behavior**
The header is expected to be aligned the way it is configured, I expect the label to  be stretched over the total ViewController width (with the same margins as the rest of the content), and thus have the textAlignment property be able to align the text in the label accordingly.

**Screenshots**
<img width="784" alt="Screenshot 2020-12-14 at 12 07 00" src="https://user-images.githubusercontent.com/26718990/102074349-f3711d80-3e04-11eb-87c7-567d791b3154.png">
<img width="1062" alt="Screenshot 2020-12-14 at 12 06 29" src="https://user-images.githubusercontent.com/26718990/102074350-f53ae100-3e04-11eb-9bfd-412d06546cd7.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS14.2
 - SDK Versions:
  - Adyen (3.8.1):
    - Adyen/Card (= 3.8.1)
    - Adyen/Core (= 3.8.1)
    - Adyen/DropIn (= 3.8.1)
  - Adyen/Card (3.8.1):
    - Adyen/Core
    - Adyen3DS2 (= 2.2.1)
  - Adyen/Core (3.8.1)
  - Adyen/DropIn (3.8.1):
    - Adyen/Card
    - Adyen/Core
  - Adyen3DS2 (2.2.1)

**Comment by descorp** [comment]
Hi @Kevinvandenhoek 

Thanks for the feedback!

Indeed a FormHeaderStyle is very limited. 
This is one of the reason it was deprecated in 3.8.1 and will be removed in v4.0.0 (approx. mid-January)

I would recommend avoiding using the components' header.

Instead, we would like to encourage you to set `showsLargeTitle = false` and create your ViewController that embeds `PresentableComponent.viewController` in it. It will allow you to have full control over your payment flow scenes' outlook and the flexibility to create a custom presentation.

At the current moment, we do not have any examples or helper classes to guide you through it, but let me know if you need any assistance.
We expecting it to be somewhat similar to the way how our [ModalViewController](https://github.com/Adyen/adyen-ios/blob/develop/AdyenDropIn/Presentation/ModalViewController.swift) is implemented.

In the meanwhile, I will work on adding helper classes and examples to both UIKit and SwiftUI in 3.8.2
