### ISSUE TITLE
Accessibility support?

### ISSUE THREAD

**Issue by minhpo** [Adyen/adyen-ios#32]
We are trying to integrate Adyen into our app. We noticed that large fonts are not supported. Is this on the roadmap?

**Comment by joostvandijk** [comment]
Hi @minhpo,

It's not our top priority, but we'll definitely be adding this in the near future.

Kind regards,

Joost

**Comment by joostvandijk** [comment]
Hi @minhpo,

Support for dynamic text has been added in 2.1.0.

Kind regards,

Joost
