### ISSUE TITLE
[Feature] Card scan/camera

### ISSUE THREAD

**Issue by jesperjohansson** [Adyen/adyen-ios#322]
**Is your feature request related to a problem? Please describe.**
The camera seems to be missing when using the card component. [It seems it was removed in 3.0.0.](https://github.com/Adyen/adyen-ios/compare/2.8.6...3.0.0)

**Describe the solution you'd like**
Add card scanning back.

**Describe alternatives you've considered**
Downgrading the version of the library.

**Additional context**
I might just not be finding the new implementation...

**Comment by descorp** [comment]
Hi @jesperjohansson 

Thanks for the feedback and sorry for the long response time.
I hope you had great holidays :D

The card scanner in v2 was only a UI wrapper, allowing merchants to plug 3rd party SDK.
Indeed, we removed this feature from v3 for the sake of simplicity and higher granularity of Adyen SDK.

Unfortunately, there was a low demand for it recently, so we never priorities it in our backlog.

Downgrading is not the best course of action.
How severally do you require this feature?

**Comment by jesperjohansson** [comment]
@descorp Ah ok, I understand. Thank you, I'll look into creating a custom UI and using the card encryption API then 👍
