### ISSUE TITLE
[NEED ASSIST] How can I use your SDK via CocoaPods in my Objective-C based project?

### ISSUE THREAD

**Issue by yanqizhao** [Adyen/adyen-ios#323]
**Describe the challenge**
I imported your SDK of the latest 3.8.2 version via CocoaPods. When I tried to import the Adyen-Swift.h file, it couldn't be found.

**Screenshots**
![adyen](https://user-images.githubusercontent.com/16577092/103399222-e8471d00-4b7a-11eb-998c-045dbc74c63e.png)

**Comment by yanqizhao** [comment]
Another question is I found that most of your API hasn't been singed with @objc, does it mean that I couldn't use that API in my Objective-C based project?

**Comment by mohammedDehairy** [comment]
Hi @yanqizhao ,

 Unfortunately DropIn/Components SDK cannot be used with Objective c code directly.

 But what you can do is create Swift files in your project that call the DropIn/Components SDK, mark those swift wrapper classes with `@objc` annotation, and then call those swift wrapper classes in your Objective c code.

**Comment by yanqizhao** [comment]
@mohammedDehairy 
Thanks a lot, I will have a try 😁
