### ISSUE TITLE
JSONSerialization error

### ISSUE THREAD

**Issue by fangshiqi-start** [Adyen/adyen-ios#324]
Why do I get an error when calling the following method？

 let actionData = try! JSONSerialization.data(withJSONObject: dic, options:.prettyPrinted)
    let action = try JSONDecoder().decode(Action.self, from: actionData)

**Comment by fangshiqi-start** [comment]
This is the action data

{
    paymentData = "Ab02b4c0!BQABAgCvvgk3JTsygflvAJxkOpi3HGoW4Uo95ReYcdQ3tVtmGehc99fuPLClB1hy7X6BUaNId6F5qRsmkDy7JN/6m1m64ady0NbnsOuU3yXKTWbcN9qMSAmQ4YlBksrhVFZ2jhCHANxjhmT1onMaDT0xb0AHBikB2rPUETZMjjgdXLn7GY7j0bWiqDI0KQsm5XfIvA7BeKZ2h6sKcn7zEjQ9upvrWbDy+vIqifKJDjzljmASOvdGR00PX43cC2nkgz44xHF6aZDyRPIj4o8n2UgJ7wkee+1FNtcTYMHwuz/ubTU5bu2g1v7zSG5iFcX1LD6Npy2T3P2ykDL2Ogdni8m+BmdQtnXRruOxYob4p+UVhUJpIJJfPZ3KAhAfZ4e2BrBdbrVuLL1h88mrtH7NHmMHD4AUWprRC6r5cEnCh8QKJURVHsn7RQls/OqTv2fySCyLHGu5Pd8laYGfRRMb4Jv293zum/KaDu5GwPGbkzwg2ikt2Ri6hXIIX5s0s2WCIbe8/1qWK/0PLHjTvfKTNsYgSX3mAtYF6q5hGVeY7wCjoC6WO2xa/4NSIsTzB20LP69Em1fHTWx4f6iJwiYt09aFw/wQ+V4K88rOA91ZYipmIrqnidiJpLGfqaA1+lHie7NRH66TjVKOUesfpaJrNw1+EAT2GngHCw5F9bSDUHJoI5oT9RBK14bmNzYZoXgUO2/4PHOAAEp7ImtleSI6IkFGMEFBQTEwM0NBNTM3RUFFRDg3QzI0REQ1MzkwOUI4MEE3OEE5MjNFMzgyM0Q2OERBQ0M5NEI5RkY4MzA1REMifSBdglbZ4ndWanaul6SlpnXpQWWPRDXLjheWJ/+x1WozMw9zR3fHAeXdz0XiEsNJ7Aeh6Dzr+XQM6vlLHJ30kZT1+eNbQzfUESMP/C16gggiINXS3V1BZz3a2vO40Ya0+0ZAPA4DWa/gD8rqeZj8vuWljI+jrBWiwebVqcuXi8LcIaQw0Tjrl1KGvXMvx5oHaSHMCYevBiM1sapMIyjMWnkjSQQ4AnvQeMPfS8Weur4FjoeTD/mQpTQG+zNz02YPEeWWTER9+cv7ocBaMQWnhy9pwXaanNtR/IhkvCs4cFRJHoPpb6+gF3H8KTCJsoJ9WTRE1eBOcG437B8rM/ExltDeOHKRL9JMAMSGSoq9pz6GdrU3xEKxYRy1o5nISO497KFROeTmNgWT2A9kCmxW63nJvh/YKR2pspU7UMz4g5w9TCQ1jUQEKHlSg1tY1veWot+dwCLZLpIk7FsfmbeLKZMFXruF56keQx5Of9Y5T6DE5o4zdPS1aLJsgSj01ZNbhwwMD7IUxRU99XwMfpB3/zsmdVoEO4xOSQbVXTNIq9xPUOFROdEWY8ML1G1qdG+bvXUvbVBG3T7mxudveG6jmgkAee/6+AZ1kzPuV8elLSdGs1GRx245bnExV4jzXf62veXNRGuXPemEudjzrtEjC5q6dxsezUCDesu25c3AN7gFon8uYfpf5UvZ9fiGsPNvNHh+pb+tZrSv1VLmY07T2zJUL7rsDpG7/Q/YXqj8ECMJjMve9y7Ln5GSmCsT/ESzu0I8hIUaznMbuosB6+G2/ug1bEBszMMdC/U+SUYBiwA6PH7eYm7MR3bwzWKqdew2Wt76CgShFFqV9Qk6NdPRmAppzzrAuJ6QVhH2YEPpdDLGBEUqWpDc3CYE9QGrAwPfLeRvu8kzkcN1imTB/M2Do9MQtDoO7qvIxnXknO1dUIs5yR2D4kdoLlrgfdFaEHJJWuUvZNfEH9drtSn9JeVx536gIrPZzqvvpHuIbMT3C9bcPVzB+H0G2jWsH6tQdYUTIwrQe1saJhBR5uzdMFQCfnkrIFP5pjAiVVbq9zsVOi+TxyYmkVLuSl5uae9DkCRhxEkPmbBjTfoQy00ayROyx9tL6ROw+2huZT97vsINmQEwjzYZcZ8bnNrdougcGMyn94ve1rbRG4CVYfw4zSR91TxW4zxZzL8RwSJyrrJyLnPelBbspHPLsrPAqPvHNsL8w0GYrM/Ie8LkJ4L3cPF2dhICv/Oyua077oE+BJAiYiRyKAXo9Ocw9RHW8FBk11TyT9LsbthxnlHDSVvWS2u4bCQtiN8TTzaP6nRCaI3/iDoekN/G6+Ke0xMTt9DiU0/TrdcpBBVc4nTy5ilskyMH2azWFtOuj8rWr4snUvYU9JWbzh1ikQ8cTn/MNvp1XEHZK5izkCHdIYuuuFYTSqZeStyl0p4Lc8fHhgv6fcZBE6ZGxMvgp8srRnNRvROJDbviEU2x6QgGu/CAzcpFIwvjy53+qD3iie/zoeKX59ixsivtgxMCn7Q7BrcmgkMIBf6SpsgcSgEBqQPyuQ+EFGdtYTEca/E8/y3FoQyenrIpKHKF/5IcHSujV4qtcnkd4EkMmbphGSK7bz8LMBNsItiXCAhcy6g2mKh5jE2/CpRGjnPjqpqi4V0lHR7RxC/9eiqVyZrrX+epJMxtWhC4Js1Qbyrcm1cjiH4kltUxROTe8hSDyWZEm+J4KdAUaIlAnK/iXWn1tmQ6qlYemRWyf1Jl813bEsaiUDFgwfu+eSXWmbBYrBbAs9nW6NZZ2JZ0o+agMy6pel88eiwqxBvvwlYJycI5FWLGSPif+8N1QSFm+6QsHoa/bNB8Qy6ra5lhW4Rv1z/TfCXDeQAoFwqBu4CGFWIZr6JOrFvmU55F4LjRK0xt6JiCZWgz/B9mBADYRUhGXdRoYse/Zczr/dQMLMpkyL/cDugB6yxTrJIkjwLVYo+2AdtI9E4pj61X6BIMH1NcuyY3CHM3X7BF1QwNA337Qe+wyRFR6TO/wAiU5sm3wQsjG+F4rVLUNK8Owh+0rC3VhCdognrdygx0qMEkreWrKwaBJkm36FH7DZW7BHIOcfuGI/5JjUmt1rABe9VDZQd3TTebkrifF1MDSK4/C04p76h3maG//raT0DMgngQ/iBcm/af29dm5zKQitnUuzymQMTv3ou6ilktdD34cHIiMxgNmxMYggDZehheVUTZdSkIuJI1XJNADy3PsR7dYKXAFjMTsEX8UCyhJZmBkCqptVwU55e8FbUj1u4RYLvx0FCOY6pC/afBcbBSgQpXELVKRe3qEC76s5tRA6lJgwHQQ/1cFlyCjuwAp4QbnUvh2P993NGaQ/tuCzlCX7ZA3cc6BVU+xDbPKji/jD/+BL7W0RD0Enlc8y/z4vc+6ex4ToaMx5tJ2DVHOL8OXi7c0Ek4tTe8wIRqsyao/sRqbccF7FnwugwD5kL+RvYHMzbefJ9j+xy2MX8Xmy800rm96YCWLgewgOtfAToAx8+OnCrNOIcW/pdRTzslRrKdZ5yi0IwP7joc3I82aS5TufOZ3sVXBfqVR4yFC7zRurONsLI5O/gkfeqPVULCBhGdgbRdkdxYE713hh3HpqFouNrMYkgrJvt5h3GQZQO8LrEqZLGXo7HEmSfC3BCKa6iVjgNBo4PPyxq0ZRj6yUzo+0Mw0LxZdoAegC40FC0LBfyvFdm79ChMIZGdYUzK9pFgTAK/wvBcyypeEKg8RTF3nmpEa5fX2y4AQ5ILja+laqggp7t7LNIOGyD3p+w8Cx4DQPnE/PpTdcnHcjP7IlLg5UrNbg6UmFjcohTqbxtbqKoRY3EgBaHm+tr4nXU2djeSIneFiJoLlnHKCbjh/ioP0NQgQzPhuoerm2rNyjh05+ZkDo5X3o5svhpWHOvY7i4JFRxiIWiEQEisDBLmUPQ7METgdlhATev7AcA5mpCSI0vhJz7B54Z+rocgPHvpdFCfLvOhA8lYwWbvp5fMeYGxRcg4lwBTSd57RUFQoJIgQyx0wmqINQk0ksRE0EkAiJXExD2srmKtfjKn4mij6Ahcos3ztoeizbLVYBcyRVy1WucUP3VFsRr1oBlVde0XoLjcSIfCfrnuu02A1x+TLRT3VceZ7RU72d43f6wwoQnJmat1xE7QQVz8WSR1IPWT7elJ+D0x+WVc4WSKR31uWkbE8l9NZymCDRSYPm2xPKzdHflPQhxv6NoQcrtmYVjF4p7hpcx60Lh5meq/nEo/Fv8CtPxOskt2Bp9ZGnStESeIWgx7z8P7W72/pQyIhZWC7+anAfQeLahPjVcx2Wn9DADhVxv2M91BMRHaEF7qbVi6XzUE/kv/RbU4v1TE/bTIn3htVlaA+YQgq1n9hvBJ55sxZD0dTMgRQ9r8Rbw2kTflwLXlt36R/PYzm1BXOQGv2UIGaSlLusye3Z20JEbUvM0r71oMornk7kZL8aAXYsaBgfd2q1MpPi5mFlVV5lAAI3+VeT6Vcqyn2jdyODIAg/utCVQ4KTsb+Gatq8UcyZCTJrNi9P6Ao4UVC9zvXRvZQTTz6uFP3/RaktqIKZo7rK9Y2+MuxmVP3+DkTaTTmkoc8GWYxrdPxRlMA4xWoASK/whaphmom94m5ocNs4ZAv2+qhrPq0y7wK7Grfngfx9uomfGLhkbtVxPPYAvluMEtILHo8r8SQ7oG5p4H0c7JiQA7SCD7o8pcIjRDUoqaG/IEuR5iDCN5bmdD/IcEy9HkwTXtfFWL0T/qp4Thp3bxHq9xiZlhAuFPJSOo95y7iPFjJcxFCO9RkWCqo/zqHWplXes9HYkq/ExQJjhB4bjrF0nZ7BEI7LBuxs0KJ5+FjYHqGXwCLq0hdUUpiUKsdft8aefGjrrFoFkmGL0DoGjwkNbYil7kXnXIBKs3+Q3zu/jpIBIyjYFDT806i2UTjAc4HmkZrRiv4L34tiOw16P2yCSmSkd9BKlVJREE7nVyClJnSlcs7wOw/lh/6ehNcoZ+JZ5kSoGD5sbBJW1Of+7RlkiEJ32uTmjJlSP3Ht+Xtdztq49Ohab7cPKl130h0Y3Rwj2FNbVzBOoh2GP/ZPz1T6k9MOJ2AcKR62EqWIERjbXiGv+SMAG5hYbVi2wXkkx5gd2tGDQhsOrxd6jeCVjJmDWmDJbG1WD17dzi4ZyFU2prNMv2nSZd0/CEpvVtBtAhOzvwfxaoluq+yFPQmjX96rFxKhzWw2T3j+jygElbT55ZLOxJQH5O9RkgqwfQRH9qf8v4N2HhARNizLYzyjXyqq8d9X5Gctqzq/YnbUW6jQ7758wQz5ayu1xczqvMmHSPxnsdV8xgMnhbDyyiYjDamtY9uMqZWP7UALUEdur29MYhAWn2X7k0chuunFHQzGlSSuekWqiOTGpP6tTnXcIO6FVJ0JAqXNbNJrh6+UG8GXaxeeLbhu7rUmptr/8izQdQ3rgzMyZIGdya2KPvPKkVVkFz2jdYir4MBeq0v93kNEmKYVDfCWatEqF+l/9Yy2mwDf7QjdmDNiSWLJyQptApFF2deh3iGvA346E85CN8j1VEnh6pOwyg5gcqGh2SwbBK1Cj+pmIQcC883r1V3OgTgrziahIjwY8KEBQ5y7r2t0cJT0oiAQ4I+WUSzv9eWLaa4EvmgEQZzu9vOycdfi7uXDkW4ZJmNbTBUKv95bRdNkF5wLAiDLY/DUK0I5cPep9FCIttaZpIYNSjUIuNskbaS2tCaDxDUprn8mDGBMQvF0ZZUDvlmnG1o6sOWRg8gktn5A3rALrtyM28Db3tyvi53DmMD4Mj54hNgyMLui/j2U+NHmHGIoN+TXT+17oMQVVeOpCJeQpCht887Surfk4FF2lAJG9QEAEGYhybxHyWMz8YJNPELrcn0IUpG/DDXNfsX/Q1vtDjisn1K7WJjJ1S9ctW1aIHLDWWbQxfBO2kCPdObDQH/PydblLxdwjj2cjK8rBIZMXaM7QH3rNGNyyvhWiHTFbGkwBDIB8RB3yd0wUreejYey18ZlJrx/AfIWjr6nbOZCrFP+9UzuTSqLe7pYP0MBm0rCYd2Www4nHdCpcmiWoaGzwA9mNjkQc6fPWN9nJybQqQWJlL6QmPOIRzZv99tEmQa/XNq39A4GiDMTR+4gMY+I4D5aF1lqSTBvVykoqhwFMIXcy3z5B/K0UWpL8ej8/UBT3r3NwSF37FPdcQP4HP1PoVIijxaUpou2ZJBTEhUdTdAXZrjzDMcU7TdiW85zpozMk+MstN6glXe9tYmyaxAgW3W6T8agSQ6bE5DYLFszpOnW/a2SwB6Crz89EBU3f/jiFY+nWcO0sr4PWyvqSwGPkFv2X+0Tl+68Hc8kH3lfeMv35Gko16HqrKSLECc/ZWlhsnPmNXpBnys4qvf6gLvGE1fU/oMm8A14bndSa2+CrMqu/1kNRpFRj1Ns7pw3Rott8Et/lf+6Tp8bo7uD4rga9gzcEC0WM+cNGuBVUuWJFpst6C8fX9B5qcNlKRwKI9cx2o13VIpfqJ/oL0Z+8z3GciPSFljq89coboeaD1ar9Naubdp4o6zGKnbRtV9YkEBiILM27CfJJLTh6Vl1Y065r9/oqo32J97NpAxbxTawmXAiQZil+djsRzUnHtZPrWk8iyoVIbsIlWIUYR9qWrXKNeKjQ1kVGmS7B0q20dOdq7DS5iEuonhHX52FbrpFROMmHW09G+uVYLqsCdsEbwJk490shdYrMir6Eo7++Qrf0A8VtXlpMKV7S+Dhq82+HXcs66DOhOY9c0BUxI50gQQJXWhxCvLm+m3ghHXi2S3SrOIVsYxod7jzeP3SR4ahAOgtpH/E2T0y1WoUUJYR2UdUMzYULMOqOhQb/lygGazqDwKk9q/AxDSeB1obvCqjizwMCg1yWd1QSpdd4c2TzfrKsHjV15cvLCXKA6R9C1nM/GK5ANsDckjW/Mm5+bhwQ+buhky/zI7F1qjIX27cdJrFcc=";
    paymentMethodType = scheme;
    resendInterval = 0;
    resendMaxAttempts = 0;
    token = "eyJkaXJlY3RvcnlTZXJ2ZXJJZCI6IkYwMTMzNzEzMzciLCJkaXJlY3RvcnlTZXJ2ZXJQdWJsaWNLZXkiOiJleUpyZEhraU9pSlNVMEVpTENKbElqb2lRVkZCUWlJc0ltNGlPaUk0VkZCeFprRk9XazR4U1VFemNIRnVNa2RoVVZaaloxZzRMVXBXWjFZME0yZGlXVVJ0WW1kVFkwTjVTa1ZTTjNsUFdFSnFRbVF5YVRCRWNWRkJRV3BWVVZCWFZVeFpVMUZzUkZSS1ltOTFiVkIxYVhWb2VWTXhVSE4yTlRNNFVIQlJSbkV5U2tOYVNFUmthVjg1V1RoVlpHOWhibWxyVTA5NWMyTkhRV3RCVm1KSldIQTVjblZPU20xd1RUQndaMHM1Vkd4SlNXVkhZbEUzWkVKYVIwMU9RVkpMUVhSS2VUWTNkVmx2YlZwWFYwWkJiV3B3TTJkNFNEVnpOemRDUjJ4a2FFOVJVVmxRVEZkeWJEZHlTMHBMUWxVd05tMXRabGt0VUROcGF6azVNbXRQVVRORWFrMDJiSFIyV21OdkxUaEVUMlJDUjBSS1ltZFdSR0ZtYjI5TFVuVk5kMk5VVFhoRGRUUldZV3B5Tm1ReVprcHBWWGxxTlVZemNWQnJZbmc0V0RsNmExYzNVbWx4Vm5vMlNVMXFkRTU0TnpaaWNtZzNhVTlWZDJKaVdtb3hZV0Y2VkcxR1EyeEViMGR5WTJKeE9WODBObmNpZlE9PSIsInRocmVlRFNNZXNzYWdlVmVyc2lvbiI6IjIuMS4wIiwidGhyZWVEU1NlcnZlclRyYW5zSUQiOiI3NjdjOTU5Mi1hMGMzLTQxMmEtYTI2Zi00MzM2NzA2Y2NiMmIifQ==";
    type = THREEDS2FINGERPRINT;
}

**Comment by fangshiqi-start** [comment]
This is the error message

dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "type", intValue: nil)], debugDescription: "Cannot initialize ActionType from invalid String value threeds2fingerprint", underlyingError: nil))

**Comment by fangshiqi-start** [comment]
I found the cause of the problem, because the type value is uppercase and needs to be converted to lowercase 。
THREEDS2FINGERPRINT -> threeds2fingerprint

**Comment by fangshiqi-start** [comment]
![4191609830222_ pic_hd](https://user-images.githubusercontent.com/57080337/103618604-35583400-4f6b-11eb-99e1-ab868a18950f.jpg)
How to take out fingerprint data？
let fingerprint = data.details.dictionaryRepresentation["threeds2.fingerprint."] ?? "" 
But this method is problematic and cannot get the data I want

**Comment by fangshiqi-start** [comment]
Does anyone reply? Need help urgently, do not understand swift language

**Comment by mohammedDehairy** [comment]
Hi @fangshiqi-start ,

Thanks for reaching out.

 We need more context to be able to help you.

 Please describe the problem, and what you're trying to achieve, also which version of the SDK are you using.

**Comment by descorp** [comment]
Hey @fangshiqi-start 

Could you provide API version and SDK version you are using?

**Comment by descorp** [comment]
@fangshiqi-start 

I am going to close this ticket due to the lack of activity.
Please, feel free to reopen it once you have any additional feedback.
