### ISSUE TITLE
[NEED ASSIST] Documentation for SwiftUI

### ISSUE THREAD

**Issue by kesavaj** [Adyen/adyen-ios#333]
**Describe the challenge**
-- Can you guys update the readme with steps for invoking drop in component using SwiftUI.
What steps did you take?
-- Tried deciphering the SwiftUI example but the code isn't straight forward. Definitely need a guide to explain more

**Documentation update (optional)**
-- the main readme doesnt have any explanation regarding this.

**Comment by mohammedDehairy** [comment]
Hi @kesavaj ,

 The whole trick lies in a custom View Modifier provided by the SDK that would present any UIViewController  modally in swiftUI apps like this:

```
struct ContentView: View {

@ObservedObject var viewModel = PaymentsViewModel()

internal var body: some View {
        Text("Hello world")
        .present(viewController: $viewModel.viewControllerToPresent)
    }
}

class PaymentsViewModel: ObservableObject, Identifiable {
 @Published internal var viewControllerToPresent: UIViewController?
}
```

 When you want to present dropIn you instantiate `DropInComponent` like you would using UIKit in your viewModel, then you set `dropInComponent.viewController` to the `viewModle.viewControllerToPresent` to present it and set it to `nil` to dismiss.
