### ISSUE TITLE
NOT NAVIGATING VIPPS APP

### ISSUE THREAD

**Issue by Cemoo** [Adyen/adyen-ios#339]
I am try to use "Vipps" from my native iOS app but not navigating the vipps app from payment methods page. Safari opens and gives invalid address error. I tried all return url combinations. Here is my request:

{
    "email":"my mail",
    "paymentMethod": {
        "type": "vipps"
    },
    "returnUrl":"com.myapp.xxx://"
}

Can you help with that? We are so struggled.

Thanks

**Comment by mohammedDehairy** [comment]
Hi @Cemoo ,

 Thanks for your message.

 Thats because we get an `https` redirect url, then the `https` link redirects to `vippsmt://`, but then safari can't handle custom scheme url.

 This seems like a problem on the backend side for sending such a redirect, we'll investigate and get back to you.

**Comment by Cemoo** [comment]
I downloaded Vipps test app from testflight, tried again. Now we have issue like attached ss. When we pressed previous button, it can navigate the vipps. 

Can you help about that?

![IMG_43EB9CC71A67-1](https://user-images.githubusercontent.com/5932810/104452306-e25a2e80-55b3-11eb-978e-266e4682d678.jpeg)

**Comment by mohammedDehairy** [comment]
Hi @Cemoo ,

 The `payments/` endpoint redirect action should have a `vippsmt://`  custom scheme url directly instead of a https link.

 Our backend team is looking into it, it looks like a backend issue, we'll keep you posted.

**Comment by Cemoo** [comment]
So the issue is on your side @mohammedDehairy ?

**Comment by mohammedDehairy** [comment]
@Cemoo , it probably is a backend issue on adyen side, its also possible that it can be solved by enabling an account data property in adyen customer area, but we're still investigating, so no definitive answer yet.

**Comment by descorp** [comment]
@Cemoo 

Seems like you was able to resolve the problem?

**Comment by mohammedDehairy** [comment]
Hi @Cemoo ,

I can confirm, there is a problem on the backend, and we're on it.

Thanks for reporting the issue.

**Comment by Cemoo** [comment]
Hi 

@descorp i didnt solve anything yet. Waiting for the news from @mohammedDehairy

**Comment by descorp** [comment]
Sorry @Cemoo 

From a screenshot you have provided in this thread it looks like a Safari app.
But on a screenshot in the other thread #346 It in-app browser.
I got the impression that the issue is resolved somehow

**Comment by Cemoo** [comment]
But two issues arw different @descorp. How can you think that it is resolved i didnt understand. In the second issue I couldnt detect redirection from vippsmt app

**Comment by descorp** [comment]
You are right, it was my mistake  😅

**Comment by Cemoo** [comment]
Also adyen repo changed, there was a example about using adyen framework. It is not exist now.

**Comment by descorp** [comment]
@Cemoo 

Indeed, we have moved all examples in [Demo](https://github.com/Adyen/adyen-ios/tree/develop/Demo) folder.

**Comment by descorp** [comment]
Hey @Cemoo 

We are doing a research on the issue.
Could you share the URL you received in `Redirect Action` response and psp reference, if you have?
