### ISSUE TITLE
[BUG] AwaitComponent localization not working

### ISSUE THREAD

**Issue by lpetka** [Adyen/adyen-ios#340]
**Describe the bug**
Localization of the AwaitComponent is not working properly (always displays message with default locale) because localizationParameters variable is not passed to created viewModel in handle method of the AwaitComponent.

**Expected behavior**
Properly localized component.

**Smartphone (please complete the following information):**
 - Device: Simulator iPhone 12
 - OS: iOS 14.3

**Comment by mohammedDehairy** [comment]
Hi @lpetka ,

 Thanks for reaching out and reporting this. 

 Thats indeed a bug, we're gonna fix it as soon as possible.

Mohamed

**Comment by mohammedDehairy** [comment]
@lpetka ,

`3.8.3` is released with a fix for this bug, can you please confirm its working as expected?.

Mohamed

**Comment by mohammedDehairy** [comment]
@lpetka ,

 I am gonna close this ticket, please feel free to reopen it if you still have the same problem.
