### ISSUE TITLE
didFail(with error: Error, from component: PaymentComponent)

### ISSUE THREAD

**Issue by bukira** [Adyen/adyen-ios#345]
**Describe the bug**
When I try to make a payment with new card or saved card it falls into the
didFail(with error: Error, from component: PaymentComponent)
function with the error
localizedTitle: "Http 404 error", localizedDescription: "Http 404 error"

**To Reproduce**

**Expected behavior**
goes into
 didSubmit(_ data: PaymentComponentData, from component: PaymentComponent)

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: 14
 - SDK Version 3.8.3

**Additional context**

**Comment by bukira** [comment]
APIError(status: Optional(404), errorCode: "404", errorMessage: "Http 404 error", type: Adyen.APIErrorType.urlError)

**Comment by mohammedDehairy** [comment]
Hi @bukira ,

Thanks for reaching out.

 Can you enable debugging `AdyenLogging.isEnabled = true`, try again  and send back the Xcode logs when submitting a payment?.

Mohamed

**Comment by bukira** [comment]
---- Request (/checkoutshopper/v1/clientKeys/10001|FCD46BDF7906638E7811F0E9FA4330DB6EA83772DB69B9529B5D587ECB5FCA0C184C209BD81271457A8CE1AF14734F6390A2A24496CA797482B33CB55CA950CC7128E878E1C66348BD2154020AC61C010ACE19B16DB2DDD8EFE524AA54157E8CC0EE6753F277DCFAD98BDF4AB917970A6B6AE2E6E15980134C185F14FE8C331E3E8AA92D48735E82F770F963138AAE4D9253BE930B3829C31EB64D45A69DE2F393EB69AB402ED94427A19AB5C2E377E2FC1C40F752872B0A379E0C5552EB253F7E67AA0C59B9514EB6DC88DD49A161B08EAEB15AA9D92011267B6BE4C7FCBA27184DF94610C9C703B95B802AAF5DD8FF681116660F59E419E510163A350E289D) ----
{

}
---- Response Headers (//checkoutshopper/v1/clientKeys/10001|FCD46BDF7906638E7811F0E9FA4330DB6EA83772DB69B9529B5D587ECB5FCA0C184C209BD81271457A8CE1AF14734F6390A2A24496CA797482B33CB55CA950CC7128E878E1C66348BD2154020AC61C010ACE19B16DB2DDD8EFE524AA54157E8CC0EE6753F277DCFAD98BDF4AB917970A6B6AE2E6E15980134C185F14FE8C331E3E8AA92D48735E82F770F963138AAE4D9253BE930B3829C31EB64D45A69DE2F393EB69AB402ED94427A19AB5C2E377E2FC1C40F752872B0A379E0C5552EB253F7E67AA0C59B9514EB6DC88DD49A161B08EAEB15AA9D92011267B6BE4C7FCBA27184DF94610C9C703B95B802AAF5DD8FF681116660F59E419E510163A350E289D) ----
[AnyHashable("Date"): Wed, 20 Jan 2021 11:57:05 GMT, AnyHashable("Server"): Apache, AnyHashable("Connection"): Keep-Alive, AnyHashable("Set-Cookie"): JSESSIONID=065B1FFAD5625723CC3DF041CD19A311.test4e; Max-Age=432000; Expires=Mon, 25-Jan-2021 11:57:05 GMT; Secure; HttpOnly; SameSite=None, AnyHashable("Keep-Alive"): timeout=15, max=100, AnyHashable("pspReference"): 8516111438257541, AnyHashable("Content-Type"): application/json;charset=utf-8, AnyHashable("Transfer-Encoding"): Identity]
---- Response (/Optional("/checkoutshopper/v1/clientKeys/10001|FCD46BDF7906638E7811F0E9FA4330DB6EA83772DB69B9529B5D587ECB5FCA0C184C209BD81271457A8CE1AF14734F6390A2A24496CA797482B33CB55CA950CC7128E878E1C66348BD2154020AC61C010ACE19B16DB2DDD8EFE524AA54157E8CC0EE6753F277DCFAD98BDF4AB917970A6B6AE2E6E15980134C185F14FE8C331E3E8AA92D48735E82F770F963138AAE4D9253BE930B3829C31EB64D45A69DE2F393EB69AB402ED94427A19AB5C2E377E2FC1C40F752872B0A379E0C5552EB253F7E67AA0C59B9514EB6DC88DD49A161B08EAEB15AA9D92011267B6BE4C7FCBA27184DF94610C9C703B95B802AAF5DD8FF681116660F59E419E510163A350E289D")) ----

---- Request (/checkoutshopper/v1/clientKeys/10001|FCD46BDF7906638E7811F0E9FA4330DB6EA83772DB69B9529B5D587ECB5FCA0C184C209BD81271457A8CE1AF14734F6390A2A24496CA797482B33CB55CA950CC7128E878E1C66348BD2154020AC61C010ACE19B16DB2DDD8EFE524AA54157E8CC0EE6753F277DCFAD98BDF4AB917970A6B6AE2E6E15980134C185F14FE8C331E3E8AA92D48735E82F770F963138AAE4D9253BE930B3829C31EB64D45A69DE2F393EB69AB402ED94427A19AB5C2E377E2FC1C40F752872B0A379E0C5552EB253F7E67AA0C59B9514EB6DC88DD49A161B08EAEB15AA9D92011267B6BE4C7FCBA27184DF94610C9C703B95B802AAF5DD8FF681116660F59E419E510163A350E289D) ----
{

}
---- Response Headers (//checkoutshopper/v1/clientKeys/10001|FCD46BDF7906638E7811F0E9FA4330DB6EA83772DB69B9529B5D587ECB5FCA0C184C209BD81271457A8CE1AF14734F6390A2A24496CA797482B33CB55CA950CC7128E878E1C66348BD2154020AC61C010ACE19B16DB2DDD8EFE524AA54157E8CC0EE6753F277DCFAD98BDF4AB917970A6B6AE2E6E15980134C185F14FE8C331E3E8AA92D48735E82F770F963138AAE4D9253BE930B3829C31EB64D45A69DE2F393EB69AB402ED94427A19AB5C2E377E2FC1C40F752872B0A379E0C5552EB253F7E67AA0C59B9514EB6DC88DD49A161B08EAEB15AA9D92011267B6BE4C7FCBA27184DF94610C9C703B95B802AAF5DD8FF681116660F59E419E510163A350E289D) ----
[AnyHashable("Date"): Wed, 20 Jan 2021 11:57:05 GMT, AnyHashable("pspReference"): 8516111438257558, AnyHashable("Set-Cookie"): JSESSIONID=065B1FFAD5625723CC3DF041CD19A311.test4e; Max-Age=432000; Expires=Mon, 25-Jan-2021 11:57:05 GMT; Secure; HttpOnly; SameSite=None, AnyHashable("Content-Type"): application/json;charset=utf-8, AnyHashable("Keep-Alive"): timeout=15, max=99, AnyHashable("Transfer-Encoding"): Identity, AnyHashable("Server"): Apache, AnyHashable("Connection"): Keep-Alive]
---- Response (/Optional("/checkoutshopper/v1/clientKeys/10001|FCD46BDF7906638E7811F0E9FA4330DB6EA83772DB69B9529B5D587ECB5FCA0C184C209BD81271457A8CE1AF14734F6390A2A24496CA797482B33CB55CA950CC7128E878E1C66348BD2154020AC61C010ACE19B16DB2DDD8EFE524AA54157E8CC0EE6753F277DCFAD98BDF4AB917970A6B6AE2E6E15980134C185F14FE8C331E3E8AA92D48735E82F770F963138AAE4D9253BE930B3829C31EB64D45A69DE2F393EB69AB402ED94427A19AB5C2E377E2FC1C40F752872B0A379E0C5552EB253F7E67AA0C59B9514EB6DC88DD49A161B08EAEB15AA9D92011267B6BE4C7FCBA27184DF94610C9C703B95B802AAF5DD8FF681116660F59E419E510163A350E289D")) ----

GError(localizedTitle: "Http 404 error", localizedDescription: "Http 404 error", code: 0)
APIError(status: Optional(404), errorCode: "404", errorMessage: "Http 404 error", type: Adyen.APIErrorType.urlError)
---- Request (/checkoutshopper/v1/clientKeys/10001|FCD46BDF7906638E7811F0E9FA4330DB6EA83772DB69B9529B5D587ECB5FCA0C184C209BD81271457A8CE1AF14734F6390A2A24496CA797482B33CB55CA950CC7128E878E1C66348BD2154020AC61C010ACE19B16DB2DDD8EFE524AA54157E8CC0EE6753F277DCFAD98BDF4AB917970A6B6AE2E6E15980134C185F14FE8C331E3E8AA92D48735E82F770F963138AAE4D9253BE930B3829C31EB64D45A69DE2F393EB69AB402ED94427A19AB5C2E377E2FC1C40F752872B0A379E0C5552EB253F7E67AA0C59B9514EB6DC88DD49A161B08EAEB15AA9D92011267B6BE4C7FCBA27184DF94610C9C703B95B802AAF5DD8FF681116660F59E419E510163A350E289D) ----
{

}
---- Response Headers (//checkoutshopper/v1/clientKeys/10001|FCD46BDF7906638E7811F0E9FA4330DB6EA83772DB69B9529B5D587ECB5FCA0C184C209BD81271457A8CE1AF14734F6390A2A24496CA797482B33CB55CA950CC7128E878E1C66348BD2154020AC61C010ACE19B16DB2DDD8EFE524AA54157E8CC0EE6753F277DCFAD98BDF4AB917970A6B6AE2E6E15980134C185F14FE8C331E3E8AA92D48735E82F770F963138AAE4D9253BE930B3829C31EB64D45A69DE2F393EB69AB402ED94427A19AB5C2E377E2FC1C40F752872B0A379E0C5552EB253F7E67AA0C59B9514EB6DC88DD49A161B08EAEB15AA9D92011267B6BE4C7FCBA27184DF94610C9C703B95B802AAF5DD8FF681116660F59E419E510163A350E289D) ----
[AnyHashable("Connection"): Keep-Alive, AnyHashable("Server"): Apache, AnyHashable("Transfer-Encoding"): Identity, AnyHashable("Keep-Alive"): timeout=15, max=100, AnyHashable("Content-Type"): application/json;charset=utf-8, AnyHashable("pspReference"): 8516111438257566, AnyHashable("Set-Cookie"): JSESSIONID=065B1FFAD5625723CC3DF041CD19A311.test4e; Max-Age=432000; Expires=Mon, 25-Jan-2021 11:57:05 GMT; Secure; HttpOnly; SameSite=None, AnyHashable("Date"): Wed, 20 Jan 2021 11:57:05 GMT]
---- Response (/Optional("/checkoutshopper/v1/clientKeys/10001|FCD46BDF7906638E7811F0E9FA4330DB6EA83772DB69B9529B5D587ECB5FCA0C184C209BD81271457A8CE1AF14734F6390A2A24496CA797482B33CB55CA950CC7128E878E1C66348BD2154020AC61C010ACE19B16DB2DDD8EFE524AA54157E8CC0EE6753F277DCFAD98BDF4AB917970A6B6AE2E6E15980134C185F14FE8C331E3E8AA92D48735E82F770F963138AAE4D9253BE930B3829C31EB64D45A69DE2F393EB69AB402ED94427A19AB5C2E377E2FC1C40F752872B0A379E0C5552EB253F7E67AA0C59B9514EB6DC88DD49A161B08EAEB15AA9D92011267B6BE4C7FCBA27184DF94610C9C703B95B802AAF5DD8FF681116660F59E419E510163A350E289D")) ----

---- Request (/checkoutshopper/v1/clientKeys/10001|FCD46BDF7906638E7811F0E9FA4330DB6EA83772DB69B9529B5D587ECB5FCA0C184C209BD81271457A8CE1AF14734F6390A2A24496CA797482B33CB55CA950CC7128E878E1C66348BD2154020AC61C010ACE19B16DB2DDD8EFE524AA54157E8CC0EE6753F277DCFAD98BDF4AB917970A6B6AE2E6E15980134C185F14FE8C331E3E8AA92D48735E82F770F963138AAE4D9253BE930B3829C31EB64D45A69DE2F393EB69AB402ED94427A19AB5C2E377E2FC1C40F752872B0A379E0C5552EB253F7E67AA0C59B9514EB6DC88DD49A161B08EAEB15AA9D92011267B6BE4C7FCBA27184DF94610C9C703B95B802AAF5DD8FF681116660F59E419E510163A350E289D) ----
{

}
---- Response Headers (//checkoutshopper/v1/clientKeys/10001|FCD46BDF7906638E7811F0E9FA4330DB6EA83772DB69B9529B5D587ECB5FCA0C184C209BD81271457A8CE1AF14734F6390A2A24496CA797482B33CB55CA950CC7128E878E1C66348BD2154020AC61C010ACE19B16DB2DDD8EFE524AA54157E8CC0EE6753F277DCFAD98BDF4AB917970A6B6AE2E6E15980134C185F14FE8C331E3E8AA92D48735E82F770F963138AAE4D9253BE930B3829C31EB64D45A69DE2F393EB69AB402ED94427A19AB5C2E377E2FC1C40F752872B0A379E0C5552EB253F7E67AA0C59B9514EB6DC88DD49A161B08EAEB15AA9D92011267B6BE4C7FCBA27184DF94610C9C703B95B802AAF5DD8FF681116660F59E419E510163A350E289D) ----
[AnyHashable("Set-Cookie"): JSESSIONID=065B1FFAD5625723CC3DF041CD19A311.test4e; Max-Age=432000; Expires=Mon, 25-Jan-2021 11:57:05 GMT; Secure; HttpOnly; SameSite=None, AnyHashable("pspReference"): 8516111438257574, AnyHashable("Content-Type"): application/json;charset=utf-8, AnyHashable("Connection"): Keep-Alive, AnyHashable("Keep-Alive"): timeout=15, max=99, AnyHashable("Transfer-Encoding"): Identity, AnyHashable("Date"): Wed, 20 Jan 2021 11:57:05 GMT, AnyHashable("Server"): Apache]
---- Response (/Optional("/checkoutshopper/v1/clientKeys/10001|FCD46BDF7906638E7811F0E9FA4330DB6EA83772DB69B9529B5D587ECB5FCA0C184C209BD81271457A8CE1AF14734F6390A2A24496CA797482B33CB55CA950CC7128E878E1C66348BD2154020AC61C010ACE19B16DB2DDD8EFE524AA54157E8CC0EE6753F277DCFAD98BDF4AB917970A6B6AE2E6E15980134C185F14FE8C331E3E8AA92D48735E82F770F963138AAE4D9253BE930B3829C31EB64D45A69DE2F393EB69AB402ED94427A19AB5C2E377E2FC1C40F752872B0A379E0C5552EB253F7E67AA0C59B9514EB6DC88DD49A161B08EAEB15AA9D92011267B6BE4C7FCBA27184DF94610C9C703B95B802AAF5DD8FF681116660F59E419E510163A350E289D")) ----

**Comment by mohammedDehairy** [comment]
Hi @bukira ,

I see you're setting the card public key as if its a client key, that's why you get the 404 error response.

this is card public key that you're setting 

```
10001|FCD46BDF7906638E7811F0E9FA4330DB6EA83772DB69B9529B5D587ECB5FCA0C184C209BD81271457A8CE1AF14734F6390A2A24496CA797482B33CB55CA950CC7128E878E1C66348BD2154020AC61C010ACE19B16DB2DDD8EFE524AA54157E8CC0EE6753F277DCFAD98BDF4AB917970A6B6AE2E6E15980134C185F14FE8C331E3E8AA92D48735E82F770F963138AAE4D9253BE930B3829C31EB64D45A69DE2F393EB69AB402ED94427A19AB5C2E377E2FC1C40F752872B0A379E0C5552EB253F7E67AA0C59B9514EB6DC88DD49A161B08EAEB15AA9D92011267B6BE4C7FCBA27184DF94610C9C703B95B802AAF5DD8FF681116660F59E419E510163A350E289D
```

you have two options:

1. Either supply the card public key (not recommended), like this:

```
let config = PaymentMethodsConfiguration()
config.card.publicKey = "10001|FCD46BDF7906638E7811F0E9FA4330DB6EA83772DB69B9529B5D587ECB5FCA0C184C209BD81271457A8CE1AF14734F6390A2A24496CA797482B33CB55CA950CC7128E878E1C66348BD2154020AC61C010ACE19B16DB2DDD8EFE524AA54157E8CC0EE6753F277DCFAD98BDF4AB917970A6B6AE2E6E15980134C185F14FE8C331E3E8AA92D48735E82F770F963138AAE4D9253BE930B3829C31EB64D45A69DE2F393EB69AB402ED94427A19AB5C2E377E2FC1C40F752872B0A379E0C5552EB253F7E67AA0C59B9514EB6DC88DD49A161B08EAEB15AA9D92011267B6BE4C7FCBA27184DF94610C9C703B95B802AAF5DD8FF681116660F59E419E510163A350E289D"
```

2. Or supply the clientKey (recommended), like this:

```
let config = PaymentMethodsConfiguration()
config.clientKey = "{client_key}"
```

see [this link](https://docs.adyen.com/user-management/client-side-authentication ) for more info regarding the client key nd how to get it.

**Comment by bukira** [comment]
Ok, has this changed recently? As my code hasn’t changed since last June and it worked before and currently works with our live app using the pre spm version of the sdk

**Comment by mohammedDehairy** [comment]
Hi @bukira ,

Nothing changed recently, setting the card public key as if its client key is impossible to work, never did, clientKey and card public key are two different kind of keys with completely different format and structure.

**Comment by bukira** [comment]
I see that the public key was deprecated, that's what has caused the issue as it replace the code with the clientKey

**Comment by bhattal** [comment]
@mohammedDehairy Hey, I am facing the same issue but I am getting http 500 error response in Ayden 4.10.3. I am also using the client key but still its fails after submit all card details on pay button click. Can you please help me out if you know anything.
