### ISSUE TITLE
Build failing on xcode for archives

### ISSUE THREAD

**Issue by RominHalltari** [Adyen/adyen-ios#352]
Hello! I am using the latest version of the library and when I need to make an archive, the build fails with the following error. Any idea how to solve this?

![image](https://user-images.githubusercontent.com/16745534/106042779-cb502c00-60dd-11eb-9d9b-9c18c350e171.png)

**Comment by mohammedDehairy** [comment]
Hi @RominHalltari ,

Thanks for reaching out.

 This seems like a code signing error, can you try [this solution](https://stackoverflow.com/questions/24023639/xcode-command-usr-bin-codesign-failed-with-exit-code-1-errsecinternalcomponen)?

**Comment by descorp** [comment]
Hey @RominHalltari 

Were you able to resolve the problem?

In our experience .framework not always work as expected with Adyen3DS (e.x. in case of Carthage)
You can also try attaching [Adyen3DS2.xcframework](https://github.com/Adyen/adyen-3ds2-ios/tree/master/XCFramework/Dynamic/Adyen3DS2.xcframework)

**Comment by descorp** [comment]
I am going to close this ticket due to the lack of activity.
Please, feel free to reopen it once you have any additional feedback.
