### ISSUE TITLE
Credit Card Payment Http 404 Error

### ISSUE THREAD

**Issue by Cemoo** [Adyen/adyen-ios#357]
Hi again,  I am here for new issue :)

![Screen Shot 2021-02-06 at 22 17 13](https://user-images.githubusercontent.com/5932810/107127720-12ea6b00-68c9-11eb-9fa6-c57e162b20ec.png)

I am filling the credit card infos like above (from test card infos.) and I got http 404 error immediately like below. It is firing didFail event. 

![Screen Shot 2021-02-06 at 22 15 41](https://user-images.githubusercontent.com/5932810/107127736-30b7d000-68c9-11eb-94a8-815d91510b0f.png)

![Screen Shot 2021-02-06 at 22 15 34](https://user-images.githubusercontent.com/5932810/107127744-39100b00-68c9-11eb-93a1-c600a2bc21af.png)

Can you help me about that please?

Thanks.

**Comment by Cemoo** [comment]
By the way I am using vipps with same configuration. You would remember my other issues about that.

**Comment by descorp** [comment]
Hey @Cemoo 

could you share the URL, full request and response?
Also a PSP reference (should be in Headers) if you have one?

**Comment by Cemoo** [comment]
Hi @descorp 

I am not sending any request directly. Just pressing pay button. I think Adyen sending request from framework itself.

**Comment by descorp** [comment]
Hey @Cemoo 

Could you check your client key?
For a proper functioning the CardComponent require a clientKey ( looks like `test_XXXX.....X`, `beta_XXXX.....X` or 'live_XXXX....X' depending on selected environment), CardComponent is trying to reach our servers to get an encryption key and if clientKey is wrong - it returns 404.

**Comment by descorp** [comment]
DropInComponent uses all other components under the hood. Did you provide a `clientKey` to an instance of a DropInComponent?

**Comment by Cemoo** [comment]
Ok I ll let you know after i have tried.

**Comment by Cemoo** [comment]
Hi @descorp 

I am sharing the configuration of DropInComponent. As you see we are providing the client key.

![Screen Shot 2021-02-10 at 22 22 23](https://user-images.githubusercontent.com/5932810/107560483-7688d700-6bee-11eb-8b13-cd8f25a19b2d.png)

**Comment by descorp** [comment]
Hey @Cemoo 

Your setup looks good. I am only wandering about assigning `leftBarButtonItem, but this is another topic :D
Does your client key looks like "test_####" ?

Did you try enabling debug logs? It should print HTTP logs in Xcode console.

**Comment by Cemoo** [comment]
Yeah ok I ll debug it. "leftBarButtonItem" was the line from your demo in github actually :)

**Comment by Cemoo** [comment]
By the way https://github.com/Adyen/adyen-ios/blob/develop/Demo/Common/PaymentsController.swift#L85-L100 url you mentioned above giving 404 error. @descorp

**Comment by Cemoo** [comment]
@descorp  actually doesn't need to debug it, I know the client key and it doesn't start with  "test", it starts with a number. It should be start with test?

**Comment by descorp** [comment]
Yes, it should start with environment name, e.x. **test_870be2854add4f56b86778353010f36c**. For Live it will look like `live_####`
You can [get one in your Adyen Customer Area](https://docs.adyen.com/development-resources/client-side-authentication#get-your-client-key).

> it starts with a number

Something like "100001|#####" ? This is a "public encryption key" - it is used on direct API calls.
404 error could be a result of misplacing those two keys.

**Comment by descorp** [comment]
> By the way https://github.com/Adyen/adyen-ios/blob/develop/Demo/Common/PaymentsController.swift#L85-L100 url you mentioned above giving 404 error. @descorp

Sorry for this. We constantly evolving our demo code and it could be troublesome to follow all this updates 😅
We split Demo sample into [Components Integration](https://github.com/Adyen/adyen-ios/blob/develop/Demo/Common/IntegrationExampleComponents.swift) and [DropIn Integration](https://github.com/Adyen/adyen-ios/blob/develop/Demo/Common/IntegrationExampleDropIn.swift) just yesterday.

In general, I would suggest to use demo examples for a specific version you are using. You can use git tags on `master` branch.

> Yeah ok I ll debug it. "leftBarButtonItem" was the line from your demo in GitHub actually :) @descorp

In latest versions of DropIn it is not needed, since DropInComponent.viewController does not expose NavigationBar on UI.

**Comment by Cemoo** [comment]
Thanks @descorp, so our live client key is wrong too. I ll handle that. I have another question actually. 

<img width="861" alt="Screen Shot 2021-02-12 at 15 15 51" src="https://user-images.githubusercontent.com/5932810/107766864-3425de00-6d45-11eb-8c4e-b91057de4299.png">

For above code, We handle the submitting from "didSubmit" event where in credit card info page,  when pressed pay button or navigation vipps app. So how can I understand selected payment method here? I have to get info about it is vipps or credit card button. How can I do that?

Thanks.

**Comment by descorp** [comment]
Hey @Cemoo 

I will move this to [Another issue](https://github.com/Adyen/adyen-ios/issues/363) if you don't mind :)

**Comment by Cemoo** [comment]
Ok @descorp  no problem, thanks for your help on this issue 👍
