### ISSUE TITLE
DropIn: get selected payment method

### ISSUE THREAD

**Issue by descorp** [Adyen/adyen-ios#363]
<img width="861" alt="Screen Shot 2021-02-12 at 15 15 51" src="https://user-images.githubusercontent.com/5932810/107766864-3425de00-6d45-11eb-8c4e-b91057de4299.png">

For above code, We handle the submitting from "didSubmit" event where in credit card info page,  when pressed pay button or when navigating to vipps app. So how can I understand selected payment method here? I have to get info about it is vipps or credit card button. How can I do that?

Thanks.

_Originally posted by @Cemoo in https://github.com/Adyen/adyen-ios/issues/357#issuecomment-778162699_

**Comment by descorp** [comment]
Hey @Cemoo

There is no directly way on DropIn integration to tell what payment method was used.
I can only suggest to look into content of a `PaymentComponentData` on `didSubmit`, however it is not necessary mean that payment started/processing. For some payment methods calling `didSubmit` only indicate the beginning of series of challenges / steps.

> I have to get info about it is vipps or credit card button. 

It is not encouraged for a shopper privacy.
Why do you need to know this?

In general, you always receive `/payments/details` response at the end of the payment with `resultCode` and `additionalData`.
You can use it for accounting on the backend.

**Comment by Cemoo** [comment]
Hi @descorp 

In our payment flow, client app is not talking with directly, I am getting response from our backend and backend talking with Adyen. Our response model is a little bit different for vipps and credit card, because of that I have to change decoding response model for different payment methods.  Then if there is no way to detect with payment method selected, I ll try to handle it on my side. I ll let you know from here that last state about that. Thanks for now.

**Comment by descorp** [comment]
I see..
Let us know if there is something you need help with!

Would you like to keep this thread open for a while?

**Comment by Cemoo** [comment]
Yes it is better to stay open. I ll close if I can solve the problem.

**Comment by Cemoo** [comment]
@descorp  I handled the vipps and credit card differences but what about 3d payment and not 3d payment? How can i detect the differences?

**Comment by descorp** [comment]
Hey @Cemoo 

> 3d payment and not 3d payment

There is a way to [pre-check](https://docs.adyen.com/api-explorer/#/BinLookup/v50/post/get3dsAvailability) whether 3D Secure is available for the specified BIN or card brand, however it is not going to tell you with 100% if it **WILL** happen .

It is not straightforward [how is it determined whether 3DS is triggered](https://www.adyen.help/hc/en-us/articles/360015995059), but all the magic happens after you submitted an encrypted card data via `payment` request.
You will only determine when it responds with 3DSAction (for 3ds2), RedirectAction (for 3ds1), or simple success/failure response.

**Comment by descorp** [comment]
Hey @Cemoo 

How is it going? Do you still need help with selected payment methods?
Is there something we can do to make it easier for you?

**Comment by Cemoo** [comment]
Hey @descorp 

Thanks for asking how are you too? No we can close the issue now, sorry I forgot to close it :(

**Comment by descorp** [comment]
@Cemoo 

It is good to know you were able to resolve the issue :)

All good!
We are currently working on a v4 major version of SDK, which allow us to do some public API changes:

I was thinking about how we can make it easier to detect selected payment methods on DropIn.
What do you think about [this PR](https://github.com/Adyen/adyen-ios/pull/381), will this be helpful for you?

**Comment by Cemoo** [comment]
Hi @descorp  

That is great news and that was required feature I think. Good job! This can be helpful I think I can check when I ll start to work on it again.

**Comment by descorp** [comment]
Always happy to help :)
This changes will be publicly available in v4 approximately next week.

**Comment by Cemoo** [comment]
Yeah I ll try it in first chance I have :)

**Comment by descorp** [comment]
I am going to close this ticket for now.
Changes released as BETA v4.
Feel free to reopen or continue here if you have feedback!

Thanks again to participating in our SDK improvement 💚

**Comment by Cemoo** [comment]
👍

**Comment by Cemoo** [comment]
I am not working on the project we used Adyen nowadays so I don't know know :)

**Comment by descorp** [comment]
oh, sorry.. well, till next time then! :D
