### ISSUE TITLE
How to set language or locale for the Drop-In?

### ISSUE THREAD

**Issue by Cattari** [Adyen/adyen-ios#365]
Guys, your own translations are great. But how do I change language for the Drop-in?
On Android it's done easily via builder. But here I can't see any way to set language during initialization, for example.

We don't need the IPhone's language but instead we want to force drop in to use the selected in-app language by the user.

Any assistance will be just great.
Thanks!

P.S. We use React Native.

**Comment by descorp** [comment]
Hi @Cattari 

It is possible: you need to provide a `LocalizationParameter` to DropInComponent, with specific `tableName`.
The `tableName` is a name of a specific **.string** file in your app's bundle.

**Comment by Cattari** [comment]
Thank you very much, @descorp!

But can we use your files?
Copy-paste to our strings will look ugly

**Comment by descorp** [comment]
No, unfortunetly.
You have to use **unique** files for tableName: 

> For the solution proposed to work, you need a different file for every supported language with a name other than `Localizable.strings`, since `Localizable.strings` is the default name the system uses when the user switches device language.

**Comment by descorp** [comment]
Thanks for letting us know!
In this case I will close the ticket :)
Feel free to continue here or reopen if feel necessary.
