### ISSUE TITLE
UIColorHelpers should use internal extension for UIColor convenience init

### ISSUE THREAD

**Issue by Haokun-Chen** [Adyen/adyen-ios#368]
**Is your feature request related to a problem? Please describe.**
When I import Adyen iOS SDK I notice we have a `Ambiguous use` compile error, because we also write our public extension to UIColor with the same init signature. This happen when I import Adyen in one file, and all the other files that has usage of this init `convenience init(hex: UInt)` have this compile error, **even though I didn't import Adyen in those files**

**Describe the solution you'd like**
Can we make this extension to UIColor internal? or somehow encapsulated by Adyen package?

**Describe alternatives you've considered**
manually modify the source code whenever I download Adyen iOS SDK or manually exclude unused source files when integrating the SDK

**Additional context**

**Comment by descorp** [comment]
Hi @Haokun-Chen 

Thanks for a feedback!
We will resolve the ambiguity it in v4.

**Comment by descorp** [comment]
Hey @Haokun-Chen 

Thanks again for contribution!
I hope [this PR](https://github.com/Adyen/adyen-ios/pull/371) will do the trick for you.

I am going to close this ticket for now, feel free to continue in this thread if you have any additional feedback.
