### ISSUE TITLE
SPM Warning

### ISSUE THREAD

**Issue by iKorich** [Adyen/adyen-ios#369]
**Describe the bug**
`
Showing All Messages
resource 'Localizable.strings' in target 'Adyen' is missing the default localization 'en-US'; the default localization is used as a fallback when no other localization matches

`

**To Reproduce**
1. Add Adyen via SPM
2. Build
3. See warning

**Expected behavior**
no warnings

**Smartphone (please complete the following information):**
 - Device: any
 - OS: 14.4
 - SDK Version 3.8.3

**Comment by mohammedDehairy** [comment]
Hi @iKorich ,

Thanks for reaching out.

Please refer to [this comment](https://github.com/Adyen/adyen-ios/issues/146#issuecomment-733570453).

```
we have tested the fallback whenever the device language is one which is not supported by the SDK, so localization and fallback to en-US works fine, but this warning is till persisting for some reason, but don't think its harmful in any way.
```

**Comment by MattCheetham** [comment]
Just wanted to voice that this one bothers me too. Currently the only warning in our project. Do we know if this is an Xcode bug we can file with Apple or is it something the framework is doing wrong?

**Comment by descorp** [comment]
Hey @MattCheetham 

Unfortunately, we have no solid conclusion if this is an Xcode bug or just our SDK doing something wrong.
We know that localization is working as expected; this is just a warning, not a blocker.

We will investigate further on how to bypass the warning...
Any information that can shed light on it is welcome :)

**Comment by descorp** [comment]
Thanks to @MattCheetham for solving this!

I am going to close this ticket for now. It is available on develop and will be publicly released in v4 beta this week.
Feel free to reopen if you still have the issue.
