### ISSUE TITLE
passing paymentSession base64 string to responseHandler in requestPaymentSession function does nothing

### ISSUE THREAD

**Issue by Farbod909** [Adyen/adyen-ios#37]
Hello.

I am using version 2.0 and when I implement the ```requestPaymentSession``` function as part of ```CheckoutControllerDelegate```, I am able to successfully receive a JSON object from the demo server that looks something like:
```
{
  "paymentSession": "eyJjaGVja2...E5OEI1In0="
}
```
However, when I pass the base64 encoded string ```"eyJjaGVja2...E5OEI1In0="``` as an argument for ```responseHandler``` nothing happens and the UI just remains in a forever loading position. Am I missing something? I am certain that the delegate is able to decode the base64 string properly because I checked it using the Xcode debugger. However, the UI remains in a loading position. Thank you for reading.

**Comment by diegomarcon** [comment]
Hi @Farbod909,

Can you check if you're retaining a reference to `CheckoutController` and to your delegate?
Seems like something is being deallocated.

Kind Regards,
Diego

**Comment by Farbod909** [comment]
Ah, you were right. I was not retaining a reference to ```CheckoutController```.

I solved the problem by adding the following property to my view controller:
```Swift
var checkoutController: CheckoutController? = nil
```

and setting its value when a button is clicked (or any other event) as follows:
```Swift
checkoutController = CheckoutController(presentingViewController: self, delegate: self)
checkoutController?.start()
```

My apologies, I was having difficulty migrating my implementation of the checkout SDK using version 2.0 since the documentation on adyen.com hasn't been updated yet. Thanks a lot for the help!

Best,
Farbod

**Comment by diegomarcon** [comment]
You're welcome and thanks for your feedback on the documentation!
We will work to update it as soon as possible.

Cheers,
