### ISSUE TITLE
How can I pass dynamic currency and country code?

### ISSUE THREAD

**Issue by descorp** [Adyen/adyen-ios#373]
I have setup Currency and country static just for testing to show Apple Pay option, How can I pass dynamic currency and country code? So it works for all the countries where Apple Pay supported...

_Originally posted by @sumitkapoorshineweb in https://github.com/Adyen/adyen-ios/issues/372#issuecomment-783497919_

**Comment by descorp** [comment]
Hey  @sumitkapoorshineweb

There is no "dynamic currency and country code" since any payment has a currency for the amount and country code where the taxes will be paid. You have to determine those based on your business specifics and/or shopper's requirements for each transaction. You can always contact [Adyen Support](https://www.adyen.help/hc/en-us) if you need further guidance.

Adyen API's primary goal is to provide you with the list of most reliable payment methods - any "unmatching" will cause a conversion drop.
The list of available payment methods depends on a currency and country, so it should be the first defense line: if some combination of codes are supported by Adyen - you will receive it in [paymentMethods](https://docs.adyen.com/api-explorer/#/CheckoutService/v66/post/paymentMethods). 

Even thought the list of [Countries and regions that support Apple Pay](https://support.apple.com/en-gb/HT207957) is extensive, Adyen covers all of them. If you feel that something is amiss - please contact [Adyen Support](https://www.adyen.help/hc/en-us)

**Comment by descorp** [comment]
Hey @sumitkapoorshineweb

Was this helpfull? Do you still have any questions?

**Comment by sumitkapoorshineweb** [comment]
yes thanks for help...

**Comment by descorp** [comment]
Nice to know :)
In this case, I will close the ticket, if you don't mind.
Feel free to reopen or continue the discussion in this thread if you have any additional feedback.
