### ISSUE TITLE
I see endless spinning wheel

### ISSUE THREAD

**Issue by georgij** [Adyen/adyen-ios#38]
I retrieve the "paymentSession" string as in the example but I see this for ever:

<img width="365" alt="bildschirmfoto 2018-07-30 um 17 30 28" src="https://user-images.githubusercontent.com/529923/43408134-d0c00cd2-9420-11e8-93fd-de6690c9621c.png">

**Comment by joostvandijk** [comment]
Hi @georgij,

In addition to @Farbod909's comment, can you also check if you're retaining a reference to your `CheckoutController` and your `CheckoutControllerDelegate`?

**Comment by georgij** [comment]
Ah yes, keeping the reference I forgot.
