### ISSUE TITLE
Unit tests failed while having "Ayden" pod

### ISSUE THREAD

**Issue by khawarcareem** [Adyen/adyen-ios#384]
Hi, my unit testing are failing while having "Ayden" pod, i've confirmed it's due to Ayden.
<img width="480" alt="Screenshot 2021-03-03 at 6 19 14 PM" src="https://user-images.githubusercontent.com/73534982/109812007-56789080-7c4d-11eb-8cc5-58c074918b1d.png">

Build is successful but when unit tests starts running it got failed.

**Logs:**
`Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x2

kernel messages:

External Modification Warnings:
Debugger attached to process.

VM Regions Near 0x10e3e7000 (cr2):
    mapped file                 10e3ac000-10e3e7000    [  236K] r--/r-x SM=ALI  Object_id=6a0424eb
--> mapped file                 10e3e7000-10e3e8000    [    4K] r--/r-x SM=PRV  Object_id=731ca6eb
    VM_ALLOCATE (reserved)      10e3e8000-10e3e9000    [    4K] rwx/rwx SM=NUL  reserved VM address space (unallocated)

Application Specific Information:
dyld: in dlopen()
@rpath/Adyen3DS2.framework/Adyen3DS2
CoreSimulator 732.18.6 - Device: iPhone 12 (E3738056-EA8D-4BF7-BAA9-FEC1615D5907) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone 12`

**Comment by mohammedDehairy** [comment]
Hi @khawarcareem ,

Thanks for reaching out!.

Couldn't reproduce it, also no other merchant is complaining about the same issue. But maybe if you give some more info we might help:

- which version of the SDK are you using?.
- Which CocoaPods version are you using?.
- Are you running tests on simulator? in this case is your MacBook the M1 MacBook or an old intel machine?
- Did you try checking `Automatically manage signing` for the test target?.

**Comment by mohammedDehairy** [comment]
I created a new project with unit tests, added `Adyen` pod with CocoaPods, created a test case that calls the 3DS2 SDK, and unit tests run with no problem.

The only potential problem I can think of is this:

```
target 'YOUR_TARGET' do
  use_frameworks!
  pod 'Adyen'

  target 'YOUR_TEST_TARGET' do
        inherit! :search_paths
  end
end
```
Your test target has to inherit the `search_paths` in the pod file.

what I suggest:
- Try importing `Adyen` using Swift Package Manager, and see if the same problem persists.
- Try importing `Adyen` using Carthage, and see if the same problem persists.
- Check if the Dev pod supports Mac catalyst.

**Comment by mohammedDehairy** [comment]
@khawarcareem ,

Any update? did you find the cause of the problem?.

**Comment by khawarcareem** [comment]
@mohammedDehairy Not really, am still trying to solve this. Even i tried to remove "Ayden" pod and Unit tests worked fine, but after installing "Ayden" pod unit tests starts failing with "bootstrap.failure".
![Uploading Screenshot 2021-03-10 at 5.03.06 PM.png…]()

**Comment by descorp** [comment]
Hey @khawarcareem 

Maybe you could to create a small public project on GitHub where we can reproduce this behaviour?
You can copy your current project and simply remove everything unrelated to the issue.

**Comment by descorp** [comment]
Hey @khawarcareem 

How is it going? Any updates?

**Comment by descorp** [comment]
Due to lack of activity I am going to close this issue for now.
Please, feel free to open once you have any additional information.
