### ISSUE TITLE
Drop-in Save Card

### ISSUE THREAD

**Issue by badredaha** [Adyen/adyen-ios#389]
**juste to ask**

How i can handle a button save card (to get boolean value) ?

**Comment by mohammedDehairy** [comment]
Hi @badredaha ,

Are you asking how can you know if the shopper switches on the `Remember for  next time` switch in `CardComponent`?

if yes, then the `PaymentComponentData` instance passed with `DropInComponentDelegate.didSubmit(_ data: from:)` has a boolean `PaymentComponentData.storePaymentMethod` which is true if shopper chooses to save their card info.

**Comment by badredaha** [comment]
thx i will close it
