### ISSUE TITLE
How do I implement CardScanDelegate?

### ISSUE THREAD

**Issue by georgij** [Adyen/adyen-ios#39]
I have added the protocol to my controller  but it keeps saying 'does not conform to protocol':
<img width="1114" alt="bildschirmfoto 2018-07-31 um 12 54 55" src="https://user-images.githubusercontent.com/529923/43455810-65f93134-94c1-11e8-93ca-fb2522eea043.png">

**Comment by joostvandijk** [comment]
Hi @georgij,

From your screenshot it looks like you're only implementing one method. Are you also implementing the second method: `func scanCard(for paymentMethod: PaymentMethod, completion: @escaping CardScanCompletion)`?

**Comment by georgij** [comment]
Sure. It just wanted to show the problem. Here is the other method:
<img width="1126" alt="bildschirmfoto 2018-07-31 um 14 11 33" src="https://user-images.githubusercontent.com/529923/43458825-e318edbc-94cb-11e8-929e-a79fe3eb6753.png">

**Comment by joostvandijk** [comment]
Are you sure you're not redefining `PaymentMethod` locally? Would it work if you change `PaymentMethod` to `Adyen.PaymentMethod` in the signatures of the delegate methods?

**Comment by georgij** [comment]
Thanks, that works. I forgot I have also other PaymentMethod defined in the project.
