### ISSUE TITLE
[BUG] Adyen SDK implicitly exports SwiftUI symbols

### ISSUE THREAD

**Issue by Lukas-Stuehrk** [Adyen/adyen-ios#393]
**Describe the bug**

The Adyen SDK [declares public extensions on SwiftUI symbols](https://github.com/Adyen/adyen-ios/blob/develop/Adyen/UI/SwiftUI/Present%20View%20Controller/ViewControllerPresenter.swift#L12). Unfortunately, this implicitly exports those symbols when you import anything from the Adyen SDK.

Then, if you import the Adyen SDK in a project which doesn't use SwiftUI, but already declares a `View` symbol, Swift tries to add the extensions from the Adyen SDK to the wrong `View`.

**To Reproduce**

1. Create a simple iOS application, e.g. by using Xcode project template.
2. Set the deployment target to iOS 12.
2. Add a protocol that declares a `View` protocol, e.g.
    ````swift
     protocol View {
         associatedtype Body : View
         var body: Self.Body { get }
     }

    extension Never : View {
        typealias Body = Never
    }

    extension View where Body == Never {
        var body: Never {
            fatalError()
        }
    }
     ````
3. Add the Adyen SDK via Cocoapods. The project will no longer compile.

**Expected behavior**
The project should compile.

This is an open edge case in Swift's module / import system. I'm not sure what's the best way to fix it for your SDK. One option would be to make it possible to opt-in to your SwiftUI extensions, e.g. by moving them into a `Adyen/SwiftUI` subspec or something like that. Or a compile time flag.

**Comment by mohammedDehairy** [comment]
Hi @Lukas-Stuehrk ,

Thanks for reaching out.

That's indeed very weird, because the our extension declaration has `@available(iOS 13.0, *)` attribute, also wrapped inside `#if canImport(SwiftUI) && canImport(Combine)` compiler flag.

Can you share what the compile error says?.

**Comment by Lukas-Stuehrk** [comment]
Sorry, I forgot to mention that you need to import the Adyen SDK as an additional step. See a minimal example at https://github.com/Lukas-Stuehrk/AdyenCompileExample

![Screenshot 2021-03-11 at 11 15 48](https://user-images.githubusercontent.com/245433/110771765-2a679b80-825b-11eb-9c63-ca756110251a.png)

**Comment by mohammedDehairy** [comment]
yeah, I added Adyen, but didn't make the `View` protocol like you shared.

and I indeed move the SwiftUI helpers to its own module and the error went away.

We can fix this in version 4, by maybe moving the SwiftUI helper to its own module like you suggested.

Can you some how work around it until we release version 4? because making a new module is a breaking change for other merchants using this SwiftUI helper, so can't make a hot fix release with this change.

**Comment by mohammedDehairy** [comment]
this worked for me:

```
protocol View {
    associatedtype Body : View
    var body: Self.Body { get }
}

extension Never : View {
   typealias Body = Never

    var body: Never {
        fatalError()
    }
}

extension UIView: View {
    typealias Body = Never
}

extension View where Body == Never {
   var body: Never {
       fatalError()
   }
}
```

**Comment by Lukas-Stuehrk** [comment]
No worries, we don't need a hotfix release and can wait for version 4. We simply forked the library and removed the SwiftUI extensions in https://github.com/Adyen/adyen-ios/blob/develop/Adyen/UI/SwiftUI/Present%20View%20Controller/ViewControllerPresenter.swift, as we are not using the SwiftUI part. This works for now and then we will upgrade to V4 when it is available.

**Comment by mohammedDehairy** [comment]
does the work around posted above work?.

because if it can be fixed with a simple work around, then moving a single file to a whole other module is sort of an overkill for a very edgy case.

**Comment by mohammedDehairy** [comment]
I moved the SwiftUI file to a new module in [this pull request](https://github.com/Adyen/adyen-ios/pull/395), let me know if the work around above works for you:

```
protocol View {
    associatedtype Body : View
    var body: Self.Body { get }
}

extension Never : View {
   typealias Body = Never

    var body: Never {
        fatalError()
    }
}

extension UIView: View {
    typealias Body = Never
}

extension View where Body == Never {
   var body: Never {
       fatalError()
   }
}
```

**Comment by descorp** [comment]
Stable v4 with new module structure is released.

Due to a lack of activity, going to close this ticket.
Please feel free to reopen or continue any further discussions.
