### ISSUE TITLE
Can't build project after converting to newer swift syntax

### ISSUE THREAD

**Issue by borglind** [Adyen/adyen-ios#4]
When opening a Xcode 8.2.1 projet - which apparently don't support Swift 2 - with the current Adyen iOS SDK, i get this:

> The target "Adyen" contains source code developed with an earlier version of Swift.
> 
> Choose "Convert" to update the source code in this project to the latest SDKs. You will be given the choice to use Swift 2.3 syntes or update to Swift 3.
> 
> This action can be performed later using "Convert to Current Swift Syntax" in the Edit menu.

I wen't ahead and clicked "Convert", as it was all it would let me do (could not compile without), but now i get four Swift Compiler Errors:

1) `/Pods/Adyen/Adyen/Core/InputDetail.swift:108:40: Same-type requirement makes generic parameter 'Element' non-generic
`
2) `/Pods/Adyen/Adyen/Plugins/Cards/CardFormViewController.swift:256:51: Value of tuple type '(String?, String?, String?)' (aka '(Optional<String>, Optional<String>, Optional<String>)') has no member 'number'`

3) `/Pods/Adyen/Adyen/Plugins/Cards/CardFormViewController.swift:257:51: Value of tuple type '(String?, String?, String?)' (aka '(Optional<String>, Optional<String>, Optional<String>)') has no member 'expiryDate'`

4) `/Pods/Adyen/Adyen/Plugins/Cards/CardFormViewController.swift:258:51: Value of tuple type '(String?, String?, String?)' (aka '(Optional<String>, Optional<String>, Optional<String>)') has no member 'cvc'`

Honestly they seem like pretty easy things to fix, but i have zero experience with Swift, and i don't know if fixing these four things will just lead to more compiler errors.

Any ideas how to fix this, and is there any plans on updating to a newer version of Swift in the future?

**Comment by joostvandijk** [comment]
Hi @borglind,

The Adyen iOS SDK is written in Swift 3 (and there's also a Swift 4 branch available). I don't exactly understand why Xcode thinks our SDK is written in an older version of Xcode, but it might help to upgrade your Xcode to the latest version (8.3.3).

If that doesn't help, could you please provide us with the following information:
1. In what version of Swift is used by the integrating project?
2. How did you add the Adyen iOS SDK to your project?

Thanks,
Joost

**Comment by borglind** [comment]
Thanks for the super quick reply!

I've updated everything, and i still get the "The target 'Adyen' contains source code developed with an earlier version of Swift." And i converted it - _but_ it actually worked, and it at least i can build my project :)

**Comment by joostvandijk** [comment]
I'm glad it's working, but you shouldn't have to convert our pod before being able to use it.

Could you check if you're running the latest version of CocoaPods? You can print the current version by running `pod --version`.  The latest version of CocoaPods is 1.3.1. If your installation is (much) older than that, try [updating CocoaPods](https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods). Then, remove the `Pods` folder from your project and run `pod install` again.

**Comment by borglind** [comment]
updated pod from 1.2 to the latest version - and it worked!

Thanks a ton :)

**Comment by joostvandijk** [comment]
I'm glad that resolved the issue! Feel free to contact us again if you happen to run into any other issues.
