### ISSUE TITLE
SwiftPackages does not show AdyenSwiftUI as an option. 

### ISSUE THREAD

**Issue by carlosdelamora** [Adyen/adyen-ios#404]
**Describe the challenge**
I am adding the a swift package using the repository URL, `https://github.com/Adyen/adyen-ios`, with specific version 3.8.4. 
The documentation says that "`AdyenSwiftUI` module needs to be explicitly added to use the SwiftUI specific helpers."
But `AdyenSwiftUI` module does not appear as an option as is shown in the screenshots attached to this ticket. 

Note: I do not know if this is relevant, but I am using a Mac M1.

**Screenshots**
<img width="726" alt="Screen Shot 2021-03-13 at 6 18 29 PM" src="https://user-images.githubusercontent.com/16446741/111053518-11611500-842a-11eb-9ba3-550ea9c1eee1.png">
<img width="729" alt="Screen Shot 2021-03-13 at 6 18 10 PM" src="https://user-images.githubusercontent.com/16446741/111053519-145c0580-842a-11eb-92d0-375c12fa2fd1.png">

**Comment by mohammedDehairy** [comment]
@carlosdelamora ,

Thanks for reaching out.

The README file you're referring to is on `develop` branch where active development is going on, and contains work that's not released yet.

So please refer to the README file on `master` branch to get the latest release (`3.8.4`) README file.

Sorry for the confusion!.

**Comment by descorp** [comment]
Hey @carlosdelamora 

I assume the issue was resolved? Can we close the ticket?
