### ISSUE TITLE
[NEED ASSIST] Configure CTA button title in DropIn

### ISSUE THREAD

**Issue by gscalzo** [Adyen/adyen-ios#416]
**Describe the challenge**
For a feature I'm implementing, I'd like to change the title of the payment button in the DropIn.
It's for a subscription, and instead of the `Confirm preauthorisation`, I'd like to have something like `Subscribe now`.
There is any way to do it?
I tried to look at the code, but it looks like the title is localised from the `.strings` file.

Any plan to add this feature?
Thanks

**Comment by mohammedDehairy** [comment]
@gscalzo ,

Thanks for reaching out.

You can provide your own `.strings` file in your app bundle, and override any of the keys in the SDK, for example to override the card component submit button title you add this to your own `.strings` file:

```
"adyen.submitButton" = "Subscribe now";
```

and the SDK will give priority to strings defined in the main app bundle over the strings defined inside the SDK.

**Comment by gscalzo** [comment]
fantastic! Thank you very much
