### ISSUE TITLE
PCI SAQ A Compliance if using react-native library

### ISSUE THREAD

**Issue by badoet** [Adyen/adyen-ios#42]
Would like to check if we built a react-native wrapper around your library
like what this library: https://github.com/tipsi/tipsi-stripe did for stripe
will we still qualify under PCI SAQ A compliance?
and is it possible to share with me why?

**Comment by joostvandijk** [comment]
Hi @badoet,

I see you have already gotten an answer on the same question for the Android SDK. Let me know if there's anything else.

Kind regards,
Joost
