### ISSUE TITLE
Capture feature

### ISSUE THREAD

**Issue by tlupo** [Adyen/adyen-ios#43]
Hello ! 

I would like to use your iOS / Android SDK on my mobile application (with the default UI elements) and I would like to know if it’s possible to use the « Capture » feature ? (https://docs.adyen.com/api-explorer/#/Payment/v30/capture)

On my mobile application, a user initiates a payment session and I need to have a pre-authorization to be sure that this user can pay the requested amount but this amount is temporary and it is the maximum amount that can be charged (the user asks for a max amount of 30€ for instance but the final amount could be 29€). 

I’ve seen the « Capture » section on your API documentation to « capture a smaller amount » but I don’t know how it works with iOS/Android SDK because it seems to work with a defined/fixed amount and a « from start to finish » process.

Best regards,
Thomas

**Comment by joostvandijk** [comment]
Hi @tlupo,

I'm sorry for the delayed response. If you set Capture Delay to manual in the Merchant Settings of your Customer Area, the amount will not be captured automatically. More information about this is available [here](https://docs.adyen.com/developers/payments-lifecycle/payment-capture). You can then use the mentioned [/capture](url
https://docs.adyen.com/api-explorer/#/Payment/v30/capture) endpoint to capture the payment.

Let me know if this answers your question.

Kind regards,

Joost van Dijk

**Comment by tlupo** [comment]
Hi @joostvandijk ,

Thank you very much for your answer. I will try to set this setting to authorize an amount on the mobile side and then, use the /capture endpoint after my process to capture the correct amount. I will give you some feedback. Thank you again.

Kind regards,
Thomas
