### ISSUE TITLE
Fix misleadingly invisible Checkout Demo Server when COM has not been selected

### ISSUE THREAD

**Issue by kornerr** [Adyen/adyen-ios#44]
Hi.

I can't get basic instructions to work: https://docs.adyen.com/developers/checkout/ios-sdk/quick-start-ios/show-payment-form-ios

`func checkoutViewController(_ controller: CheckoutViewController, didFinishWith result: PaymentRequestResult)` always has `error(Adyen.Error.unexpectedData)` in `result`.

I use `TbmaTestCOM` account.

Thanks.

**Comment by kornerr** [comment]
Looks like I got confused by the presense of both `TbmaTest` and `TbmaTestCOM` entities. Not sure how different those are. I had to use `Checkout Demo Server` api key that is only visible when you switch to `TbmaTestCOM`.

Totally misleading. You should fix it.

**Comment by joostvandijk** [comment]
Hi @kornerr,

Thanks for your feedback. We've forwarded it to the Customer Area team which is responsible for this behaviour.

Kind regards,

Joost
