### ISSUE TITLE
Issue with Codable/Decodable classes

### ISSUE THREAD

**Issue by yogita1071** [Adyen/adyen-ios#444]
In my project, Request and Response are inherited from CustomEncodable/CustomDecodable classes.
But in Adyen SDK, PaymentMethods,Actions classes are inherited from Encodable/Decodable classes.

Do i need to modify PaymentMethods,Actions classes to CustomEncodable/CustomDecodable in my project?
for Exp - 

extension PaymentMethods: CustomDecodable {
    static func decode(_ data: Data) -> CustomDecodable? {
        return try? JSONDecoder().decode(PaymentMethods.self, from: data)
    }
}

I am not sure . Please help me.

**Comment by mohammedDehairy** [comment]
Hi @yogita1071 ,

Thanks for reaching out.

I assume `CustomEncodable/CustomDecodable` are your own defined protocols.
I think it should be okay to extend `PaymentMethods/Actions` to implement those custom protocols.

Mohamed

**Comment by yogita1071** [comment]
ok Thanks .
