### ISSUE TITLE
I need help with Adyen integration.

### ISSUE THREAD

**Issue by JeanBarreiros** [Adyen/adyen-ios#45]
It follows iOS below, We want that when it is called a CheckoutController **Screen 1** does not appear and Screen 2 already entering the Credit card.

**Screen 1 (DESIRE THAT SCREEN DOES NOT APPEAR)**
![image](https://user-images.githubusercontent.com/43014224/45116158-52289680-b128-11e8-8782-47c9b752305f.png)

**Screen 2 (APPEARING DIRECTLY THAT)** *Accepting credit card only*
![image](https://user-images.githubusercontent.com/43014224/45116174-594fa480-b128-11e8-9cbf-f1df50aab4fc.png)

**Comment by JeanBarreiros** [comment]
Deployment Target 9.3
Adyen v.1.18.1

**Comment by joostvandijk** [comment]
Hi @JeanBarreiros,

This is not possible with the current version of the SDK. However, we are planning on releasing this functionality soon. This would mean that you would have to upgrade from 1.18.1 to our latest version, which will bring some breaking changes. If you need this functionality, but are unable to build your own UI, I suggest you look into migrating soon.

Kind regards,

Joost
