### ISSUE TITLE
[BUG?] AdyenCard does not compile in Xcode 12.5 beta and SPM

### ISSUE THREAD

**Issue by kikettas** [Adyen/adyen-ios#450]
**Describe the bug**

After trying to build the project with Xcode 12.5 and using SPM, I got the following error:

<img width="252" alt="image" src="https://user-images.githubusercontent.com/9082270/114050897-f056dd00-988c-11eb-859c-b15a58335295.png">

And I saw that the `Package.swift` file is missing that dependency for `AdyenCard`.

**To Reproduce**
1. Clean Build folder
2. Build-for-testing the project that declares Adyen with SPM and Xcode 12.5

**Expected behavior**
The project compiles.

**Smartphone (please complete the following information):**
 - Device: iPhone 12 (though it does matter)
 - OS: iOS 14.5
 - SDK Version: 3.8.4

**Additional context**

**Comment by mohammedDehairy** [comment]
Hi @kikettas ,

`AdyenCard` is depending on `Adyen3DS2` in [Package.swift](https://github.com/Adyen/adyen-ios/blob/d7cf01ceb569c433f1c8082dae9d5ec2f65bb356/Package.swift#L56).

can you try opening Xcode menu `File` -> `Swift Packages` -> `Update to latest package versions`?. and make sure your Xcode project navigator looks like this:

![Screen Shot 2021-04-08 at 5 31 39 PM](https://user-images.githubusercontent.com/2619933/114054627-5002b780-9890-11eb-99c5-019131656422.png)

you  can also try opening Xcode menu `File` -> `Swift Packages` -> `Reset Package Caches`.

Mohamed

**Comment by kikettas** [comment]
You mean in that specific commit, right? Let me give it a try!

**Comment by kikettas** [comment]
Any news regarding what I mentioned above? ☝️

**Comment by mohammedDehairy** [comment]
Hi @kikettas ,

 I was waiting for your reply actually :-). did you try what I suggested? 

- `File -> Swift Packages -> Update to latest package versions`.
- `File -> Swift Packages -> Reset Package Caches`.

`AdyenCard` is depending on `Adyen3DS2` in [Package.swift](https://github.com/Adyen/adyen-ios/blob/d7cf01ceb569c433f1c8082dae9d5ec2f65bb356/Package.swift#L56) in the commit with the tag `3.8.4`.

And on my machine it works fine with Xcode `12.4`.

<img width="273" alt="Screen Shot 2021-04-15 at 5 45 57 PM" src="https://user-images.githubusercontent.com/2619933/114898613-8e5d2100-9e12-11eb-9c3c-db32c6e15dd9.png">

**Comment by kikettas** [comment]
Hi @mohammedDehairy,

We do have that version and works fine in Xcode 12.4 but it does not in Xcode 12.5, as I mentioned in the issue.

The Package.swift for that version does not hace the dependency inside AdyenCard.

**Comment by mohammedDehairy** [comment]
@kikettas ,

> The Package.swift for that version does not hace the dependency inside AdyenCard.

What do you mean by that? its definitely there, right [here](https://github.com/Adyen/adyen-ios/blob/d7cf01ceb569c433f1c8082dae9d5ec2f65bb356/Package.swift#L56).

> We do have that version and works fine in Xcode 12.4 but it does not in Xcode 12.5, as I mentioned in the issue.

This must be a bug with the 12.5 beta Xcode, beta versions are supposed to be buggy, can you fall back to Xcode 12.4 for now?

**Comment by kikettas** [comment]
@mohammedDehairy,

I should have checked the wrong tag, but it's there in `3.8.4` 👍 

> This must be a bug with the 12.5 beta Xcode, beta versions are supposed to be buggy, can you fall back to Xcode 12.4 for now?

It's the latest beta and it might be released later this week as there's a keynote tomorrow (and iOS 14.5 is currently in beta 8). Tested what you mentioned and we still have the issue.

<img width="134" alt="image" src="https://user-images.githubusercontent.com/9082270/115199000-fcdffe80-a0f2-11eb-8953-9afc4b261b0f.png">

Could it be because now SPM loads the packages dynamically by default?

**Comment by kikettas** [comment]
I have some more deterministic info. If you remove the _DerivedData_ folder and build the project, it will fail. But if you do hit the build button again, it works.

For local builds it should be ok, but it'll fail always in the CI side :(

**Comment by kikettas** [comment]
I opened an issue [here](https://forums.swift.org/t/xcode-12-5-rc-no-such-module-after-removing-deriveddata/47709).

**Comment by mohammedDehairy** [comment]
let's see what would be the replies.

**Comment by descorp** [comment]
Hey @kikettas 

Is this still the issue with Adyen v4 and a stable Xcode?

**Comment by kikettas** [comment]
Hey @descorp!

I migrated from SPM to manual embedding for .xcframeworks to make it work with Xcode 12.5, but I have not tried with the latest version. But yeah, let's close this as it's no longer an issue.
