### ISSUE TITLE
Issue with Adyen Payment

### ISSUE THREAD

**Issue by yogita1071** [Adyen/adyen-ios#454]
I am getting "checker = false",  due to the invalid swift json object.
If i use amount.formatted in bodyParameters, then getting response 400 due to formatted amount value "$15"
Please Help

**Here is my code**

  
        let amount = Adyen.Payment.Amount(value: ConfigurationAdyen.amount.value, currencyCode: 
       ConfigurationAdyen.amount.currencyCode)
        
        let bodyParameters: HTTPBodyParameters = [
            "amount": amount,
            "paymentMethod": paymentComponentData.paymentMethod.dictionaryRepresentation]
        
        let checker = JSONSerialization.isValidJSONObject(bodyParameters)
        
        if checker{
            bodyContent = try? JSONSerialization.data(withJSONObject: bodyParameters)
        } else {
            bodyContent = nil
        }

**Comment by mohammedDehairy** [comment]
Hi @yogita1071 ,

Thanks for reaching out!.

if this is the `payments/` request body you're referring to, then I believe that's the wrong way to include the amount JSON object, please refer to the Checkout API [documentation](https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments__reqParam_amount), `Adyen.Payment.Amount` implements `Encodable` protocol, so you are able to serialize it into JSON, please refer to [Apple docs](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types) for how to serialize and unserialize JSON.

**Comment by yogita1071** [comment]
Oh actually issue is with the Adyen version. 
I am using Adyen 3.1.2 but Adyen.Payment.Amount implements Encodable protocol is in 4.0.0.

**Comment by yogita1071** [comment]
I have different issue after upgrade to 4.0.0 version of Adyen.
Please refer the screenshot.

Error - "Type 'ISACAdyenIntegration' does not conform to protocol 'DropInComponentDelegate'
Do you want to add protocol stubs?"

As i have already added stub. Don't know why i am getting this.
