### ISSUE TITLE
Issue with Swift version

### ISSUE THREAD

**Issue by yasodhar12590** [Adyen/adyen-ios#47]
Hi,

I followed the steps in integration document. When I compile the app Im getting following errors. It could be swift compatibility issue. Im using xcode9.4 and swift4.1. Can someone help me to fix it..

<img width="598" alt="screen shot 2018-10-07 at 8 49 07 pm" src="https://user-images.githubusercontent.com/43932735/46583359-5e7b7880-ca73-11e8-8ebf-7a2fd23b6533.png">

**Comment by joostvandijk** [comment]
Hi @yasodhar12590,

The latest version of the SDK uses Swift 4.2. If you're unable to upgrade to Xcode 10, I would recommend using the previous version of the SDK (2.1.1).

Best,

Joost

**Comment by yasodhar12590** [comment]
2.2.1 gives me SSL error. Im unable to download it using pod.



<img width="934" alt="screen shot 2018-10-09 at 10 43 11 am" src="https://user-images.githubusercontent.com/43932735/46688854-092e9b00-cc1c-11e8-888b-85d6c2fd61d6.png">

**Comment by yasodhar12590** [comment]
Hi @joostvandijk  is there any update on this?

**Comment by joostvandijk** [comment]
Hi @yasodhar12590,

This doesn't look like an Adyen/CocoaPods issue, but more like a connection issue with GitHub. Can you try again?

Joost

**Comment by yasodhar12590** [comment]
Hi @joostvandijk,

SDK 2.2.1 works for me now. SSL issue was on my side. Thank you so much.
