### ISSUE TITLE
Upgrade to 4.0.0 Beta 1 [RedirectComponent not work any more]  

### ISSUE THREAD

**Issue by badredaha** [Adyen/adyen-ios#479]
**Describe the bug**
All works well before  4.0.0-beta.1 version but after migration, the Redirection does not work anymore.

**To Reproduce**
Make a payment with 3DS1 card

**Expected behavior**
Open 3DS 1 WebView 

**Smartphone (please complete the following information):**
 - Device: Simulator iPhone 12 Pro Max 
 - Adyen : 4.0.0 Beta 1
 - Adyen 3DS2 2.2.1

**Additional context**

**Comment by mohammedDehairy** [comment]
Hi @badredaha ,

do you use `RedirectComponent` on its own or through `DropInComponent`?.

if you're using `RedirectComponent` you need to set `RedirectComponent.presentationDelegate` as mentioned in the `MIGRATION.md` file.

**Comment by badredaha** [comment]
Hi @mohammedDehairy 

We use DropInComponent.

**Comment by mohammedDehairy** [comment]
@badredaha 
and what Checkout API version you're using? is it 67+? just to properly debug the issue.

**Comment by badredaha** [comment]
@mohammedDehairy  

We use v51

**Comment by mohammedDehairy** [comment]
@badredaha , for v51 redirect works fine:


https://user-images.githubusercontent.com/2619933/117122695-6c621900-ad96-11eb-9db5-81af40215184.mov

can you share a video, or steps to reproduce it, including the exact test card you're using?.

**Comment by badredaha** [comment]
I will make a video.
 
Before migration to 4.0.0 beta1 all works fine

**Comment by mohammedDehairy** [comment]
Also we just released `4.0.0-beta.2`, maybe check this release if it fixes the problem.

**Comment by badredaha** [comment]
I upgrade to 4.0.0beta2 same things :/

Test card:
4212 3456 7890 1237 03/30 737

**Comment by mohammedDehairy** [comment]
sorry @badredaha , can't reproduce it, can you please share a video?.

 also, do you call `DropInComponent.handle(action)` or do you use the redirect component your self to handle redirect actions?.

**Comment by badredaha** [comment]
i call self.dropInComponent?.handle(action)

**Comment by badredaha** [comment]
## Card used : 

Mastercard | 5212 3456 7890 1234 | JP | 03 | 2030 | 737
-- | -- | -- | -- | -- | --

## What I changed/adapt after migration:

- Remove -> self.dropInComponent?.pay = Payment(amount: Payment.Amount(value: amountDecimal, currencyCode: currencyCode))  Until i implement the new way to show amount
- Add the new **didSubmit** method with PaymentMethod
- Add the clientKey to DropInComponent.PaymentMethodsConfiguration


Find the two videos (3.8.4 and 4.0.0.beta2): 

## 3.8.4 **WORK FINE**
https://user-images.githubusercontent.com/3824662/117280042-82d5a680-ae62-11eb-8b5a-b51637ac57f0.mov


## 4.0.0.beta2 **WEBVIEW NOT WORK ANY MORE**


https://user-images.githubusercontent.com/3824662/117280668-1effad80-ae63-11eb-87f6-4175d44d6ade.mov

**Comment by mohammedDehairy** [comment]
@badredaha , why do you dismiss `DropInComponent` right after the shopper click `Pay`? you should only dismiss it after the `/payments` endpoint return with an action, then call `DropInComponent.handle(action)` if there was an action, if not then you can dismiss it in case payment is successful or failed.

that's the issue, you dismiss `DropInComponent` immediately after clicking pay

**Comment by badredaha** [comment]
@mohammedDehairy and why its work fine with 3.8.4 ? 
i will check that and i will give you feedbacks

**Comment by badredaha** [comment]
@mohammedDehairy yes that work fine. 👍 

If i remember, the reason why i dismiss the DropInComponent right after the shopper click because before 4.0.0 the cancel was clickable and we can't reset the process payment. 

The best way was to dismiss after process payment begin

**Comment by mohammedDehairy** [comment]
@badredaha , indeed the cancel button is not clickable, so no issues any more, right? can I close the issue?

https://user-images.githubusercontent.com/2619933/117288708-12338780-ae6c-11eb-84b4-69bee909fec1.mov

**Comment by badredaha** [comment]
When i call dismiss after dropin.handle(action) the WebView Appear After Disappear ?

**Comment by mohammedDehairy** [comment]
you shouldn't dismiss `DropInComponent` at all except for either payment successful or error or shopper cancels.

**Comment by badredaha** [comment]
Ok Thx 👍
