### ISSUE TITLE
Issue while using checkoutshopper/demoserver/

### ISSUE THREAD

**Issue by aabhishekRavi** [Adyen/adyen-ios#49]
I'm using **https://checkoutshopper-test.adyen.com/checkoutshopper/demoserver/paymentSession** to get payment session. 

Getting Status Code 403 when I'm requesting for /paymentSession with,
Header: [Content-Type and x-demo-server-api-key]
Body: [amount, merchantAccount, reference, channel, token, returnUrl, countryCode, shopperLocale, shopperReference]

**Comment by joostvandijk** [comment]
Are you sure you're using the **Demo Server API Key** (not the regular API Key)?

**Comment by joostvandijk** [comment]
@aabhishekRavi You need to grab the Demo Server API Key, it's on the same page.

**Comment by aabhishekRavi** [comment]
Thanks @joostvandijk 🤓
You can close this.

**Comment by joostvandijk** [comment]
Glad it's resolved! We'll work on making this more clear in the future.
