### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by JustasL** [Adyen/adyen-ios#5]
Any plans to add Carthage support?

**Comment by olutsenko** [comment]
Hello @JustasL,

Sorry for late reply.

We definitely want to add Carthage support. There are some challenges due to SDK's modular architecture. We are looking into this and you'll hear from us once Carthage support is in place.

Regards,
Oleg

**Comment by ihor-vovk-lohika** [comment]
Hello! Don't you want to attach fat binaries (device + simulator arch) to your releases? For those who use Carthage.

**Comment by ihor-vovk-lohika** [comment]
I mean can you attach a fat binary of Adyen (device + simulator arch) to the Assets section of your releases https://github.com/Adyen/adyen-ios/releases before you add Carthage support? So that we don't need to build it from the sources by ourselves.

Thanks,
Ihor

**Comment by diegomarcon** [comment]
Hi @ihor-vovk-lohika, @JustasL 

Carthage support was released in version [2.0.0](https://github.com/Adyen/adyen-ios/releases/tag/2.0.0) 🎉 

Regards,
Diego
