### ISSUE TITLE
[BUG]  `RedirectComponent` calls `didFail(with: ComponentError.cancelled)` prematurely for in-app browser app-switching

### ISSUE THREAD

**Issue by leslieolivier** [Adyen/adyen-ios#502]
**Describe the bug**
For an external app-switch (to e.g. Vipps) the `RedirectComponent` is using the `WebRedirectComponent` to open the action redirect url in an in-app browser (`SFSafariViewController`). The user then gets the choice to open the external app. At the same time the user presses "Open", the `safariViewControllerDidFinish` gets called on the `WebRedirectComponent`. This causes the `RedirectComponent` to call it's delegate with `didFail(with: ComponentError.cancelled)`. Our app assumes this means the payment should be cancelled and release the `RedirectComponent` object, so when the external app sends the return url back after authorization, there is no action component in our app to handle it.

**To Reproduce**
1. Select payment method with in-app browser app-switching (e.g. Vipps)
2. Click on 'Open' in in-app browser to open Vipps.
3. Switch back to main app and see that the in-app browser has been dismissed. 
4. Assuming the main app has released the RedirectComponent object, the Vipps return url has no object to handle it.

**Expected behavior**
I expect `didFail(with: ComponentError.cancelled)` to only get called, if the payment is cancelled (by user or external app).
I also expect the in-app browser to stay open while the external app has not yet returned, so the user can cancel the payment by pressing "Cancel" in the in-app browser toolbar (or elsewhere on the page).

**Smartphone: **
 - Device: iPhoneXs Max, iPad Pro
 - OS: iOS 14.4.1, iOS 14.0.1
 - SDK Version: Adyen iOS 3.8.0

**Comment by descorp** [comment]
Hey @leslieolivier 

Thanks for reaching out.

This is a known behaviour: unfortunately, there is no way to tell if dismission of a SFSafariViewController was a result of user's action or app-to-app redirect in iOS.

This was corrected in 3.8.2 - now app-to-app redirect via SafariVC will falsely trigger `func didCancel(component: PresentableComponent, from dropInComponent: DropInComponent)`, but not `func  didFail(with error: Error, from component: DropInComponent)`.

**Comment by descorp** [comment]
Hey @leslieolivier 

I did some experiments.
This code works nice on RedirectComponent to prevent false delegate call: 

```swift
            DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
                if UIApplication.shared.applicationState == .active {
                    self.delegate?.didFail(with: ComponentError.cancelled, from: self)
                }
            }
```

We will patch this behaviour on v4.

**Comment by leslieolivier** [comment]
Thanks! We will try to use direct issuer links instead for redirects, but it's nice to have a solution, if we still need the in-app browser redirects.

**Comment by leslieolivier** [comment]
Hi again,

I just wondered whether the change you made to `func presentationControllerDidDismiss(_ presentationController: UIPresentationController)` shouldn't also be made to `func safariViewControllerDidFinish(_ controller: SFSafariViewController)`.

I would also propose to make the following change (in both `presentationControllerDidDismiss` and `safariViewControllerDidFinish`) with a call to `didOpenExternalApplication`, if the app is inactive/backgrounded when the `SFSafariViewController` is dismissed. This will enable the app to handle the app switching in the same way as for custom links/universal links (for example by informing the user, that the app is waiting for the external app to return).

This is based on the 3.8.5 version of the SDK:

```
    internal func safariViewControllerDidFinish(_ controller: SFSafariViewController) {
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
            if UIApplication.shared.applicationState == .active {
                self.delegate?.didFail(with: ComponentError.cancelled, from: self)
            }
            else {
                self.delegate?.didOpenExternalApplication(self)
            }
        }
    }
```

**Comment by descorp** [comment]
Hey @leslieolivier 

This is a great idea! Thanks!
I will make a patch for v4.

**Comment by descorp** [comment]
Here is a new [PR](https://github.com/Adyen/adyen-ios/pull/509)

**Comment by descorp** [comment]
BTW, were you able to do similar fix on your side?

**Comment by leslieolivier** [comment]
If I use 0.1s as delay, the `applicationState` is (almost) always `.active`. If I use 0.5s as delay, then sometimes  `applicationState` is still `.active` (this mostly happens, if the external app is not already running). If I use 1.0s as delay, then `applicationState` is never `.active` in my tests (iPhone Xs Max, iOS 14.4.1) and `didOpenExternalApplication` is called every time.

I have not experienced that the `DispatchQueue.main.asyncAfter(deadline: .now() + 0.5)` block did not get executed. In all cases, I either got `didFail` or `didOpenExternalApplication`.

Could the result of your tests be because it seems you only made the changes to `func presentationControllerDidDismiss(_ presentationController: UIPresentationController)` and not also `func safariViewControllerDidFinish(_ controller: SFSafariViewController)`? In my tests, it is always `safariViewControllerDidFinish(_ controller: SFSafariViewController)` that gets called when the user accepts the redirect - never `presentationControllerDidDismiss(_ presentationController: UIPresentationController)` (The original change you proposed should IMHO  be copied to `safariViewControllerDidFinish(_ controller: SFSafariViewController) and maybe removed from `presentationControllerDidDismiss(_ presentationController: UIPresentationController)` as this only seems to get called when it is actually a user VC drag-down dismissal).

It is true that the method might not be 100% reliable and it might also cause some false `didOpenExternalApplication` in edge cases (like user cancelling followed by a quick manual/OS app switch). But it is important for our app, that we can detect the app switching and present a relevant UI to the user, if he returns to our app without having performed anything in the external payment app.

**Comment by descorp** [comment]
Oh, indeed! 
`safariViewControllerDidFinish` is the one called on app-to-app redirect!

**Comment by descorp** [comment]
> If I use 0.5s as delay, then sometimes applicationState is still .active (this mostly happens, if the external app is not already running). 

Are you using it outside of the RedirectComponent, on your app's level?
I wonder what kind of delay this is causing..
I found that `DispatchQueue.main.asyncAfter(deadline: .now() + 0.0002)` works for BrowserComponent just fine on my device 🤔

**Comment by descorp** [comment]
Hey @leslieolivier 

Do you have any additional feedback?

Thanks to you,  the fix on v4 will be released soon :) 
Also I assume that you were able to make a fix locally on v3, right?

**Comment by leslieolivier** [comment]
Hi @descorp 

Thanks, I don't have any additional feedback at the moment.
I have indeed made a similar fix locally on v3 (I preferred not to change the SDK code, so I have implemented a copy of some of the SDK classes, but will remove these when we upgrade to v4).

**Comment by descorp** [comment]
Due to a lack of activity, going to close this ticket.
Please feel free to reopen or continue any further discussions.
