### ISSUE TITLE
[NEED ASSIST] RedirectComponent weird behaviour

### ISSUE THREAD

**Issue by jesus-verse** [Adyen/adyen-ios#504]
**Describe the challenge (optional)**
I don't know why but RedirectComponent is not handling the action if I run the code without breakpoints, but if I put a breakpoint just on RedirectComponent.handle(action) the action is handled properly and webview is showed. It's a very weird behaviour.

Please, could you help me with that ?

**Screenshots**

self.redirectComponent is a class variable.

![Screenshot 2021-05-12 at 10 20 25](https://user-images.githubusercontent.com/52409139/117942730-accc1480-b30b-11eb-9523-fea2cf787d93.png)

**Comment by descorp** [comment]
Hey @jesus-verse 

Thanks for reaching out.

What version of SDK are you using?

**Comment by jesus-verse** [comment]
- Adyen (3.8.3):
    - Adyen/Card (= 3.8.3)
    - Adyen/Core (= 3.8.3)
    - Adyen/DropIn (= 3.8.3)
  - Adyen/Card (3.8.3):
    - Adyen/Core
    - Adyen3DS2 (= 2.2.1)
  - Adyen/Core (3.8.3)
  - Adyen/DropIn (3.8.3):
    - Adyen/Card
    - Adyen/Core
  - Adyen3DS2 (2.2.1)

**Comment by jesus-verse** [comment]
just update to the latest version(3.8.5) and same result

**Comment by descorp** [comment]
Hm.. Could you try delay call of `handle(actionRedirect)` like?

```swift
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            self.redirectComponent.handle(actionRedirect)
        }
 ```
