### ISSUE TITLE
Error: The provided SDK token could not be parsed 

### ISSUE THREAD

**Issue by aabhishekRavi** [Adyen/adyen-ios#51]
Hi, 
I'm getting 'this' response when requesting for /paymentSession using your demoserver under checkoutViewController(_: requiresPaymentDataForToken: completion:) delegate method. 
```json
{
type: "validation"
errorCode:14_012,
errorMessage: "The provided SDK token could not be parsed."
}
```
**Pod**: 
Adyen (1.18.0)
AdyenCSE(1.1.1)

**/paymentSession API Request** : 
POST https://checkoutshopper-test.adyen.com/checkoutshopper/demoserver/paymentSession

**Headers** :
"Content-Type": "application/json",
"x-demo-server-api-key": SDK_KEY

**Body**
let paymentDetails: [String: Any] = [
            "amount": [
                "value": 200,
                "currency": "EUR"
            ],
            "reference": "iOS & M+M Black dress & accessories",
            "countryCode": "NL",
            "shopperLocale": "nl_NL",
            "shopperReference": "shopper@company.com",
            "returnUrl": "objective-c-example://",
            "channel": "ios",
            "token": token
        ]

**Comment by joostvandijk** [comment]
Thanks. Are you using CocoaPods without the use of `use_frameworks!`? This causes the token creation to fail. We suggest using the SDK as a dynamic framework (so with `use_frameworks!` in the Podfile).

**Comment by aabhishekRavi** [comment]
Thanks. Yes, you get it right. 
But, whenever I try to install pods with `use_framework!` then it starts complaining about few files and modules in my project. 
`Could not build module 'ABCD'`
`XYZ file not found`

P.S: Working on Objective-C Project.

**Comment by joostvandijk** [comment]
I see. It's probably because some other pods are not compatible with `use_framework!`. Unfortunately, we don't support the use without `use_frameworks!` right now. It's something we are looking into for newer versions, but it's not being worked on now.

**Comment by aabhishekRavi** [comment]
Thanks for the reply. Is there any alternative approach which I can follow?
I would be great to know if you have any expected deadline for the newer release with this fix?

**Comment by joostvandijk** [comment]
The only thing I can recommend now is to use Carthage for integrating, but you would have to update to version 2 of the SDK. The fix has not been scheduled yet, but when it will be done, it will be for version 2 only.

**Comment by joostvandijk** [comment]
Hi @aabhishekRavi, we're using Xcode 10 with Swift 4.2

**Comment by aabhishekRavi** [comment]
Thanks, @joostvandijk, 
Can you suggest me which release version should I use for iOS 9.0 ~> deployment compatibility?
As I can see the latest release minimum deployment target is iOS 9.3.

**Comment by joostvandijk** [comment]
If you need to support iOS 9.0, the most recent version you can use is 1.18.1

**Comment by aabhishekRavi** [comment]
When I'm trying to update Carthage with `1.18.1`

`
*** Fetching adyen-ios
*** Checking out adyen-ios at "1.18.1"
*** xcodebuild output can be found in /var/folders/37/087l2d3j0pb_qgcph8p0g2vm0000gp/T/carthage-xcodebuild.5CffjM.log
*** Building scheme "Adyen" in Adyen.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/<MY LOCAL PATH>/Carthage/Checkouts/adyen-ios/Adyen.xcworkspace -scheme Adyen -configuration Release -derivedDataPath /Users/<MY_USER_NAME>/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/adyen-ios/1.18.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/37/087l2d3j0pb_qgcph8p0g2vm0000gp/T/adyen-ios SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/USER_NAME/Documents/<PROJECT_NAME>/Carthage/Checkouts/adyen-ios)
`

**Comment by joostvandijk** [comment]
I'm sorry, I forgot to mention that Carthage support was only added in version 2.0. However, that does mean you would have to use CocoaPods, which gets you back to your first issue. As a temporary suggestion, I'd suggest to raise your deployment target to 9.3, given that most of iOS 9.x users are on 9.3 ([source](https://data.apteligent.com/ios/)). However, we'll work on static library support, so you can use the SDK with `use_frameworks!`.

**Comment by aabhishekRavi** [comment]
Thanks for the help @joostvandijk. 
It's better to move to iOS 9.3.
And, you can close this.

**Comment by joostvandijk** [comment]
Great! I will keep this open until we have fixed the static library support. It should arrive soon.

**Comment by aabhishekRavi** [comment]
Hey @joostvandijk , 
I'm facing an issue while integrating `CheckoutViewContoller`.
I can click the `Credit Card `button but, nothing is happening. Ideally, it should navigate me to A`dd Credit Card `view.

<img width="334" alt="screenshot 2018-11-20 at 3 06 23 pm" src="https://user-images.githubusercontent.com/44661944/48764557-f953ad80-ecd5-11e8-9070-1bd43cba3f59.png">

**Comment by joostvandijk** [comment]
Hey,

Can you tell me which integration method you ended up using? Cocoapods without use_frameworks!, or Carthage?

**Comment by aabhishekRavi** [comment]
It's Carthage.

**Comment by joostvandijk** [comment]
Are you embedding all Adyen*.frameworks? Most importantly, Adyen.framework, AdyenInternal.framework and AdyenCard.framework should all be embedded

**Comment by aabhishekRavi** [comment]
Yes, I have embedded following frameworks binaries in , 

1. Adyen
2. AdyenWeChatPay
3. AdyenInternal
4. AdyenOpenInvoice
5. AdyenCard
6. AdyenApplePay
7. AdyenSEPA

**Comment by aabhishekRavi** [comment]
Whenever I taking retrieving `paymentSession` from Adyen Test Server it's working perfectly fine. 
When I switch to my own `paymentSession` which is generated by my server then, it behaves like this.

Is there any way to validate paymentSession authenticity?

**Comment by joostvandijk** [comment]
Could you send the request you make + the response you get to joost.vandijk@adyen.com? I can then take a look to see if something's going wrong there.

**Comment by joostvandijk** [comment]
We have added support for static library usage (so without `use_frameworks!`) in 2.4.0. Make sure to follow [this note](https://github.com/Adyen/adyen-ios/wiki/Using-Adyen-as-a-static-framework) in the wiki to avoid issues.
