### ISSUE TITLE
ApplePay Component cancel issue

### ISSUE THREAD

**Issue by zayar-supers** [Adyen/adyen-ios#517]
I used ApplePayComponent to pop up payment sheet controller and cannot cancel the payment by clicking Cancel button before authenticate the payment. Nothing is happening when I click Cancel button.

Another issue is when I click the upper area of the payment sheet at that time, the payment sheet disappears but the controller is still in view hierarchy when I debug the view hierarchy.

Can I able to check didFail delegate method will be called for the upper scenarios ?
Cause didFail delegate is not called upon my testing. 

Is this possible to happen this kind of issues if I am using the improper client key for the ApplePayComponent ?

The iOS sdk version I used is the latest v3.8.5.

**Comment by descorp** [comment]
Hey @zayar-supers 

Thanks for reaching out!

The `client key` has no effect on  ApplePayComponent.

Quick questions:

1) Do you persist the component?
2) Does `didFail` called when you click 'Cancel' ?
3) Did you try dismissing it manually?

**Comment by zayar-supers** [comment]
@descorp Thanks for your confirmation on client key portion.

The component is not dismiss and `didFail` is not called when I click 'Cancel'.
I did not try to dismiss it manually.

I only try to present component in this code as the sample.

` let payment = Payment(amount: Payment.Amount(value: amt, currencyCode: "SGD"),
                                      countryCode: "SG")
                
                let configuration = ApplePayComponent.Configuration(summaryItems: [PKPaymentSummaryItem(label: “***”, amount: NSDecimalNumber(decimal: amt), type: .final)], merchantIdentifier: “***”)
                
                let applePayComponent = try ApplePayComponent(paymentMethod: paymentMethod, payment: payment, configuration: configuration, cancelHandler: {
                    print("Apple Pay is cancel.")
                }) 
                applePayComponent.clientKey = “***”
                applePayComponent.delegate = self
                applePayComponent.environment = .test
                self.present(applePayComponent.viewController, animated: true)`

**Comment by descorp** [comment]
aha!

there are few things you need to do:

1) persist `applePayComponent` until the payment is finished.

```swift
private var applePayComponent: ApplePayComponent?
```

2) dismiss top viewController (in your case it is `self`) when finished

```swift

    private func finish(with resultCode: PaymentsResponse.ResultCode) {
        let success = resultCode == .authorised || resultCode == .received || resultCode == .pending

        applePayComponent?.stopLoading(withSuccess: success) { [weak self] in
            self?.dismiss {
                // Do success flow
            }
        }
    }

    private func finish(with error: Error) {
        let isCancelled = ((error as? ComponentError) == .cancelled)

        self.dismiss {
            if !isCancelled {
                // Do nothing - user decided not to continue with ApplePay
            } else {
                // Do unsuccess flow
        }
    }

```

**Comment by zayar-supers** [comment]
@descorp Thanks for your sample snippet. My problem was the component did not persist. Now the issue is solved. 🍻
