### ISSUE TITLE
Documentation BCMC mobile

### ISSUE THREAD

**Issue by DriesVS** [Adyen/adyen-ios#52]
Hi,

We are trying to get the iOS SDK to work with BCMC mobile via deeplinks to the BCMC app. We currently only see the Bancontact Card option on the test environment. Are there any docs available to get this to work via a deeplink to the BCMC app?

Dries

**Comment by olutsenko** [comment]
Hi Dries,

BCMC app payment flow is available as a separate payment method (different from Bancontact Card). Please reach out to support@adyen.com so we can enable it for your account.

Regards,
Oleg

**Comment by DriesVS** [comment]
Hi Oleg,

Thanks for getting back to us this quick.

The Bancontact app feature was added successfully to the list of payment methods. We now have Bancontact card and Bancontact app. Bancontact card works fine with the test card numbers found at https://docs.adyen.com/developers/test-cards/test-card-numbers. When I use Bancontact app a web view is opened saying the request is invalid (see the attached screenshot). Is there any additional configuration that needs to be done from our end?

Regards,
Dries

![img_4eebfc6f5b19-1](https://user-images.githubusercontent.com/4460617/49045392-28d05180-f1d1-11e8-9e83-bd07585f5208.jpeg)

**Comment by olutsenko** [comment]
Hi Dries,

It looks like configuration was not set correctly by us. Would you mind contacting support@adyen.com again so they can fix this mistake shortly.

Apologies for the inconvenience.

Regards,
Oleg

**Comment by DriesVS** [comment]
Hi Oleg,

We contacted support, this issue is resolved and can be closed.

Thanks, Dries
