### ISSUE TITLE
[NEED ASSIST] Cannot press cancel if redirect didn't work

### ISSUE THREAD

**Issue by jesperjohansson** [Adyen/adyen-ios#522]
**Describe the challenge**
We have noticed that if you manually open the drop-in app instead of getting redirected back to it, you cannot close the drop-in and you get stuck.

We want to be able to close the drop-in. In the attached video the user decides to not open the drop-in app automatically. But the user can't close the drop-in now because they were not redirected back.

Is there any way to make the cancel button pressable?

**Screenshots**
https://user-images.githubusercontent.com/21033162/120659979-2b3d5180-c487-11eb-9ab1-819b460901f9.mp4

**Comment by descorp** [comment]
Hey @jesperjohansson 

Thanks for reaching out!

What SDK version are you using?
This supposed to be fix in v4.

**Comment by jesperjohansson** [comment]
@descorp Thanks for your reply! We are using `4.0.0-beta.2`. I tried setting `isUserInteractionEnabled = true` on the view that contains the drop-in but it doesn't seem to work. It looks like this is the `guard` that prevents me from pressing cancel:
```
    // DropInComponent.swift
    private func didSelectCancelButton(isRoot: Bool, component: PresentableComponent) {
        guard !paymentInProgress || component is Cancellable else { return }
        
        if isRoot {
            self.delegate?.didFail(with: ComponentError.cancelled, from: self)
        } else {
            navigationController.popViewController(animated: true)
            userDidCancel(component)
        }
    }
```
We have only had this issue with the payment method "Swish" so far, so I was thinking if there is a workaround maybe we can make it cancelable only for Swish

**Comment by descorp** [comment]
Hey @jesperjohansson 

sorry for misunderstanding: it is fixed in current `develop` and will be released on v4 (hopefully within a week), but it is not available on 4.0.0-beta.2.

BTW, how does your `returnURL` looks like?
Is it custom url scheme or universal link?

Another thing: "unfreezing" the UI is not going to resolve the issue with "unknown state" - if the payment completed but user didn't performed redirect back to the app.

**Comment by jesperjohansson** [comment]
@descorp Ah okay! Our `returnURL` is currently:`adyen.io.ancon.leen://io.ancon.leen`. It was previously `adyencheckout://io.ancon.leen` but we had to change it because we had other apps that would open that also had `adyencheckout://x`

**Comment by descorp** [comment]
Interesting.
From my experience BankID never asks if you'd like to be redirected to "my app".
I am wandering it is BankID app's version of iOS version..

To add some level of control, we have added `func didOpenExternalApplication(_ component: DropInComponent)` to [DropInComponentDelegate](https://github.com/Adyen/adyen-ios/blob/develop/AdyenDropIn/DropInComponentDelegate.swift#L58)
It could add some level of control: if user returns to the app and AppDelegate wasn't hit - you can dismiss the DropIn and initiate polling of your backend for payment status.

**Comment by jesperjohansson** [comment]
@descorp Alright, thanks we might do that in the future
