### ISSUE TITLE
I'm building a custom UI for the card payment. How can I know the Card Type? 

### ISSUE THREAD

**Issue by GabrielMassana** [Adyen/adyen-ios#536]
**Describe the challenge**

Our client do not want to use the UI Adyen CardComponent and has requested us to build a custom one.

**Documentation update (optional)**

[The documentation](https://docs.adyen.com/payment-methods/cards/custom-card-integration?tab=i_os_2) is clear on how to validate and encrypt the Card data.

What it is not clear is how to know the Card Type the user is typing.

This is a cool feature you provide on the Drop In and CardComponent. So, while the user types, you are able to detect the type for the card number.

There is no documentation about this, as far as I can see. 

I found out that this can be done with this call:

``` swift
let paymentMethods = [paymentMethods retrieved from v67/paymentMethods]
let type = paymentMethods.adyen.type(forCardNumber: cardNumberString)
```

It is ok to use this function? Is there a better way to do this?

**Comment by mohammedDehairy** [comment]
Hi @GabrielMassana ,

Thanks for reaching out!.

Yes, you can use the mentioned functionality, but please keep in mind that this logic under the hood uses regex's to identify the card brand, but they're not 100% accurate, they more like best effort, so its not recommended to depend on it for critical logic like for example blocking payments or something like that.

**Comment by GabrielMassana** [comment]
Hello,

Thanks for the answer.

It is ok, I just use this function to show the card icon.

I guess those are really good to validate the card values right?

```swift
        let cardValidator = CardNumberValidator()
        let isCardValid = cardValidator.isValid(cardNumber)
        let expiryValidator = CardExpiryDateValidator()
        let isExpiryValid = expiryValidator.isValid(month + year)
        let securityCodeValidator = CardSecurityCodeValidator()
        let isSecurityCodeValid = securityCodeValidator.isValid(cvv)

```

**Comment by mohammedDehairy** [comment]
yes, we use the same validators in our components, so you can use them :-).
