### ISSUE TITLE
Failed to parse payment session response Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0."

### ISSUE THREAD

**Issue by Sanjaypbh** [Adyen/adyen-ios#54]
While integrating adyen in iOS getting error failed to parse payment session response

**Comment by joostvandijk** [comment]
Could you provide a little bit more information? What is the data that you pass in as your payment session?

**Comment by Sanjaypbh** [comment]
@joostvandijk thanks for response i used below code 

func requestPaymentSession(withToken token: String, for checkoutController: CheckoutController, responseHandler: @escaping (String) -> Void) {
        let url = URL(string: "https://checkoutshopper-test.adyen.com/checkoutshopper/demoserver/paymentSession")!
        print(token)
        let parameters: [String: Any] = [
            "amount": [
                "currency": "EUR",
                "value": 17408
            ],
            "channel": "iOS",
            "reference": "2",
            "token": token,
            "returnUrl": "my-shopping-app://",
            "countryCode": "NL",
            "shopperReference": "user349857934"
        ]
        
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.httpBody = try? JSONSerialization.data(withJSONObject: parameters, options: [])
        request.allHTTPHeaderFields = [
            "X-API-Key": "AQEohmfuXNWTK0Qc+iSEgGs0q/2vTYhFIYdOv6Z5+e26jqP59rEl8iQR4RDBXVsNvuR83LVYjEgiTGAH-xOtEatUe4TRcyv60mfAg1p+0uzagPc3ad9tRq/8j1NM=-7bq2e2wT2PdgYFD4", // Replace with your own Checkout Demo API key.
            "Content-Type": "application/json"
        ]
        
        let session = URLSession(configuration: .default)
        session.dataTask(with: request) { data, response, error in
            if let error = error {
                fatalError("Failed to retrieve payment session: \(error)")
            } else if let data = data {
                do {
                    guard let json = try JSONSerialization.jsonObject(with: data, options: .allowFragments) as? [String: Any] else { fatalError() }
                    guard let paymentSession = json["paymentSession"] as? String else { fatalError() }
                        responseHandler(paymentSession)
                } catch {
                    fatalError("Failed to parse payment session response: \(error)")
                }
            }
            }.resume()
    }

**Comment by joostvandijk** [comment]
It looks like you're connecting to the demo server, but not passing your demo server API key. It's a different API key, found under your normal API key. Make sure to also change the header back to `X-Demo-Server-API-Key`.

**Comment by Sanjaypbh** [comment]
@joostvandijk  i have  changed X-API-Key to  X-Demo-Server-API-Key but still have same problem

**Comment by joostvandijk** [comment]
You need to pass in the actual demo server API key. It's found below your regular API key in the Customer Area.

**Comment by joostvandijk** [comment]
Also, please make sure to never post your API key on public places like GitHub. It's supposed to stay secret. I have removed it, but I would recommend rolling the API key to avoid any risk.

**Comment by Sanjaypbh** [comment]
@joostvandijk thanks i will take care about it

**Comment by Sanjaypbh** [comment]
should i follow this link?
https://docs.adyen.com/developers/user-management/how-to-get-the-api-key

**Comment by joostvandijk** [comment]
Yes. After generating an API key, the demo server API key should be on the same page.

**Comment by Sanjaypbh** [comment]
@joostvandijk  thanks for resolve my issue

**Comment by Sanjaypbh** [comment]
@joostvandijk  i need to make CVC/CVV to secure entry in credit card option.

**Comment by joostvandijk** [comment]
@Sanjaypbh This is currently not possible.

**Comment by Sanjaypbh** [comment]
@joostvandijk  ok and Thanks for response

**Comment by Sanjaypbh** [comment]
@joostvandijk  hi can i passed totalAmountToPay = 474.11 for "value" : totalAmountToPay

**Comment by joostvandijk** [comment]
Hi @Sanjaypbh, I don't fully understand your question. Please refer to the documentation on [docs.adyen.com](https://docs.adyen.com/developers/checkout/ios-sdk#step2createpaymentsession) to learn more about the API calls your backend has to make.

**Comment by Sanjaypbh** [comment]
Ok

**Comment by Sanjaypbh** [comment]
@joostvandijk how can i get mspReference

**Comment by joostvandijk** [comment]
@Sanjaypbh You'll get the pspReference when you verify the payment result with our backend: https://docs.adyen.com/developers/checkout/ios-sdk#step3verifypaymentresult
