### ISSUE TITLE
[NEED ASSIST] CC payments with ThreeDS2 action

### ISSUE THREAD

**Issue by Basca** [Adyen/adyen-ios#554]
**Describe the challenge**
Using following setup:
API V67
SDK 4.0.0-beta.2
Drop-in UI

When starting a payment with a CC that requires a 3D Secure 2 authentication using one of the following creditcards:
https://docs.adyen.com/development-resources/test-cards/test-card-numbers#test-3d-secure-2-authentication

We don't get any paymentData back after the 3D secure step, from the delegate method `func didProvide(_ data: ActionComponentData, from component: DropInComponent)` as intentionally disabled as seen here:
https://github.com/Adyen/adyen-ios/commit/6b93cd3a2e04399c2ff58c337632cad662631ed0

However when looking at the API documentation for V67, it clearly states 
>  In v67 and later, you will always get this value from the Component.
https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments/details__reqParam_paymentData

The API and the SDK are now conflicting in requirements, we would like to get things cleared up so we can proceed on the correct way forwards. Please assist/advise.

**Debugger logs**
When ran through demo app, following requests output is given:
```---- Request (/payments/details) ----
{
  "details" : {
    "threeDSResult" : "<result>"
  },
  "paymentData" : null,
  "merchantAccount" : "<merchant>"
}
---- Request Headers (/payments/details) ----
["X-API-Key": "<api key>", "Content-Type": "application/json"]
---- Request query (/payments/details) ----
[:]
---- Response Headers (//v67/payments/details) ----
[AnyHashable("Date"): Tue, 29 Jun 2021 11:50:59 GMT, AnyHashable("Content-Type"): application/json;charset=UTF-8, AnyHashable("Transfer-Encoding"): Identity, AnyHashable("Set-Cookie"): JSESSIONID=<sessionId>; Path=/checkout; Secure; HttpOnly, AnyHashable("Connection"): Keep-Alive, AnyHashable("Keep-Alive"): timeout=15, max=100, AnyHashable("Server"): Apache, AnyHashable("pspReference"): <pspReference>]
---- Response (/payments/details) ----
{
  "refusalReasonCode" : "0",
  "pspReference" : "<pspReference>",
  "resultCode" : "Authorised",
  "merchantReference" : "Test Order Reference - iOS UIHost",
  "additionalData" : {
    "checkoutThreeD.selectedBrand" : "mc",
    "checkoutThreeD.merchantReference" : "Test Order Reference - iOS UIHost"
  }
}
```

**Comment by mohammedDehairy** [comment]
Hi @Basca ,

Thanks for reaching out and pointing out the contradiction.

The API Doc's is the one that's not accurate, we'll update it ASAP.

Indeed with v67 and the new compact 3DS2 flow -with one `/payments/details` call-, no paymentData is needed when calling `/payments/details`, as evident by the fact that the logs posted indicates the payment succeeded with `Authorised`.

sorry for the confusion.

Mohamed

**Comment by descorp** [comment]
Hey @Basca 

Does this answers your question?
Do you need any additional assistance?
