### ISSUE TITLE
Alipay & Redirect Component

### ISSUE THREAD

**Issue by nsimunko** [Adyen/adyen-ios#559]
**Describe the bug**
RedirectComponent doesn't call the `didProvide` delegate method on successful authorization through Alipay web, inside the webview.
The webview just redirects to my API and shows a JSON transaction status response with a `transactionStatus: CAPTURED`.

**To Reproduce**
Initiate a transaction with `"paymentMethod":{"type":"alipay_wap"}`. Change the transaction status to `CAPTURED`, and pass the `action` object from the response to `RedirectComponent.handle()`

**Expected behavior**
On success, `didProvide(data:from:)` delegate method should be called, so I can use the data to finish the transaction and dismiss the component. 

**Screenshots**
| Alipay auth success | After I press "Complete" |
| --- | --- |
| ![IMG_1737](https://user-images.githubusercontent.com/22167575/125070814-c0e88400-e0b8-11eb-93a7-d78b2050b6c0.PNG) | ![IMG_1738](https://user-images.githubusercontent.com/22167575/125070809-bfb75700-e0b8-11eb-9142-95f81e302f0c.PNG) |

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.6
 - SDK Version 3.8.5

**Comment by descorp** [comment]
Hey @nsimunko 

Seems like something went wrong during redirect.

> The webview just redirects to my API

What is your `returnUrl` ?
Was `AppDelegate.application(_ app:, open url:, options:)` triggered?

**Comment by nsimunko** [comment]
I'm sending the same URL as with 3DS1 & 2. It's the registered app URL scheme, but AppDelegate doesn't receive anything. Everything about the transaction and returnUrl is the same as with 3DS1 authorization. The only difference is that I'm updating the transaction status to `CAPTURED` instead of `AUTHORISED`. 

My backend guy is telling me that the transaction passed, but I need the result, to finish authorization on our side, and dismiss the component.

**Comment by nsimunko** [comment]
Here is what the body for creating a transaction looks like:
```JSON
{
  "channel":"iOS",
  "userId":"shopperRef",
  "confirmationPageUrl":"SLPaymentSDK-Example://redirect",
  "paymentMethod": {
    "type":"alipay_wap"
  },
  "basket": {
    "currency":"CNY",
    "shoppingItems": [
      {
        "amount":10000,
        "assortment":"PAYMENT_TEST"
      }]
    }
}
```

This is sent to my backend, which is handling the transactions. The URL is the same as with 3DS flows, which work flawlessly.

**Comment by descorp** [comment]
> My backend guy is telling me that the transaction passed, but I need the result, to finish authorization on our side, and dismiss the component.

Indeed, you need to receive a redirect URL to generate RedirectDetails, that can be used for `payment/details`.

> The webview just redirects to my API

How Alipay can knows your API? Do you provide it somewhere? 🤔

I would like to better understand what is happening on your backend.
Do you have example of request your backend sends to Adyen API?

**Comment by nsimunko** [comment]
@descorp we think that it has something to with Alipay configuration on the backend. Alipay gets a redirect URL for our API, but not for our app. Possibly something to do with different `alipay` methods for the web and for mobile (`alipay_wap`). I'll let you know when do some fixes on our backend.

**Comment by nsimunko** [comment]
@descorp Ok, looks like there was something on our backend, that sent the URL to our api as redirect url, instead of the one I sent it. Something to do with our backend supporting both web & mobile payments. 
It looks good now. Thanks for your assistance. :)

**Comment by descorp** [comment]
Hey @nsimunko 

there is nothing wrong with backend sending the URL to our api as redirect url, as long as it redirects back to mobile :)
Thanks for verifying!
