### ISSUE TITLE
AdyenInternal/Assets/Localization.swift @IBInspectable visibility

### ISSUE THREAD

**Issue by yan-zaitsev** [Adyen/adyen-ios#56]
Hi, we have integrated your framework using CocoaPods into our project and now all xibs has IBInspectable  `localizedAccessibilityLabelKey `, `localizedTextKey `, `localizedPlaceholderKey` properties in IB. It is very annoying and they are in conflict with our own properties.
As IB does not ignore private/internal properties, maybe you could avoid usage of them? (At this moment I didn't found usage in your code)

**Comment by joostvandijk** [comment]
Hi @yan-zaitsev,

Thanks for noticing! We used to use these extensions when we were still using Interface Builder in our project. However, as we don't use them anymore, I've removed them. It should be fixed in the next update. Sorry for the inconvenience.

With kind regards,

Joost

**Comment by joostvandijk** [comment]
Hi @yan-zaitsev,

This issue has been fixed in the latest release (2.6.0).

With kind regards,

Joost
