### ISSUE TITLE
[NEED ASSIST] how to implement custom Native 3DS2 

### ISSUE THREAD

**Issue by GabrielMassana** [Adyen/adyen-ios#560]
**Describe the challenge**
We are building a custom UI for our client.
So, we are not using Adyen Drop In or Components.

I tried to follow your demo app. However, I can not see where the Native 3DS2 screen is instantiated.

How do I implementing Native 3DS2?

This is a sample of the data returned by Adyen, if I'm not wrong this should start a 3DS2 flow, right?

```swift
{
    "resultCode": "IdentifyShopper",
    "authentication": {
        "threeds2.fingerprintToken": "eyJ0aHJl...="
    },
    "details": [
        {
            "key": "threeds2.fingerprint",
            "type": "text"
        }
    ],
    "paymentData": "Ab02b4c0!...=="
}
```

**Documentation update (optional)**
Some helping documentation on this will be nice.
I can only see documentation related to Adyen Drop In and Components

**Screenshots**

**Comment by nsimunko** [comment]
I'm not from Adyen, but as far as I know, you don't make your own 3DS2 screen. 3DS2 Component redirects to the users banking, or card provider app, where authentication is handled.

**Comment by descorp** [comment]
Hey @GabrielMassana 

You can use [ThreeDS2Component.appearanceConfiguration](https://github.com/Adyen/adyen-ios/blob/develop/AdyenActions/Components/3DS2/ThreeDS2Component.swift#L22) for this, but you would have to make a custom instance of `ThreeDS2Component`

**Comment by descorp** [comment]
Hey @GabrielMassana 

Do you need any additional help with ThreeDS2Component customisation?

**Comment by descorp** [comment]
I am going to close this ticket due to the lack of activity.
Feel free to respond or reopen if needed.
