### ISSUE TITLE
[NEED ASSIST] Customize placeholders colors

### ISSUE THREAD

**Issue by digocse** [Adyen/adyen-ios#582]
**Describe the challenge**
I'm trying to have different colors for the credit card, expiry date and CVV placeholders within the textfields of `CardComponent`:
`1234 5678 9012 3456` / `MM/AA` / `3 digits`

What steps did you take?
I've already tried playing around with many attributes but none of them worked. Should it be `hintLabel`? 
One of my trials:

            var cardStyle = FormComponentStyle()
            cardStyle.hintLabel = TextStyle(font: UIFont.preferredFont(forTextStyle: .body), color: UIColor.orange)

or:

            var cardStyle = FormComponentStyle()
            cardStyle.hintLabel.backgroundColor = UIColor.orange
            cardStyle.hintLabel.color = UIColor.orange

What is the expected behavior?
I'd like to have a different colors on the placeholders

**Screenshots**
<img src="https://user-images.githubusercontent.com/22969298/128058481-c2c5cebc-0420-4592-a21b-3317c45929e5.png" width="40%" height="40%">

Appreciate your support!

**Comment by descorp** [comment]
Hey @digocse 

To set placeholder style use 

```swift
var cardStyle = FormComponentStyle()
cardStyle.textField.placeholderText = TextStyle(...)
```

**Comment by descorp** [comment]
Hm... Indeed this is bug from our side.

Thanks for feedback!

**Comment by descorp** [comment]
Here is [PR](https://github.com/Adyen/adyen-ios/pull/584) to fix CVC placeholder customisation

**Comment by digocse** [comment]
Perfect, thanks a lot. Appreciate your effort!

**Comment by descorp** [comment]
Hey @digocse 

v4.1.0 is released, could you verify that it is fixed?

**Comment by descorp** [comment]
I am going to close this ticket for now.
Please feel free to reopen if necessary.
