### ISSUE TITLE
Storing payments information.

### ISSUE THREAD

**Issue by StanleyOned** [Adyen/adyen-ios#59]
Hello,

Right now, I'm trying to figure out how to retrieve/save payments that the user previously used before. I'm using the custom integration project where theirs a **Bool ShouldStoredDetails** but is not being used anywhere is not storing the user's payment method information. Any help would be appreciated!

Thanks!

**Comment by joostvandijk** [comment]
Hi @StanleyOned,

First, you must provide a `shopperReference` to your `/paymentSession` call, and also provide `enableOneClick` as `true`.
Then, when making a payment, set the `PaymentDetail` `storeDetails` to `true`.
Upon the next `/paymentSession` call, when providing the same `shopperReference`, you should receive the stored payment methods.

In the custom integration example, this should be done on line 82 of `PaymentRequestManager.swift`:
method.details.storeDetails?.value = cardDetails?.shouldStoreDetails

Hope this helps!

Joost
