### ISSUE TITLE
Xamarin support

### ISSUE THREAD

**Issue by rodrigueslg** [Adyen/adyen-ios#6]
Is there any plans to do a Xamarin official integration?

I need to implement Adyen in my Xamarin project, and I'm encountering a lot of trouble trying to do this.

I think we may need to change the payment hub because of the poor support, but we already spent a lot of time on this.

**Comment by olutsenko** [comment]
Hello @rodrigueslg,

Xamarin support is not in our roadmap at this moment. For now, we concentrate our efforts on delivering best native experience.

Regards,
Oleg
