### ISSUE TITLE
Accessing stored payment information

### ISSUE THREAD

**Issue by StanleyOned** [Adyen/adyen-ios#60]
Hello Again,

Previously I submitted an issue regarding storing the user payment information. But I ran into another problem, how can I access the store payment information and confirm a purchase with the stored payment information.

**This is what I have right now**
```private func updateCardDetails(paymentMethod: PaymentMethod?) {
        guard let storedDetails = paymentMethod?.storedDetails as? StoredCardPaymentDetails else {
            return
        }
        cardDetails = CardDetails(name: storedDetails.holderName,
                                  number: storedDetails.number,
                                  expiryMonth: String(storedDetails.expiryMonth),
                                  expiryYear: String(storedDetails.expiryYear),
                                  cvc: "737",
                                  shouldStoreDetails: true)
    
    }
```
I cannot send the payment because I only get back the encoded information. Also, the **storedDetails.holderName** doesn't quite match with what I inputted previously which was **John Smith** 
![Screen Shot 2019-03-12 at 4 23 04 PM](https://user-images.githubusercontent.com/6315252/54233394-3fca5380-44e3-11e9-8f8e-6e19a3ce195f.png)

**Comment by joostvandijk** [comment]
Hi @StanleyOned,

To initiate a payment with a stored payment method, simply pass the entire `PaymentMethod` in the [`selectPaymentMethod`](https://adyen.github.io/adyen-ios/Docs/Protocols/PaymentControllerDelegate.html#/s:5Adyen25PaymentControllerDelegateP06selectB6Method4from3for16selectionHandleryAA09SectionedB7MethodsV_AA0bC0CyAA0bF0VctF)'s selection handler.

The `storedDetails` in a stored payment method are simply for display purposes.

If the holder name is incorrect, it's likely not passed to the SDK correctly. If you don't have it yet, add the following to your `/paymentSession` call:
```json
"configuration": {
    "cardHolderName": "required"
}
```

This will make the SDK collect the holder name field.

With kind regards,

Joost

**Comment by StanleyOned** [comment]
Hello @joostvandijk,

I tried passing the stored payment method but it ends up failing in the **didFinish** method.
Heres what I have:
```
func selectPaymentMethod(from paymentMethods: SectionedPaymentMethods, for paymentController: PaymentController, selectionHandler: @escaping (PaymentMethod) -> ()) {
        if !paymentMethods.preferred.isEmpty {
            paymentMethod = paymentMethods.preferred.first
            selectionHandler(paymentMethod!)
            return
        } else {
            paymentMethod = paymentMethods.other.first
        }
        paymentMethodCompletion = selectionHandler
    }
```
Can you please provide details information, if you don't mind.

Thank you!

**Comment by joostvandijk** [comment]
Hi @StanleyOned,

I think you are forgetting to set the payment details. You can check which details are being asked by looking in the payment method's `details`.

Note that for stored cards, you still need to ask the user to enter the CVC.

With kind regards,

Joost

**Comment by StanleyOned** [comment]
@joostvandijk I figured it out!
Thank you for helping me!

**Comment by joostvandijk** [comment]
No problem! Feel free to contact us afain if you have any questions.
