### ISSUE TITLE
Does this SDK support 3DS?

### ISSUE THREAD

**Issue by drewpitchford** [Adyen/adyen-ios#61]
What the title says. Does this repo support 3DSv2?

Thanks!

**Comment by joostvandijk** [comment]
Hi @drewpitchford,

This SDK does support 3D-Secure 2.0. It contains an integration with our [3D-Secure 2.0 SDK](https://github.com/Adyen/adyen-3ds2-ios).

Be aware that this is currently for testing purposes only. A version that is ready for the live environment will be released soon.

Kind regards,

Joost

**Comment by drewpitchford** [comment]
Can we use Adyen's SDK code with our 3DS Server or are we required to use Adyen's 3DS Server for the SDK to work?

**Comment by joostvandijk** [comment]
Hi @drewpitchford,

Could you explain the usecase for this? Are you using Adyen for the authorisation, but a different 3DS Server for authentication?

**Comment by drewpitchford** [comment]
@joostvandijk Yes, using a different 3DS Server for authentication.... can we use a separate authentication flow outside of Adyen (using Adyen's SDK)? Just asking with respect to the authenticaiton flow only... not authorisation. Thanks.

**Comment by joostvandijk** [comment]
Yes, it's possible, but you do have to provide the SDK with the directory server ID and public key. Normally, you would receive these from our 3DS Server, but if you are using a different one, these values might not be available.

**Comment by drewpitchford** [comment]
Thanks. One more question, how are you handling encryption/decryption within the iOS SDK? Is it a native or other type of solution?

**Comment by joostvandijk** [comment]
All of the cryptographic functionality is natively implemented.

**Comment by drewpitchford** [comment]
Is it open sourced? We’d like to verify the cryptography ourselves.

**Comment by joostvandijk** [comment]
The 3DS SDK is not open source unfortunately, as this is not allowed by the EMVCo specification. However, the SDK will also go through the PCI certification, which will certify the implementation of the cryptographic functionality.
