### ISSUE TITLE
[BUG] [Adyen3DS2 v2.2.3  &  Adyen v3.6.0] - ThreeDS2Component.swift:57:75: 'nil' is not compatible with expected argument type 'String'

### ISSUE THREAD

**Issue by mohadian** [Adyen/adyen-ios#612]
**Describe the bug**
We are using `pod 'Adyen', '3.6.0'` in our integration, however, since yesterday we are getting the following compile-time error 

```
Pods/Adyen/AdyenCard/3DS2 Component/ThreeDS2Component.swift:57:75: 'nil' is not compatible with expected argument type 'String'

            let transaction = try service.transaction(withMessageVersion: nil)
```

It seems the following change is not compatible with the version `3.6.0`

https://github.com/Adyen/adyen-ios/blob/develop/Adyen.podspec#L64
```
plugin.dependency 'Adyen3DS2', '2.2.3'
```

As workaround, I have downgraded the 'Adyen3DS2' to '2.2.2' in our Podfile.lock. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - SDK Version [e.g. 3.3.0]

**Additional context**

**Comment by mohammedDehairy** [comment]
Hi @mohadian ,

Thats a side effect that the podspec of `3.6.0` defines the 3DS2 SDK dependency with `>=`, [here](https://github.com/Adyen/adyen-ios/blob/75d73f708d390fb528bc1f03bae1945a4f000936/Adyen.podspec#L48).

and indeed what you did is what I was going to suggest, which is to downgraded the 'Adyen3DS2' to '2.2.2' in the Podfile.

The other way is to upgrade to at least `3.7.0`.

The reason why this build error, is that in 3DS2 SDK starting v `2.2.3`, the  `withMessageVersion` is not optional any more, it has to has a valid value.

There's nothing we can do from our side unfortunately.

Mohamed

**Comment by mohadian** [comment]
Thank you for the update
Since this change breaks 3.6.0, is it possible to update the podspec?

**Comment by mohammedDehairy** [comment]
The pod spec starting from version 3.7.0 hard fixes the 3DS2 SDK dependency version, so if you upgrade to at least 3.7.0, this problem will disappear.

Or downgrade the 3DS2 SDK version to the desired version in the pod file like you mentioned.

BTW, you shouldn't use 3DS2 SDK 2.2.x with components SDK versions below 3.7.0.

3.6.0 should use 2.1.x.

**Comment by mohadian** [comment]
Thanks for the reply. 
I will use 3.7.0+. It would be good if the Adyen library points to specific versions.

**Comment by mohammedDehairy** [comment]
I will close this issue for now, and feel free to reopen it if needed.
