### ISSUE TITLE
[BUG] SDK 3.8.5 - iOS 14.6+ - Payment card FormViewController disappears when entering CVC (probably collapses to 0 height).

### ISSUE THREAD

**Issue by leslieolivier** [Adyen/adyen-ios#614]
Hi,

We have been experiencing a weird bug for some time and have now been able to reproduce it.

On an iOS 14.6+ phone, go to Accessibily settings and enable "Reduce motion" AND enable "Prefer cross-fade transitions".

Open an Adyen payment card omponent (SDK 3.8.5) entry form. When entering CVC code the first 2 digits can be entered, but when entering the 3. digit, the whole form disappears.

I have not been able to debug it with my current version of Xcode as it only supports iOS 14.4, but I suspect that the problem could be in the `keyboardWillChangeFrame` method of `FormViewController` class.

According to some reports on the internet, the last keyboard frame does not have an height and origin (0,0) when the keyboard disappears (as it does when you enter the last CVC digit) while "Prefer cross-fade transitions" is enabled. This would cause the bottomConstraint to be set to -UIScreen.main.bounds.height and this the FormViewController view would get a height of 0 and the form would disappear.

```
    @objc private func keyboardWillChangeFrame(_ notification: NSNotification) {
        guard let keyboardFrame = notification.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? CGRect else { return }
        var heightOffset = keyboardFrame.origin.y - UIScreen.main.bounds.height
        
        if #available(iOS 11.0, *) {
            heightOffset += min(abs(heightOffset), view.safeAreaInsets.bottom)
        }
        
        bottomConstraint?.constant = heightOffset
    }
```

As mentioned, this is just a theory of why the bug happens, but it would be great, if you could release a fix to SDK 3.8.5 as a lot of users apparently have "Prefer cross-fade transitions" enabled. SDK 4.0 might not have the same bug as I can see some of the keyboard handling code has changed, but we are not yet ready to migrate to 4.0.

Thanks :)

**Comment by mohammedDehairy** [comment]
@leslieolivier ,

Thanks a lot for reporting the bug, and coming up with this theory! nice thinking!.

we'll investigate first if the bug happens in v 4.0.0.

and we'll consider releasing `3.8.6` to fix it.

**Comment by descorp** [comment]
Hey @leslieolivier 

Thanks for a thorough research!

I have checked on v4 - it works fine.

Do you you have any numbers on how many of your shoppers are effected?
We will look into possible workarounds on v3, but, unfortunately, we can't promise to give a fix a high priority.

**Comment by descorp** [comment]
This PR #652 should fix the issue.
Seems like something is wrong with scrolling offset when motion is reduced 🤔

**Comment by descorp** [comment]
@leslieolivier 

3.8.6 was released, could you verify if it fixes the issue for you?

**Comment by descorp** [comment]
I am going to close this ticket for now. 
Feel free to reopen it if necessary.
