### ISSUE TITLE
Remember for next time toggle

### ISSUE THREAD

**Issue by rumnat** [Adyen/adyen-ios#62]
"Remember for next time toggle" doesn't set latest saved card as default preselected for next payment. It saves a card to the list but always shows only the first saved

**Comment by diegomarcon** [comment]
Hi @rumnat, 

We will work on a fix for the order of the saved payment methods. I'll keep you posted when this change is available.

Thanks for opening the issue!

**Comment by joostvandijk** [comment]
Hi @rumnat,

This issue has been fixed on the backend. It should be available on our test environment now, and will be deployed to our live environment next week. Could you confirm if this works for you?

Thanks,

Joost

**Comment by rumnat** [comment]
it does. Thanks guys good job
