### ISSUE TITLE
[BUG] Show 3DS challenge fails: Message element defined as required is missing from the message

### ISSUE THREAD

**Issue by mohadian** [Adyen/adyen-ios#621]
**Describe the bug**
I am getting an error trying to show challenge:

```
{
	"acsTransID": "b676f6e4-47ef-4359-a070-70f2f9a12953",
	"errorComponent": "C",
	"errorDescription": "Message element defined as required is missing from the message.",
	"messageVersion": "2.1.0",
	"errorMessageType": "CRes",
	"errorCode": "201",
	"errorDetail": "oobContinueLabel",
	"threeDSServerTransID": "4188320e-b3fe-4e92-bbfc-562972c93108",
	"sdkTransID": "1721ade0-88e4-434b-ae19-2b55bb9acf0b",
	"messageType": "Erro"
}
```

**To Reproduce**
Using Adyen DropIn 3.8.0 (of even 3.7.0), when I try to make a payment using Pleo credit card (MC), the DropIn tries to open the 3DS challenge page, it fails with the above error.

In fact, I can see two calls to https://3ds-a.live.ext.prod.enfuce.com

first one
Request: `eyJraWQiOiI2OTdjYWJiNC1kN2YxLTRhZmEtOW....`
Response: `eyJraWQiOiI2OTdjYWJiNC1kN2YxLTR....`

The second one fails with the above error

**Expected behavior**
The SDK should display the 3DS challenge page.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 14.2
 - SDK Version 3.8.0

**Additional context**
We used to use 'Adyen', '3.6.0' version and we used to get a different error
```
{
	"messageType":"Erro"
	,"messageVersion":"2.2.0"
	,"threeDSServerTransID":"7281478a-317b-426f-99fb-d16c9755d0a2"
	,"acsTransID":"b7e90cb8-a2ec-43fa-8e41-bb46d9137cab"
	,"dsTransID":"35d629ac-f230-4d39-8dc6-8a42df60ddf7"
	,"sdkTransID":"f2911aa5-c42d-4b4c-bcbc-5f553598b579"
	,"errorCode":"203"
	,"errorDescription":"Invalid format"
	,"errorDetail":"Field [messageVersion] has a wrong value [2.2.0]"
	,"errorMessageType":"CReq","errorComponent":"A"
}
```

I have to try to upgrade to 3.7.0 and 3.8.0 which result in a different error. (which is mentioned above `Message element defined as required is missing from the message`

To be clear, I just updated the version in the Pod and did not make any modification to the code (3.6.0 -> 3.7.0)

On Friday I managed to make a successful transaction, however today it failed ( no code change )

I have also raised an issue on Android as well 
https://github.com/Adyen/adyen-3ds2-android/issues/38

**Comment by mohammedDehairy** [comment]
Hi @mohadian ,

Thanks for reaching out! :-)

The error with `3.6.0` make sense, because `3.6.0` is not compatible with 3DS2 SDK 2.2.x, it has to work with 2.1.x-rc.x.

And about the error with `3.8.0`:

```
{
	"acsTransID": "b676f6e4-47ef-4359-a070-70f2f9a12953",
	"errorComponent": "C",
	"errorDescription": "Message element defined as required is missing from the message.",
	"messageVersion": "2.1.0",
	"errorMessageType": "CRes",
	"errorCode": "201",
	"errorDetail": "oobContinueLabel",
	"threeDSServerTransID": "4188320e-b3fe-4e92-bbfc-562972c93108",
	"sdkTransID": "1721ade0-88e4-434b-ae19-2b55bb9acf0b",
	"messageType": "Erro"
}
```

This simply means that the ACS must have sent `oobContinueLabel` parameter in the CRes (challenge response) but didn't, and this field is required as mentioned by the `errorDescription`, so this is an ACS error.

You need to contact the issuer's ACS to fix this error, if you need help contacting the ACS let us know.

Mohamed

**Comment by mohadian** [comment]
Hi 
Thank you for the reply.

Is there anything we can do to resolve it? or it is an integration issue on ACS part?

The above JSON is part of the request payload of  https://3ds-b.live.ext.prod.enfuce.com/acs/app

I am wondering if you have received any other similar support requests for this issuer's ACS?

Regards
Mostafa

**Comment by mohammedDehairy** [comment]
Hi @mohadian ,

 `Is there anything we can do to resolve it? or it is an integration issue on ACS part?`

Unfortunately this is an error from the ACS side, there is nothing you or us can do except contact the ACS and make sure they fix it.

`I am wondering if you have received any other similar support requests for this issuer's ACS?`

For this issuer in particular, no as far as I know, but we have received those kinds of issues from other ACS's in the past, and they were indeed ACS's problems.

**Comment by mohadian** [comment]
Thanks for the prompt reply. 

in that case, we probably need your help contacting the correct ACS. Please let me know if you require any details from my side, I have provided a few Charles logs to Anusha (Adyen Support) and I am happy to provide you with any further details if required.

**Comment by mohammedDehairy** [comment]
Hi @mohadian ,

We sent an email to the ACS, we'll update you once we get a reply.

Mohamed

**Comment by ACathelin** [comment]
Hi @mohadian, 

We reached out to the ACS causing this Erro.
I'll update the thread once I have more information about this subject.

Antoine

**Comment by mohadian** [comment]
Hi, Thank you for the update. Please let me know if you require any further details from our side.

**Comment by kanclalg** [comment]
@mohammedDehairy @ACathelin is there any update? We're also experiencing the same issue.

**Comment by mohammedDehairy** [comment]
@kanclalg 
This is a question rather to @mohadian ?, since the ACS asked to follow up with them directly.

@mohadian any update you can share here?

**Comment by mohadian** [comment]
We have reached out to enfuce and they are still investigating this issue with the ACS. unfortunately, they cannot get us a timetable on when we would have a solution fixed. (this is based on their response on 1st Oct

I am wondering if @ACathelin has any updates?

**Comment by beetsandroots** [comment]
Hey there,

Was this issue resolved? We are also facing it

**Comment by mohammedDehairy** [comment]
Hey @beetsandroots ,

can you share the error?

**Comment by beetsandroots** [comment]
Hey @mohammedDehairy 

This is the error we receive when paying with Mastercard issued by Pleo ( https://www.pleo.io/de )

{
“acsTransID” : “b89b0e3a-afc0-4c6f-8642-1fc20e521c9e”,
“errorMessageType” : “CRes”,
“messageVersion” : “2.1.0",
“errorDescription” : “Message element defined as required is missing from the message.“,
“errorComponent” : “C”,
“errorCode” : “201",
“errorDetail” : “challengeInfoText”,
“messageType” : “Erro”,
“sdkTransID” : “2218ca16-04eb-4706-ab22-a5feb3859dec”,
“threeDSServerTransID” : “0accbb85-da83-4642-b0cd-523103824ade”
}

We use
- iOS SDK version 4.8.0
- v68 Checkout API version

**Comment by mohammedDehairy** [comment]
Hey @beetsandroots ,

I found the ACS reference number, its `3DS_LOA_ACS_EQWO_020200_00280`, its [this one](https://www.emvco.com/wp-content/uploads/approved_products/uploaded/loa/3DS_LOA_ACS_EQWO_020200_00280_20May20.pdf), you need to reach out to them and ask them to fix the issue, their CRes is missing the `challengeInfoText` which is required.

Mohamed

**Comment by mohammedDehairy** [comment]
I will close the issue for lack of activity, please feel free to comment on the issue if you face a similar issue with an ACS and we'll try to help!.
