### ISSUE TITLE
[BUG] Drop-In "Attempt to present… on… which is already presenting…" 

### ISSUE THREAD

**Issue by alexkent** [Adyen/adyen-ios#622]
**Describe the bug**
When selecting a payment method from the popup sheet we occasionally get stuck (the sheet doesn't dismiss, close button stops working, user is stuck) and the following error is logged:

```MyApp Dev[4551:1427358] [Presentation] Attempt to present <AdyenDropIn.DropInNavigationController: 0x11183ac00> on <UINavigationController: 0x11182e400> (from <MySDK.CheckoutPaymentViewController: 0x10fdbdaa0>) which is already presenting <AdyenDropIn.DropInNavigationController: 0x11282f000>.```

**To Reproduce**
1. Present DropIn…
```
let dropInComponent = DropInComponent(paymentMethods: paymentMethods, configuration: configuration)
self.adyenDropInComponent = dropInComponent
dropInComponent.delegate = self
self.present(dropInComponent.viewController, animated: true)
```
2. Tap a payment method (we currently only support Creditcards)

**Expected behavior**
Normally the Payment Selector sheet dismisses and the Payment Details sheet appears.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 14.7
 - SDK Version: 4.0

**Comment by descorp** [comment]
Hey  @alexkent 

> MyApp Dev[4551:1427358] [Presentation] Attempt to present <AdyenDropIn.DropInNavigationController: 0x11183ac00> on <UINavigationController: 0x11182e400> (from <MySDK.CheckoutPaymentViewController: 0x10fdbdaa0>) which is already presenting <AdyenDropIn.DropInNavigationController: 0x11282f000>.

This message says that you are presenting `DropInNavigationController` on `CheckoutPaymentViewController` that is already presenting another `DropInNavigationController`..

Do you have any ideas where the second `DropInNavigationController` is coming from?
Can you check if you are creating and presenting `DropInComponent` multiple time?

**Comment by descorp** [comment]
Hey @alexkent 

Were you able to resolve the issue?

**Comment by descorp** [comment]
I am going to close this ticket for now.
Please feel free to reopen if necessary.
