### ISSUE TITLE
[BUG] Dropin locale is broken

### ISSUE THREAD

**Issue by xanderdeseyn** [Adyen/adyen-ios#623]
According to the documentation [here](https://docs.adyen.com/online-payments/ios/drop-in#localization), we should be able to specify some locals that have predefined translation sheets. However, this does not seem to work in practice, it always displays english:

```swift
dropInConfiguration.localizationParameters = LocalizationParameters(bundle: nil, tableName: nil, keySeparator: nil, locale: "nl-NL")
```

**Comment by descorp** [comment]
Hey @xanderdeseyn 

At the moment, the SDK is following recommendations from Apple to localise the app based on a device's locale.
In v4.1.0  the  `locale: "nl-NL"` is only specifying the "locale" for some formatters (e.x. AmountFormatter).

>  it always displays english:

If you want to enforce a specific translation - you can use custom `tableName`:

1) Copy [Localizable.strings](https://github.com/Adyen/adyen-ios/tree/develop/Adyen/Assets) resource;
2) Add it to app's bundle and give it a locale-specific name (e.x. `Localizable-NL.strings`);
3) Send a name as `tableName`:

```swift
LocalizationParameters(bundle: nil, tableName: "Localizable-NL", keySeparator: nil, locale: "nl-NL")
```

**Comment by xanderdeseyn** [comment]
Cheers, works like a charm.
