### ISSUE TITLE
[NEED ASSIST] DropIn Credit Card - Error 403 inside library call for "/clientKeys"

### ISSUE THREAD

**Issue by Jack25apr** [Adyen/adyen-ios#626]
**Describe the challenge**
I'm mostly using **DropIn** example, sofort test mode works ok, but got error after  submitting the Credit Card data, after entering demo data:
3700 0000 0000 002   
03/30
3700

I've seen that next request fails with 403 error:

**https://checkoutshopper-live.adyen.com/checkoutshopper/v1/clientKeys/test_SOME_MY_CLIENT_KEY?clientKey=test_SOME_MY_CLIENT_KEY**

response:

`<!doctype html><html lang="en"><head><title>HTTP Status 403 – Forbidden</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 – Forbidden</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> The server understood the request but refuses to authorize it.</p><hr class="line" /><h3>AdyenSE</h3></body></html>`

in the app I got just callback in 
```
func didFail(with error: Error, from component: DropInComponent) {

}
```

Another observations/questions:

why the ios library in the TEST mode enviornment uses live shopper url: **https://checkoutshopper-live.adyen.com** for:
- payment methods logos i.e. (https://checkoutshopper-live.adyen.com/checkoutshopper/images/logos/small/mc@3x.png)
- **checkoutshopper/v1/clientKeys/** request that I'm facing the main problem  

I saw that got payment methods ok from test mode URL : **https://checkout-test.adyen.com**.

**Comment by descorp** [comment]
Hey @Jack25apr 

> why the ios library in the TEST mode enviornment uses live shopper url

Probably this is what causing a problem: you are using `test` client key on `live` environment.

Make sure you are creating `APIContext` correctly
```
var apiContext = APIContext(environment: .test,  clientKey: "test_SOME_CLIENT_KEY" )
let configuration = DropInComponent.Configuration(apiContext: apiContext)
```

**Comment by Jack25apr** [comment]
@descorp 
Hi Vladimir, thanx for reply

I've tested your suggestion, but then I got 2 main problems: 

1.  Error on loading payment method images (the payment method list has empty rectangles with method names):
https://checkout-test.adyen.com/checkoutshopper/images/logos/small/card@3x.png
https://checkout-test.adyen.com/checkoutshopper/images/logos/small/giropay@3x.png
and so on:
HTTP/1.1 401 401
000 HTTP Status Response - Unauthorized

2. the bigger main problem -  iOS library making call after entering test card details and pressing "EUR 10.00 PAY"
 _https://checkout-test.adyen.com/checkoutshopper/v1/clientKeys/test_MY_KEY_DATA*********?clientKey=test_MY_KEY_DATA*********

what works ok:

- getting the list of payment methods: 
https://checkout-test.adyen.com/v67/paymentMethods?clientKey=test_SOME_NUMBERS......********
- Selecting and using Sofort, (webview and success/fail callback)

**Comment by Jack25apr** [comment]
Seems resolved. Card **test** payment and images works ok.
Maybe it was fixed by itself or you just fixed it right now. Thanx. Issue May be closed.

**Comment by descorp** [comment]
hm.. let us know if the same error occurs again

**Comment by zeusent** [comment]
Hey guys! I am using version 4.8.0 and I have the same problem. I've checked and made sure that my client key is a test environment key (the key starts with `test_`) and the app connects to the the test environment.

Trying to make a test credit card payment fails with the same error as described in the first post here: https://checkoutshopper-test.adyen.com/checkoutshopper/v1/clientKeys/{my_client_key}?clientKey={my_client_key} always returns HTTP 403 

I have no idea how to fix this...

**Comment by descorp** [comment]
Hey @zeusent 

One gets 403 if query param (`clientKey={my_client_key}`) is wrong. 
Can you try a shorter URL `https://checkoutshopper-test.adyen.com/checkoutshopper/v1/clientKeys/{my_client_key}` ?

**Comment by zeusent** [comment]
Hey @descorp! Thanks for opening up my eyes! 🤦‍♂️ I was using a wrong client key, pf... Sorry for digging up this old thread...

**Comment by Jack25apr** [comment]
@zeusent no problem, I assume same problem was here originally :)
