### ISSUE TITLE
[BUG] TextField class name collision

### ISSUE THREAD

**Issue by Jack25apr** [Adyen/adyen-ios#627]
**Describe the bug**
I'm using CocoaPods, I have Material library in my project, they have TextField custom class from UITextField
Adyen also have class named TextField.
My proposal is to use less common name for custom textfields, i.e. **TextField** .

**To Reproduce**
1. Add Adyen library, i.e. CocoaPods
2. Add Material library, i.e. CocoaPods or other library that have already TextField subclass
3. Import somewhere 2 modules Adyen and Other library i.e. Material
`"'TextField' has different definitions in different modules; first difference is definition in module Adyen.Swift'"`

**Expected behavior**
Compile ok, if use less common name for subclasses

**Comment by descorp** [comment]
Taken care of in #632 
Will be released in 4.2.0

**Comment by descorp** [comment]
@Jack25apr 

4.2.0 released. Could you verify that it fixes the issue for you?

**Comment by Jack25apr** [comment]
@descorp  tested with 4.2.0 and it works! Thanx a lot. The issue could be closed.
