### ISSUE TITLE
[The card holder name is not encrypted] 

### ISSUE THREAD

**Issue by ronstorm** [Adyen/adyen-ios#629]
I was trying to integrate Adyen-ios SDK to our company app and I faced a big problem over there. I found the Card Model (https://github.com/Adyen/adyen-ios/blob/develop/AdyenEncryption/Model/Card.swift) with a public holder’s name but there is no way to encrypt the holder’s name. The SDK is actually encrypting the Card number, cvc, expiry month and expiry year. Our backend is not being able to decrypt the holder’s name which creates a problem on our app side. Can it be solved somehow?

**Comment by descorp** [comment]
Hey @ronstorm 

Thanks for reaching out!

Adyen API does not expect holder's name to be encrypted: you can use un-encrypted [`holderName` property](https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments__reqParam_paymentMethod-CardDetails-holderName).
Here in [API Explorer](https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments__reqParam_paymentMethod-CardDetails-cupsecureplus-smscode) you can see that only encrypted fields expected are:

-  encryptedCardNumber 
- encryptedExpiryMonth 
- encryptedExpiryYear 
- encryptedSecurityCode

**Comment by descorp** [comment]
Hey @ronstorm 

Was the issue resolved?

**Comment by descorp** [comment]
@ronstorm 

I am going to close this ticket.
Feel free to reopen it, if needed.
