### ISSUE TITLE
Credit card fill form UI

### ISSUE THREAD

**Issue by rumnat** [Adyen/adyen-ios#63]
I can't change the color of the navigation bar on the Credit card fill form. Can you please make the appearance more configurable to cover all the possible design cases?

**Comment by diegomarcon** [comment]
Hi @rumnat,

There's a configuration for navigation bar color on Appearance object, but indeed it's being overridden by another component.

We will fix this behaviour and add to the next release.

Thanks for spotting this!

**Comment by rumnat** [comment]
Thanks for your work guys. Would be great to have access directly to the av bar layer so I can add shadow or apply more UI configuration

**Comment by diegomarcon** [comment]
Hi @rumnat,

Release 2.8.0 contains a fix for the first issue you mentioned. Now the color will propagate to card form view controller.

We will consider internally the second suggestion about the navigation bar layer. 

Thanks for your feedback.
