### ISSUE TITLE
[BUG]  - Janky DropIn animation in iOS 15

### ISSUE THREAD

**Issue by gscalzo** [Adyen/adyen-ios#630]
**Describe the bug**
The appearing animation of the DropIp is not smooth as in iOS 14: 
firstly the screen occupies almost all the available space and then it shrinks to its expected height

**To Reproduce**
1. open the DropIn in iOS 15
2. the DropIn appears with a janky animation

**Expected behavior**
Same smooth animation as in iOS 14

**Screenshots**
Below, 2 videos to show the problem:
* [iOS 15 animation](https://user-images.githubusercontent.com/5433/134042410-c832f2c9-a496-4884-bd09-7cd8fc889d64.mov)
* [iOS 14 animation](https://user-images.githubusercontent.com/5433/134042406-27de7f08-8e09-4c16-bf8e-1bda08149948.MP4)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS15
 - SDK Version: 4.1.0

** Context**
The app is the same, downloaded from the AppStore

**Comment by descorp** [comment]
Hey @gscalzo 

Huge thanks for a feedback!
Indeed, we only tried iOS 15 on simulator 🤔

We investigate!

**Comment by descorp** [comment]
*UPD*

I have tried on iPhone Xr iOS 15.0 **RC** (19A344) and I can't reproduce this 🤔
I'll try to check with other devices..

What is the target version of your app? 
What was iOS version of the device before it was updated to iOS 15?
Could be any "Accessibility" features on?
If you run the app from Xcode - does it still have janky animation?

**Comment by gscalzo** [comment]
Target version is 14.0+.
Tested on iPhone 11 iOS 15.0 RC (19A344)
The app is on SwiftUI.
Build with Xcode 12.5 (12E262)

Building and running with Xcode 12.5 shows the janky animation

But building with Xcode Version 13.0 (13A233) the animation is smooth in both simulator and device.

**Comment by descorp** [comment]
@gscalzo 

Can we assume that issue is resolved? 
This sound like something outside the scope of the SDK 🤔

**Comment by gscalzo** [comment]
Can we keep it open until at least we migrate our dev toolchian to Xcode 13 a test in in Prod? It should happen this week or early next week
