### ISSUE TITLE
[BUG] [CRASH]

### ISSUE THREAD

**Issue by badredaha** [Adyen/adyen-ios#634]
**Describe the bug**
Crash 

**To Reproduce**
Choose a saved card (3DS2)
Put the CVV
When screen waiting is shown (or when a Screen 3DS2 is shown) the App Crash.

**Smartphone (please complete the following information):**
 - Device: iPhone12 Pro Max
 - OS: 14.5
 - SDK Version 4.0.0

**Crash stack**
"Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread."

**Comment by descorp** [comment]
Hey @badredaha 

> When screen waiting is shown (or when a Screen 3DS2 is shown) the App Crash.

How do you show them? 
Are you using `dropInComponent.handle(action)` or  `actionComponent.handle(action)` ?
Could you try to wrap it in `DispatchQueue.main.async { . . . . }` ?

**Comment by badredaha** [comment]
I use : `dropInComponent?.handle(action)`

**Comment by badredaha** [comment]
I will close this issue when I wrapped into DispatchQueue all work well.

Thx @descorp
