### ISSUE TITLE
[BUG] Failing to archive with Xcode 13 with adyen 3.8.4 version

### ISSUE THREAD

**Issue by RajaZahid** [Adyen/adyen-ios#635]
**Describe the bug**
Try to create archive with Xcode 13 but failing. Error messages being displayed in attached screenshot

**Expected behavior**
Archive should be created

**Screenshots**
<img width="258" alt="Screenshot 2021-09-22 at 4 27 10 pm" src="https://user-images.githubusercontent.com/1908483/134335614-5a0d1bef-41df-4848-9056-4f01fe067a01.png">

**Smartphone (please compl
ete the following information):**
 - Device: iPhone
 - OS: iOS 15
 - SDK Version : 3.8.4

**Comment by RajaZahid** [comment]
@ffittschen thanks
I am using SPM. I have tried adding both v3 branch and above commit as well but still getting error.

**Comment by RajaZahid** [comment]
@ffittschen Got it, it will work once they review and approve pull request.

**Comment by descorp** [comment]
Hey @RajaZahid are you running M1 mac or Intel ?

**Comment by RajaZahid** [comment]
> Hey @RajaZahid are you running M1 mac or Intel ?

Hey @descorp 
I am running Intel.

**Comment by descorp** [comment]
Hey @RajaZahid 

Thanks for confirming.
Could you check if this [solution](https://github.com/Adyen/adyen-ios/pull/640) works for you?

**Comment by descorp** [comment]
PR is merged to `v3` branch. @RajaZahid could you check if it solves the issue for you?

**Comment by nomanyousuf** [comment]
Are there any plans for this fix to release or when it will be available?

**Comment by descorp** [comment]
@nomanyousuf 

It is already pushed to `v3` branch. You can select it on your package manager.
We will be released in the next couple of weeks.

**Comment by RajaZahid** [comment]
> PR is merged to `v3` branch. @RajaZahid could you check if it solves the issue for you?

@descorp I have verified this is resolved when I use package from v3 branch.
