### ISSUE TITLE
[NEED ASSIST] Adyen 4.1.0 minimum deployment target?  

### ISSUE THREAD

**Issue by leslieolivier** [Adyen/adyen-ios#638]
The README.MD says the minimum deployment target is iOS10, but according to the podspec-file, it is iOS11. Can you confirm that Adyen 4.1.0 will not be available for iOS10?

Thanks

**Comment by descorp** [comment]
Hey @leslieolivier 

Indeed! Documentation was outdated 😅

Thanks for pointing out!
v4 is only available on iOS11+
