### ISSUE TITLE
[BUG] Not open Select PaymentMethod Popup in iOS 15.

### ISSUE THREAD

**Issue by hiral101** [Adyen/adyen-ios#639]
**Describe the bug**
i have tested in iOS 15. but still not open PaymentMethod Popup. 
iOS working in iOS 14 or below.

**Smartphone (please complete the following information):**
 - Device: [iPhone8]
 - OS: [iOS14.6]

**Additional context**
Xcode Version: 13.0
Mac OS Version: Bigsur(11.4)

**Comment by descorp** [comment]
Hey @hiral101 

Thanks for reaching out!

Could you provide more details on what is not opening?
Do you mean DropInComponent ?

**Comment by hiral101** [comment]
@descorp Fixed issue.

**Comment by descorp** [comment]
What was the issue? :)
For the record and future generations?

**Comment by chrilaggou** [comment]
@hiral101 we are facing the same issue, can you please provide more details of how you fixed it? ty
