### ISSUE TITLE
Missing picture of Thailand E-banking

### ISSUE THREAD

**Issue by rumnat** [Adyen/adyen-ios#64]

**Comment by rumnat** [comment]
<img width="351" alt="Screenshot 2019-04-15 at 11 26 21 AM" src="https://user-images.githubusercontent.com/10436125/56118275-7f7dd280-5f9c-11e9-841d-bb2a018628ed.png">

**Comment by diegomarcon** [comment]
Hi @rumnat,

We are investigating the missing icons for Thailand E-banking.

I'll update you when when we have a fix for it.

**Comment by diegomarcon** [comment]
Hi @rumnat,

There were new logos uploaded to our backend.
Can you confirm that this solves the missing logo issue for you?

Cheers,

**Comment by rumnat** [comment]
work like a charm, thanks
