### ISSUE TITLE
[NEED ASSIST] Hide CVV field

### ISSUE THREAD

**Issue by GustavoCaiafa** [Adyen/adyen-ios#641]
Hello guys, how are you doing?

I'm using CardComponent and trying to hide the CVV field. I was able to hide the date field (and setting a default value to 1035) by going through the subviews and comparing the view to FormTextInputViewView, like below(all done inside CardComponent):

```
guard let componentViewController = self.viewController as? SecuredViewController,
              let rootViewController = componentViewController.children.first as? FormViewController,
              let scrollView = rootViewController.view.subviews.first as? UIScrollView,
              let stackView = scrollView.subviews.first as? UIStackView else {
            return
        }
        let stackDate = stackView.subviews[1]
        var formDate : FormTextItemView<FormTextInputItem>?

        for view in stackDate.subviews{
            if view is UIStackView{
                var subviewLocal : UIView?
                subviewLocal = view.subviews[0]
                if subviewLocal is FormTextInputItemView{
                    formDate = subviewLocal as? FormTextItemView
                    formDate?.item.value = "1035"
                    subviewLocal?.isHidden = true
                    subviewLocal?.removeFromSuperview()
                }
            }
        }
```
        
 The problem now is: CVV field is of FormCardSecurityCodeItem, and i can't really access that. So, how can i hide the CVC field and set a default value to it? Also, is there a cleaner and easier way of hiding the date field too?

**Comment by nauaros** [comment]
Hi @GustavoCaiafa!

Going through the view hierarchy and parsing it may be quite a hacky way of solving this problem.

For the `CardComponent`, there's a configuration object called `CardComponent.Configuration` where you'll find the property `showsSecurityCodeField` (defaults to `true`) where you can disable the security field.

For now, we don't provide any way to fill the date field nor the CVC one. May I ask what's the use case so we can understand what you're trying to achieve.

**Comment by GustavoCaiafa** [comment]
Hi @nauaros, thanks for the answer, it did solve my problem. 

And to answer, we need to provide a default value (for both date and CVV) for cards that don't have those fields. I was able to solve this by changing the value for the security code key in the card dictionary.

**Comment by descorp** [comment]
@GustavoCaiafa 

> And to answer, we need to provide a default value (for both date and CVV) for cards that don't have those fields.

This doesn't sounds right.
Our CardComponent is capable to check if entered card's issuer requires CVC, Expire date or any other information.
It is possible by checking card's BIN number agains Adyen's database.
In case CVC or Date is not required - it supposed to be empty, not "default".
The approach you described above will most likely lead to a conversion drop.

If you are capable with 100% determine whether a card needs "default" CVV or not - I would recommend using a custom solution instead of CardComponent..
