### ISSUE TITLE
[Feature] iOS 15 - Add card to Apple Pay  - ApplePayComponent

### ISSUE THREAD

**Issue by eduardourso** [Adyen/adyen-ios#659]
**Is your feature request related to a problem? Please describe.**
On iOS 15 Apple now allows the user to add a card in case there isn't one added to the wallet already. 
When creating the ApplePayComponent it is required to have a card on the wallet otherwise the component creation fails.

https://www.apple.com/ios/ios-15/features/

<img src="https://user-images.githubusercontent.com/3766687/136200664-731b22d0-b04e-4f06-93c1-019e91c5dd2e.png" width="300">

**Describe the solution you'd like**
When creating the ApplePayComponent it shouldn't be required to have a card on the wallet.

**Additional context**
The following check on iOS 15 (`ApplePayComponent.swift`) could just be ignored:

![Screenshot 2021-10-06 at 14 05 39](https://user-images.githubusercontent.com/3766687/136200844-7b5f5d0c-6e2c-4b58-9b0e-5a97f0b151da.png)

and PassKit would present the following alert to the user to add a card to the wallet and proceed with the payment.

<img src="https://user-images.githubusercontent.com/3766687/136199672-86985a85-2312-46fc-893b-3e0e3e507b7e.jpeg" width="300">

Thanks for the support and looking forward to seeing this live.

**Comment by descorp** [comment]
Hey @eduardourso 

Thanks a lot for a feedback!
Indeed, we are looking into this improvement for quite a while now!
Will keep you posted in this thread!

**Comment by descorp** [comment]
@eduardourso 

4.3.0 was released last week.
Could you verify if it works for you?

to activate the feature, use `appleComponentConfig.allowOnboarding  = true`

**Comment by descorp** [comment]
I am going to close this ticket for now. 
Feel free to reopen it if necessary.
