### ISSUE TITLE
E-Banking wrong status code

### ISSUE THREAD

**Issue by rumnat** [Adyen/adyen-ios#67]
When I chose either **error** or **pending refused** I get success result with **received** status in
`func didFinish(with result: Adyen.Result<PaymentResult>, for checkoutController: CheckoutController) `
<img width="387" alt="Screenshot 2019-04-22 at 9 00 51 AM" src="https://user-images.githubusercontent.com/10436125/56477984-ee4bb600-64dd-11e9-9956-f886a3ff08b5.png">

**Comment by rumnat** [comment]
Seems to be a server issue because it was fine week ago

**Comment by joostvandijk** [comment]
Hi @rumnat,

This is likely not related to the SDK. Could you send an email to support@adyen.com with any details you can provide (merchant account, request/response)?

Thanks,

Joost

**Comment by rumnat** [comment]
Sent a video, thanks

**Comment by joostvandijk** [comment]
Hi @rumnat,

I'm closing this issue as I'm hoping it's been resolved by support.

Thanks,

Joost
