### ISSUE TITLE
[Feature] Is Address validation possible?

### ISSUE THREAD

**Issue by isidoro-giffgaff** [Adyen/adyen-ios#676]
**Describe the challenge**
We would like to validate the billing address on the adyen SDK card component. We are using the full address mode.

At the moment on the didSubmit delegate we are calling an API to validate the address, but if the address is invalid the only way to give feedback to the user is through an alert. Is it possible for us to tap into the form error messages? It would really improve the usability from the user point of view.

Thanks

**Comment by descorp** [comment]
Was released on [5.3.0](https://github.com/Adyen/adyen-ios/releases/tag/5.3.0)
