### ISSUE TITLE
Navigation Bar not respecting safe area

### ISSUE THREAD

**Issue by brurend** [Adyen/adyen-ios#68]
In all iPhones with notchs the navigation bar is not respecting it and the title is really close to it, almost under it. The navigation bar should be able to adapt to all iPhone sizes.

**Comment by joostvandijk** [comment]
Hi @brurend,

The navigation bar should adapt properly. What version of iOS are you testing on?

Thanks,

Joost

**Comment by brurend** [comment]
Hi, I'm testing in iOS 12.2, Adyen 2.7.2, iPhone Xr. I'm attaching a screenshot



![IMG_9CC78E20748B-1](https://user-images.githubusercontent.com/6145411/56668603-2aba1600-6686-11e9-9db6-0817afaa4f7d.jpeg)

**Comment by joostvandijk** [comment]
This doesn't really look like our UI, or at least not any recent version of it. Are you using a custom UI, or customizing our UI via the Appearance class? In case of the latter, could you show what your customization looks like in code?

**Comment by brurend** [comment]
I will take a look at our custom layout and then give you a reply, thanks for the help
