### ISSUE TITLE
[NEED ASSIST] CompileAssetCatalog Error after updating from 3.6.0 to 3.8.5

### ISSUE THREAD

**Issue by Manouli** [Adyen/adyen-ios#689]
I am trying to update the pod from version 3.6.0 to 3.8.5. Everything seems to work fine locally but when I send it to our CI I am getting an error 

```
The following build commands failed:
CompileSwift normal arm64
CompileSwift normal arm64
CompileAssetCatalog /Users/build/Library/Developer/Xcode/DerivedData/XXXX/Build/Intermediates.noindex/ArchiveIntermediates/XXX/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AdyenCard.bundle /Users/build/blueocean/workspace/XXXX/ios/Pods/Adyen/AdyenCard/Assets/AdyenCardAssets.xcassets
```

Looking at the log 

```
/Users/build/blueocean/workspace/XXXX/ios/Pods/Adyen/AdyenCard/Assets/AdyenCardAssets.xcassets: error: None of the input catalogs contained a matching stickers icon set or app icon set named  "AppIcon-Dev"
```

Any help will be much appreciated.

**Comment by descorp** [comment]
Hey @Manouli 

Are you developing a library / framework?
Do you have a local podspec with bundled local `.xcassets` ?

There is an [issue with Cocoapods](https://github.com/CocoaPods/CocoaPods/issues/7745) not able to proccess resources.

**Comment by Manouli** [comment]
Hey @descorp 

No its a react native app. We use the Adyen ios pod in the pod file there.

**Comment by descorp** [comment]
Hey @Manouli 

Ok, interesting.
I will try to reproduce the issue for v3.8.5 then.

Adyen iOS SDK v4 works perfectly fine with React Native.
Have you considered updating to the latest version?

**Comment by Manouli** [comment]
@descorp I am considering this now since I can't find a solution to use v3.8.5 😀. It will be a bigger job since v4 is introducing some breaking changes but I will see what I can do.

**Comment by descorp** [comment]
@Manouli 

Hopefully, the difference v3 -> v4 is not too big.

Let us know if you have any issues with it!
I would advise to create one ticket per issue.

**Comment by Manouli** [comment]
@descorp thank you for your help! Really appreciate it 🙏

**Comment by descorp** [comment]
I am going to close this for now 🙂
Let us know if you have any issues with migrations!
