### ISSUE TITLE
PaymentRequestManager didFinish not responding

### ISSUE THREAD

**Issue by brurend** [Adyen/adyen-ios#69]
PaymentRequestManager didFinish only responds once, if we try to call it again it gives no response at all.

**Comment by joostvandijk** [comment]
Hi @brurend,

What do you mean with "call it again"? The PaymentController is designed to be used only once. After the payment, you have to instantiate a new one.

Thanks,

Joost

**Comment by brurend** [comment]
Hi, thank you for the reply.

By "call it again" I mean if the first request fails, if the user lost connection for example and then tried again a minute later without leaving the view

**Comment by joostvandijk** [comment]
Right now, that flow is not supported. After didFinish is invoked, the view should be dismissed by you. There's no support in place for resuming a payment.

**Comment by brurend** [comment]
Ok, thank you for the reply.
