### ISSUE TITLE
[BUG] 3DS 1 Challenge not triggered AI v67 with 4.2.0

### ISSUE THREAD

**Issue by badredaha** [Adyen/adyen-ios#698]
**Describe the bug**
With API upgrade to v67 the 3DS 1 was not triggered! 

**To Reproduce**
Upgrade API to v67 and make payment with 3DS 1 card such as: 

> Visa | 4212 3456 7890 1237 | CA | 03 | 2030 | 737

**Expected behavior**
3DS 1 challenge triggered 

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Max Pro
 - OS: 14.5
 - SDK Version 4.2.0
 

**Additional context**
API Migration from v55 to v67

**Comment by descorp** [comment]
Hey @badredaha 

I am getting 3DS1 with this TEST card on my end.
Could you set `AdyenLogging.isEnabled = true` and share logs that you are getting in Xcode output?

**Comment by badredaha** [comment]
Hey @descorp 

The good question is: should I send browserInfo to get the 3DS1 challenge? right now I have the 3DS2 challenge but if I test 3DS 1 the payment go success directly

**Comment by descorp** [comment]
Hey @badredaha 

Sorry for a long reply.

What do you see if you provide no `browserInfo`?

On v66 we set "frictionless" 3DS1 flow as default flow - when you provide `browserInfo`, we can check it agains risk management system and if risk is minimal - returns "success".

**Comment by badredaha** [comment]
Hye @descorp 

No problem :)

> What do you see if you provide no browserInfo?

- If I test 3DS 1 -> No challenge triggered
- If I test 3DS 2 -> The challenge triggered


> If I provide browserInfo?
- If I test 3DS 1 -> The challenge triggered
- If I test 3DS 2 -> The challenge triggered

**Comment by descorp** [comment]
Hey @badredaha 

> If I test 3DS 1 -> No challenge triggered

This doesn't sound right 🤔
Could you provide `pspReference` ?

> If I test 3DS 1 -> The challenge triggered

Is it native 3DS2, web 3DS2 or web 3DS1 ?

**Comment by badredaha** [comment]
Web 3DS 1.

psdRef: 883636551921282E

**Comment by descorp** [comment]
Thanks!

> The good question is: should I send browserInfo to get the 3DS1 challenge?

`BrowserInfo` is required for 3DS1 and we recommend always send it.
This is [doc page](https://docs.adyen.com/online-payments/3d-secure/api-reference#3d-secure-2-additional-data-objects) about additional info for 3DS.

---

Previously I mentioned that `If no browserInfo the 3DS1 challenge supposed to be triggered..`. 
This is actually not entirely true.

In the logs I see message:
```
BrowserInfo was not populated with dummy values as populateBrowserInfoFor3ds is not true and 3DS was not forced
```

Have you previously forced 3DS?
Could check if you have property `populateBrowserInfoFor3ds` and set it to `true` on your CA ?

**Comment by badredaha** [comment]
The browserInfo haven't the acceptHeader ?browserInfo: Optional(Adyen.BrowserInfo(userAgent: Optional("Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148")))) from component <Adyen.DropInComponent: 0x7fc24e82a800>

**Comment by descorp** [comment]
Hey @badredaha 

This is a great question, actually 😅
Looks like we have some misalignments with our documentation!
Thanks for pointing out! I'll get back to you shortly..

**Comment by descorp** [comment]
We still figuring this one out..
In a meanwhile you can ignore `acceptHeader`, just make sure you have `browserinfo` with `userAgent` set

**Comment by badredaha** [comment]
Thx @descorp a will check that and give you feedbacks

**Comment by badredaha** [comment]
Thx I will close this. We send browserInfo to null after enable `populateBrowserInfoFor3ds ` and works
