### ISSUE TITLE
Custom translation

### ISSUE THREAD

**Issue by rumnat** [Adyen/adyen-ios#70]
Hello, thank you for custom translation possibility added in 2.8.0. Can you please help. It works only when translated strings are in the base localized file. If I put them to Localizable.strings file for the Thai language it doesn't work. Also, "Cancel" key seems to be overridden and always Cancel event if the translation provided

**Comment by joostvandijk** [comment]
Hi @rumnat,

I think this might be a limitation of the iOS translation system. Assuming your base language is English, can you add our English strings to your localization file? If you then put your Thai strings in the Thai localization, it should work.

Regarding the cancel button, it's localized by iOS, as it uses the `UIBarButtonSystemItemCancel`.

Best,

Joost

**Comment by rumnat** [comment]
I have tried to put your english translation to english and base localization files (english is base for the app) and thai translation to the Thai file. Didn't work

**Comment by joostvandijk** [comment]
Hi @rumnat,

I've tried to reproduce it, but I can't get it to "not work". If I make sure the hosting app is localized for English and Thai, and then add the Thai translations to the host app, the SDK does pick them up:

![Simulator Screen Shot - iPhone Xs - 2019-04-30 at 11 19 58](https://user-images.githubusercontent.com/8394738/56952189-0359c200-6b3a-11e9-907f-c9d5c7bed781.png)

Are you sure your configuration is correct?

Kind regards,

Joost

**Comment by rumnat** [comment]
Yes, added translations to appropriate localized string files. Can you share a sample, please? It should take custom translation regardless of a locale key send from a back-end?

**Comment by joostvandijk** [comment]
Yes, it should. If you take our Quick Integration Example from the Examples folder, what I did was:
- Add a Localizable.strings file for English to the app.
- Enable Thai localization.
- Put the Thai strings into the Localizable.strings for Thai.
- Run the simulator in Thai language.

The SDK then picks up the Thai strings.

**Comment by rumnat** [comment]
Hi, so it works only if device language is Thai. It doesn't work if app language is TH or we send TH locale from the back end

**Comment by joostvandijk** [comment]
Hi @rumnat,

That's correct - we use the default `NSLocalizedString` functions to localize the strings. If you're app is using Thai translations without the device language being Thai, I assume you're using a custom localization method?

**Comment by rumnat** [comment]
We use `NSLocalizedString(key, tableName: nil, bundle: bundleForCurrentLanguage(), value: "", comment: "")` passing bundle `Bundle.main.path(forResource: locale.localeName, ofType: "lproj")` based on selected city.
So is there anything we can achieve Adyen translation based on app language?

**Comment by joostvandijk** [comment]
I see. I'm afraid that we don't see any good options for enabling this behavior while keeping the integration simple for all other users of this SDK. If you really want to, you can go a hacker route as explained [here](https://stackoverflow.com/questions/1669645/how-to-force-nslocalizedstring-to-use-a-specific-language). Or, you'll have to build your own UI with our custom integration route.

**Comment by rumnat** [comment]
ok I see. Thank you guys
