### ISSUE TITLE
[BUG] Sometimes in PaymentMethodListComponent, The method can't click

### ISSUE THREAD

**Issue by yuchuanxing** [Adyen/adyen-ios#705]
**The 'UIStackView' area of ListCell can't click**

When I present a PaymentMethodListComponent, and I click the  Apply Pay or Credit card method, but It doesn't work,  the delegate method  `override public func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) ` don't work.  When I click the ListCell.ListItemView.ImageView or the cell area except titleSubtitleStackView, it works!.  I think, may be. There has a little problem.

**To Reproduce**
1. Go to 'Payment Methods'
2. Click on 'Apply pay',  click on the 'titleSubtitleStackView' area  

I integrate Adyen with drop in,  The Adyen version is 4.4.0.

**Expected behavior**
I hope when I click the Payment Methods, it can always navigate to next page

**Screenshots**
<img width="376" alt="Screen Shot 2021-11-11 at 2 14 50 PM" src="https://user-images.githubusercontent.com/92570828/141250753-24181f06-11f1-481e-97a8-593bf0ca534d.png">

![Screen Shot 2021-11-11 at 2 26 53 PM](https://user-images.githubusercontent.com/92570828/141250791-620b7e1d-401c-4dbe-84d0-13eedecccbe6.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone12] simulator
 - OS: [e.g. iOS15.0]
 - SDK Version [e.g. 4.4.0]

**Additional context**
May be  There has anther  problem,  The activityIndicatorView can't show

**Comment by descorp** [comment]
Hey @yuchuanxing 

Could you share a code snippet of your DropInComponent initialisation?

**Comment by yuchuanxing** [comment]
`    

        guard let configuration = self?.environment.adyenPaymentConfiguration else {return}
            if (self?.defaultRepository?.getUserProfile()?.userId) != nil {
                configuration.card.showsStorePaymentMethodField = true
            } else {
                configuration.card.showsStorePaymentMethodField = false
            }
            configuration.applePay = ApplePayComponent.Configuration(summaryItems: [
                PKPaymentSummaryItem(
                    label: "CSCSW, Inc",
                    amount: NSDecimalNumber(decimal: Decimal(request.decimalAmount)),
                    type: .final
                ),
            ], merchantIdentifier: self?.environment.adyenAppleMerchantID ?? "", allowOnboarding: false)
            
            configuration.payment = Payment(
                amount: Amount(
                    value: Int(request.zeroDecimalAmount),
                    currencyCode: "USD"
                ), countryCode: "US"
            )

            let dropInComponent = DropInComponent(
                paymentMethods: paymentMethods,
                configuration: configuration,
                style: .cscgoStyle,
                title: Localizations.Wallet.paymentMethods
            )

            dropInComponent.delegate = self
            viewController.present(dropInComponent.viewController, animated: true)
            self?.dropIn = dropInComponent
`

**Comment by descorp** [comment]
hm.. 

```swift
self?.dropIn = dropInComponent
```

I assume that you are calling this code in closure with `[weak self]`?
Any chance that `self` already destroyed when that line is hit?

**Comment by yuchuanxing** [comment]
![](https://user-images.githubusercontent.com/92570828/141250753-24181f06-11f1-481e-97a8-593bf0ca534d.png)
我可以弹出这个页面，但是当我点击 ‘Apply Pay’ 或者 ‘Credit Card’ 的是时候， 如果点击的是图片，可以跳转到下一个页面，但是如果是点击的是文字， 需要多点击几次才可以跳转。

**Comment by descorp** [comment]
Sorry, would you mind translating? 😅

**Comment by yuchuanxing** [comment]
I mean when I  click the icon of  'Apple Pay' , it works, but when I click the  text of 'Apple Pay', sometimes it doesn't
work.    it's same situation with my  iPhone 7 mobile

**Comment by yuchuanxing** [comment]
sorry for my poor English,   I will give you a video about the  ticket

https://user-images.githubusercontent.com/92570828/141270997-7610932a-6bc6-4751-af7c-cf29ca85fab7.mov

**Comment by descorp** [comment]
No worries :)
Video is very helpfull!

This is very interesting case.
I can not reproduce it on my end with same setup 🤔

Can you run [AdyenUIHost](https://github.com/Adyen/adyen-ios/tree/develop/Demo) demo app that we ship along the SDK to verify if this is specific toy your dev setup or to your application?

**Comment by yuchuanxing** [comment]
I run the demo , it's correct, and I check my code , I found  my fault.  when I  delete the following code ,  it works! 

`extension UIStackView {
    override open func touchesEnded(_: Set<UITouch>, with _: UIEvent?) {
        endEditing(false)
    }
}
`

**Comment by yuchuanxing** [comment]
I fixed it
