### ISSUE TITLE
[NEED ASSIST] Apple pay doesn't return

### ISSUE THREAD

**Issue by geterkan** [Adyen/adyen-ios#706]
Hey,

I'm trying to implement Apple pay with Adyen but have a problem. 

**Describe the challenge**
Tried payment with `ApplePayComponent` and authorized with faceid successfully, but it doesn't return or trigger anything just shows not complete error after 10-15 sec.

Same with these:
https://github.com/stripe/stripe-ios/issues/1467
https://developer.apple.com/forums/thread/91837
https://community.shopify.com/c/shopify-discussions/apple-pay-payment-won-t-complete/m-p/807508

**What steps did you take?**
Regular Apple pay payment with `ApplePayComponent`

**What is the expected behavior / API ?**
Should trigger `PaymentComponentDelegate.didSubmit` callback after authorization via faceid/touchid. 

Adyen SDK version : 4.3

Thanks for your help in advance,
Erkan

**Comment by descorp** [comment]
Hey @geterkan 

Have you tried with different devices?
Can you make payment with the devices on [ApplePay Demo page](https://applepaydemo.apple.com/) ?

**Comment by geterkan** [comment]
Thank you for quick response @descorp 

- It works on demo page 
- I havent tried different device yet. 
- didSubmit is not triggered
- I have a strong reference to the component.

Then I will try another device first.

**Comment by geterkan** [comment]
Yeah it was because of the device. I just reset the device and it is working now.
Thanks for your reply again.

**Comment by descorp** [comment]
Thanks for sharing @geterkan 💚

We had similar situation with one of the test devices. Indeed, factory reset did the job for us as well.
