### ISSUE TITLE
[NEED ASSIST] PaymentComponentData to dictionaryRepresentation

### ISSUE THREAD

**Issue by RajaZahid** [Adyen/adyen-ios#709]
In v3 we were able to get dictionaryRepresentation for PaymentComponentData but in latest version we can only use encodable. 
Is this still possible to get dictionaryRepresentation from PaymentComponentData ?

**Comment by mohammedDehairy** [comment]
Hi @RajaZahid ,

`dictionaryRepresentation` was a hack to get around the fact that `PaymentMethodDetails` is an opaque  protocol and you can't JSON encode it without knowing the concrete type, but now all you need to do is the following:

```Swift
internal func didSubmit(_ data: PaymentComponentData, for paymentMethod: PaymentMethod, from component: DropInComponent) {
        let jsonData = try? JSONEncoder().encode(data.paymentMethod.encodable)
   }

or 

func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        let currentConfiguration = ConfigurationConstants.current
        let amount = data.amount ?? currentConfiguration.amount
        
        try container.encode(data.paymentMethod.encodable, forKey: .details)
        /// The rest ....
    }
```

**Comment by descorp** [comment]
Due to the lack of activity, I am going to close this ticket.
Feel free to reopen if you need additional feedback.
