### ISSUE TITLE
Cathrage build faild

### ISSUE THREAD

**Issue by kwkatbabel** [Adyen/adyen-ios#71]
After adding ``github "adyen/adyen-ios" `` and running ``carthage update --platform iOS``

*** Fetching adyen-ios
*** Checking out adyen-ios at "2.8.1"
*** xcodebuild output can be found in /var/folders/2_/nh34n6t56dn9tnmjkdrvk7980000gp/T/carthage-xcodebuild.TimPQR.log
*** Building scheme "Adyen" in Adyen.xcworkspace
*** Building scheme "AdyenApplePay" in Adyen.xcworkspace
*** Building scheme "AdyenCard" in Adyen.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/weikeat/Documents/Babel/babel-fit-app/ios/Carthage/Checkouts/adyen-ios/Adyen.xcworkspace -scheme AdyenCard -configuration Release -derivedDataPath /Users/weikeat/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/adyen-ios/2.8.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/2_/nh34n6t56dn9tnmjkdrvk7980000gp/T/adyen-ios SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/weikeat/Documents/Babel/babel-fit-app/ios/Carthage/Checkouts/adyen-ios)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/2_/nh34n6t56dn9tnmjkdrvk7980000gp/T/carthage-xcodebuild.TimPQR.log

**Comment by joostvandijk** [comment]
Hi @kwkatbabel,

We're working on fixing this issue. In the meanwhile, you can use version 2.8.0.

With kind regards,

Joost

**Comment by joostvandijk** [comment]
Issue should be resolved with 2.8.2!
