### ISSUE TITLE
[BUG] AMEX

### ISSUE THREAD

**Issue by badredaha** [Adyen/adyen-ios#710]
**Describe the bug**
Amex (e.g: 3451 7792 5488 348 ) **The drop UITextField show a red error ** -> `The entered card brand isn't supported`
**To Reproduce**

1. Show DropIn
2. Tape Amex card text edit 
3. See error In Red

**Screenshots**

![Screenshot 2021-11-16 at 12 30 47](https://user-images.githubusercontent.com/3824662/141977799-584e245e-bd48-4c47-9ca9-5d521c3eff5c.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS 15
 - SDK Version DropIn 4.2.0

**Comment by descorp** [comment]
Hey @badredaha 

Could you check if amex in a list of `brands` in PaymentMethods:

```
{
      "name" : "Credit Card",
      "brands" : [
        "mc",
        "visa",
        "amex",
        "maestro",
        "cup",
        "diners",
        "discover",
        "jcb",
      ],
      "type" : "scheme"
    },
 ```

**Comment by badredaha** [comment]
Hey @descorp 

I confirm that we don't receive amex in payment methods.

Thx for your responses Sorry for the inconvenience :/ I will close this one.
