### ISSUE TITLE
XCode 10.2.1 + Adyen 2.8.1 + SWift 4.2 cannot be imported by the Swift 5.0.1 compiler

### ISSUE THREAD

**Issue by mkharibalaji** [Adyen/adyen-ios#72]
Hi Team,
         I am trying to use a react native plugin AdyenReactNative Pod which internally uses Adyen Pod,

Pod Version
Installing Adyen (2.8.1)
Installing Adyen3DS2 (0.9.6)
Installing AdyenInternal (2.8.1)
Installing AdyenReactNative (1.2.0)

AdyenReactNative.swift:2:8: error: **module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0.1 compiler**: /Users/mkharibalaji/reactnative/fermynt/node_modules/adyen-react-native/ios/Adyen.framework/Modules/Adyen.swiftmodule/arm.swiftmodule
import **Adyen**

Any help would be great.

When surfed through the bug it sounds to be a common issue for iOS developers across various product SDK which would support XCode 10.2 to recompile it with swift 5 with XCode 10.2.I am even worried what would happen if we are to upgrade to XCode 11 with new features.

Similar issue on another Payment SDK,

https://github.com/razorpay/razorpay-pod/issues/56

Right now is a blocker for us.All that we require is a Swift 5 compiled version of Adyen framework pod

Thanks & regards,
Hari

**Comment by joostvandijk** [comment]
Hi @mkharibalaji,

We did an update yesterday that set the pod's version to Swift 5.0. Could you try again with this latest version?

Kind regards,

Joost

**Comment by mkharibalaji** [comment]
@joostvandijk - It's fixed.

Thanks a lot for the quick turn around !!!
