### ISSUE TITLE
[BUG] Payment with stored BCMC card shows "Pay with MasterCard" in confirmation modal

### ISSUE THREAD

**Issue by xanderdeseyn** [Adyen/adyen-ios#721]
1. Add a bancontact (BCMC) card as stored payment method
2. Make payment with it through the dropin
3. Confirmation modal says "MasterCard" instead of Bancontact

**Comment by descorp** [comment]
Hey @xanderdeseyn 

Thank you for reaching out.

What SDK version are you using?
Were you using `BCMCComponent` or `CardComponent`?

**Comment by xanderdeseyn** [comment]
We were using the Dropin, no specific component. Version 4.1.0.

**Comment by descorp** [comment]
Thanks.

`bancontact` cards are often a dual-branded cards, and if it is available on your CA - there are 2 components available on DropIn:
BCMC and Card. Which one were you using?

![Screenshot 2021-12-01 at 13 00 52](https://user-images.githubusercontent.com/2648655/144231051-2b43eb88-3e1d-4271-b5a2-e98a7699c1be.png)

**Comment by descorp** [comment]
OK, I was able to reproduce the behaviour.
Seems like a bug on our side, indeed!

**Comment by xanderdeseyn** [comment]
Ok! Is there a workaround in the meantime?

**Comment by descorp** [comment]
Sorry, no workaround for now 🙁
We are working on fix.

**Comment by xanderdeseyn** [comment]
Fix is working!

**Comment by descorp** [comment]
Sorry for the inconvenience 😅
I'm going to close this thread for now and will share here when the original issue is fixed on our server.
