### ISSUE TITLE
[NEED ASSIST] App clip support

### ISSUE THREAD

**Issue by bonmw** [Adyen/adyen-ios#722]
**Describe the challenge**
We are developing an AppClip and wish to use Adyen payments. However, it's not possible to use URL Schemes/Universal links to invoke an AppClip, which is needed to complete the payment flow for 3DS verifications.
Is there any possibilities for a work around?

Can we use a regular https-url to end up on a web page instead of redirecting back to the app? Currently it doesn't seem to work.
How can we complete the payment flow once we forwarding the app again from a third party app?

Thanks

![IMG_2FB35D62EF74-1](https://user-images.githubusercontent.com/95345576/144215145-4b509736-c989-498c-bd89-754253b4ef24.jpeg)

**Comment by descorp** [comment]
Hey @bonmw 

Thanks for reaching out!

This is an interesting case 🤔
There is a potential workaround: when user completes the payment, your API should receive a weebhook with payment status within few minutes. 
You can try relying on some sort of real-time communication with your API (polling, web-sockets, push notification etc)

**Comment by bonmw** [comment]
Hi @descorp
Thanks for your quick response.
I don't fully understand the second solution by letting the web-page handle `payment/details`. Do you mean to first let the app handle the initial `payment/methods` etc and pass our web-page as the `returnUrl`, because that does not seem to work. That's the screen shot I attached above. 

Or did you mean to redirect the whole checkout flow instead of using the native components?

**Comment by descorp** [comment]
yes, I was thinking if you can pass `"returnUrl": "https://your-company.com/...",` for [/payments](https://docs.adyen.com/api-explorer/#/CheckoutService/v68/post/payments) request.

Are you using DropIn or CardComponent?
On a screenshot - is this the URL from **action** that you receive as response to `/payments`?
Could you attach a video?

**Comment by bonmw** [comment]
Yes, we are using drop-in. This is was happening when I'm setting a regular https url that is not universal link as the `returnUrl` and using a 3DS 1 card (one of the test cards):
https://user-images.githubusercontent.com/95345576/144383721-374a823d-1c57-4594-b207-403b5df823fc.MP4

I'm getting this response then:
      "method" : "POST",
```
      "paymentMethodType" : "scheme",
      "type" : "redirect",
      "url" : "https:\/\/test.adyen.com\/hpp\/3d\/validate.shtml"
```

**Comment by descorp** [comment]
Hey @bonmw 

> "method" : "POST",

I see. This must be misconfiguration on CA.
Mobile is not capable of handling "POST" requests.
Do you send `"channel": "iOS"` on `\payments` ?

**Comment by bonmw** [comment]
That seems to work! Thanks!
 Is there any other side effects of hard setting those parameters to "GET"?

**Comment by descorp** [comment]
It is safe to do on Mobile.
Just make sure to remove it for web or api-only flow.

**Comment by descorp** [comment]
I am going to close this ticket for now.
Feel free to reopen if necessary!

**Comment by bonmw** [comment]
Great, thanks!

**Comment by alex-tiqets** [comment]
Hey @descorp,

We are facing a similar problem. As it has almost been two years, I wonder if there are better ways of handling this.

Just got a reply from technical support engineer at Apple confirming that app clips don't support redirects and recommending this approach:
> If you want your users to go back to your App Clip, use `SFSafariViewController` to show the web page in the App Clip. Once the user finishes the payment, they can dismiss the view controller

Does the DropIn support using `SFSafariViewController`? Do you know if there's a way to redirect back to it without using deep linking scheme?

Thanks,
Alex

**Comment by descorp** [comment]
Hey @alex-tiqets 

> Does the DropIn support using SFSafariViewController? Do you know if there's a way to redirect back to it without using deep linking scheme?

You can use [adyen-web](https://github.com/Adyen/adyen-web).

If AppClip supports PushNotifications - try approach above.

**Comment by alex-tiqets** [comment]
Thanks for quick response Vladimir.

> You can use [adyen-web](https://github.com/Adyen/adyen-web)

To start and complete the entire checkout flow in `SFSafariViewController`? What if we are taken to another app for authorization, we'd still be facing the same problem. Or do you mean just doing the entire flow in Safari?

> If AppClip supports PushNotifications - try approach above

Just to confirm:

We set a web URL as `returnURL` → after authorization is complete, Safari is opened with this URL where we complete the transaction and notify the user that the payment was successfully completed → send a push notification back to App Clip to dismiss the payment flow and present successful order screen.

Am I getting this right?

**Comment by descorp** [comment]
> Am I getting this right? 

Yes, something like this :)
We haven't tried this flow from our side, so please let us know if there are any flaws.
