### ISSUE TITLE
provideAdditionalDetails 3D-Secure 2.0 Quick Integration ?

### ISSUE THREAD

**Issue by mkharibalaji** [Adyen/adyen-ios#73]
Hi Team,
          Does the QuickIntegration sdk  still require a custom implemntation of provideAdditionalDetails ? If it has to be handled how to handle it - Any example Please ...?

**provideAdditionalDetails(_:for:detailsHandler:)** in PaymentControllerDelegate is now required to be implemented. This is the entry-point for 3D-Secure 2.0 (and WeChat Pay). If you don't do 3D-Secure 2.0 or WeChat Pay, you can leave the implementation empty.

Thanks & regards,
Hari

**Comment by joostvandijk** [comment]
Hi @mkharibalaji,

If you use the Quick Integration (`CheckoutController`), you don't need to implement this method (it's not in the `CheckoutControllerDelegate`). If you're using Custom Integration (`PaymentController`), you need to implement it to support 3D Secure 2 and WeChat Pay. An implementation example can be found in our custom integration example.

Kind regards,
Joost

**Comment by mkharibalaji** [comment]
@joostvandijk .Thanks a lot
