### ISSUE TITLE
CheckoutControllerDelegate in 3.0.0?

### ISSUE THREAD

**Issue by caddac** [Adyen/adyen-ios#74]
3.0.0 was just released, looks like the CheckoutControllerDelegate was removed? The docs at https://docs.adyen.com/checkout/ios-sdk/ still reference it. 

Can you please confirm how the ios integration should be accomplished in 3.0.0? Using Drop-in per the readme?

**Comment by joostvandijk** [comment]
Hi @caddac,

We're actively working on updating the documentation and hope to publish it soon. Adyen Components is a new way of integrating, so it also requires some changes on the backend. Our README is a good place to start with the Drop-in, but you can also wait for the full documentation to go live.

Of course, the previous version (2.x.x) will continue to be supported.

Kind regards,

Joost

**Comment by caddac** [comment]
Any ETA on the new documentation for 3.0.0?

**Comment by joostvandijk** [comment]
We expect it to be published before the end of the month.

**Comment by bukira** [comment]
is the documentation there yet?

**Comment by diegomarcon** [comment]
Hi @bukira,

Yes, the v3.0.0 documentation is available at: https://docs.adyen.com/checkout/ios/

**Comment by bukira** [comment]
Thanks,

Is there a sample app?

**Comment by diegomarcon** [comment]
Hi @bukira, 

Right now only the UIHost app has the basics on how to instantiate and present the components/Drop-in. 

More complete examples will follow on the next few releases.

**Comment by bukira** [comment]
Hi,

This crashes on the following:

**Comment by caddac** [comment]
Docs for 3.0.0 look awesome. However, are the docs for 2.8.4 available anywhere still?

**Comment by diegomarcon** [comment]
Hi @caddac,

Thanks for the feedback :)

The docs for the previous version can be found at: https://docs.adyen.com/checkout/ios-sdk/

Cheers,

**Comment by diegomarcon** [comment]
Hi @bukira,

Can you share more information on the error itself?

Also, the UIHost has a dependency to the 3ds2-sdk, so you need to run `carthage bootstrap` on the main directory for setting it up.

I'll close this issue as it is related to docs, but feel free to open a new one with the specific error and extra information like Xcode version.

Cheers,
