### ISSUE TITLE
Issue with the implementing Drop-In delegate

### ISSUE THREAD

**Issue by yogita1071** [Adyen/adyen-ios#758]
Hi,

I am facing an issue when integrating the Adyen SDK 4.6.1 version.
While conforming to the "DropInComponentDelegate", it is showing the error.
I have already added the methods but it's still showing me the below error.
<img width="788" alt="Screenshot 2022-01-10 at 9 05 10 PM" src="https://user-images.githubusercontent.com/82076998/148793121-4e57c844-01a3-447b-9bdc-dae45fa07264.png">

**Comment by descorp** [comment]
Hey @yogita1071 

What happens when you click "Fix" button ?

**Comment by yogita1071** [comment]
It adds one more “didsubmit” delegate method. 
i have tried clean build folder. Also removed the derivedata.

**Comment by descorp** [comment]
Hm.. This is some weird Xcode behaviour. What Xcode is this? 
It could be a result of something else on the page being broken.. 

Could you try commenting `extension ISACAdyenIntegration: DropInComponentDelegate` and build without it?
Then start with first writing `extension ISACAdyenIntegration: DropInComponentDelegate { }` and when error apepars press "Fix".. 🤔

**Comment by yogita1071** [comment]
I am using Xcode 12.5, let me try this solution then. 
Thanks

**Comment by contentadyen** [comment]
Hi there - how do ***@***.*** unsubscribe from these emails?

**Comment by yogita1071** [comment]
Hi,

I am getting this message .
<img width="1393" alt="Screenshot 2022-01-11 at 10 56 58 AM" src="https://user-images.githubusercontent.com/82076998/148886287-67f6676c-8a1f-4823-b3ce-0a4c1fe60fc8.png">

Candidate has non-matching type '(PaymentComponentData, PaymentMethod, DropInComponent) -> ()'

**Comment by descorp** [comment]
Were you able to compile without the `extension ISACAdyenIntegration: DropInComponentDelegate` ?
Do you have any other class / 3rd party dependency with a name `PaymentMethod`, `PaymentComponentData`, `DropInComponent ` e.t.c. ?

**Comment by yogita1071** [comment]
Hi, 
Yes, I am able to compile successfully without the "extension ISACAdyenIntegration: DropInComponentDelegate".
No, we do not have any other third party library with the names PaymentMethod, PaymentComponentData, DropInComponent. Only Adyen SDK.

**Comment by descorp** [comment]
When you see this error, you can't compile?
Could maybe try to do same thing on a blank new project?

Sorry, I am running out of ideas 😅
The only thing I can think of is a name conflict (e.x. `PaymentComponentData`) or just a random weird Xcode behaviour that usually disappear after you clean and recompile..

**Comment by yogita1071** [comment]
I have tried with the new Xcode 13.2.1. The same error appears.
For the other component, it is working fine. :-(

**Comment by descorp** [comment]
Have you tried blank project?

**Comment by yogita1071** [comment]
Yes, I tried with the empty project. It might be possible it is breaking when I upgrade to the latest version.
Let me try then updating the SDK again. I will get back to you soon.

**Comment by lorderster** [comment]
please, can you check if PaymentMethod is not declared twice in your project? it will conflict with the PaymentMethod declared in the Adyen framework.

**Comment by yogita1071** [comment]
Sure. thanks

**Comment by descorp** [comment]
I am going to close this thread due to lack of activity.
Feel free to continue discussion in here.
