### ISSUE TITLE
Adyen 2.8.3 + Sofort/GiroPay + Test Account

### ISSUE THREAD

**Issue by mkharibalaji** [Adyen/adyen-ios#76]
Hi Team ,
       I am getting the below error after integrating Adyen 2.8.3 + Sofort/GiroPay + Test Account

![image](https://user-images.githubusercontent.com/5992474/59759495-d5793a00-92ad-11e9-9b5f-76f3cb127125.png)

Any Idea on why am i getting this error and the redirect is not sending back the repsonse.

Thanks & regards,
Hari

**Comment by joostvandijk** [comment]
Hi @mkharibalaji,

Are you sure the `returnUrl` specified in your request to `/paymentSession` is correct and registered in your Info.plist?

Best,

Joost

**Comment by mkharibalaji** [comment]
Yep It was my mistake the return url was missed.

Thanks a lot again @joostvandijk  :)
