### ISSUE TITLE
[NEED ASSIST] Start Paypal registration flow in app locally

### ISSUE THREAD

**Issue by geterkan** [Adyen/adyen-ios#769]
Hello Dear Adyen Team,

Is it possible to start Paypal registration flow in app locally?

We currently have this flow together with the checkout flow. An URL starts this flow which comes from BE at the begging of first checkout process. We want to split this unified flow to two different flows. First will be registration and second will be checkout.

Current url to start paypal flow: https://test.adyen.com/hpp/checkout.shtml?u=redirectPayPal&asdasdasdasdasd

Note: We are not using Drop-In components.
Adyen SDK: v4.6.1

**Comment by mohammedDehairy** [comment]
Hi @geterkan ,

This is not supported by DropIn or components out of the box, not sure if its inside the scope of a checkout experience.

But you can just load the PayPal registration url in a safari view controller, would this work?

Mohamed

**Comment by geterkan** [comment]
Hi @mohammedDehairy,

Seems I missed your answer. So sorry.
Regarding the solution we solved it internally by sending corresponsing url from server.

Thanks again @mohammedDehairy 
Erkan
