### ISSUE TITLE
Adyen 2.8.3 SWift <-> ObjC

### ISSUE THREAD

**Issue by mkharibalaji** [Adyen/adyen-ios#77]
Hi Team,
          I basically have a react native app which is using ObjC.So when i tried to implement applicationDidOpenURL i am not able get Adyen Instance and getting this error "Use of undeclared identifier 'Adyen'"

Any help would be great,

......
......
#import <Adyen/Adyen-Swift.h>

- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options {

  BOOL handledAdyen =[Adyen application:app openURL:url options:options];// Use of undeclared identifier 'Adyen'
  
  return handledAdyen;
}

Thanks & regards,
MK HB

**Comment by joostvandijk** [comment]
Hi @mkharibalaji,

We recommend adding a new Swift class that bridges this call to the Objective-C environment. Something like this should work:
```swift
@objc class AdyenObjectiveCBridge: NSObject {
    
    @objc(applicationDidOpenURL:)
    static func applicationDidOpen(_ url: URL) -> Bool {
        Adyen.applicationDidOpen(url)
    }
    
}
```

You can then call it from Objective-C:
```objc
[AdyenObjectiveCBridge applicationDidOpenURL:...];
```

Best,

Joost

**Comment by mkharibalaji** [comment]
Thanks a lot @joostvandijk  :)

It Worked !!!
