### ISSUE TITLE
Localization SDK IOS

### ISSUE THREAD

**Issue by imadghanimi** [Adyen/adyen-ios#775]
Hello,

i have a small problem in the ios SDK, it is that it always takes the default language of iphones, despite passing the desired language in the shopper parameter
Locale (Ex: es-ES or es_ES) and countryCode (Ex: ES).

As you can see in the capture below, we have the payment method displayed in Spanish (it makes sense because it's the return of the api https://checkout-test.adyen.com /v68/paymentMethods), on the other hand the SDK elements always remain in French (default language of iphone)

Please tell us how we are going to proceed so that the SDK will be dynamically translatable

![Simulator Screen Shot - iPhone 11 Pro Max - 2022-02-01 at 10 54 17](https://user-images.githubusercontent.com/12783574/151949526-c11672c5-679f-4e6d-9724-f3f59431adef.png)

**Comment by imadghanimi** [comment]
Thanks for your return,
otherwise, in the new version we don't have Spanish.strings, I have Assets/es-ES.lproj/Localizable.strings , I think the structure has been changed, here is what I have

<img width="344" alt="Capture d’écran 2022-02-01 à 12 29 00" src="https://user-images.githubusercontent.com/12783574/151961563-608fa996-b281-4d82-bc80-c0d8f7a55ce4.png">

**Comment by descorp** [comment]
Hey @imadghanimi 

`Spanish.strings` is just en example. What we suggesting is that you come up with your own naming strategy (main goal: it should be different from `Localizable.strings`) so you can can target those file names based on the language/locale you are trying to enforce.

**Comment by imadghanimi** [comment]
can you tell me in which folder to create the Localizable.strings files

**Comment by descorp** [comment]
Hey @imadghanimi 

You don't need to create new `Localizable.strings`. You need to create `###.strings` files for every language you want your app to support. It could be in any folder (group) in your project, just make sure it is not a folder reference .

**Comment by descorp** [comment]
Hey @imadghanimi 

Do you need any additional help with localisation?

I am going to close this ticket due to lack of activity.
Feel free to continue in this thread.
