### ISSUE TITLE
[BUG] 3DS2 fingerprint is stuck at "Continue" label

### ISSUE THREAD

**Issue by leslieolivier** [Adyen/adyen-ios#778]
When paying with a Mastercard by ING Bank, we have a user who gets stuck during the fingerprint part of the 3ds2 flow.

While handling the `ThreeDS2FingerprintAction` the flow shows a screen asking the user to "Continue". When pressing "Continue" the screen just reloads. So the action never provides a fingerprint we can use to send to our backend.

![unnamed](https://user-images.githubusercontent.com/14924761/152154322-309b8194-82ec-4a87-9b3e-36ba2b19af49.png)

We are using Adyen 4.4.0 with Adyen3DS2 2.2.4.

We would expect the fingerprint part of 3ds2 to be frictionless (i.e. not show any UI), but if it does we would expect the flow to continue after a UI is shown. We are not sure if it's a bug somewhere in the 3ds2 components or an error on the bank's side?

Thanks in advance!

**Comment by mohammedDehairy** [comment]
Hi @leslieolivier ,

are you sure the action was `ThreeDS2FingerprintAction` or `ThreeDS2Action`? because it can happen that if its `ThreeDS2Action` then the finger print + challenge are done together in one go, in this case the SDK submits the finger print internally and gets back a challenge, in this case it seems like an OOB challenge in which the shopper need to go to their banking app to perform the challenge then come back and press continue.

**Comment by mohammedDehairy** [comment]
Hi @leslieolivier ,

 The 3DS2 SDK (according to EMVCo 2.2.0) unfortunately doesn't support automatic redirect to the banking app, unfortunately the shopper has to go to their banking app themselves 😅 , maybe with protocol version 2.3.0 it will be supported.

**Comment by leslieolivier** [comment]
Thanks, can the 3DS2 SDK redirect to a ING webpage where the challenge could occur (i.e. not an app) or is that also not supported?

**Comment by mohammedDehairy** [comment]
Yes, it can be an HTML challenge in 3DS2 protocol (but that's up to the issuer bank), or a 3DS1 challenge which is handled by the redirect component rather than the 3DS2 Component.

**Comment by leslieolivier** [comment]
Ok, thanks. We will then assume that there is some misconfiguration from the bank's side, if the user does not have a banking app.

**Comment by ajacquelin** [comment]
Hello, I was able to reproduce it on my personal credit card on both iOS and Android latest SDK version.
Is there any recommendation on how to fix it ?

**Comment by descorp** [comment]
Hi @ajacquelin 

I would follow an advice of @jreij from Android SDK: this seems like issuer bank misbehaviour, so our support should be able to figure it out and/or contact the bank.
