### ISSUE TITLE
AdyenDropin Build 3.0.0 doesn't build with Carthage 

### ISSUE THREAD

**Issue by bukira** [Adyen/adyen-ios#78]
*** Building scheme "AdyenDropIn" in Adyen.xcodeproj

Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/***/Carthage/Checkouts/adyen-ios/Adyen.xcodeproj -scheme AdyenDropIn -configuration Release -derivedDataPath /Users/crissmyers/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/adyen-ios/3.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/f2/fxh98r9d4cd1v_m1qnll5vyw0000gp/T/adyen-ios SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/***/Carthage/Checkouts/adyen-ios)

from the Carthage log

Carthage/Checkouts/adyen-ios/AdyenCard/3DS2 Component/ThreeDS2ComponentFingerprint.swift:7:8: error: no such module 'Adyen3DS2'

Command CompileSwift failed with a nonzero exit code

** ARCHIVE FAILED **

The following build commands failed:
	CompileSwift normal armv7
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	CompileSwift normal arm64
(3 failures)

**Comment by diegomarcon** [comment]
Hi @bukira,

Can you share more information on your setup? Carthage and xcode version, which cartage command you used, etc?

Can you also try cleaning all cache/derived data and retry with a clean directory?

With latest carthage, new project I get the following:

➜  adyen-ios-carthage-demo carthage version
0.33.0

➜  adyen-ios-carthage-demo carthage update
*** Cloning adyen-ios
*** Fetching adyen-3ds2-ios
*** Checking out adyen-ios at "3.0.0"
*** Checking out adyen-3ds2-ios at "0.9.6"
*** xcodebuild output can be found in .../carthage-xcodebuild.WElK9G.log
*** Downloading adyen-3ds2-ios.framework binary at "0.9.6"
*** Building scheme "Adyen" in Adyen.xcodeproj
*** Building scheme "AdyenDropIn" in Adyen.xcodeproj
*** Building scheme "AdyenCard" in Adyen.xcodeproj

Thanks

**Comment by bukira** [comment]
Hi

Latest Xcode version always and swift 5 (10.2.1)

From my Cartfile.resolved

github "adyen/adyen-3ds2-ios" "0.9.6"
github "adyen/adyen-ios" “3.0.0"

Carthage version 0.33.0

*** Checking out adyen-3ds2-ios at "0.9.6"
*** Checking out adyen-ios at "3.0.0"
*** xcodebuild output can be found in /var/folders/f2/fxh98r9d4cd1v_m1qnll5vyw0000gp/T/carthage-xcodebuild.CTM6De.log
*** Downloading adyen-3ds2-ios.framework binary at "0.9.6"
*** Building scheme "Adyen" in Adyen.xcodeproj
*** Building scheme "AdyenDropIn" in Adyen.xcodeproj
*** Building scheme "AdyenCard" in Adyen.xcodeproj

Ok that worked this, wierd how it didn’t before, I will close the issue


Do you have any documentation of how to integrate the new dropin and how to use Adyen.Appearance and set Billing address


Kind Regards

Criss

**Comment by bukira** [comment]
works this

**Comment by diegomarcon** [comment]
Hi @bukira,

Documentation will be updated before the end of the month on the Adyen website.

Adyen.Appearance is not available on 3.0.0 but we are working on it for 3.1 that should come soon.

Thanks

**Comment by bukira** [comment]
Hi,

At the end of which month will the documentation be updated?

Regards

Criss
