### ISSUE TITLE
[NEED ASSIST] QuickType Autofill Card Number inside TextField

### ISSUE THREAD

**Issue by Kristijan22** [Adyen/adyen-ios#783]
**Describe the challenge**
I would like to know if it's possible to get a QuickType prompt to autofill credit card number into `FormCardNumberItemView` from iCloud Keychain. I see `.textContentType` is properly set to `.creditCardNumber` and based on Apple documentation this should be enough.

I added a couple of cards to both Safari saved cards and wallet but I couldn't get the QuickType to appear.

I'm wondering how to enable this feature.

**Comment by descorp** [comment]
Hey @Kristijan22 

Thanks for reaching out!
To my knowledge credit card autofill is only available on Safari and SFViewController.
`textContentType` is mostly for UI/UX and fully controlled by Apple.

```
textContentType:

Use this property to give the keyboard and the system information about the expected semantic meaning for the content that users enter... the system can in some cases automatically select an appropriate keyboard and improve keyboard corrections and proactive integration with other text input opportunities. 
```

**Comment by Kristijan22** [comment]
Thank you for the reply! 👍 Unfortunately, it seems to be that way. I was hoping I was just missing some information.
