### ISSUE TITLE
[NEED ASSIST] Option to add Bank Account using Adyen SDK -iOS

### ISSUE THREAD

**Issue by sandeepdhama-vts** [Adyen/adyen-ios#786]
Hi~
I'm using CardComponent on iOS. Creating card components and save credit/debit cards. now our requirement is to add back account same way we add cards for ACH payments. So here are my 2 questions with respect to adding bank account-

1- is there a way we can add Bank Account like cards using Adyen SDK on iOS?
2. Can we use Plaid SDK to add Bank account? does Adyen works with Plaid? 
SDK Version: 4.4.0

**Comment by descorp** [comment]
Hey @sandeepdhama-vts 

> is there a way we can add Bank Account like cards using Adyen SDK on iOS

ACH [supports recurring payment](https://docs.adyen.com/payment-methods/ach-direct-debit), so I believe it should be possible to "store" the account the same way as you store the card.

iOS SDK is mostly a UI wrapper. Usually, all manipulations are done on backend side. You can check this page for more information about [Stored payments](https://docs.adyen.com/online-payments/tokenization/create-and-use-tokens)

If you have any difficulties - I would advise you to reach out for [Adyen Support](https://www.adyen.help/hc/en-us)

> Can we use Plaid SDK to add Bank account? does Adyen works with Plaid?
SDK Version: 4.4.0

I am not familiar with this platform, so I would again advise to reach out [Adyen Support](https://www.adyen.help/hc/en-us).

**Comment by sandeepdhama-vts** [comment]
Thanks @descorp  do we have any class UI to show UI to add bank accounts on iOS?

**Comment by descorp** [comment]
Sorry @sandeepdhama-vts 

We are still investigating this question..
I will get back to you when have more information.

**Comment by erenbesel** [comment]
Hello @sandeepdhama-vts 
Sorry for the late response. We are adding this functionality on our upcoming v5 release. The `ACHDirectDebitComponent` will have the option to store the payment method and the Drop-in will display it in the stored payment methods list.

**Comment by mohammedDehairy** [comment]
v5 has been released with the mentioned functionality, so will close this issue for now, please feel free to reopen if you're still experiencing issues!.
