### ISSUE TITLE
Valid list of country codes?

### ISSUE THREAD

**Issue by caddac** [Adyen/adyen-ios#79]
Can you please provide a link to the valid list of country codes as needed here: https://docs.adyen.com/checkout/ios/drop-in/#step-1-get-available-payment-methods . 

I've tried `US`, `en_US`, and `en-US` but all return 

`{"status":422,"errorCode":"200","message":"Invalid country code","errorType":"validation"}`.

**Comment by diegomarcon** [comment]
Hi @caddac 

`US` should be valid.

You can try also here:
https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v49/paymentMethods

The following request should return a valid list of payment methods:

```json
{
  "merchantAccount": "YOUR_MERCHANT_ACCOUNT",
  "countryCode": "US",
  "amount": {
    "currency": "USD",
    "value": 1000
  },
  "channel": "iOS"
}
```

If the problem persists, please drop an email to support@adyen.com, so they can help you setup your merchant account.

Regards,
