### ISSUE TITLE
[NEED ASSIST] DropInComponent's viewController wont's dismiss after returning from redirect flow.

### ISSUE THREAD

**Issue by heikkihautala** [Adyen/adyen-ios#796]
DropInComponent's viewController cannot be dismissed or cancelled after returning from `redirectShopper` flow.

In `redirectShopper` flow, after submitting credentials in the webview, our app is returned to, and the delegate method `didProvide` gets called, after which we finish the payment (card details submission in our case) and try to dismiss the DropInComponent. The problem is, it won't dismiss and the cancel button does nothing. Card details can still be edited, and pressing the submit button again does nothing but starts the activity indicator on the button.

I'd expect the dropIn to dismiss the viewController.

This happens only in the redirect flow. The native `threeDS2` flow has no problems. If I cancel the redirect webview, the dropIn's viewController can be dismissed afterwards. Our problem only occurs when the user presses the `Submit` button in the webview which triggers the `returnUrl` redirection and call to `RedirectComponent.applicationDidOpen(from: url)` in the `AppDelegate`.

I also tried dismissing the dropInComponent earlier, right after calling `dropInComponent.handle(action)` as per documentation, but then I get:
```
Attempt to present <SFSafariViewController: 0x13d35c000> on <Adyen.DropInNavigationController: 0x13c378400> (from <Adyen.DropInNavigationController: 0x13c378400>) whose view is not in the window hierarchy.
```

Adyen SDK version: 4.5.0

**Comment by descorp** [comment]
Hey @heikkihautala 

Thanks for reaching out!

How do you dismiss it?

You should dismiss from your checkout viewController:

```swift
myViewController.present(dropinComponent.viewController, animated: true)
...
myViewController.dismiss(animated: true)
```

**Comment by heikkihautala** [comment]
Thanks, that solved it. I was trying to dismiss it through the dropIn:
`dropInComponent.viewController.dismiss(animated: true, completion: nil)`
