### ISSUE TITLE
Language detection

### ISSUE THREAD

**Issue by julienphilbert** [Adyen/adyen-ios#8]
Hello Adyen Team,

I am unable to get the right localisation using your interface.
My interface shows a mix of English and French 

![simulator screen shot - iphone 8 plus - 2017-10-09 at 10 42 59](https://user-images.githubusercontent.com/270344/31330715-c8f4df6a-acdf-11e7-8e0e-e61f796e6ad5.png)

(iPhone is in French)
![simulator screen shot - iphone 8 plus - 2017-10-09 at 10 50 05](https://user-images.githubusercontent.com/270344/31330678-a30ae89e-acdf-11e7-9e23-6129d7c2726b.png)

From my experiments, I think that language is not recognised properly or the interface is not updated with the right file:

I am using these parameters in **paymentDetails**
`"countryCode": "DE",`
 `"shopperLocale": "fr_FR",`
Result: https://www.dropbox.com/s/uvws0qxyhbb5cbh/lang-mix.png?dl=1

To dig a bit more, I changed parameters to:
`"countryCode": "DE",`
 `"shopperLocale": "es_ES",`

As a result I got a mix of Spanish and English (iPhone in French)
https://www.dropbox.com/s/jw7xbdf2w7vek6i/lang-mix2.png?dl=1

Let me know if I can help
Thank you

**Comment by joostvandijk** [comment]
Hi @julienphilbert,

The language of the payment methods are determined by the backend using the shopper locale. The rest of the language is determined by iOS itself. However, it's important to note that iOS will only select the French language for our SDK if the hosting app (your app) also offers French localisation. Is your app localised in French? If not, that's probably why the language isn't selected.

Best,
Joost

**Comment by joostvandijk** [comment]
Hi @julienphilbert,

Do you have an update on this?

Kind regards,
Joost
