### ISSUE TITLE
Cant copy the UIHost App, crashes on environment

### ISSUE THREAD

**Issue by bukira** [Adyen/adyen-ios#80]
I am trying to duplicate th UIHost app in my iOS app for DropinUI, my code below

import Adyen
import AdyenCard
import AdyenDropIn
import Adyen3DS2

extension AGCheckoutViewController: DropInComponentDelegate {
    internal func didSubmit(_ data: PaymentComponentData, from component: DropInComponent) {
        // Should call /payment via merchant backend
        //finish()
    }
    
    internal func didProvide(_ data: ActionComponentData, from component: DropInComponent) {
        // Should call /payment/details via merchant backend
        //finish()
    }
    
    internal func didFail(with error: Error, from component: DropInComponent) {
        //finish(with: error)
    }
}

class AGCheckoutViewController: UIViewController {

private var paymentMethodsAdyen: PaymentMethods?

override func viewDidLoad() {
        super.viewDidLoad()
        // Load payment methods from json file. This should be requested to /paymentMethods endpoint via merchant backend
        if let path = Bundle.main.path(forResource: "PaymentMethods", ofType: "json"),
            let data = try? Data(contentsOf: URL(fileURLWithPath: path)) {
            self.paymentMethodsAdyen = try? Coder.decode(data) as PaymentMethods
        }
    }

@IBAction func makePayment() {
        presentDropInComponent()
    }
    
    private var currentComponent: Component?
    private func presentDropInComponent() {
        guard let paymentMethodsAdyen = paymentMethodsAdyen else { return }
        let configuration = DropInComponent.PaymentMethodsConfiguration()
        configuration.card.publicKey = "<ADD-YOUR-CARD-PUBLIC-KEY>"  <-- I use mine here from the portal 
        
        let component = DropInComponent(paymentMethods: paymentMethodsAdyen, paymentMethodsConfiguration: configuration)
        component.delegate = self
        present(component)
    }
    
    private func present(_ component: PresentableComponent) {
        component.environment = .test
        component.payment = Payment(amount: Payment.Amount(value: Int((basket?.orderTotal?.amount ?? 0.0) * 100), currencyCode: basket?.orderTotal?.currency ?? "GBP"))        
        present(component.viewController, animated: true)
        
        currentComponent = component
    }
    
    private func handle(_ action: Action) {
        if let dropInComponent = currentComponent as? DropInComponent {
            dropInComponent.handle(action)          
            return
        }
    }
}

When I run the app it crashes on line
 component.environment = .test

Environment.swift
Thread 1: EXC_BREAKPOINT (code=1, subcode=0x105d95714)
/// Adyen's default live environment.
    public static let live = Environment.liveEurope

The UIHost app builds so I must be duplicating something incorrectly but I can't figure it out

**Comment by bukira** [comment]
@diegomarcon any ideas on this?

**Comment by diegomarcon** [comment]
Hi @bukira,

Can you run the UIHost from the cloned project?

You can also try cleaning derived data and checking for any redeclaration of Environment.

**Comment by bukira** [comment]
@diegomarcon 

Yes I can run the app from your project fine, but it crashes on my app and I cant see anything that's different, I will clean and delete

**Comment by bukira** [comment]
@diegomarcon I quit Xcode, delete all derived data and did c elan and build and it sill crashes, I did a search for Environment and cant find, unless someone elses third party library has it

**Comment by diegomarcon** [comment]
Can you share: 

- How are you integrating the project (cocoapods/carthage)
- Which xcode/swift version you're in

Thanks

**Comment by bukira** [comment]
Carthage

github "adyen/adyen-ios”

Using caching

Xcode 10.2.1
Swift 5

**Comment by bukira** [comment]
Cart file resolved

github "adyen/adyen-3ds2-ios" "0.9.6"
github "adyen/adyen-ios" “3.0.0"

Embeded binaries
Adyen3DS2.framework
AdyenDropIn.framework
AdyenCard.framework
Adyen.framework

And I import into my viewcontroller

import Adyen
import AdyenCard
import AdyenDropIn

Regards

**Comment by diegomarcon** [comment]
Thanks for the information. 

I'll setup an internal test and get back to you.

**Comment by bukira** [comment]
thanks, I can send email and code via private email,

When It crahses it does the environment.text, then environment.live, then environment.livEurope and then crashes on environment.live a second time

**Comment by diegomarcon** [comment]
I was able to reproduce it locally with a clean project.

It seems to be related with swift compiler optimisations during the carthage build. 

I'll get back to you when I have more info. 

Cheers,

**Comment by diegomarcon** [comment]
Indeed the issue is related to swift compiler optimisations on the `release` profile.

For testing purposes you can use: 
`carthage bootstrap --configuration Debug` 

This will build the frameworks without the compiler optimisations.

In the mean time we will fix the issue and provide a patch in the next few days.

Thanks again for reporting the issue.

**Comment by bukira** [comment]
thanks, glad we found the issue :-)

**Comment by diegomarcon** [comment]
Hi @bukira 

Patch [3.0.1](https://github.com/Adyen/adyen-ios/releases/tag/3.0.1) was released and it fixes the issue.

Let us know if you run into any other issue.

Cheers!
