### ISSUE TITLE
[BUG] Apple Pay infinite loading

### ISSUE THREAD

**Issue by janpodmolik** [Adyen/adyen-ios#800]
**Describe the bug**
Adyen's `ApplePayComponent` is using the deprecated method [paymentAuthorizationViewController(_:didAuthorizePayment:completion:)](https://developer.apple.com/documentation/passkit/pkpaymentauthorizationviewcontrollerdelegate/1616195-paymentauthorizationviewcontroll), saves the `completion` block for later but fails to call it in the future.

The payment itself succeeds, but `ApplePayComponent` doesn't inform PassKit of the result. This results in infinite loading (until iOS times the request out). As this issue wasn't present in Adyen `3.9.1`, we'd like to keep the UX clean and consistent going forward.

**To Reproduce**
1. Use `ApplePayComponent`.
2. Present its view controller.
3. Authorize payment via Apple Pay.
4. Infinite loading occurs.
5. After about 20 seconds, iOS times out.

Reproducibility: 100%

**Expected behavior**
After user authorizes the payment, the Apple Pay modal shows the user that the payment succeeded and dismiss.

**Screenshots**
<img src="https://user-images.githubusercontent.com/55555447/154665797-fedaef89-1968-460f-8820-6da23daca5c1.PNG" width="350">

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 12]
 - OS: [e.g. iOS 15.3.1]
 - SDK Version [e.g. 4.7.0]

**Additional context**
Workaround:
```swift
extension ApplePayComponent: PKPaymentAuthorizationViewControllerDelegate {
    ...

    public func paymentAuthorizationViewController(_ controller: PKPaymentAuthorizationViewController,
                                                   didAuthorizePayment payment: PKPayment,
                                                   completion: @escaping (PKPaymentAuthorizationStatus) -> Void) {
        guard payment.token.paymentData.isEmpty == false else {
            completion(.failure)
            delegate?.didFail(with: Error.invalidToken, from: self)
            return
        }

        paymentAuthorizationCompletion = completion
        let token = payment.token.paymentData.base64EncodedString()
        let network = payment.token.paymentMethod.network?.rawValue ?? ""
        let billingContact = payment.billingContact
        let shippingContact = payment.shippingContact
        let details = ApplePayDetails(paymentMethod: applePayPaymentMethod,
                                      token: token,
                                      network: network,
                                      billingContact: billingContact,
                                      shippingContact: shippingContact)
        
        submit(data: PaymentComponentData(paymentMethodDetails: details, amount: self.amountToPay, order: order))
        
        // MARK: - ISSUE
        // The call to this method is missing somewhere in Adyen.
        // Adding it here fixes this issue.
        finalizeIfNeeded(with: true)
    }
}
```

**Comment by mohammedDehairy** [comment]
@W3xly ,

Thanks for reaching out!.

```Swift
finalizeIfNeeded(with: true|false)
```

This is supposed to be called by you, not us, since only you know if the payment is successful or not, since you make the `payments` call.

so according to the `payments` call response, you should call `applePayComponent.finalizeIfNeeded(with: true|false)`.

Mohamed

**Comment by janpodmolik** [comment]
@mohammedDehairy 

Oh, we can see that now. We had to forget about it when updating to the latest version. I'm really sorry, we are going to test it right away. 

Thanks a lot for quick answer.

**Comment by mohammedDehairy** [comment]
@W3xly 

I would also recommend to test on iOS 14 and lower, and to actively dismiss the applePayComponent instance when the payment call is concluded.

Mohamed
