### ISSUE TITLE
Adyen is defining public extensions on types they don't own

### ISSUE THREAD

**Issue by ffittschen** [Adyen/adyen-ios#802]
**Describe the challenge**
The Adyen SDK is defining a public extension on `URL` in [URLHelpers.swift](https://github.com/Adyen/adyen-ios/blob/4.7.0/Adyen/Helpers/URLHelpers.swift).

As these definitions  are conflicting with extensions within our app, could you please move them behind the [`AdyenScope`](https://github.com/Adyen/adyen-ios/blob/4.7.0/Adyen/Helpers/AdyenScope.swift) as you also do with extensions of other types that you don't own, instead of declaring it as a public extension on URL?

Additionally to `URL`, I also discovered public extensions on `Result` and `View`, which should probably be scoped as well.

**Comment by descorp** [comment]
Hey @ffittschen 

Thank you for the feedback!
Indeed, we will move `URL` to `AdyenScope`.

> public extensions on Result and View, which should probably be scoped as well.

Unfortunately, we cannot use `AdyenScope` with Result because it is generic and with View because it is a protocol.

**Comment by PrabhuShrinivas** [comment]
Hey @descorp any updates on this ? this is blocking us. Thanks

**Comment by descorp** [comment]
Hey @PrabhuShrinivas 

We have applied them on current `develop` branch and planing to release as v5.0.0.
Fix for v4 is possible as well, however we didn't moved forward with this, because it will lead to a breaking change:
we would have to deprecate this method first in v4.7.2, and finally remove in 4.7.3.

I am sorry to hear that this is a blocker for you.
Is it possible to use other property name (at least for now)?

**Comment by batschz** [comment]
@descorp any ETA for v5.0.0?

**Comment by descorp** [comment]
Hey @batschz 

We are planing v5.0.0 release in Q2(hopefully first half).
Currently, we are working on a big release of [Adyen Sessions](https://docs.adyen.com/online-payments/web-drop-in#create-payment-session) for mobile

**Comment by denizgueltek** [comment]
@descorp since Q2 is almost about to end, are there any updates regarding this?

**Comment by descorp** [comment]
Hey @denizgueltek 

Are you asking for v4 or v5 ?

**Comment by denizgueltek** [comment]
Latest updated we had from you @descorp was that this blocker for us will be fixed on v5.0.0 right? So we are waiting for v5.0.0 if nothing has changed from your side? 

> Hey @PrabhuShrinivas
> 
> We have applied them on current `develop` branch and planing to release as v5.0.0. Fix for v4 is possible as well, however we didn't moved forward with this, because it will lead to a breaking change: we would have to deprecate this method first in v4.7.2, and finally remove in 4.7.3.
> 
> I am sorry to hear that this is a blocker for you. Is it possible to use other property name (at least for now)?

**Comment by descorp** [comment]
Sorry for a loooong reply.
We have going to remove it next major release for v4
PR is [here](https://github.com/Adyen/adyen-ios/pull/996)

**Comment by mohammedDehairy** [comment]
since this has been fixed, will close this issue for now, please feel free to reopen or create a new issue if you're still experiencing issues!.
