### ISSUE TITLE
Attempted to read an unowned reference but object 0x6000023e0e60 was already deallocated

### ISSUE THREAD

**Issue by caddac** [Adyen/adyen-ios#82]
I'm getting this error after I select `Credit Card` from the Payment Method selection UI. I'm using 3.0.0 and Drop-In components. The reference in my error message is the `Adyen.DropInComponent` as seen here: 
![Screen Shot 2019-07-02 at 1 42 08 PM](https://user-images.githubusercontent.com/5695743/60537975-4a496c80-9ccf-11e9-939d-e4f33761e3d6.png)

My app has a single ViewController (the default one for a single view app) and it is also the delegate for Drop-In. 

Any ideas why I'm getting this error?

**Comment by caddac** [comment]
Quick update, I've also tried this using a separate UIViewController for the `DropInComponentDelegate` implementation, however I'm still getting this same error

**Comment by caddac** [comment]
OK, not sure whats going on here, but if I put a break point here: https://github.com/Adyen/adyen-ios/blob/671aa710adf73251a6fa10844ad02969975c09d7/AdyenDropIn/DropInComponent.swift#L72 and just let it stop there, then hit continue, it works and I get the Credit Card entry screen.

**Comment by diegomarcon** [comment]
Hi @caddac,

Are you holding a strong reference to the DropInComponent that is being presented?

**Comment by caddac** [comment]
Not sure if this answers your question, but if I implement the delegate on the ViewController (the only view controller in the entire app) then everything works, but only if I have the breakpoint (referenced above) in place. 

Here is the implementation where I show the drop in. 
```
@objc func pressedAction(_ sender: UIButton) {
        withPaymentList() { (paymentMethods) in
            let configuration = DropInComponent.PaymentMethodsConfiguration()
            configuration.card.publicKey = "my_public_key...."

            let dropInComponent = DropInComponent(paymentMethods: paymentMethods,
                    paymentMethodsConfiguration: configuration)
            dropInComponent.delegate = self
            dropInComponent.environment = .test
            self.present(dropInComponent.viewController, animated: true)
        }
    }
```

**Comment by diegomarcon** [comment]
It seems that the dropInComponent is being deallocated, because no strong reference is kept to that object.

You can extract the dropInComponent to a class variable, keeping the reference. for example: 

```
var dropInComponent: DropInComponent?

@objc func pressedAction(_ sender: UIButton) {
        withPaymentList() { (paymentMethods) in
            let configuration = DropInComponent.PaymentMethodsConfiguration()
            configuration.card.publicKey = "my_public_key...."

            dropInComponent = DropInComponent(paymentMethods: paymentMethods,
                    paymentMethodsConfiguration: configuration)
            dropInComponent?.delegate = self
            dropInComponent?.environment = .test

            if let viewController = dropInComponent.viewController {
                 self.present(viewController, animated: true)
            }
        }
    }
```

Let me know if this helps.

**Comment by phamquocthang** [comment]
> It seems that the dropInComponent is being deallocated, because no strong reference is kept to that object.
> 
> You can extract the dropInComponent to a class variable, keeping the reference. for example:
> 
> ```
> var dropInComponent: DropInComponent?
> 
> @objc func pressedAction(_ sender: UIButton) {
>         withPaymentList() { (paymentMethods) in
>             let configuration = DropInComponent.PaymentMethodsConfiguration()
>             configuration.card.publicKey = "my_public_key...."
> 
>             dropInComponent = DropInComponent(paymentMethods: paymentMethods,
>                     paymentMethodsConfiguration: configuration)
>             dropInComponent?.delegate = self
>             dropInComponent?.environment = .test
> 
>             if let viewController = dropInComponent.viewController {
>                  self.present(viewController, animated: true)
>             }
>         }
>     }
> ```
> 
> Let me know if this helps.

I have same issue. Successfully fixed it by applying to approach

**Comment by caddac** [comment]
Perfect, that fixes it. Thanks!
