### ISSUE TITLE
[NEED ASSIST] 

### ISSUE THREAD

**Issue by Venkat1128** [Adyen/adyen-ios#825]
**Describe the challenge**
We are using cardComponent and would like to customize field names? is there a way to do this? (Ex: Security Code Instead CVV)

**Comment by mohammedDehairy** [comment]
@Venkat1128 ,

Thanks for reaching out!.

You can do this by creating a `Localizable.strings` file in your app bundle and override the keys in the SDK bundle, for example for `Security Code Instead CVV` you can override the key `"adyen.card.cvcItem.title" = "Security Code";` in the `Localizable.strings` in your app bundle .

Mohamed

**Comment by Venkat1128** [comment]
That's great Thanks @mohammedDehairy
