### ISSUE TITLE
[NEED ASSIST] 3DS2  how to convert "ActionComponentData.details" to String

### ISSUE THREAD

**Issue by zhangduyu** [Adyen/adyen-ios#828]
**Describe the bug**

Base on the document from https://docs.adyen.com/online-payments/3d-secure/native-3ds2/ios-component 

“After completing the required authentication, the Component invokes the didProvide method from the ActionComponentDelegate. Get the contents of **data.details** and **data.paymentData**, and pass this to your server. Dismiss the Component immediately, or wait until you have submitted the details to your server."

After I got "data.details" from  didProvide method, I need to convert data.details to a string as my '/payments/details’ API only accept String as the value of parameter.

Is there a way I can covert data.details to a string?

**Screenshots**
![image](https://user-images.githubusercontent.com/7981548/157175169-e83094d2-0f69-430e-b99c-90830a8b3553.png)

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS
 - SDK Version 4.4.0

**Comment by descorp** [comment]
Hey @zhangduyu 

Thank you for reaching out.
Yes, you have to wrap it in `Encodable` container:

```swift
struct EncodableActionData: Encodable {
    let data: ActionComponentData

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data.details.encodable, forKey: .details)
        try container.encode(data.paymentData, forKey: .paymentData)
    }

    private enum CodingKeys: String, CodingKey {
        case details
        case paymentData
    }
}

...

// Then you can encode the container
let encodableActionData =  EncodableActionData(data: data)
let jsonData = try? JSONEncoder().encode(encodableActionData)

// Then to  
let jsonString = String(data: jsonData, encoding: .utf8)

// Or Base 64
let base64String = jsonData.base64EncodedString()
```

**UPD**

Or, if you only need `details` - you can use 

```swift
let detailsData = try? JSONEncoder().encode(data: data.details.encodable)

// Then to  
let jsonString = String(data: detailsData, encoding: .utf8)

// Or Base 64
let base64String = detailsData.base64EncodedString()
```

**Comment by zhangduyu** [comment]
Thanks, helped a lot.

Here is the code sample may help someone with the same problem.

` var details:ThreeDS2Details = data.details as! ThreeDS2Detail
   let jsonEncoder = JSONEncoder()
   et jsonData = try! jsonEncoder.encode(details.encodable)
   let detailsStr = String(data: jsonData, encoding: String.Encoding.utf8)`
