### ISSUE TITLE
[BUG] Custom 'Card Component' UI style FormComponentStyle.footnoteLabel not working

### ISSUE THREAD

**Issue by zhangduyu** [Adyen/adyen-ios#837]
**Describe the bug**
Hi,
I found it's not working when I was working on customize the 'Card Component' FormComponentStyle.footnoteLabel UI.
FormComponentStyle.textField is working normally.
Could you please help to take a look?

**Screenshots**
![image](https://user-images.githubusercontent.com/7981548/159907945-86999277-798d-4e33-a83c-467516b2f9c1.png)

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 15
 - SDK Version: the latest
**Additional context**
Here is my code:
`      var style = FormComponentStyle();
        //
        let textColorBlack = UIColor.init(red: 16/255.0, green: 17/255.0, blue: 37/255.0, alpha: 1)
        let textColorGray = UIColor.init(red: 167/255.0, green: 169/255.0, blue: 191/255.0, alpha: 1)
        
        //
        let notaSansBoldFont = UIFont(name: "NotoSans-Bold", size: 14)
        let notaSansFont = UIFont(name: "NotoSans", size: 16)
        //
        var textField = FormTextItemStyle()
        
        // title(Card number/Expire date/CVV)
        var titleTextStyle = TextStyle(font:notaSansBoldFont!, color: textColorBlack);
        titleTextStyle.textAlignment = .left;
        textField.title = titleTextStyle;
        
        style.textField = textField
        
        // Error code
        let notaSansFont2 = UIFont(name: "NotoSans", size: 14)
        var footnoteLabelTextStyle = TextStyle(font:notaSansFont2!, color: UIColor.red);
        footnoteLabelTextStyle.textAlignment = .center;
        style.footnoteLabel = footnoteLabelTextStyle`

**Comment by zhangduyu** [comment]
There are 2 more questions:
1 Is there a way I can modify the height of 'Save Card' Toggle?
2Is there a way I can modify the height of main button?

**Comment by mohammedDehairy** [comment]
Hi @zhangduyu ,

Thanks for reaching out.

1- its indeed possible to modify the `Save Card` toggle, using `FormComponentStyle.toggle`.
2- No dimensions of UI components can't be modified, except for corner radii.

**Comment by zhangduyu** [comment]
Hi @mohammedDehairy ,
Thanks for you replying, it helped a lot.

For the dimensions of UI components can't be modified, if Adyen can support it both for the Toggle widget and 'Pay' button?

**Comment by zhangduyu** [comment]
BTW is there a way that I can change the Title of Add Credit Card ViewController? 
I can not find the 'Credit Card' text from ".strings" file.

**Comment by mohammedDehairy** [comment]
> If Adyen can support it both for the Toggle widget and 'Pay' button?

I don't think we have plans to enable adjusting the dimensions of UI elements

> is there a way that I can change the Title of Add Credit Card ViewController?

the string 'Credit Card' comes in the `paymentMethods/` call response from Adyen backend, so in theory your code parses that response (either on your backend or in your app), so you can override the name sent by the Adyen backend, we'll try to make it easier to modify the name, but overriding the  `paymentMethods/` call response names is the way to go for now unfortunately.

**Comment by neelSharma12** [comment]
@zhangduyu In v5 there will be an easy way to override the PM name in the DropIn list. So, please keep an eye for our upcoming version 😄
