### ISSUE TITLE
Memory Leak in AdyenToolkit

### ISSUE THREAD

**Issue by jsheetzati** [Adyen/adyen-ios#84]
Seems like there is a memory leak somewhere within AdyenToolkit. I verified the issue is present in the sample app as well.

For every transaction that I perform, instances of ADYPendingTransaction, ADYStatusTenderRunner and ADYTransactionProcessor are showing up as a leak in XCode's memory graph. With this occurring in the sample app, I do not believe it is an issue in our application.

![image](https://user-images.githubusercontent.com/15350893/60616191-898ec080-9d96-11e9-8a5d-286f287bb592.png)

![image](https://user-images.githubusercontent.com/15350893/60616315-c9ee3e80-9d96-11e9-8a3c-b3e700a92ec8.png)

**Comment by diegomarcon** [comment]
Hi @jsheetzati ,

Thanks for reporting the issue, but this repository is for a different Adyen product.

I'll kindly ask for you to email your query to possupport@adyen.com.

Thanks
