### ISSUE TITLE
Android: The "Next" button in the CC-drawer keyboard is not responsive.

### ISSUE THREAD

**Issue by malassen** [Adyen/adyen-ios#843]
**Describe the bug**
The "Next" button on the keyboard in the CC-drawer is responsive on iOS but not on Android. If you have a small screen size and you enter text in the input field "Name on Card" you will not be able to logically/intuitively access the (blue) Pay button (on the bottom, as the final step). If you want to access the Pay button in this scenario you have to click into one of the other input fields or click the native android back button. On iOS the "Next" button minimizes the keyboard and lets you click/access the Pay button.

**To Reproduce**
Use a device with a screen size about 4.5 inches (or smaller.
--

1. Go to the CC-swipeable drawer for CC-information entry
2. Enter/focus the input field "Name on Card"
3. Now try to click "Next" on keyboard and verify that it is inresponsive and that you cant access the Pay button (as the natural next step).

**Expected behavior**
When clicking the "Next" button on the keyboard, the keyboard should minimize itself to reveal the Pay/confirm/finish button.

**Screenshots**

![IMG_2139](https://user-images.githubusercontent.com/102803791/161286972-cf705b42-54e5-4e94-8879-39f7d7a2f56b.JPG)

**Smartphone (please complete the following information):**
 - Device: Small screen size phones like Samsung SM-A320FL or iPhone SE.
 - OS: Android
 - SDK Version:
 

**Additional context**

**Comment by descorp** [comment]
Hey @malassen 

This seems like an issue for https://github.com/Adyen/adyen-android.

**Comment by malassen** [comment]
Hey @descorp, right, is there a way to move it? Feel free to.

**Comment by descorp** [comment]
Hey @malassen 

Unfortunately, there is no way to move it.
`adyen-ios` and `adyen-android` are two independent repos.
Could you copy the content to https://github.com/Adyen/adyen-android/issues ?
It is better if you do so, this way we will keep original author.

**Comment by malassen** [comment]
Allright @descorp.

Closing this and adding an issue to: https://github.com/Adyen/adyen-android
