### ISSUE TITLE
Public key missing for CardComponent.Configuration

### ISSUE THREAD

**Issue by BartlomiejSopalaKarhoo** [Adyen/adyen-ios#845]
According to documentation for showing the available cards in your payment form
https://docs.adyen.com/online-payments/3d-secure/native-3ds2/ios-drop-in#collect-additional-parameters-in-your-payment-form

we should set configuration.card.publicKey, but publicKey is no longer part or CardComponent.Configuration and also is not supported in  version 4.0.0+.

What steps should I take instead of this described above?

**Comment by mohammedDehairy** [comment]
Hi @BartlomiejSopalaKarhoo ,

Thanks for reaching out!

This page in docs is indeed out of date, we're sorry for the inconvenience, you  can find the up to date way of initializing DropInComponent [here](https://docs.adyen.com/online-payments/ios/drop-in#step-2-add-drop-in).

**Comment by descorp** [comment]
Hey @BartlomiejSopalaKarhoo 

Thanks for feedback! 
We updated documentation 💚
