### ISSUE TITLE
Apple Pay + Adyen 2.8.3 -Nothing happens on Clicking

### ISSUE THREAD

**Issue by mkharibalaji** [Adyen/adyen-ios#85]
Hi Team,
        From the standard option of Apple Pay  Click nothing happens - No Crash,literally no apple pay dialog is poping out.

      I am using Adyen 2.8.3.Could you please help on what could be missing.

Thanks & regards,
Hari

**Comment by diegomarcon** [comment]
Hi @mkharibalaji,

Did you follow all the steps on https://docs.adyen.com/payment-methods/apple-pay/#description ?

Are you testing on device or simulator? 

Thanks

**Comment by mkharibalaji** [comment]
Hi @diegomarcon ,
               Yes I am following the steps except step 3 & 4 ,I am not passing the Company Name.

               Missing Step 3 is that a Problem.Because i am using Quick Integration via https://github.com/dmitry-blackwave/adyen-react-native

               It is iPhone XR device.

Thanks

**Comment by diegomarcon** [comment]
Hi @mkharibalaji,

Missing step 3 shouldn't be a problem.

We cannot check the integration via the react native plugin. 
You can either open an issue there or try to reproduce in one of our examples provided with 2.8.3.

Thanks,
