### ISSUE TITLE
Cannot click on Pay in Card Component in Adyen 3.0.1

### ISSUE THREAD

**Issue by brianpham93** [Adyen/adyen-ios#86]
I'm working with new Card Component on Adyen 3.0.1 iOS. After basic setup as in documentation, card component did show up and allow me to enter card details. However, when I click on Pay button, nothing happens.

Below is my code. Basically I need to enter amount into a text field and app will call to backend to get available payment methods, then later check if Card payment is available when click on Credit Card button

```
import UIKit
import Alamofire
import Adyen

class ViewController: UIViewController {
    
    private var paymentMethods: PaymentMethods?
    
    @IBOutlet weak var amountTextField: UITextField!    
    @IBOutlet weak var creditCardBtn: UIButton!
    @IBAction func creditCardBtn_Tapped(_ sender: UIButton) {
        do {
            guard let cardPaymentMethod = paymentMethods?.regular[0] as? CardPaymentMethod else {
                return
            }
            let cardComponent = CardComponent(paymentMethod: cardPaymentMethod, publicKey: "<MY PUBLIC KEY>")           
            cardComponent.delegate = self as! PaymentComponentDelegate
            cardComponent.environment = .test
            present(cardComponent.viewController, animated: true)
        } catch (let e){
            print("Unexpected error: \(e)")
        }
    }
  
    override func viewDidLoad() {
        super.viewDidLoad()
        amountTextField.delegate = self      
    }
}

extension ViewController:UITextFieldDelegate {
    
    func textFieldDidEndEditing(_ textField: UITextField) {
        print("keyed in")
        
        let url = "http://<MY OWN BACKEND URL>/paymentMethods?amount={0}"
        
        Alamofire.request(url.formatWithText([amountTextField.text!])).responseJSON { response in
            do{
                self.paymentMethods = try JSONDecoder().decode(PaymentMethods.self, from: response.data as! Data)            }
            catch {
                print("JSONSerialization error:", response.error)
            }
        }
    }
}


extension ViewController:PaymentComponentDelegate{
    func didSubmit(_ data: PaymentComponentData, from component: PaymentComponent) {
        print(String(data: data as! Data, encoding: .utf8))
    }

    func didFail(with error: Error, from component: PaymentComponent) {
        print("card payment failed \(error)")
    }
}
```

**Comment by joostvandijk** [comment]
Hi Brian,

Looks like the component isn’t retained after presenting. Can you try storing it in a property until you dismiss the component’s view controller? This should fix your issue.

Best,

Joost

**Comment by brianpham93** [comment]
Thank Joost. It works

**Comment by bhattal** [comment]
@joostvandijk Hey, Can you please check the code. I am using the Ayden 4.10.3 version. And when I send all the details of card  to Ayden pay button it fails and gave http 500 error code. And call this function .  

    func didFail(with error: Error, from component: Adyen.PaymentComponent) {
        print("failure -->", error)
    }                   
  
```swift
// View controller code 
    class ViewController: UIViewController, PaymentComponentDelegate {
  
    var apiContext: APIContext?
    @IBOutlet weak var currencyTF: UITextField!
    @IBOutlet weak var AmountTF: UITextField!
    var cardPaymentMethod: CardPaymentMethod!
    var payment: PaymentMethodsResponse!
    var cardDetails = [String]()
    var cardName = String()
    weak var cardComponentDelegate: CardComponentDelegate?
    var formButton: FormButtonItem?
    var cardComponentG: CardComponent?

    
    
    func didSubmit(_ data: Adyen.PaymentComponentData, from component: Adyen.PaymentComponent) {
      print("Success")
    }
    
    func didFail(with error: Error, from component: Adyen.PaymentComponent) {
        print("failure -->", error)
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        self.cardComponentG?.delegate = self
        let cartID = "" // Replace with your cartID
        let token = "" // Replace with your actual token
        self.hitAPI(cartID: cartID, token: token)
    }
    
    
    @IBAction func paymentCheckout(_ sender: Any) {
        self.test()
    }
    
    func test() {
        
        let apiContext = APIContext(environment: Environment.test, clientKey: clientKey)
        // Add additional required parameters if needed and inject the instance of `APIContext`.
        let confg = CardComponent.Configuration(showsHolderNameField: true, showsStorePaymentMethodField: false)
        let paymentMethod = MyCardPaymentMethod(type: "scheme", name: cardName, brands: cardDetails, fundingSource: .credit)
        let styleBlack =  FormComponentStyle(tintColor: .black)
        
        let cardComponent = CardComponent(paymentMethod: paymentMethod, apiContext: apiContext, configuration:confg, style: styleBlack)
        cardComponent.delegate = self
        // cardComponent.style.backgroundColor = .blue
        
        // Keep the component instance to avoid it being destroyed after the function is executed.

        // Optional. In this example, the Pay button will display 10 EUR.
        if let price = AmountTF.text {
            let amount = (Int(price) ?? 1) * 100
            cardComponent.payment = Payment(amount: Amount(value: amount, currencyCode: "INR"), countryCode: "IN")
        } else {
            cardComponent.payment = Payment(amount: Amount(value: 0,currencyCode: "INR"), countryCode: "IN")
        }
        
        self.cardComponentG = cardComponent
        DispatchQueue.main.async {
            let presentedViewController = cardComponent.viewController // Replace with your view controller
            let transitioningDelegate = BottomPartialTransitioningDelegate()

            presentedViewController.modalPresentationStyle = .formSheet
            presentedViewController.transitioningDelegate = transitioningDelegate

            // Present the view controller
            self.present(presentedViewController, animated: true, completion: nil)
            self.cardComponentG = cardComponent
        }
        self.cardComponentG = cardComponent
    }
}


extension ViewController {
    
    func hitAPI(cartID: String, token: String) {
        let baseURLString = "https://eccobffqaapp.azurewebsites.net/v1/checkout/paymentMethods/"
        let cartIDPathComponent = "\(cartID)"
        let urlString = baseURLString + cartIDPathComponent

        guard let apiURL = URL(string: urlString) else {
            print("Invalid URL")
            return
        }

        var request = URLRequest(url: apiURL)
        request.httpMethod = "GET"
        request.addValue("Bearer \(token)", forHTTPHeaderField: "Authorization")

        // Make the API request using URLSession
        let task = URLSession.shared.dataTask(with: request) { data, response, error in
            if let error = error {
                print("Error: \(error.localizedDescription)")
                return
            }

            if let httpResponse = response as? HTTPURLResponse {
                if httpResponse.statusCode == 200 {
                    if let data = data {
                        // Process the response data (if needed)
                        do {
                            let responseJSON = try JSONSerialization.jsonObject(with: data, options: [])
                            print("Response JSON: \(responseJSON)")
                            let paymentM = try JSONDecoder().decode(PaymentMethodsResponse.self, from: data)
                            self.payment = paymentM
                            for paym in self.payment.data {
                                self.cardDetails.append(contentsOf: paym.brands)
                                self.cardName = paym.name
                            }
                        } catch {
                            print("Error parsing response data: \(error)")
                        }
                    }
                } else {
                    print("API request failed with status code: \(httpResponse.statusCode)")
                }
            }
        }

        task.resume()
    }
}

struct MyCardPaymentMethod: AnyCardPaymentMethod {
    var type: String

    var name: String

    func buildComponent(using builder: PaymentComponentBuilder) -> PaymentComponent? {
        builder.build(paymentMethod: self)
    }
    var brands: [String]
    var fundingSource: CardFundingSource?
    // Add other required properties and methods as needed
}

// MARK: - Payment Methods
struct PaymentMethodsResponse: Codable {
    let statusCode: Int
    let success: Bool
    let message: String
    let data: [PaymentMethodRes]
}

// MARK: - Datum
struct PaymentMethodRes: Codable {
    let brands: [String]
    let name, type: String
}

class BottomPartialPresentationController: UIPresentationController {
    override var frameOfPresentedViewInContainerView: CGRect {
        // Adjust the frame to control the presentation's height from the bottom
        let containerViewBounds = containerView?.bounds ?? CGRect.zero
        let presentedViewHeight: CGFloat = 300 // Adjust this to your desired height
        let yOrigin = containerViewBounds.height - presentedViewHeight
        return CGRect(x: 0, y: yOrigin, width: containerViewBounds.width, height: presentedViewHeight)
    }
    // You can also implement other methods for animations and interactions if needed
}

class BottomPartialTransitioningDelegate: NSObject, UIViewControllerTransitioningDelegate {
    func presentationController(forPresented presented: UIViewController, presenting: UIViewController?, source: UIViewController) -> UIPresentationController? {
        return BottomPartialPresentationController(presentedViewController: presented, presenting: presenting)
    }
}
```

**Comment by descorp** [comment]
Hey @bhattal 

What is the `error`?

If you need more details -  enable logs by calling
```swift
        #if DEBUG
            AdyenLogging.isEnabled = true
        #endif
```

---

My guess - your `clientKey` is incorrect

**Comment by bhattal** [comment]
@descorp 
 This is my Ayden log. You can check
 
---- Request (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
---- Request base url (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
https://checkoutshopper-test.adyen.com/
---- Request Headers (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
["Content-Type": "application/json"]
---- Request query (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
["clientKey": "test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M"]
2023-08-09 15:04:09.384332+0530 EccoCheckoutProcess[19897:245250] Can't find keyplane that supports type 11 for keyboard iPhone-PortraitChoco-NumberPad; using 27303_PortraitChoco_iPhone-Simple-Pad_Default
2023-08-09 15:04:09.412348+0530 EccoCheckoutProcess[19897:245250] API error: <_UIKBCompatInputView: 0x12bd3f3c0; frame = (0 0; 0 0); layer = <CALayer: 0x60000086f240>> returned 0 width, assuming UIViewNoIntrinsicMetric
2023-08-09 15:04:09.412426+0530 EccoCheckoutProcess[19897:245250] API error: <_UIKBCompatInputView: 0x12bd3f3c0; frame = (0 0; 0 0); layer = <CALayer: 0x60000086f240>> returned 0 width, assuming UIViewNoIntrinsicMetric
---- Response Headers (//checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
[AnyHashable("Content-Type"): text/html, AnyHashable("traceparent"): 00-e0ce52ecc4a8311a0a588e7d05295a5a-4fc9ea05ce19f324-01, AnyHashable("Content-Length"): 1022, AnyHashable("Date"): Wed, 09 Aug 2023 09:34:08 GMT]
---- Response (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Unknown error - Adyen</title>
        <link href="/checkoutshopper/css/checkout-error-page.css" rel="stylesheet">
    </head>
    <body>
        <div class="app__main-container">
            <div class="robot-page">
                <div class="robot-page__image">
                    <img src="../images/checkout-error-robot.gif"/>
                </div>
                <div class="robot-page__content">
                    <h1 class="adl-heading margin-left-16 margin-right-16">500 - Bad request</h1>
                    <p class="adl-paragraph margin-left-16 margin-right-16">The page you're looking for seems to be having some issues.</p>
                    <p class="adl-paragraph margin-left-16 margin-right-16">Try refreshing this page or navigate back to previous pages if the problem persists.</p>
                </div>
            </div>
        </div>
    </body>
</html>

---- Request (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
---- Request base url (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
https://checkoutshopper-test.adyen.com/
---- Request Headers (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
["Content-Type": "application/json"]
---- Request query (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
["clientKey": "test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M"]
---- Response Headers (//checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
[AnyHashable("Content-Type"): text/html, AnyHashable("Content-Length"): 1022, AnyHashable("Date"): Wed, 09 Aug 2023 09:34:09 GMT, AnyHashable("traceparent"): 00-b6287ccaccee115fcc6fd5bb5dc9c444-8962ed96b8f793e9-01]
---- Response (/checkoutshopper/v1/clientKeys/test_OYQGEYN5CBFY7HWWVHUEA54NTIWCAQ3M) ----
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Unknown error - Adyen</title>
        <link href="/checkoutshopper/css/checkout-error-page.css" rel="stylesheet">
    </head>
    <body>
        <div class="app__main-container">
            <div class="robot-page">
                <div class="robot-page__image">
                    <img src="../images/checkout-error-robot.gif"/>
                </div>
                <div class="robot-page__content">
                    <h1 class="adl-heading margin-left-16 margin-right-16">500 - Bad request</h1>
                    <p class="adl-paragraph margin-left-16 margin-right-16">The page you're looking for seems to be having some issues.</p>
                    <p class="adl-paragraph margin-left-16 margin-right-16">Try refreshing this page or navigate back to previous pages if the problem persists.</p>
                </div>
            </div>
        </div>
    </body>
</html>

**Comment by descorp** [comment]
@bhattal 

I would prefer to continue any further discussion on [issue](https://github.com/Adyen/adyen-ios/issues/1302) above.
