### ISSUE TITLE
[NEED ASSIST] Customize the Payment Sheet for Apple Pay [Drop in]

### ISSUE THREAD

**Issue by prabel** [Adyen/adyen-ios#865]
**Describe the challenge**
Hi,
my last build was rejected by Apple because of this issue: 
```
Your app uses Apple Pay as a purchasing mechanism but does not provide the necessary material purchase information to the user prior to the sale of goods and services.

Specifically, your app does not include the following:

- Merchant's name on the payment sheet
```
What I find out in [Apple documentation ](https://developer.apple.com/design/human-interface-guidelines/apple-pay/overview/checkout-and-payment/) is that I'm missing `Bussines_name` on `Pay` label. Is it possible to replace `Pay total` label with some custom text?

```Provide a business name after the word Pay on the same line as the total. Use the same business name people will see when they look for the charge on their bank or credit card statement. This provides reassurance that payment is going to the right place. For example: Pay [Business_Name].```

**Screenshots**
<img width="400" alt="Zrzut ekranu 2022-04-20 o 14 56 24" src="https://user-images.githubusercontent.com/3511381/164235638-180d5506-cd6c-47e2-9a8d-b4ae1a7885ba.png">

Thanks for help 🙏

**Comment by erenbesel** [comment]
Hi @prabel ,
The `summaryItems` property in the configuration of `ApplePayComponent` determines these items.
You can specify your own `[PKPaymentSummaryItem]` array with their own label strings.

Hopefully this should help, let me know if it doesn't.

**Comment by prabel** [comment]
Perfect, thank you @erenbesel for the quick reply. I already used it, but I didn't know that the last element from this array is also used in this place.
