### ISSUE TITLE
[NEED ASSIST] - Payconiq by Bancontact redirects do not work with dropin sdk

### ISSUE THREAD

**Issue by owinter86** [Adyen/adyen-ios#868]
**Describe the challenge**

- We have integrated the drop in sdk and it functions as expected for all the current payment methods
- We have recently included the Bancontact payment method, but we get "Safari cannot open the page because the address is invalid" when the user has completed payment in their banking app. We confirm the payment is successful, but the redirect back to the app fails
- We have no issues with the similar flows like ideal and 3ds flows, the redirect back to the app works as expected.
- We are unsure on what we need to do to get this to work, or if the error is even due to our implementation.

**Screenshots**
![image](https://user-images.githubusercontent.com/2920419/164655886-766bf3b3-9656-467d-92d3-9b590ae99e56.png)
![image (1)](https://user-images.githubusercontent.com/2920419/164655970-8a104576-5bb3-47d0-b37e-e83bb5b1facf.png)
![image (2)](https://user-images.githubusercontent.com/2920419/164655999-762f9143-beb9-407a-b2bf-6d3fad731a84.png)

**Comment by descorp** [comment]
Hey @owinter86 

Thanks for reaching out!

Do you know the a redirect URL?
Could you share `pspreference` (you can find it in a header of `\payments' response)

**Comment by oliverwinter-vdb** [comment]
Pspreference for the problematic payment is 

JB4BP6QTQHBBFF32

**Comment by descorp** [comment]
Hey @owinter86

I was able to recover `return URL` from pspreference and redirect to your app with it(if open as link) , so I am not sure what might cause Safari issue.

Is it easy to reproduce?
Is this behaviour occurs every time you make payment?

**Comment by oliverwinter-vdb** [comment]
Hey @descorp its not easy to reproduce as it's the bankcontact payment method which can only be tested on production, with a Belgian bank account that has the bank contact activated. It's a widely reported error from
Belgian users, and one of the users reported back the same error with an entirely separate app (that we did not create) that seems to also utilise adyen.

So we are not sure if it's an internal adyen issue, or the bank is misconfigured to redirect back the app/app's with the given return urls.

**Comment by descorp** [comment]
Thanks @owinter86 

We will do internal LIVE tryout and to check with bank, if necessary.

In a meanwhile, to be on a safe side, I would suggest to consider any payment in "pending" state after you start handling the `Action` and until you know the outcome (success or failure).
I believe you receive hooks about successful payment after some time ?

**Comment by descorp** [comment]
Hey @owinter86 
Were you able to workaround the issue?

**Comment by oliverwinter-vdb** [comment]
Hey @descorp the issue still occurs, but the payments go through fine, it's just redirect that's causing issues. So the user will manually return to the app after seeing the error.

**Comment by descorp** [comment]
Hey @owinter86 

Sorry for a loooong reply 😅
Redirects are a big issue for a native mobile (iOS especially).
We are working on means and infrastructure to improv native redirect in v5.

Successful redirect is a "happy flow", so it is recommended to have a "pending" state to fallback in case payment result is not yet determined.

**Comment by mohammedDehairy** [comment]
will close this issue for lack of activity, please feel free to reopen or create a new issue if you're still experiencing issues!.
