### ISSUE TITLE
DropInComponentDelegate didFail, how to determine cancellation?

### ISSUE THREAD

**Issue by caddac** [Adyen/adyen-ios#87]
The `DropInComponentDelegate`  defines `func didFail(with error: Error, from component: DropInComponent)`. It appears if the user presses the Cancel button during checkout that didFail is called. 

How do I determine the failure reason from the the `Error`?

**Comment by caddac** [comment]
Looks like 
```
if let error = error as? ComponentError, error == .cancelled {
            // cancelled is true
        }
```

does the trick

**Comment by diegomarcon** [comment]
Hi @caddac,

Yes, you can determine the type of error based on the `ComponentError` [enum](https://adyen.github.io/adyen-ios/Docs/Enums/ComponentError.html#/s:5Adyen14ComponentErrorO9cancelledyA2CmF). 

Cheers,
