### ISSUE TITLE
[NEED ASSIST] Is this repo deprecated?

### ISSUE THREAD

**Issue by erik-kallen** [Adyen/adyen-ios#871]
I'm having a hard time understanding whether this is the current way of integrating Adyen into iOS.

The documentation at https://docs.adyen.com/online-payments/classic-integrations/checkout-sdks/ios-sdk links to this repo (and also mentions the 'Adyen' pod), and the top of that page says very clearly that **The Checkout SDK integrations are being phased out**.

However, that page also says

> We strongly recommend you switch to the latest [online payments](https://docs.adyen.com/online-payments) integration

and by clicking around from that page, I can get to https://docs.adyen.com/online-payments/ios/components, which does not carry a deprecation notice, and also links to this repo.

So, different parts of the documentation make conflicting statements on the status of this repo. Some clarification would be nice

**Comment by descorp** [comment]
Hey @erik-kallen 

Thank you for your feedback!
Indeed, `classic integration` link should lead to a specific [v2 branch](https://github.com/Adyen/adyen-ios/tree/v2), however, technically, it is still the same repo 😄

[iOS Components integration](https://docs.adyen.com/online-payments/ios/components) is the correct, up-to-date documentation, that describing [v4 branch](https://github.com/Adyen/adyen-ios/tree/v4) on this repo.
