### ISSUE TITLE
[NEED ASSIST] Supporting multiple clientKeys

### ISSUE THREAD

**Issue by taraspasichnyk** [Adyen/adyen-ios#876]
**Describe the challenge**
I work on the iOS application that uses multiple backends, that use different client keys.
When making a payment on the first backend with some card, I cannot make a payment with the same card on second backend.
Always getting `{"status":422,"errorCode":"174","message":"Unable to decrypt data","errorType":"validation"}` for whichever comes last.

It seems to me, that Adyen somehow caches a first used public key?
Maybe this issue is connected to this one - https://github.com/Adyen/adyen-magento2/issues/777 ?
Was resolved for magento but nor iOS.

**Comment by descorp** [comment]
Hey @taraspasichnyk 

Thanks for reaching out!
This should be fixed in [4.7.1](https://github.com/Adyen/adyen-ios/releases/tag/4.7.1)
What SDK version are you using?

**Comment by taraspasichnyk** [comment]
Hey @descorp ! Thank you for the response. Should have included that info in the initial message.

I am using a pod `4.4.0` version. 

Will give a `4.7.1` a go. 

Thank you!

**Comment by taraspasichnyk** [comment]
Worked perfectly. Thank you for the help.
