### ISSUE TITLE
Recurring payments using Drop-in components

### ISSUE THREAD

**Issue by caddac** [Adyen/adyen-ios#88]
Are recurring payments supported using the drop-in components? 

Seems like I could use Drop-in to authorize the first payment, then use https://docs.adyen.com/classic-integration/recurring-payments/capture-a-recurring-payment/ to capture that payment detail?

**Comment by joostvandijk** [comment]
Hi @caddac,

The components are purely used to collect the payment method details. Then, in your request to `/payments`, set the [`storePaymentMethod`](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v49/payments__reqParam_storePaymentMethod) flag to true. If you then [provide the shopper reference](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v49/payments__reqParam_storePaymentMethod) in your request to `/paymentMethods`, you'll also retrieve the list of stored payment methods for that shopper. You can use these stored payment methods by setting `paymentMethod.storedPaymentMethodId` in your request to `/payments`.

This flow is relatively new, as we recently unified the recurring and oneclick payments flow. I hope this brief overview helps. The documentation will follow soon.

Best,

Joost

**Comment by caddac** [comment]
Ok, to recap and clarify my understanding, for a new user that has never signed up
1. get paymentMethods as specified in DropIn docs
2. capture user payment details
3. submit a payment (the first one for this member), specifying the shopperReference and `storePaymentMethod=true`

4. after that, on a schedule, submit a payment to `/payments`, specifying the `paymentMethod.storedPaymentMethodId` from the initially stored payment method.

Does that sound right?

**Comment by joostvandijk** [comment]
@caddac This is correct! But, between 3 and 4, you'd have to do `/paymentMethods` again, with the `shopperReference`, to retrieve the identifier of the previously stored payment method. This value can be cached.

**Comment by caddac** [comment]
I'm assuming I can also use these payment details to setup a recurring payment in adyens backend, so we don't have to submit payment request monthly?

**Comment by joostvandijk** [comment]
Unfortunately, our backend system has no "subscription engine" to automatically perform payments on a recurring basis.

**Comment by caddac** [comment]
This is pretty disappointing. Your sales site seems to indicate you support recurring and subscription payments (https://www.adyen.com/our-solution/online-payments/recurring-subscription) and this is one feature I need

**Comment by joostvandijk** [comment]
I understand, but it's unfortunately not an issue with our drop-in/components. Please feel free to open a new issue if you have further questions.
