### ISSUE TITLE
[NEED ASSIST] Display bank logo based on `CardType`

### ISSUE THREAD

**Issue by ajacquelin** [Adyen/adyen-ios#885]
**Describe the challenge**
We would like to display a card type icon for a given card number by using the download link:
```  https://checkoutshopper-live.adyen.com/checkoutshopper/images/logos/[img-size]/[pm-type]/[issuerid][suffix].png```

In order to do that we need to know which card type match for a given `cardNumber` string.
This is already done internally in the `CardType` enum:
https://github.com/Adyen/adyen-ios/blob/3241506dc6cc9dedbc9d66e15ccbc9ca1c8ce729/Adyen/Core/Models/CardType.swift#L339

Is it possible to expose the `func matches(cardNumber: String) -> Bool {` method ?

**Comment by descorp** [comment]
Hey @ajacquelin 

Thanks for reaching out!
Are you writing your own custom Card Component implementation?


`func matches(cardNumber: String) -> Bool` will be public on [v5](https://github.com/Adyen/adyen-ios/blob/develop/Adyen/Core/Models/CardType.swift#L339)
For now you can probably just copy our class locally.

**Disclaimer**
Function `matches(cardNumber: String) -> Bool` is very basic and does not provide a reliable card type detection. 
It is only suitable to distinguish major card schemes.
For a reliable card detection use [`didChangeCardBrand(_ value: [CardBrand]?, component: CardComponent)`](https://github.com/Adyen/adyen-ios/blob/develop/AdyenCard/Components/Card/CardComponentDelegate.swift)

**Comment by ajacquelin** [comment]
thanks for the quick response!
indeed we have our own card component implementation.

Have a nice day
