### ISSUE TITLE
[NEED ASSIST] Handle QR code action with swish payment

### ISSUE THREAD

**Issue by AhmedOsman00** [Adyen/adyen-ios#889]
**Describe the challenge**
we would like to handle the QR code action using Adyen components, we got response by `/payments` as below, is the QR code action handling is supported for swish payment method type?

```
{
    "paymentData": "",
    "paymentMethodType": "swish",
    "qrCodeData": "xxxx",
    "url": "xxxx",
    "type": "qrCode"
}
```

**Comment by descorp** [comment]
Hey @AhmedOsman00 

Thanks for reaching out!

Can you describe your case?
Opening QR on mobile sounds like a poor UX, especially when mobile app available.

**Comment by AhmedOsman00** [comment]
Hey @descorp, thanks for your reply, I'm asking about if the swish app is not found, could we open the QR on mobile?

Also one more question, how we can test it on the test environment, as it redirects me to the swish app and I couldn't find information about how to test it like this, the documentation states that the payment will approved immediately.

**Comment by descorp** [comment]
> if the swish app is not found, could we open the QR on mobile

We haven't thought about it previously, but this is technically possible, we have proved it yesterday 😅
Unfortunately, right SDK is not capable of checking if app is installed on the device.
You can make a custom solution by verifying if Action have type 'qrcode' and manually parse it to a `QRCodeAction`.

> how we can test it on the test environment

The only way is to install [Vipps test app](https://github.com/vippsas/vipps-developers/blob/master/vipps-test-environment.md#vipps-test-apps) on your real iOS device. You can find more info in [Adyen Docs](https://docs.adyen.com/payment-methods/vipps/ios-drop-in#test-and-go-live)

**Comment by AhmedOsman00** [comment]
@descorp, I think Vipps is not like Swish. [Adyen Docs](https://docs.adyen.com/payment-methods/swish/web-drop-in) states that the payment should be approved immediately, should we do something from our side ?

**Comment by descorp** [comment]
oh, sorry 😅
Swish is indeed different payment method - unfortunately, we don't have official iOS docs yet.
Current documentation only describes Web integration with QRcode.

To make a sandbox account you need to contact `tekniksupport@getswish.se`
