### ISSUE TITLE
adyen-ios 3.0.1 fails to build in Carthage

### ISSUE THREAD

**Issue by donnellyk** [Adyen/adyen-ios#89]
We are seeing a couple of strange things during our Carthage build of 3.0.1:

```
[12:14:06]: *** Skipped building adyen-3ds2-ios due to the error:
[12:14:06]: Dependency "adyen-3ds2-ios" has no shared framework schemes for any of the platforms: iOS
[12:14:06]: If you believe this to be an error, please file an issue with the maintainers at https://github.com/adyen/adyen-3ds2-ios/issues/new
```

And then an error when trying to build scheme "AdyenDropIn" in Adyen.xcodeproj
```
.../Carthage/Checkouts/adyen-ios/AdyenCard/3DS2 Component/ThreeDS2ComponentFingerprint.swift:7:8: error: no such module 'Adyen3DS2'
import Adyen3DS2
       ^

** ARCHIVE FAILED **
```

Looks related to https://github.com/Adyen/adyen-ios/issues/78 but I was not able to resolve it by clearing away caches. I've deleted Xcode's DerivedData, Carthage's DerivedData, and Carthage's Build and Checkout folders.

Cartfile:
```
github "adyen/adyen-ios" ~> 3.0
```

Cartfile.resolved:
```
github "adyen/adyen-3ds2-ios" "0.9.6"
github "adyen/adyen-ios" "3.0.1"
```

Xcode Version 10.2.1 (10E1001)
MacOS 10.14.5
Carthage 0.33.0

Temporarily resolves this by downgrading to 2.8, but we'll need 3.0 very shortly for 3DS3 Components.

**Comment by joostvandijk** [comment]
Hi @donnellyk,

It looks like something is going wrong with pulling in the 3DS2 dependency. Are you using any flags, such as `--no-use-binaries`, when using Carthage?

**Comment by donnellyk** [comment]
We are, I'll do some testing.

**Comment by joostvandijk** [comment]
The issue is that `Adyen3DS2` is a binary-only framework (as per EMVCo rules). Therefore, integration with Carthage is tricky, and we currently rely on this flag being present.

**Comment by donnellyk** [comment]
Makes sense. We used that flag for a reason on our CI machine, but I don't remember why so we'll just give it a shot and see what happens.

**Comment by donnellyk** [comment]
That seemed to do the trick. And by the sounds of it, if we need to use `--no-use-binaries`, we can probably just ensure `adyen3DS2.framework` is in the correct folder before the carthage script and everything will work as expected.
