### ISSUE TITLE
[NEED ASSIST] Restrict accepted characters in input fields

### ISSUE THREAD

**Issue by nscille** [Adyen/adyen-ios#896]
Hi, I'm trying to restrict which characters the user can put into the input fields for the billing address. Specifically, I want the fields to not accept punctuation and to only accept English letters. Is this possible?

**Comment by descorp** [comment]
Hey @nscille 

Unfortunately, we don't have a setting or an easy way to do so. 

Be aware, that limiting shopper's input to only latin symbols might cause issues in different regions.

As a solution, you can build your own address form and then populate your CardComponet or DropInComponent with `billingAddress` via `Configuration.shopperInformation`.
 
As alternative, you can fork our card component and change `Formatter` and/or `Validator` in [createTextItem(for field: AddressField, from viewModel: AddressViewModel) -> FormItem](https://github.com/Adyen/adyen-ios/blob/develop/Adyen/UI/Form/Items/Address/FormFullAddressItem.swift#L141)

**Comment by nscille** [comment]
Ok thanks we'll try one of these

**Comment by nscille** [comment]
We decided to do our own validation based on what the user inputs, but we're having trouble accessing the `holderName` field. Do you know how we can access ths?

**Comment by erenbesel** [comment]
Hi @nscille, `PaymentComponentData` has a `paymentMethod` property that conforms to `PaymentMethodDetails`, which is what `CardDetails` also is.
So you can cast the `paymentMethod` property into `CardDetails` and have access to `holderName` and other properties if needed.

Hope this helps!

**Comment by nscille** [comment]
Yep this works, thanks for the help!
