### ISSUE TITLE
Xcode v 9.0 (9A235) Swift Compiler Error

### ISSUE THREAD

**Issue by cvadstrup** [Adyen/adyen-ios#9]
It is not possible to run the projects in Xcode Version 9.0 (9A235).

Steps to reproduce:

1. Download sample from git
2. Pod update or install (pod version 1.9.1)
3. Open workspace and build project
4. Gets 11 Swift Compiler Errors

**Comment by joostvandijk** [comment]
Hi @cvadstrup,

There's currently an issue with our examples, as they try to compile our SDK with Swift 3.2, even though we've migrated to Swift 4.0. You can fix this manually by changing the Swift version of the example app in the build settings to 4.0, then run `pod install` again. However, we'll publish an update tomorrow which fixes this. I'll update this issue once the update is available.

Sorry for the inconvenience!

Best,
Joost

**Comment by joostvandijk** [comment]
Hi @cvadstrup,

The update has been published! Feel free to let us know when you run into any other issues.

Best,
Joost
