### ISSUE TITLE
[NEED ASSIST] Adyen CSE to old integration support

### ISSUE THREAD

**Issue by JonathanAJ** [Adyen/adyen-ios#919]
Hello everyone,

I need support to make my flutter application integrate with Adyen CSE encryption. I coded a native plugin, it use:

`CardEncryptor.Card.encryptedToToken()` in `AdyenCard/Utilities/Encryption/CardEncryptorExtensions.swift` of **v3.9.1** but the output encryption not working.

  My plugin using Android CSE in https://github.com/Adyen/adyen-android/tree/develop/cse working fine, but iOS not support! My server API with old integration need 'encryptedData' info.

**Comment by nauaros** [comment]
Hi @JonathanAJ!

Thanks for raising this issue. Can you please provide us with the kind of error you're getting?

**Comment by descorp** [comment]
Hey @JonathanAJ 

Any update on this?

**Comment by descorp** [comment]
I am closing this topic due to a lack of activity
