### ISSUE TITLE
ThreeDS2Component.ChallengeResult.payload internal access

### ISSUE THREAD

**Issue by IbrahimalKhayat** [Adyen/adyen-ios#92]
Hi,

While trying to integrate the ThreeDS2 component (v3.1.0) into our app, I am unable to get the payload from theChallengeResult due to internal access modifier. Is there a way to get the payload? I need to send it to backend. Should it be public? I am a bit lost here...

**Comment by joostvandijk** [comment]
Hi @IbrahimalKhayat,

This is a mistake on our side. We'll include a fix in todays release!
My apologies for the inconvenience.

Joost

**Comment by IbrahimalKhayat** [comment]
Fixed in v 3.1.1
