### ISSUE TITLE
[NEED ASSIST] Is there a reason why credit card expiration allows 3 month old credit cards?

### ISSUE THREAD

**Issue by JeanAzzopardi** [Adyen/adyen-ios#928]
We're currently in the process of integrating Adyen into an app, and we have a question about:

https://github.com/Adyen/adyen-ios/blob/06afadbce62d7c8e9fcf0ba41f9b563b5f14df55/AdyenCard/Validators/CardExpiryDateValidator.swift#L27-L44

Namely, why is the month difference allowed to be as large as 3 months?

E.g. as this code snippet shows, a card with an expiration date 3 months in the past is being shown as valid.
Is there a reason why this is being done? Could this "-3" be controlled in a parameter?

```
let dateFormatter = DateFormatter()
dateFormatter.locale = Locale(identifier: "en_US_POSIX")
dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZ"
let referenceDate = dateFormatter.date(from: "2022-06-01T00:00:00+0000")!


let validator = CardExpiryDateValidator(referenceDate: referenceDate)

validator.isValid("0322") //TRUE
```

**Comment by descorp** [comment]
Hi @JeanAzzopardi 

This is UI validation. We allow 3 month time because sometimes banks allow expired cards to work after expiration (for ex. during Covid lockdown, to prevent queues in bank offices).
The real validation and fraud detection would be performed on our backend after submitting the payment details.

**Comment by JeanAzzopardi** [comment]
Thanks, @descorp, this makes sense. Would you consider making it parametrizable?

**Comment by descorp** [comment]
@JeanAzzopardi 

Seems like you are the first one to request it.
Could you describe your business's case? What impact are you expecting from this feature?

**Comment by Kidkie** [comment]
Revisiting this, is there a way to turn this off via options?
