### ISSUE TITLE
Minimum deployment target 10.3 ?

### ISSUE THREAD

**Issue by ajanauskas** [Adyen/adyen-ios#93]
Is there any reason why SDK requires minimum deployment target of 10.3 and not 10.0? 

Would be great to have it set at 10.0 if possible.

**Comment by joostvandijk** [comment]
Hi @ajanauskas,

This was because of a dependency required 10.3, but that has since been lowered to 10.0. We'll investigate if we can lower the deployment target to 10.0 without introducing new issues.

Best,

Joost

**Comment by ajanauskas** [comment]
Thank you !

**Comment by gudantianya** [comment]
Xcode deployment target 9.0, currently only available in version 1.8.1, how to use the latest version 3.1.1

**Comment by joostvandijk** [comment]
Hi,

In the latest release, 3.1.2, we lowered the deployment target to 10.0.

@gudantianya There's currently no plans to lower the deployment target to 9.0.

Best,

Joost
