### ISSUE TITLE
Possibility to make postal code optional

### ISSUE THREAD

**Issue by leslieolivier** [Adyen/adyen-ios#939]
We want to ask users for postal code during card payments and use this to reduce the interchange/scheme fees in US where we pay an overprice, if we don't know the zip code of customer/card issuer.

However, we do not want to make to mandatory to enter the zip code. So we need the field, but currently the validation requires at least 2 characters. We would like to be able to put in .optionalPostalCode instead of .postalCode.

Best regards,
Leslie

**Comment by erenbesel** [comment]
Hi @leslieolivier,

You are in luck! As we are adding something similar to this even on the current `v4` branch soon. 

We will keep you updated :)

**Comment by leslieolivier** [comment]
Thanks @erenbesel!

We will upgrade to 4.8.0 and take a look :)
