### ISSUE TITLE
RedirectComponent not working

### ISSUE THREAD

**Issue by IbrahimalKhayat** [Adyen/adyen-ios#94]
Hi, 

While trying out the RedirectComponent. I keep getting redirected to a web page that shows a 500 http error. After a bit of investigation, it seems to me that the problem is that the SDK never sets the proper params. 

According to the documentation the request should be a POST with the params MD, TermsURL and PaReq set in the body using URLEncoding. 

Something that corresponds to the cURL 
```
curl https://test.adyen.com/hpp/3d/validate.shtml \
--data-urlencode 'PaReq=eNpVUttygjAQ/RXbDyAJl4LMmg6VztQH1LH63GHCjtApAQNU9O...' \
--data-urlencode 'TermUrl=https://your-company.com/...' \
--data-urlencode 'MD=djIhMFQxMHpFRHlyY3BOSHJ1UUNmZnk1Zz09IZ3a9YOyDsr30Ni+jrj0M3pyy...'
```

Please correct me if I am wrong, after checking the RedirectComponent implementation, it looks to me that the SDK is trying to make a GET request, without passing the parameters (MD, PaReq & TermURL)

If I am using the wrong component for 3DS and handling or the redirect action, I would appreciate it if you point me to the right direction.

regards

**Comment by joostvandijk** [comment]
Hi @IbrahimalKhayat,

If you specify a `returnUrl` with a custom host (like `my-app://`), our backend will detect this as a mobile-flow and supply a GET URL instead of a URL that requires a POST request (which is not supported by the Safari View Controller). Let me know if this works.

Best,

Joost

**Comment by IbrahimalKhayat** [comment]
That makes sense now, I will try it out. I would recommend making it more clear in the documentation as I have completely missed it.

thanks

**Comment by joostvandijk** [comment]
You're right, it's not very well documented right now. We'll make sure it gets added.

**Comment by IbrahimalKhayat** [comment]
works as described, thanks!
