### ISSUE TITLE
Change colours in Drop In components

### ISSUE THREAD

**Issue by owinter86** [Adyen/adyen-ios#95]
Is there any way to change the colors for the ios drop in components, like the pay/submit button on the card component?

**Comment by joostvandijk** [comment]
Hi @owinter86,

The color of the submit button is inferred from the view controller's view's tint color. If you set the `tintColor` on the component's `viewController.view` (or higher in your view hierarchy, like on your key window), it should be propagated to the submit button.

Best,

Joost

**Comment by nnarayann** [comment]
Hi @joostvandijk, any updates on the customization options? (e.g. font, text colors, etc). Right now the tint is the only way or am I missing something?. Thank you in advance!.

**Comment by joostvandijk** [comment]
Hi @nnarayann,

We're still working on it - we hope to have it ready in January.

Best,

Joost

**Comment by nnarayann** [comment]
Ok, thank you for the update @joostvandijk!

**Comment by SMJ93** [comment]
Hey Joost, any update with the customisation options?

**Comment by joostvandijk** [comment]
Hi @SMJ93,

We have added a lot of customization options in the latest release. You can use them by instantiating a `DropInComponent.Style` structure and passing it in the initializer of the `DropInComponent`. We are working on writing up the documentation. In the meanwhile, I would suggest looking at the structure directly to see the customization options.

Best,

Joost

**Comment by SMJ93** [comment]
Awesome! Thanks @joostvandijk

**Comment by descorpapps** [comment]
Any customization components for Android? I haven't found anything @SMJ93

**Comment by mohammedDehairy** [comment]
Hi @descorpapps ,

 Thanks for your message.

I would recommend to ask this question in the Android repo issues section.

https://github.com/Adyen/adyen-android/issues

**Comment by Abhishekgarg727** [comment]
Read my answer for android adyen dropin customisation here :https://github.com/Adyen/adyen-android/issues/194#issuecomment-663880944
