### ISSUE TITLE
[NEED ASSIST] Encryption of card details seems to be broken from 3.8.0 onwards

### ISSUE THREAD

**Issue by drekka** [Adyen/adyen-ios#954]
**Describe the challenge**

We are using the `CardEncryptor` to encrypt card details to go to a server. The code currently uses v3.1.2 which is old so I was attempting to update it and also manage it through SPM rather than CocoaPods. However I've found that up to v3.7.0 works fine, but v3.8.0 and later all fail the credit card transaction when it gets to the server. 

I noticed from the release notes that v3.8.0 had it's encryption code re-written in Swift so I'm wondering if the results have changed, or do we need to upgrade the software on our server, or has the encryption algorithm been changed or what else might be the problem?

Unfortunately I only have access to the iOS code at this time so I'm working in the dark a bit here and our server only returns the fact that there was an error, not what the error was.

**Comment by descorp** [comment]
Hey @drekka 

I wasn't able to reproduce this - both 3.8.0 and 3.7.0 encrypt CC data as expected 🤔
#worksonmymachine

What is your current API version?
What error are you facing?

One thing I can think of - on 3.7.0 we have introduced [clientKey](https://docs.adyen.com/development-resources/client-side-authentication#get-your-client-key) concept.

How did your integration code changes with 3.8.0?
Could be that you are setting **publicKey** instead of **clientKey** ?

**Comment by drekka** [comment]
Hi, Thanks for replying. I'm still trying to find out what API we are using as I don't work in that area. I just got told Integration 0.1.18 if that makes any sense. As our current version of the iOS SDK is 3.1.2 I'm pretty sure we are not using a client key so I'll have to look into that and talk with the other teams about an upgrade. I presume Adyen would recommend it for security purposes. passing the wrong key makes sense and would explain why 3.8.0 doesn't work for me.

**Comment by fahidattique55** [comment]
Hi there!

I'm using custom card encryption [here](https://docs.adyen.com/payment-methods/cards/custom-card-integration?tab=i_os_2) as per docs, I should get encrypted values starting like,
```
{
    "encryptedCardNumber":"adyenjs_0_1_18$MT6ppy0FAMVMLH...",
    "encryptedExpiryMonth":"adyenjs_0_1_18$MT6ppy0FAMVMLH...",
    "encryptedExpiryYear":"adyenjs_0_1_18$MT6ppy0FAMVMLH...",
    "encryptedSecurityCode":"adyenjs_0_1_18$MT6ppy0FAMVMLH..."
}
```
**But Instead**

I'm getting encrypted values JWT token look alike. see attach ss below,

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/12518061/187236674-69e8a382-7573-4e27-991e-7552487d76b1.png">

Any idea what am I missing?

**Comment by mohammedDehairy** [comment]
Hi @fahidattique55 ,

this is a new encryption format that making use of the standard [JSON Web Encryption](https://www.rfc-editor.org/rfc/rfc7516), has been introduced a long time ago instead of the old `"adyen` prefixed payload.

so that's expected.

**Comment by fahidattique55** [comment]
Hi @mohammedDehairy 

Thanks for your quick response. I'm facing error from my server side using this encryption value of card token. I'll ask backend dev team to check. Thanks for clarification.

**Comment by mohammedDehairy** [comment]
I will close this ticket for lack of activity, please feel free to reopen it if you're having issues with the JWE encryption format.
