### ISSUE TITLE
[NEED ASSIST] AdyenContext not found in Adyen module

### ISSUE THREAD

**Issue by ralzuhouri** [Adyen/adyen-ios#965]
I am trying to get the example in the readme file to compile:

`let apiContext = APIContext(clientKey: clientKey, environment: Environment.test)
let context = AdyenContext(apiContext: apiContext, analyticsConfiguration: analyticsConfiguration)
let configuration = DropInComponent.Configuration(context: context)`

I added with the swift package manager the latest Adyen package and I made sure that I have the following packages installed:
- Adyen 4.8.0
- Adyen3DS2 2.2.6
- AdyenNetworking 1.0.0
- AdyenWeChatPayInternal 2.1.0

Then I tried to insert the above code snippet in the example. And I get this error: "Cannot find 'AdyenContext' in scope".
I looked for AdyenContext and I verified that it is indeed present in the Adyen repository under the path Adyen/Core/AdyenContext.

But if you look at the below screenshot, the AdyenContext directory is missing from the package loaded with the Swift package manager:

![Screenshot 2022-07-28 at 16 36 57](https://user-images.githubusercontent.com/32909027/181557921-fbe29aa2-6c8e-44ab-a2b8-5a1342a049be.png)

So the class is missing and hence the error.

Can somebody provide an example with some steps on how to successfully run the above code snipper (it's in the readme page)?

**Comment by erenbesel** [comment]
Hello @ralzuhouri ,

In preparation of our upcoming version 5 (develop branch), we recently updated our documentation to the new integration that will come with v5, but forgot to provide the documentation for v4. We will add samples for v4 branches soon.

In the meantime, allow me to direct you to our documentation page which currently refers to v4 integration.
https://docs.adyen.com/online-payments/ios/drop-in


Thanks for notifying us with this :)

**Comment by ralzuhouri** [comment]
If I follow this documentation I get the error "Value of type 'DropInComponent' has no member 'payment'"

**Comment by descorp** [comment]
Hey @ralzuhouri 

Indeed, thanks for pointing it out!
Seems like our official documentation is outdated 😅

We are working on a new versioning system for Adyen Docs and are looking to improve this in future.
Sorry for the inconvenience

For now you can use GitHub [v4.8.0 README](https://github.com/Adyen/adyen-ios/tree/4.8.0) as a reference documentation.

The `payment` were moved from DropInComponent to a `DropInComponent.Configuration `. You can set it as:
```swift
let configuration = DropInComponent.Configuration(apiContext: apiContext)
configuration.payment = payment
```

**Comment by ralzuhouri** [comment]
Thank you for your reply,

This clarifies some things.

Another problem I am experiencing is that I cannot directly decode a PaymentMethods object from the server's response, like shown in the code examples:

`let paymentMethods = try JSONDecoder().decode(PaymentMethods.self, from: response.data!)`

The decoder fails, and what I receive from the server is a very different JSON data, which I could summarize with this struct:

`struct CheckoutResponse: Decodable {
            struct PaymentMethod: Decodable, Adyen.PaymentMethod {
                func buildComponent(using builder: PaymentComponentBuilder) -> PaymentComponent? {
                    return nil
                }
                
                struct Issuer: Decodable {
                    var id: String?
                    var name: String?
                }
                
                struct Configuration: Decodable {
                    var merchantId: String?
                    var intent: String?
                }
                
                var name: String
                var type: String
                var issuers: [Issuer]?
                var brands: [String]?
                var configuration: Configuration?
            }
            
            struct AdyenData: Decodable {
                var paymentMethods: [PaymentMethod]
            }
            
            struct Data: Decodable {
                var adyen: AdyenData
                var order: Order
            }
            
            var adyen: AdyenData
            var order: Order
        }`

If I pass this custom struct to the decoder, it's able to decode Adyen's response.

Like you see the fields are different from the ones that we can see in Adyen.PaymentMethods (with the fields 'paid', 'stored', 'regular'). 

I am not sure how to proceed. Shall I convert this struct to a PaymentMethods struct at this point? Or maybe there is another way?

**Comment by descorp** [comment]
Hey @ralzuhouri 

Were you able to resolve the issue?

**Comment by descorp** [comment]
I am closing this topic due to a lack of activity
