### ISSUE TITLE
[NEED ASSIST] Unit testing "Unable to find bundle named Adyen_Adyen" while using SPM

### ISSUE THREAD

**Issue by andreymosin** [Adyen/adyen-ios#968]
**Describe the challenge**

Hey there! I am trying to unit test Adyen and encountering the following error. This happens every time when Adyen is trying to resolve Bundle like
` 
public static var componentLoadingMessageColor: UIColor {
            UIColor(named: "awaitLoadingMessageColor",
                    in: Bundle.coreInternalResources,
                    compatibleWith: nil) ?? componentPlaceholderText
        }
`

Error looks like this:

Test Case '-[AdyenPayTests.AdyenPayServiceTests testEventsAction]' started.
Adyen/resource_bundle_accessor.swift:27: Fatal error: unable to find bundle named Adyen_Adyen
2022-08-01 15:53:37.190577+0200 xctest[23087:206326] Adyen/resource_bundle_accessor.swift:27: Fatal error: unable to find bundle named Adyen_Adyen

This is happening from the moment I've migrated Adyen to SPM.

Thank you!

**Comment by descorp** [comment]
Hey @andreymosin 

What SDK version are you using?
How do you accessing `Bundle.coreInternalResources`? 
It is `internal` and were not intended for direct use.

According to [Apple documentation](https://developer.apple.com/documentation/xcode/bundling-resources-with-a-swift-package):
> When you build your Swift package, Xcode treats each target as a Swift module. If a target includes resources, Xcode creates a resource bundle and an internal static extension on Bundle to access it for each module. 

Can you reach the resource via `Bundle.module` ?

Can you find `Adyen.framework` manually (see example below) ?

```swift
Bundle.allFrameworks.first { $0.bundlePath.contains("Adyen.framework") }
```

Can you share the source code of a test that is failing?

**Comment by andreymosin** [comment]
Hey @descorp 
SDK verion is 4.7.3
During the testing `AdyenActionComponent` instance is being created.
Next what is happening is calls initializer of `AwaitComponentStyle` that tries to access `UIColor.Adyen.componentLoadingMessageColor`. All this happens inside `AdyenActions` framework. I don't access it directly.

`Bundle.allFrameworks.first { $0.bundlePath.contains("Adyen.framework") }` returns nil.

Only Adyen related framework that is loaded is the one that runs test

```
(lldb) po Bundle.allFrameworks.first { $0.bundlePath.contains("Adyen") }
▿ Optional<NSBundle>
  - some : NSBundle <...../Build/Products/Debug-iphonesimulator/AdyenPayTests.xctest/Frameworks/FirebaseDatabase.framework> (loaded)
```

Testable imports in Unit test are
```
@testable import Adyen
@testable import AdyenActions
```

Line of code that triggers the fatal - `let actionComponent = AdyenActionComponent(apiContext: apiContext())`


Thank you!
Andrey

**Comment by descorp** [comment]
@andreymosin 

TBH, I am surprised that `@testable` works with SPM - I would expect dSYM to be deleted on a spot 🤔

However, I [can not reproduce this issue](https://github.com/descorp/DemoCheckout/blob/main/DemoAppTests/DemoAppTests.swift).
What am I missing?

**Comment by descorp** [comment]
Hey @andreymosin 

Were you able to resolve your issue?

**Comment by andreymosin** [comment]
@descorp Unfortunately not. Adyen is dependency of framework A that is imported to framework B. Running tests on framework B causes this problem. Workaround I've implemented is to check if the tests are running and if so - not call any adyen logic that will require Adyen to access it's resources.

**Comment by descorp** [comment]
Sorry to hear that @andreymosin 
Please let us know if we can help resolving this issue. 
We are always interested in learning more about any use cases for our SDK.
