### ISSUE TITLE
[Request] PaymentMethods conformance to Equatable & Hashable

### ISSUE THREAD

**Issue by Abdo-codes** [Adyen/adyen-ios#969]
**Is your feature request related to a problem? Please describe.**
for payment methods object that's being serialized from backend response with PaymentMethods object, PaymentMethod protocol should have Equatable, Hashable protocols in order to generate a list of payment methods easily for UI.

**Describe the solution you'd like**
add conformance to Equatable, Hashable to payment method protocol

**Describe alternatives you've considered**
On receiving payment methods from the backend and showing them as a list, diffable data source needs objects to conform to Equatable and Hashable to display the methods.

**Comment by descorp** [comment]
Hey @Abdo-codes 

Thank you for the feedback!

Unfortunately, [this is impossible to achieve](https://khawerkhaliq.com/blog/swift-protocols-equatable-part-one/): as you noticed - `PaymentMethod` is a protocol and `Equatable` does not work well with protocols.

As a workaround, you can just wrap `PaymentMethod` into an Equatable & Hashable struct of your own. This is also a recommended  approach to separate Adyen API DTOs and your App's UI layer models.

**Comment by Abdo-codes** [comment]
Thanks for responding, and the link. That's exactly the solution I went for already. 
Appreciate your quick response 👍
