### ISSUE TITLE
[NEED ASSIST] How to change language within app for card view

### ISSUE THREAD

**Issue by Chaithra-TV** [Adyen/adyen-ios#973]
Hi Team Im facing issue to change language to French for Adyen card screen all the time its showing in English.

**Comment by erenbesel** [comment]
Hi @Chaithra-TV , could you provide more details?

Are you using your own localization files rather the SDK's maybe? By default the SDK follows its own localization strings based on the device's language.

**Comment by descorp** [comment]
Hey @Chaithra-TV 

Were you able to resolve your problem?

**Comment by mohammedDehairy** [comment]
will close this issue for now, please feel free to reopen or create a new issue if you're still experiencing issues!.
