### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Gadagoju007** [Adyen/adyen-ios#986]
**Issue Description**
DropInComponent keep saying not confirmed to protocol even though I have confirmed to protocol & implemented the delegate methods

Xcode Version: 13.3

**Screenshots**

<img width="905" alt="Screenshot 2022-08-23 at 7 43 50 PM" src="https://user-images.githubusercontent.com/104971300/186181174-13683158-ed87-4fa0-9b35-cdf3cfb6c7d8.png">

is this a Xcode bug or framework issue ?

I would be glad if someone help or address this issue

**Comment by erenbesel** [comment]
Hi @Gadagoju007, 

What happens if you press the `Fix` button from Xcode's suggestion?

**Comment by Gadagoju007** [comment]
Hi @erenbesel 
once I click fix it again adds this   method which is already there

func didSubmit(_ data: PaymentComponentData, for paymentMethod: PaymentMethod, from component: DropInComponent) {

**Comment by erenbesel** [comment]
Interesting, what version of the SDK are you using and through which tool you installed it (cocoapods etc)?

**Comment by Gadagoju007** [comment]
> Interesting, what version of the SDK are you using and through which tool you installed it (cocoapods etc)?

Xcode : 13.3 and I used CocoaPods

**Comment by erenbesel** [comment]
Also what is the version of the Adyen SDK?

**Comment by Gadagoju007** [comment]
> Also what is the version of the Adyen SDK?

Adyen (4.8.0)

**Comment by descorp** [comment]
@Gadagoju007 

This seems like Xcode behaviour.

`PaymentController` - is it generic?
Maybe a naming collision? Try using `Adyen.PaymentComponentData`, `Adyen. PaymentMethod` 🤔

**Comment by Gadagoju007** [comment]
> @Gadagoju007
> 
> This seems like Xcode behaviour.
> 
> `PaymentController` - is it generic? Maybe a naming collision? Try using `Adyen.PaymentComponentData`, `Adyen. PaymentMethod` 🤔

I was able to solve I just uninstalled Xcode and installed its not showing that error  that's a wired issue

**Comment by descorp** [comment]
Thanks for letting us know @Gadagoju007 

Uninstalling Xcode seems a radical solution 😅
You can try [Deep cleaning Xcode](https://gist.github.com/ekreutz/b245da335cc10b0d270136b35eb22d1f) if things goes "weird"
