### ISSUE TITLE
No public init for Action in the 3DS2 and Redirect components 

### ISSUE THREAD

**Issue by moia-hari** [Adyen/adyen-ios#99]
The adyen SDK expects that the ComponentActions are initialized with the JSON response from the adyen API. The ComponentActions like `ThreeDS2FingerprintAction` and `ThreeDS2ChallengeAction` does not have a public init() so the only way to initialize this is by using a `JSONDecoder`.

In our use-case, the app communicates to our payment backend using Protobufs and Payment backend communicates to adyen and the result is then converted and sent back as Protobuf messages. So, in the app, we have the values for initiating an Action but, not as JSON.

Question: Is there a reason why Adyen does not allow direct initialization of Actions?

Currently, we are working around this issue in a purely nonoptimal way.

**Comment by moia-hari** [comment]
I would like to open a PR adding the `public init` for these actions.

**Comment by joostvandijk** [comment]
Hi @moia-hari,

It's a good question, and there's no reason why we can't have actions being initialized with the raw data. We'll ship the merged changes with the next release.

Thanks!

Joost

**Comment by joostvandijk** [comment]
Hi,

This issue has been fixed in the latest release, 3.1.2. Please feel free to reopen the issue if the new release doesn't work as expected.

Best,

Joost
