### ISSUE TITLE
[NEED ASSIST] how to connect card reader

### ISSUE THREAD

**Issue by MaximGolovlev** [Adyen/adyen-ios#995]
- I cannot locate PaymentServiceDelegate
https://docs.adyen.com/point-of-sale/card-reader-solution/integration-reader#make-a-sessions-request
it is not even in your repo https://github.com/Adyen/adyen-ios/search?q=PaymentServiceDelegate

cannot locate DeviceManagerDelegate
https://docs.adyen.com/point-of-sale/card-reader-solution/device-management#uikit

**Comment by descorp** [comment]
Hey @MaximGolovlev 

[This repo](https://github.com/Adyen/adyen-ios) is intended for our Checkout "Online Payments" SDK :)

What you are looking for is our SDK for Tap To Pay/Card Reader. 
We do not have a public repo for it just yet, but you can begin the process by submitting request here -> https://www.adyen.com/pos-payments/tap-to-pay-on-iphone

Or you can reach out to your existing Adyen contact person as described here -> https://docs.adyen.com/point-of-sale/tap-to-pay#before-you-start

Apologies for the confusion.
