### ISSUE TITLE
Non-existent path referenced in podspec

### ISSUE THREAD

**Issue by jszumski** [Adyen/adyen-ios#997]
**Describe the bug**
Non-existent resources are referenced in the `Card` subspec

**To Reproduce**
```
  s.subspec 'Card' do |plugin|
    plugin.dependency 'Adyen/Core'
    plugin.dependency 'Adyen/Encryption'
    plugin.source_files = 'AdyenCard/**/*.swift'
    plugin.exclude_files = 'AdyenCard/**/BundleSPMExtension.swift'
    plugin.resource_bundles = {
        'AdyenCard' => [
            'AdyenCard/Assets/**/*.strings',
            'AdyenCard/Assets/**/*.xcassets'
        ]
    }
  end
```
Looking on disk `AdyenCard/Assets/` doesn't contain any `.strings` files.

**Expected behavior**
All file patterns in the podspec should match something.

**Screenshots**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by descorp** [comment]
Hey @jszumski

Thanks for pointing it out!
Indeed, some unused leftovers.

Created PR #998

**Comment by descorp** [comment]
Hey @jszumski

Thanks for pointing it out!
Indeed, some unused leftovers.

Created PR #998

**Comment by mohammedDehairy** [comment]
This issue has been fixed in v5 release!.

will close this issue for now, please feel free to reopen or create a new issue if you're still experiencing issues!.
