### ISSUE TITLE
[NEED ASSIST] Large increase in app size after updating to 4.9.0

### ISSUE THREAD

**Issue by sahalin** [Adyen/adyen-ios#999]
Hello,

We've just updated to the latest version from 3.9.1 and our App Clip is now over the size limit by 1.8 MB. 

Is there a way to decrease this by maybe custom importing the frameworks and excluding things like 3DS? For the App Clip all we really need right now is the Drop-in and Apple Pay. Or any other ways to trim the dependency size will be appreciated.

Thanks,
Alex

**Comment by descorp** [comment]
Hey @sahalin 

I don't think there is a feasible solution at the moment.
Drop-In is an umbrella of everything SDK provides - if you are using it, everything is imported.
We indeed might consider splitting `AdyenComponents` and/or `AdyenActions` into individual pieces, but then managing 20-30 sub-dependency might be a nightmare.. In other words, this is probably not going to happen in the nearest future

You can try custom integration by importing only `Adyen` or even try API-only approach. 
Feel free to copy any of our code - it is MIT license.

**Comment by sahalin** [comment]
Hi Vladimir, that will make our job much harder 😅, but thanks for quick reply!

**Comment by descorp** [comment]
@sahalin 

You can always ask questions (create new issue) here if you have any difficulties!
We are keen to learn more about how our merchants use our libraries, especially for a specific case like App Clip!
